### ISSUE TITLE
Download links for ImageNet pretrained weights not working

### ISSUE THREAD

**Issue by realwecan** [facebookresearch/Detectron#1]
Thanks for the amazing work!

It seems that the links to download the ImageNet pretrained models (in Detectron format) are not working, giving 403 Forbidden errors:

https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#imagenet-pretrained-models

Download links for other models work just fine.

**Comment by rbgirshick** [comment]
Thanks for reporting this issue, @realwecan! Fixed links should be pushed to the repo in several minutes. In the meantime, you can refer to these:

- [R-50.pkl](https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl): converted copy of MSRA's original ResNet-50 model
- [R-101.pkl](https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-101.pkl): converted copy of MSRA's original ResNet-101 model
- [X-101-64x4d.pkl](https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/FBResNeXt/X-101-64x4d.pkl): converted copy of FB's original ResNeXt-101-64x4d model trained with Torch7
- [X-101-32x8d.pkl](https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/20171220/X-101-32x8d.pkl): ResNeXt-101-32x8d model trained with Caffe2 at FB
- [X-152-32x8d-IN5k.pkl](https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/25093814/X-152-32x8d-IN5k.pkl): ResNeXt-152-32x8d model **trained on ImageNet-5k** with Caffe2 at FB (see our [ResNeXt paper](https://arxiv.org/abs/1611.05431) for details on ImageNet-5k)

**Comment by rbgirshick** [comment]
Fixed by efc0c0ed9abcc48dd82d85556f31bf893ac6661c.
