### ISSUE TITLE
ld: cannot find -lpthread

### ISSUE THREAD

**Issue by RomRoc** [facebookresearch/Detectron#105]
Hello, I tried to install Detectron on a new Aws Ec2 instance using [this](https://aws.amazon.com/marketplace/pp/B077GCH38C?qid=1517589713039&sr=0-4&ref_=srh_res_product_title) Ami, p2.xlarge (Nvidia gpu integrated), but during installation process I got errors:
/home/ubuntu/anaconda3/envs/caffe2_p27/compiler_compat/ld: cannot find -lpthread
/home/ubuntu/anaconda3/envs/caffe2_p27/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

It's very easy to replicate my issue, because I started from a fresh new ec2 instance and I made these steps:
-  After ssh logon I selected Caffe2 with Python2 (CUDA 9) environment.
- I executed sudo apt-get update and sudo apt-get upgrade
- python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success
- python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
1
- pip install numpy>=1.13 pyyaml>=3.12 matplotlib opencv-python>=3.2 setuptools Cython mock scipy
- mkdir download
- COCOAPI=/home/ubuntu/download/
- git clone https://github.com/cocodataset/cocoapi.git $COCOAPI
- cd $COCOAPI/PythonAPI
- make install

Last output lines are:
creating build/lib.linux-x86_64-2.7/pycocotools
gcc -pthread -shared -B /home/ubuntu/anaconda3/envs/caffe2_p27/compiler_compat -L/home/ubuntu/anaconda3/envs/caffe2_p27/lib -Wl,-rpath=/home/ubuntu/anaconda3/envs/caffe2_p27/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-2.7/pycocotools/_mask.o build/temp.linux-x86_64-2.7/../common/maskApi.o -L/home/ubuntu/anaconda3/envs/caffe2_p27/lib -lpython2.7 -o build/lib.linux-x86_64-2.7/pycocotools/_mask.so
/home/ubuntu/anaconda3/envs/caffe2_p27/compiler_compat/ld: cannot find -lpthread
/home/ubuntu/anaconda3/envs/caffe2_p27/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
error: command 'gcc' failed with exit status 1

**Comment by nielsole** [comment]
https://github.com/cocodataset/cocoapi/issues/94#issuecomment-350152998
