### ISSUE TITLE
Why does it need to do RoIFeatureTransform multi times at different branches?

### ISSUE THREAD

**Issue by huyangc** [facebookresearch/Detectron#108]
As the code shows, when adding fast rcnn  head, a RoIFeatureTransform is done, and when adding mask head, RoIFeatureTransform is done again. Is it necessary to do so for the backward gradient or something else? Can I just do RoIFeatureTransform once (before adding different branches)?

**Comment by Sundrops** [comment]
Firstly, ROI_XFORM_RESOLUTION of  fast rcnn branch and mask branch may be different. Secondly, you can do RoIFeatureTransform once when ROI_XFORM_RESOLUTION of the two branches is same. But It also need backward gradient twice,

**Comment by huyangc** [comment]
I get it. Is it because the mask branch only needs to use the fg_rois, and it is easier to implement when apply two RoIFeatureTransform for two different inputs other than select the fg_rois_pool after RoIFeatureTransform?

**Comment by huyangc** [comment]
Yes, the resolutions are different between fast rcnn branch and mask branch is also an import factor to do it twice.

**Comment by Sundrops** [comment]
Yes, the mask branch only needs to use the fg_rois. But I think selecting the fg_rois_pool after RoIFeatureTransform is much efficient when the resolutions are same between the two branches. So the difference of resolutions is the most  important factor  to do RoIFeatureTrancsform twice. Ps: this codebase is really flexible.

**Comment by rbgirshick** [comment]
Thanks for providing explanations @Sundrops 👍 .

**Comment by huyangc** [comment]
Thanks! I miss the resolution difference between mask and box! @Sundrops
