### ISSUE TITLE
RetinaNet: how to re-train only the CLASS subnet while keeping the model's pre-trained weights of backbone and box subnet?

### ISSUE THREAD

**Issue by AmitaiPerlstein** [facebookresearch/Detectron#109]
## PLEASE FOLLOW THESE INSTRUCTIONS BEFORE POSTING
1. Please thoroughly read README.md, INSTALL.md, GETTING_STARTED.md, and FAQ.md
2. Please search existing *open and closed* issues in case your issue has already been reported
3. Please try to debug the issue in case you can solve it on your own before posting

## After following steps 1-3 above and agreeing to provide the detailed information requested below, you may continue with posting your issue
(**Delete this line and the text above it.**)

### Expected results

What did you expect to see?

### Actual results

What did you observe instead?

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by rbgirshick** [comment]
Simply delete the relevant parameter keys from the blob dictionary in a pretrained model's `.pkl` file. Read `utils.net.initialize_gpu_from_weights_file` for more information.
