### ISSUE TITLE
Single picture calculation time is 1s

### ISSUE THREAD

**Issue by kiaoio4** [facebookresearch/Detectron#114]
The calculation time is about 1s for one single picture based on GPU 1080ti using Mask R-CNN, is this normal?

**Comment by kiaoio4** [comment]
Image resolution is 640 * 480

**Comment by topcomma** [comment]
The first image is slower than the others.
I tested on 1080Ti GPU, the first image inference time is about 0.85s ,the second is 0.13s for 600*1000.

**Comment by rbgirshick** [comment]
`infer_simple.py` prints out an explanation for exactly this question:

"Note: inference on the first image will be slower than the rest (caches and auto-tuning need to warm up)"
