### ISSUE TITLE
fpn upsamping while featmap width/height is an odd number

### ISSUE THREAD

**Issue by mmclkv** [facebookresearch/Detectron#121]
Hi guys,
    I found that the upsampling op in detectron takes a single scaling factor as parameter, however, if the height/width of the feature map at some middle stage is an odd number, for example 15, the height/width of the feature map at next stage will be 8. Therefore, while building FPN, the height/width of the lateral part(which is 15) and the height/width of the topdown part(which will be 8x2=16) will not match.  How do you deal with this problem?

**Comment by KaimingHe** [comment]
There is a coarsest stride defined:
https://github.com/facebookresearch/Detectron/blob/2f8161edc3092b0382cab535c977a180a8b3cc4d/lib/utils/blob.py#L53

**Comment by mmclkv** [comment]
Thanks @KaimingHe !
