### ISSUE TITLE
Accessing net's output

### ISSUE THREAD

**Issue by raviv** [facebookresearch/Detectron#123]
Hi,

How can I access the network's outputs after each iteration? 
I assume this would be somehow available after each call to 
`workspace.RunNet(model.net.Proto().name)`

My end goal is to visualize inference once every few iterations to "debug" the net.

Thanks!

**Comment by rbgirshick** [comment]
You can fetch blobs from the Caffe2 workspace, which will copy the GPU tensor into a `numpy` `ndarray`. For example, this [line](https://github.com/facebookresearch/Detectron/blob/master/lib/core/test.py#L160) fetches the `gpu_0/rois` blob which contains the region of interest predictions from the `RPN` part of the network.

**Comment by raviv** [comment]
Thanks @rbgirshick.
Can access the inputs (image) the same way? I want to see the effect of augmentation on my images.
If so, what would be the blobs's name for that?

**Comment by manyaafonso** [comment]
Hi @raviv , would you be willing to share your modified code for this visualization? Thanks.

**Comment by raviv** [comment]
@manyaafonso, I eventually ditched Detectron so can't help you with that.

**Comment by manyaafonso** [comment]
@raviv thanks for getting back quickly. A coworker of mine also ditched detectron for matterport's maskrcnn, so I'll give that a try too.
