### ISSUE TITLE
Running Detectron on Mac OS X

### ISSUE THREAD

**Issue by daniildavydzik** [facebookresearch/Detectron#126]
Could i run Detectron on CPU , without GPU support? 

* Operating system: Mac OS X High Sierra

**Comment by ALEXKIRNAS** [comment]
No, you couldn't.  From [INSTALL.md](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md):
```
Notes:
- Detectron operators currently do not have CPU implementation; a GPU system is required.
- Detectron has been tested extensively with CUDA 8.0 and cuDNN 6.0.21.
```

**Comment by ir413** [comment]
@daniildavydzik: As pointed out by @ALEXKIRNAS and stated in the [requirements](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md), we do not support building and running on OS X at this time. Sorry for the inconvenience.
