### ISSUE TITLE
Is online hard example mining supported?

### ISSUE THREAD

**Issue by kampelmuehler** [facebookresearch/Detectron#129]

**Comment by zhangtao22** [comment]
the same question,and I want to know how to select the pos and neg label as 1:5

**Comment by ir413** [comment]
Hi @kampelmuehler  and @zhangtao22, online hard example mining is currently not implemented.

**Comment by fangpengcheng95** [comment]
I am trying to implement OHEM for Detectron

**Comment by zxDeepDiver** [comment]
@fangpengcheng95 Hi, how is your progress?
