### ISSUE TITLE
where is the SoftmaxFocalLoss() and SigmoidFocalLoss() implementation?

### ISSUE THREAD

**Issue by zhangtao22** [facebookresearch/Detectron#130]
I search the total project, can not find it

**Comment by rbgirshick** [comment]
Most of the detectron custom ops are in the Caffe2 detectron module https://github.com/caffe2/caffe2/tree/master/modules/detectron. The RoIAlign op is in the core set of Caffe2 operators.

**Comment by kxhit** [comment]
Hi! @zhangtao22 
Can not find it either. Did you solve it?

@rbgirshick 
The page can't be found in the link you gave. 
Need help!! Thanks!

**Comment by ir413** [comment]
Thanks for flagging @kxhit. We updated the link and it should work again now.

**Comment by kxhit** [comment]
Thanks a lot！！！
By the way, is there a tensorflow implementation？
