### ISSUE TITLE
Documentation request: detailed configs description

### ISSUE THREAD

**Issue by ALEXKIRNAS** [facebookresearch/Detectron#132]
Thanks for amazing Detectron repo. I am trying to configure my own models (Mask R-CNN, RetinaNet) and I am a little bit confusing by some options in configs. Can you provide documentation with description of config options for your models?

Thanks,
Alex

**Comment by ir413** [comment]
Hi Alex, please see comments in [`config.py`](https://github.com/facebookresearch/Detectron/blob/master/lib/core/config.py) for the description of config options.

**Comment by ALEXKIRNAS** [comment]
@ir413, Thanks.
