### ISSUE TITLE
Multi-scale test "error: Range subprocess error"

### ISSUE THREAD

**Issue by Eric-mingjie** [facebookresearch/Detectron#133]
Multi-scale test error
-----------------------------------------------------------------------------------
**There is no problem when I use single scale testing. But when I set cfg.TEST.SCALES to (400,500), then the following error shows:**

At:
  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at pybind_state.h:423] . Exception encountered running PythonOp function: IndexError: index 1 is out of bounds for axis 0 with size 1

At:
  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
 Error from operator:
input: "gpu_0/rpn_cls_probs_fpn6" input: "gpu_0/rpn_bbox_pred_fpn6" input: "gpu_0/im_info" output: "gpu_0/rpn_rois_fpn6" output: "gpu_0/rpn_roi_probs_fpn6" name: "GenerateProposalsOp:gpu_0/rpn_cls_probs_fpn6,gpu_0/rpn_bbox_pred_fpn6,im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:4" } arg { name: "spatial_scale" f: 0.015625 } arg { name: "grad_output_indices" } device_option { device_type: 0 }Error from operator:
input: "gpu_0/rpn_cls_probs_fpn6" input: "gpu_0/rpn_bbox_pred_fpn6" input: "gpu_0/im_info" output: "gpu_0/rpn_rois_fpn6" output: "gpu_0/rpn_roi_probs_fpn6" name: "GenerateProposalsOp:gpu_0/rpn_cls_probs_fpn6,gpu_0/rpn_bbox_pred_fpn6,im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:4" } arg { name: "spatial_scale" f: 0.015625 } arg { name: "grad_output_indices" } device_option { device_type: 1 cuda_gpu_id: 0 }
*** Aborted at 1518176599 (unix time) try "date -d @1518176599" if you are using GNU date ***
PC: @     0x7f4928c045f7 __GI_raise
*** SIGABRT (@0x4335000040c2) received by PID 16578 (TID 0x7f4805ffb700) from PID 16578; stack trace: ***
    @     0x7f49296a8100 (unknown)
    @     0x7f4928c045f7 __GI_raise
    @     0x7f4928c05ce8 __GI_abort
    @     0x7f491bfc38bd __gnu_cxx::__verbose_terminate_handler()
E0209 19:43:19.922534 18308 pybind_state.h:422] Exception encountered running PythonOp function: IndexError: index 1 is out of bounds for axis 0 with size 1

  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
terminate called recursively
    @     0x7f491bfc1906 __cxxabiv1::__terminate()
    @     0x7f491bfc1951 std::terminate()
    @     0x7f491bfeb978 execute_native_thread_routine
    @     0x7f49296a0dc5 start_thread
    @     0x7f4928cc521d __clone
Traceback (most recent call last):
  File "tools/test_net.py", line 161, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing)
  File "tools/test_net.py", line 122, in main
    results = parent_func(multi_gpu=multi_gpu_testing)
  File "/mnt/lustre/Detectron/lib/core/test_engine.py", line 59, in test_net_on_dataset
    num_images, output_dir
  File "/mnt/lustre/Detectron/lib/core/test_engine.py", line 82, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir
  File "/mnt/lustre/Detectron/lib/utils/subprocess.py", line 92, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/mnt/lustre/Detectron/lib/utils/subprocess.py", line 130, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: -6)
srun: error: : tasks 0-3: Exited with exit code 1

**The script I was running is tools/test_net.py. It works when TEST.SCALES is a single number. But it fails to work when I change it to a list of numbers.
Error also occurs when I use **single gpu** test. Error is shown as follows:**

At:
  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at pybind_state.h:423] . Exception encountered running PythonOp function: IndexError: index 1 is out of bounds for axis 0 with size 1

At:
  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
 Error from operator: 
input: "gpu_0/rpn_cls_probs_fpn6" input: "gpu_0/rpn_bbox_pred_fpn6" input: "gpu_0/im_info" output: "gpu_0/rpn_rois_fpn6" output: "gpu_0/rpn_roi_probs_fpn6" name: "GenerateProposalsOp:gpu_0/rpn_cls_probs_fpn6,gpu_0/rpn_bbox_pred_fpn6,im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:4" } arg { name: "spatial_scale" f: 0.015625 } arg { name: "grad_output_indices" } device_option { device_type: 0 }Error from operator: 
input: "gpu_0/rpn_cls_probs_fpn6" input: "gpu_0/rpn_bbox_pred_fpn6" input: "gpu_0/im_info" output: "gpu_0/rpn_rois_fpn6" output: "gpu_0/rpn_roi_probs_fpn6" name: "GenerateProposalsOp:gpu_0/rpn_cls_probs_fpn6,gpu_0/rpn_bbox_pred_fpn6,im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:4" } arg { name: "spatial_scale" f: 0.015625 } arg { name: "grad_output_indices" } device_option { device_type: 1 cuda_gpu_id: 0 }
*** Aborted at 1518177779 (unix time) try "date -d @1518177779" if you are using GNU date ***
E0209 20:02:59.444838  5693 pybind_state.h:422] Exception encountered running PythonOp function: IndexError: index 1 is out of bounds for axis 0 with size 1

At:
  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
terminate called recursively
PC: @     0x7fc1a122c5f7 __GI_raise
*** SIGABRT (@0x433500005080) received by PID 20608 (TID 0x7fc06f7fe700) from PID 20608; stack trace: ***
    @     0x7fc1a1cd0100 (unknown)
    @     0x7fc1a122c5f7 __GI_raise
    @     0x7fc1a122dce8 __GI_abort
    @     0x7fc1945eb8bd __gnu_cxx::__verbose_terminate_handler()
    @     0x7fc1945e9906 __cxxabiv1::__terminate()
E0209 20:02:59.465358  5692 pybind_state.h:422] Exception encountered running PythonOp function: IndexError: index 1 is out of bounds for axis 0 with size 1
At:
  /mnt/lustre/Detectron/lib/ops/generate_proposals.py(90): forward
terminate called recursively
    @     0x7fc1945e9951 std::terminate()
    @     0x7fc194613978 execute_native_thread_routine
    @     0x7fc1a1cc8dc5 start_thread
E0209 20:02:59.472615  5691 pybind_state.h:422] Exception encountered running PythonOp function: IndexError: index 1 is out of bounds for axis 0 with size 1

At:
  /mnt/lustre/sunmingjie/Detectron/lib/ops/generate_proposals.py(90): forward
terminate called recursively
    @     0x7fc1a12ed21d __clone
srun: error: : task 0: Aborted

**Comment by ir413** [comment]
Hi @Eric-mingjie, instead of using `TEST.SCALES` you should use the `SCALES` option for the relevant test-time augmentation configuration (e.g. `BBOX_AUG`). Please see [test_time_aug](https://github.com/facebookresearch/Detectron/tree/master/configs/test_time_aug) configs for examples.

**Comment by Eric-mingjie** [comment]
Thanks! It works for me @ir413 . But I still have one question. Don't we need to set TEST.SCALES configuration? Or the setting of BBOX_AUG.SCALES and KPS_AUG.SCALES will automatically set TEST.SCALES in Detectron framework.

**Comment by Eric-mingjie** [comment]
Thanks @ir413 ! It solves my problem.

**Comment by soumenms2015** [comment]
@ir413 Does multi TEST.SCALES support for RetinaNet? I can't see any configuration for retinanet. Could you please provide it?

**Comment by ir413** [comment]
Hi @soumenms2015, test-time augmentations are currently not supported for RetinaNet (e.g. see [here](https://github.com/facebookresearch/Detectron/blob/master/lib/core/test.py#L56-L59)). Will will look into adding support for this in the future. Sorry for the inconvenience.
