### ISSUE TITLE
out of memory Error from operator

### ISSUE THREAD

**Issue by 89douner** [facebookresearch/Detectron#135]
I wanna use the Detectron with other Object Detection models.
When I install this by following this instruction and run 'infer_simple.py', there is no error message.

However. when I install Detectron after installing OpenCV 3.2.0 and tensorflow 1.5.0, I got below error message when I run 'inter_simple.py'. (There are nine test images in 'demo' folder. but, only four test images saved in "/tmp/detectron-visualizations" folder.)

![2018-02-10 00-09-42](https://user-images.githubusercontent.com/31752297/36034897-d4bfebda-0df8-11e8-92b8-1612f6fddaa4.png)

May be, I guess  the problem may be caused by OpenCV or tensorflow 1.5.0 version's environment variable (export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/extras/CUPTI/lib64)
[https://www.tensorflow.org/install/install_linux](url)

Please answer ! Thanks !

### System information

* Operating system: Ubuntu 16.04
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.6) 5.4.0
* CUDA version: 9.0
* cuDNN version: 7.0.5 for CUDA 9.0
* NVIDIA driver version: 390.12
* GPU models (for all devices if they are not all the same): Geforce GTX 1050 Ti
* `PYTHONPATH` environment variable: 
/home/jeonghyunsu/detectron/lib 
/usr/local
/home/jeonghyunsu/caffe2/build
* `python --version` output: 2.7.12
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @89douner, it seems that you're running out of memory on some of the demo images. Geforce GTX 1050 Ti may currently not be sufficient to run the model you are trying to use.

Please see #21 for the relevant discussion.

> For example, you can run Faster R-CNN with the default ResNet-50 config using:
>
>```
>python2 tools/infer_simple.py \
>  --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml \
>  --output-dir /tmp/detectron-visualizations \ 
>  --image-ext jpg \
>  --wts https://s3-us-west-2.amazonaws.com/detectron/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl \
>  demo
>```
>
>which should not require more than 3GB to run on the demo images.
