### ISSUE TITLE
Docker build fails 

### ISSUE THREAD

**Issue by VinceKumar** [facebookresearch/Detectron#14]
I do not see an image named 'caffe2:cuda8-cudnn6-all-options' on docker hub and that seems to be the reason why the build is failing

**Comment by burningion** [comment]
I've added a pull request for this. It seems the Dockerfiles were broken in the caffe2 repo.

https://github.com/facebookresearch/Detectron/pull/15

**Comment by VinceKumar** [comment]
Thank you! Testing it right now.

**Comment by ir413** [comment]
Hi @VinceKumar and @burningion, please see the instructions for building the Caffe2 image provided in our [`INSTALL.md`](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md) file:

```
cd /path/to/caffe2/docker/ubuntu-16.04-cuda8-cudnn6-all-options
# Use the latest Caffe2 master
sed -i -e 's/ --branch v0.8.1//g' Dockerfile
docker build -t caffe2:cuda8-cudnn6-all-options .
```

I believe the pull request @burningion added removes the `--branch v0.8.1` from the Caffe2 dockerfile, as is done in the instructions above.

**Comment by burningion** [comment]
Hey @ir413, you're totally right!

Somehow we both managed to completely miss that. I expect there will be others in the future.

Would you be open to putting a README.md inside of the `docker/` directory? 

It could even just be a copy paste of the instructions from `INSTALL.md` above for replacing the (currently) broken Caffe2 Dockerfile.

I think this will save you from people re opening this issue in the future.

Either way, thanks!

**Comment by VinceKumar** [comment]
I don't understand the building of the Caffe image part 😕. There is no provided dockerfile relating to Caffe in this repo or one on dockerhub.

**Comment by burningion** [comment]
@VinceKumar the related Dockerfile for Caffe2 is here:

https://github.com/caffe2/caffe2/tree/master/docker

That's the one the instructions are trying to get you to build, once you get rid of the `--branch v0.8.1/` from the appropriate Dockerfile.

**Comment by pandamax** [comment]
Here is a [Chinese Blog](http://blog.csdn.net/pandamax/article/details/79154389) account for this issue in detail,which may help you.

**Comment by ir413** [comment]
We're working with the Caffe2 team on uploading up-to-date Caffe2 images to the docker hub, which should eliminate the need to build the Caffe2 dockerfiles locally and make the overall docker setup process smoother. Sorry for the inconvenience.

@VinceKumar: As @burningion said, we assume that you have the Caffe2 repo cloned locally. If it makes it clearer, you can replace

```
cd /path/to/caffe2/docker/ubuntu-16.04-cuda8-cudnn6-all-options
```

with

```
# CAFFE2=/path/to/caffe2
git clone https://github.com/caffe2/caffe2.git $CAFFE2
cd $CAFFE2/docker/ubuntu-16.04-cuda8-cudnn6-all-options
```
in the instructions I posted above.
