### ISSUE TITLE
Using only bbox detection

### ISSUE THREAD

**Issue by EgorAntonovich** [facebookresearch/Detectron#140]
I know that  caffe  has opportunity discarding layers, but i don't know how to make it on caffe2 in detectron
I need only bbox detection in my experiments, may be who know how to discard leyer which respond of mask detection?

**Comment by uefall** [comment]
Hello @EgorAntonovich:

You can follow those config yaml files which's name without "mask_rcnn" or "keypoint_rcnn" keyword，their config have no MRCNN or  KRCNN part, while creating your model, it will no add ROI_MASK_HEAD or  ROI_KEYPOINTS_HEAD to your detect backbone and becomes a bbox detect only model.

**Comment by ir413** [comment]
@EgorAntonovich: to compute only the bounding boxes you can use one of the Fast/Faster R-CNN models from the [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md).

For example, you can run e2e Faster R-CNN with the default ResNet-101 config using:

```
python2 tools/infer_simple.py \
   --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-101-FPN_2x.yaml \
   --output-dir /tmp/detectron-visualizations \
   --image-ext jpg \
   --wts https://s3-us-west-2.amazonaws.com/detectron/35857952/12_2017_baselines/e2e_faster_rcnn_R-101-FPN_2x.yaml.01_39_49.JPwJDh92/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
  demo
```
