### ISSUE TITLE
can mask rcnn train in an end-to-end way rather than alternating training?

### ISSUE THREAD

**Issue by liangzimei** [facebookresearch/Detectron#141]
hello,
can mask rcnn train in an end-to-end way rather than alternating training?  does it work well?

**Comment by terrychenism** [comment]
Sure, plz check https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_1x.yaml

**Comment by liangzimei** [comment]
@terrychenism thank you~
