### ISSUE TITLE
Can I use Detectron platform to train a detection model on my own data?

### ISSUE THREAD

**Issue by SniperZhao** [facebookresearch/Detectron#142]
Right now I can train model on COCO dataset. 
However I wish to train on my own dataset, what should I do for preparation?
Something like:
    The format of labeling data file?
    How can Detectron find the pair of image and its related labeling file?

**Comment by mattifrind** [comment]
Yes, that's possible. Please refer to the [Dataset readme.md](https://github.com/facebookresearch/Detectron/tree/master/lib/datasets/data) and the other issues about this topic. #131 #97 #98 
You can find all your answers there. (except the fine-tuning with a different number of categories. I have no  solution for that problem yet) For help with the annotation format you can check out my[ post about ](http://matti.frind.de/?p=2089)that topic.

**Comment by SniperZhao** [comment]
Thank you mattifrind.

**Comment by raviv** [comment]
@mattifrind any clue on how to change the number of categories?

**Comment by mattifrind** [comment]
@raviv I'm sorry but I'm currently on my winter vacations so I'm not smarter than before. I just can you pass on to the idea of @SniperZhao at issue #97. I haven't tested his idea but I think that should work. It's not very beautiful but currently the best solution I have to offer.

**Comment by qwert1337** [comment]
You have to set the number of classes in the .yaml description file, which has to fit the number of classes in the .json file. I think it is +1 in yaml for the background.

**Comment by iamsaksham** [comment]
> Yes, that's possible. Please refer to the [Dataset readme.md](https://github.com/facebookresearch/Detectron/tree/master/lib/datasets/data) and the other issues about this topic. #131 #97 #98
> You can find all your answers there. (except the fine-tuning with a different number of categories. I have no solution for that problem yet) For help with the annotation format you can check out my[ post about ](http://matti.frind.de/?p=2089)that topic.

Updated url for [Dataset readme.md](https://github.com/facebookresearch/Detectron/tree/master/detectron/datasets/data)
