### ISSUE TITLE
Freezing RPN weights during training of MaskRCNN on custom dataset

### ISSUE THREAD

**Issue by tt7533** [facebookresearch/Detectron#143]
I am trying to train just the classifier of the mask-rcnn on my own dataset. 
Therefore I need to freeze the weights of all the other layers. I tried to find a way to take all the relevant learning multipliers to zero (lr_mult in the old caffe) but I couldn't find it in the param_init_net.pbtxt file.

I did however find the switch TRAIN.FREEZE_CONV_BODY to freeze the backbone architecture. Is there a way to freeze the RPN as well?

**Comment by rbgirshick** [comment]
Just insert a `StopGradient` op in the correct place(s). For example usage, see https://github.com/facebookresearch/Detectron/blob/master/lib/modeling/ResNet.py#L103.
