### ISSUE TITLE
Softmax focal loss

### ISSUE THREAD

**Issue by boundles** [facebookresearch/Detectron#144]
Hi, it seems that focal loss implemented in Caffe2 is different from paper, right?

**Comment by jwnsu** [comment]
it's certainly different. Caffe2 version in this repository has FPN built-in and cannot turn off FPN without code changes. Also, so far couldn't get any reasonable accuracy with current codebase on a new dataset.

**Comment by rbgirshick** [comment]
You're probably looking for the the sigmoid version, which is what we describe in the paper. https://github.com/caffe2/caffe2/blob/master/modules/detectron/sigmoid_focal_loss_op.cu.
