### ISSUE TITLE
Does Detectron support mulit-gpu inference?

### ISSUE THREAD

**Issue by topcomma** [facebookresearch/Detectron#146]
Hi Kaiming,

First thanks for your great work.
If we want to use Detectron on specific application, found it is the difficult problem to performance of inference, it seems only to support single gpu for interference, can we extend it onto multi-gpu?

Thanks.
Hu Xingui

**Comment by KaimingHe** [comment]
Detectron applied multi-gpu inference at the dataset level by splitting the test set into subsets and distributing them to multiple gpus, see: https://github.com/facebookresearch/Detectron/blob/master/lib/core/test_engine.py#L100

We have not supported multi-gpu inference of one image.

**Comment by topcomma** [comment]
@KaimingHe ， Thanks for your help and support.
