### ISSUE TITLE
Help detectron ops lib

### ISSUE THREAD

**Issue by shane-santos** [facebookresearch/Detectron#147]
https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md

When we were trying the steps to finish installing Detectron, we encountered errors in the step below:
Check that Detectron tests pass (e.g. for SpatialNarrowAsOp test):
python2 $DETECTRON/tests/test_spatial_narrow_as_op.py

![screenshot from 2018-02-12 18-26-14 1](https://user-images.githubusercontent.com/36176709/36092807-9818d034-1023-11e8-9cdd-22b878cfcae1.png)

I am using:
* Operating system: Ubuntu 14.04
* Compiler version: gcc
* Caffe2 on CPU - only
* `PYTHONPATH` environment variable:  /usr/local 
/home/ubuntu/caffe2/build
* `python --version` output: 2.7

**Comment by ir413** [comment]
Hi @shane-santos, Detectron currently requires Caffe2 with GPU support (Caffe2 [detectron ops](https://github.com/caffe2/caffe2/tree/master/modules/detectron) only have GPU implementation for now). Please see [INSTALL.md](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md) for Detectron requirements.
