### ISSUE TITLE
Is it possible to export Detectron pre-trained models as onnx models?

### ISSUE THREAD

**Issue by kumardesappan** [facebookresearch/Detectron#151]
Is it possible to export Detectron pre-trained models as onnx models?
If it is not supported now,  Do you have plans to support this in the near future?

**Comment by alaaadnan229** [comment]
<input autocorrect="off" autocapitalize="off" autocomplete="off" name="n" autofocus="1" id="u_0_0" style="-wap-input-format: '*N'" type="text">

**Comment by ir413** [comment]
cc @dzhulgakov and @orionr

**Comment by orionr** [comment]
Hi @kumardesappan. We are definitely interested in exporting Detectron models to ONNX. However, there is work to be done there. In fact, we also have work to do in exporting Detectron models to Caffe2 pb files, which can be run with base Caffe2 and C++ (on a mobile device, for example).

We're in progress on adding some Detectron models to the Caffe2 model zoo at

https://github.com/caffe2/models

and eventually some of those will make their way into the ONNX model zoo at

https://github.com/onnx/models

No ETA yet, but something we are working on. Hope that helps!

**Comment by kumardesappan** [comment]
@orionr Thanks. Hoping see onnx based object detection models soon.
Thanks and Regards,
Kumar.D

**Comment by borisfom** [comment]
The issue is closed but I can't seem to find ONNX models for detectron anywhere - is there still plan for that ?

**Comment by frownbreaker** [comment]
+1 an update would be helpful

**Comment by cardboardcode** [comment]
+1 Any updates on this?
