### ISSUE TITLE
Dockerfile build image breaks

### ISSUE THREAD

**Issue by ataraxus** [facebookresearch/Detectron#153]
### Expected results

Successfully built Docker image

### Actual results

Docker image generation breaks with message: 
```
Step 6/14 : RUN pip install numpy>=1.13 pyyaml>=3.12 matplotlib opencv-python>=3.2 setuptools Cython mock scipy
 ---> Running in f4f376afde8d
  Could not find a version that satisfies the requirement pyyaml (from versions: )
No matching distribution found for pyyaml
```
### Detailed steps to reproduce

```
docker build -t demo/detectron .
```

### System information

* Operating system: Mac OS X 10.12.6
* docker info
Containers: 11
 Running: 1
 Paused: 0
 Stopped: 10
Images: 67
Server Version: 17.03.1-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952 GiB
Name: moby
ID: 6UNM:IE6B:F34C:74BT:7KGF:75ZX:KSYY:NSGS:45O4:OEP5:RLP2:DAK6
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 32
 Goroutines: 41
 System Time: 2018-02-13T15:02:38.973343708Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by ataraxus** [comment]
Sorry my bad! This happens if you are running behind an corporate proxy..

**Comment by manyaafonso** [comment]
Hi @ataraxus , how did you solve this? Did you edit the files /etc/docker/daemon.json, /etc/default/docker or did you change your network settings?
