### ISSUE TITLE
I want to classify only car class

### ISSUE THREAD

**Issue by Ruslan1990** [facebookresearch/Detectron#156]
I want to classify only car class.

As a result of running infer_simply.py, i want to a image that contains only car class and car segmentation (does not contain other class)

How can i do this?

**Comment by ir413** [comment]
Hi @Ruslan1990, detections computed in [`infer_simple.py`](https://github.com/facebookresearch/Detectron/blob/master/tools/infer_simple.py#L116) are stored in the format described in the docs of [this function](https://github.com/facebookresearch/Detectron/blob/master/lib/core/test_engine.py#L302). You can retrieve the car detections using the index corresponding to the [car class](https://github.com/facebookresearch/Detectron/blob/master/lib/datasets/dummy_datasets.py#L31).
For example, something like:

```
car_boxes = cls_boxes[3]
car_segms = cls_segms[3]
```



Of course you can also train a car detector that only detects cars.

**Comment by srikanth-kilaru** [comment]
Hi @ir413 
With a InceptionResnet backbone, I was able to detect only one class and one instance. I had to turn off FPN as I was getting a blob dimension mismatch. Could this be the reason. Thanks

**Comment by zhangjinjing3** [comment]
When I wanted to detect the line, which is not included in the 80 coco classes, I can only detect the box ,but  not the mask, what should I do ?

**Comment by zhangjinjing3** [comment]
@ir413
