### ISSUE TITLE
Providing a Proposal File

### ISSUE THREAD

**Issue by chrisby** [facebookresearch/Detectron#164]
Hi there,

I was able to train a mask RCNN on my data set but run into problems when I run 

`python2 tool/test_net.py --cfg config/12_2017_baselines/MY_VERSION_OF_mask_rcnn_R-50-C4_sx.yaml`

The error I get is 

`cfg.TEST.PROPOSAL_FILE = cfg.TEST.PROPOSAL_FILES[i] 
IndexError: tuple index out of range`

I assume this arises because I did not specify a proposal file. My question is: in which format can I provide a proposal file for a private dataset? 

Thanks,
Christian

**Comment by ir413** [comment]
Hi @chrisby, we expect the proposals for a dataset to be provided in a `pkl` file that contains a serialized `proposals` dictionary with the following entries:

```
proposals.keys() - ['cfg', 'ids', 'scores', 'boxes']
```
where
```
proposals['cfg'] - config used to compute the proposals
proposals['ids][i] - id for the i-th image
proposals['scores'][i] - ndarray (N_i,) containing scores for the proposals in the i-th image
proposals['boxes'][i]  - ndarray (N_i, 4) containing coordinates (x1, y1, x2, y2) for the proposals in the i-th image
```

It may be instructive to download one of the proposal files from the [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) and inspect it interactively. You may also find it useful to look at [`_add_proposals_from_file`](https://github.com/facebookresearch/Detectron/blob/master/lib/datasets/json_dataset.py#L253) to see how proposals get loaded from file and [`rpn_generator`](https://github.com/facebookresearch/Detectron/blob/master/lib/core/rpn_generator.py) to see how proposals get computed and stored to a `pkl` file.

Note that you can use RPN models from the [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) to compute (and store in the expected format) the proposals for your dataset.

We plan to add the information about the proposals file format to the documentation in the future.
In the meantime, let us know if the above is unclear.

**Comment by chrisby** [comment]
Thanks, that's already very helpful! I think I will use one of the baseline RPNs to compute the proposal file an subsequently link it to my dataset.

**Comment by CoinCheung** [comment]
Excuseme, but what is the use of the file 'cfg' ? If I use the proposals that I extract from the training set by hand instead of some RPN, what would the structure of the proposal file be like, do I still need other filed other than the 'boxes' ? Would it be possible that I simply use naive fast rcnn combined with my self-made proposals with detectron ?

**Comment by CoinCheung** [comment]
Excuseme, but what is the use of the file 'cfg' ? If I use the proposals that I extract from the training set by hand instead of some RPN, what would the structure of the proposal file be like, do I still need other filed other than the 'boxes' ? Would it be possible that I simply use naive fast rcnn combined with my self-made proposals with detectron ?

**Comment by jason718** [comment]
proposals['cfg']  seems useless if you want to use your own proposals. In Detectron/tools/convert_selective_search.py they are not using 'cfg' keys.  

Is this correct @ir413 ?

**Comment by ir413** [comment]
@CoinCheung, @jason718: `proposals['cfg']` is not required so using a proposal file without it (e.g. as produced by `convert_selective_search`) should still work. I think that having the config file embedded in the proposals file is still useful for reproducibility as it records the hyper-parameters that were used to compute the proposals.

**Comment by tengerye** [comment]
Hi, do I need to use external selective search codes? I could not find any in this project.

**Comment by tengerye** [comment]
@ir413 Hi, thanks for the kind reply. Suppose I have the proposals from the selective search of an image, would you please give me a simple example about the parameters to run with `[convert_selective_search](https://github.com/facebookresearch/Detectron/blob/master/tools/convert_selective_search.py)`.
