### ISSUE TITLE
Missing ImageIDs in detection.pkl

### ISSUE THREAD

**Issue by chrisby** [facebookresearch/Detectron#166]
### Expected results

A detections.pkl file that contains the ImageId for which the segments/boxes were found. 

### Actual results

A detections.pkl file wiht keys `['cfg', 'all_segms', 'all_keyps', 'all_boxes']`

I trained a mask RCNN and provided the proposal file with the help of a RPN. Subsequently I ran the `test_net.py` command.

**Comment by ir413** [comment]
Hi @chrisby, the keys you list under actual results are as expected (an entry with image ids is not expected in `detections.pkl`). See the docs of [`empty_results`](https://github.com/facebookresearch/Detectron/blob/master/lib/core/test_engine.py#L302) for the description of the format used for `all_segms`, `all_keyps` and `all_boxes`. Contiguous indices used to index per image results correspond to sorted image ids (as specified in the json annotations; e.g. see [`get_roidb`](https://github.com/facebookresearch/Detectron/blob/master/lib/datasets/json_dataset.py#L87) function).

**Comment by chrisby** [comment]
I see, I just thought it would convenient to all information at hand e.g. to further process the results. But from a pure application point of view it is no really necessary. Thank you.
