### ISSUE TITLE
How to extend Detectron framework?

### ISSUE THREAD

**Issue by skrish13** [facebookresearch/Detectron#167]
I was interested in knowing the best way to tweak the models and build something on top of it Eg: A simple case where I train another branch of a FCLayer on top of ROIPool/ROIAlign outputs?

Even any hints/directions would be of great help.

**Comment by ir413** [comment]
Hi @skrish13, if you would like to experiment with adding a new branch/head it may be helpful to start by looking at the [`build_generic_detection_model`](https://github.com/facebookresearch/Detectron/blob/master/lib/modeling/model_builder.py#L155) function. You can then study how fast/mask/keypoints heads are constructed and add a new head following the same pattern.

**Comment by skrish13** [comment]
Cool, thanks for the quick reply!
