### ISSUE TITLE
merge weights of RPN and Fast-rcnn into a faster-rcnn model for end-to-end inference

### ISSUE THREAD

**Issue by bendidi** [facebookresearch/Detectron#170]
### Expected results

not really expected , but more of a feature :  is it possible to merge the weights of RPN and Fast-rcnn , to make end-to-end inference directly (after they were trained separately ) ? if so could you please give hints of how 

### Actual results

proposals generation with RPN and then use them in a faster-rcnn network

on another note , is it also possible to run them in two different GPU's simultaneously ?

**Comment by ir413** [comment]
Hi @bendidi, if by trained separately you mean trained with alternating/stagewise training described in the [Faster R-CNN NIPS paper](https://papers.nips.cc/paper/5638-faster-r-cnn-towards-real-time-object-detection-with-region-proposal-networks), then you can still use the [`FASTER_RCNN` flag](https://github.com/facebookresearch/Detectron/blob/ec3df46631e1a868c6bfce48ccad80ff16a35469/lib/core/config.py#L459-L469) to enable the RPN subnetwork at inference time.

**Comment by bendidi** [comment]
Hi @ir413 , I actually didn't use stage wise training (i will try it, and see if it gives same results ) , my goal was to train the two parts separately to gain in memory and use higher resolution images, so i've got two separate pkl files for the two networks ( I generate 2000 proposals with  the RPN and feed them to the fast-rcnn for detection with a `ResetWorkspace` between them)  which is not really the best way to do it , 
that's why I was wandering if they couldn't be merged in one network and do end-to-end inference

**Comment by bendidi** [comment]
can I use stage-wise training of a faster-rcnn by initializing the model with the RPN and fast-rcnn i trained in both stages respectively ?

**Comment by ir413** [comment]
Training an RPN and using its proposals to train a Fast R-CNN are some of the steps required for alternating/stagewise training of Faster R-CNN. Please refer to the paper I linked above or these [slides](https://www.dropbox.com/s/xtr4yd4i5e0vw8g/iccv15_tutorial_training_rbg.pdf?dl=0)
 (specifically slide 38) for a description of alternating/stagewise training. Note that joint training which requires ~10-15% more memory in our current implementation is considerably simpler and faster.

**Comment by bendidi** [comment]
Thank you , I'll check it out ! 
I've tried joint training with lower resolution , and got somewhat worse results than separate training with bigger resolution
