### ISSUE TITLE
can't create operators implemented in detectron module

### ISSUE THREAD

**Issue by breadbread1984** [facebookresearch/Detectron#171]
I want to use operators provided in detectron module. I tried UpsampleNearest and got the following error message.

> E0221 11:07:40.414309  1997 operator.cc:130] Cannot find operator schema for UpsampleNearest. Will skip schema checking.
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at operator.cc:190] op. Cannot create operator of type 'UpsampleNearest' on the device 'CUDA'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "tensor1" output: "tensor2" type: "UpsampleNearest" arg { name: "scale" f: 2 } device_option { device_type: 1 }

The following code is what I tested.

```Protobuf
name: "test"
network {
name: "network1"
op {
	type: "GivenTensorFill"
	output: "tensor1"
	arg {
		name: "shape"
		ints: 1
		ints: 2
		ints: 3
		ints: 3
	}
	arg {
		name: "values"
		floats: 13
		floats: 22
		floats: 3
		floats: 14
		floats: 53
		floats: 26
		floats: 7
		floats: 38
		floats: 9
		
		floats: 11
		floats: 41
		floats: 15
		floats: 10
		floats: 54
		floats: 22
		floats: 92
		floats: 2
		floats: 8
	}
}
op {
	type: "UpsampleNearest"
	input: "tensor1"
	output: "tensor2"
	arg {
		name: "scale"
		f: 2
	}
}
op {
	type: "Print"
	input: "tensor2"
	arg {
		name: "to_file"
		i: 1
	}
}
device_option {
	device_type: 1
}
}
execution_step {
	network: "network1"
	num_iter: 1
}
```

**Comment by ir413** [comment]
Hi @breadbread1984, please provide more information about the installation steps you've taken, your system information and the exact command you're trying to run.

All of the operators from the Caffe2's detectron module are compiled into a [single library](https://github.com/caffe2/caffe2/blob/master/modules/detectron/CMakeLists.txt). So if you're able to succesully run one of the Detectron ops tests (e.g. for [`SpatialNarrowAs operator`](https://github.com/facebookresearch/Detectron/blob/master/tests/test_spatial_narrow_as_op.py#L88-L89); see instructions in [INSTALL.md](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md)), you should also be able to load the `UpsampleNearest` operator.

**Comment by breadbread1984** [comment]
I see python program uses InitOpsLibrary to load operators provided in modules. How can I use them with run_plan which is provided in caffe2 toolset. The above code is for run_plan. You may test it with 
```Bash
run_plan  --plan  path/to/this/code
```
I also want to use the operator in C++ environment. How can I link my deploy program properly with detectron operator module?

**Comment by breadbread1984** [comment]
information for my installation is given below.
OS: ubuntu 17.04
compiler version: gcc-6.3.0
cmake version: cmake-3.6.3
cmake argument: cmake .. -DCMAKE_INSTALL_PREFIX=/home/xieyi/opt/caffe2 -DCUDA_HOST_COMPILER=/usr/bin/gcc-5 -DUSE_NCCL=OFF -DUSE_NNPACK=OFF -DUSE_ROCKSDB=OFF
libraries version: CUDA 8.0.44 OpenCV-3.4.0

**Comment by ir413** [comment]
Following the [`module_test_dynamic.cc`](https://github.com/caffe2/caffe2/blob/fb4c82dd435c952681a6f7ea6e69c4def408d7f8/modules/module_test/module_test_dynamic.cc#L22) example from the Caffe2 repo, I think you should be able to load the Caffe2 Detectron module (`caffe2_detectron_ops_gpu` lib) in the same way.

**Comment by breadbread1984** [comment]
Thx for the clue. I finally figure it out. caffe2 provides a function called LoadModel in C++. I can create operators of detectron after the following code
```C++
LoadModel("","/path/to/libcaffe2_detectron_ops_gpu.so");
```
