### ISSUE TITLE
Failure in running Detectron test "SpatialNarrowAsOp" due to exclusion of libcaffe2_detectron_ops_gpu.so in library path

### ISSUE THREAD

**Issue by mikaelfs** [facebookresearch/Detectron#172]
### System information

* Operating system: Ubuntu 16.04LTS
* Compiler version: GCC 5.4.0
* CUDA version: 9.1.85
* cuDNN version: 7.0.5
* NVIDIA driver version: 390.30
* GPU models (for all devices if they are not all the same): GeForce GTX 1080 Ti 
* `PYTHONPATH` environment variable: /usr/local
* `python --version` output: 2.7.12

### Expected results

What did you expect to see?
Detectron test was properly executed and passed

### Actual results

What did you observe instead?
```
No handlers could be found for logger "caffe2.python.net_drawer"
net_drawer will not run correctly. Please install the correct dependencies.
E0221 13:02:30.755249 10303 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0221 13:02:30.755264 10303 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0221 13:02:30.755266 10303 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Traceback (most recent call last):
  File "/opt/detectron/tests/test_spatial_narrow_as_op.py", line 88, in <module>
    utils.c2.import_detectron_ops()
  File "/opt/detectron/lib/utils/c2.py", line 41, in import_detectron_ops
    detectron_ops_lib = envu.get_detectron_ops_lib()
  File "/opt/detectron/lib/utils/env.py", line 73, in get_detectron_ops_lib
    'version includes Detectron module').format(detectron_ops_lib)
AssertionError: Detectron ops lib not found at '/usr/local/lib/python2.7/dist-packages/lib/libcaffe2_detectron_ops_gpu.so'; make sure that your Caffe2 version includes Detectron module
```

### Detailed steps to reproduce

1. Install Caffe 2  from source with GPU support based on the instruction in [https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile)

2. Install Detectron based on instruction in [https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md)

3. Run the Detectron test to observe the error

```
$ python2 $DETECTRON/tests/test_spatial_narrow_as_op.py
```

This may be related with another issue previously reported #86 

### Root cause

When installing Caffe 2 from source, the `libcaffe2_detectron_ops_gpu.so` will be created / copied to `/usr/local/lib`. However, in `lib/utils/env.py`, the method `get_detectron_ops_lib()` when called will return Detectron library based on the directory of caffe2 module. With default install, the directory will be `/usr/local/lib/python2.7/dist-packages/caffe2` instead of `/usr/local/lib`. This way, the Detectron library is flagged as NOT EXISTS and error is raised

### Resolve

Without code change: copy `libcaffe2_detectron_ops_gpu.so` to `/usr/local/lib/python2.7/dist-packages/caffe2`

Code change: add additional logic to check the library location based on the location of `libcaffe2.so` or other similar approach

**Comment by ir413** [comment]
Hi @mikaelfs, thanks for the detailed description. If you set your `PYTHONPATH` to point to the Caffe2 build directory (`/path/to/caffe2/build`) Detectron should be able to find the Caffe2 detectron ops library. We plan to make the library search code more robust to this.

**Comment by ir413** [comment]
92f6cd6 should enable Detectron to find the ops lib in your setting.

**Comment by enzocheng0601** [comment]
Hi, @mikaelfs

I can't even find the file named "libcaffe2_detectron_ops_gpu.so", but I'm sure that I have already successfully installed caffe2 since I have tried the command "python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure" " and it returns "Success" back.

Does this mean the version of my caffe2 is so old that it doesn't include that library?

Thanks!

**Comment by mikaelfs** [comment]
@enzocheng0601 

Did you install the latest version of Caffe 2 by cloning the repo and building from source? When I posted the issue, other Caffe 2 distributables did not have Detectron module built into Caffe 2 executables (including the Docker image). 

The command `python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"` is used to detect whether Caffe 2 was installed properly. This, however, did not check if the Detectron module was also properly built into Caffe 2.

You need to run the test scripts (e.g. `test_spatial_narrow_as_op.py`) to check if your Caffe 2 build also supports Detectron module.

**Comment by ColinJLZhang** [comment]
> @enzocheng0601
> 
> Did you install the latest version of Caffe 2 by cloning the repo and building from source? When I posted the issue, other Caffe 2 distributables did not have Detectron module built into Caffe 2 executables (including the Docker image).
> 
> The command `python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"` is used to detect whether Caffe 2 was installed properly. This, however, did not check if the Detectron module was also properly built into Caffe 2.
> 
> You need to run the test scripts (e.g. `test_spatial_narrow_as_op.py`) to check if your Caffe 2 build also supports Detectron module.

Hi, @mikaelfs 

I met the same problem, I installed Caffe2 from the Docker imge. Is there a way to let me install Detectron module in a container? Do I have to reinstall Caffe2 by buliding from source to have Detectron module?

Thanks!

**Comment by mikaelfs** [comment]
> Hi, @mikaelfs
> 
> I met the same problem, I installed Caffe2 from the Docker imge. Is there a way to let me install Detectron module in a container? Do I have to reinstall Caffe2 by buliding from source to have Detectron module?
> 
> Thanks!

You can use this Dockerfile as the base to create a docker image for Detectron https://github.com/facebookresearch/Detectron/blob/master/docker/Dockerfile

Please note, the Dockerfile uses CUDA 9.0. You may need to check if there is a Caffe2 docker image that is built against more recent CUDA version.
