### ISSUE TITLE
How to get the coco dataset?

### ISSUE THREAD

**Issue by similsusan** [facebookresearch/Detectron#178]
Hey Guys,

I am new to this so I might be doing some mistake. I have successfully installed detectron and ran Inference without any issues. Now I am trying to run COCO dataset with 1 GPU. The Caffe2 installation was successful. 

I am getting the below error. Actually there is no images in coco_val2014 folder. 

'
Traceback (most recent call last):
  File "tools/test_net.py", line 127, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing)
  File "tools/test_net.py", line 98, in main
    output_dir, ind_range=ind_range, multi_gpu_testing=multi_gpu_testing
  File "/mnt/nvme/simsus/detectron/lib/core/test_engine.py", line 83, in run_inference
    results = parent_func(output_dir, multi_gpu=multi_gpu_testing)
  File "/mnt/nvme/simsus/detectron/lib/core/test_engine.py", line 106, in test_net_on_dataset
    all_boxes, all_segms, all_keyps = test_net(output_dir, gpu_id=gpu_id)
  File "/mnt/nvme/simsus/detectron/lib/core/test_engine.py", line 168, in test_net
    ind_range
  File "/mnt/nvme/simsus/detectron/lib/core/test_engine.py", line 288, in get_roidb_and_dataset
    roidb = dataset.get_roidb()
  File "/mnt/nvme/simsus/detectron/lib/datasets/json_dataset.py", line 109, in get_roidb
    self._prep_roidb_entry(entry)
  File "/mnt/nvme/simsus/detectron/lib/datasets/json_dataset.py", line 142, in _prep_roidb_entry
    assert os.path.exists(im_path), 'Image \'{}\' not found'.format(im_path)
AssertionError: Image '/mnt/nvme/simsus/detectron/lib/datasets/data/coco/coco_val2014/COCO_val2014_000000000724.jpg' not found'

I am not sure how to get the images. I went through the Readme.md to setup datasets, but could not find anything useful. Maybe I am missing something. 

### System information

* Operating system: Ubuntu 16.04
* Compiler version: GCC 5.4.0
* GPU models (for all devices if they are not all the same): GM200 [GeForce GTX TITAN X]
* `PYTHONPATH` environment variable: ../caffe2/build
* `python --version` output: Python 2.7.12

**Comment by mattifrind** [comment]
You need to download the data from the [COCO website](http://cocodataset.org/#download). Download the 2014 annotations and images and paste them in the folder as mentioned in the readme in the data folder. 
url)

**Comment by glhfgg1024** [comment]
...

**Comment by similsusan** [comment]
@mattifrind  It worked. Thanks a lot.

**Comment by BanuSelinTosun** [comment]
@mattifrind @gadcam 

Do you mean the train/val annotations? Can you give the exact names of the files in this link?
![image](https://user-images.githubusercontent.com/27472189/42716994-2460a408-86b3-11e8-83cc-19ed976d005d.png)
