### ISSUE TITLE
Failing to view/open output 33887522274_eebd074106_k.jpg.pdf after running mode successfully

### ISSUE THREAD

**Issue by partnercloudsupport** [facebookresearch/Detectron#179]
### Expected results

I expect to see the picture of pdf inference on file 34501842524_3c858b3080_k.jpg.pdf located in my tmp/detectron-visualizations folder

###What did you expect to see? 

A Picture of my image from pdf

### Actual results

What did you observe instead?
Failure to open pdf

### Detailed steps to reproduce
installed evince, gvfs-bin, fbi for fbgs, eog to view PDF file. ALL commands fail to open pdf
E.g.:

```
The command that you ran

gvfs-open 33887522274_eebd074106_k.jpg.pdf
```
System information:

Operating system: UBUNTU 16.04
Compiler version:
Timestamp : Tue Feb 20 06:45:13 2018
Driver Version : 390.30

Attached GPUs : 4
GPU 00000000:00:03.0
Product Name : GRID K520
Product Brand : Grid

GPU models (for all devices if they are not all the same): AWS AMI
PYTHONPATH environment variable:
~/src/caffe2/caffe2$ echo $PYTHONPATH
/home/ubuntu/src/caffe2/build:/home/ubuntu/src/caffe2/caffe2/build:
/home/ubuntu/src/caffe2/caffe2/cmake:
/home/ubuntu/src/caffe2/build:/home/ubuntu/src/caffe2/caffe2/python:
/home/ubuntu/src/caffe2/caffe2/python/operator_test:/home/ubuntu/src/caffe2/build (TRIED EVERYTHING!)
python --version output: 2.7

Additional information:

Can the team provide away to view output to tmp/detectron-visualitions after running 
python tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west 2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo

I would like to see if the model is running correctly and applying mask to picture. Please advise.  Thank you.

**Comment by ir413** [comment]
Hi @partnercloudsupport, if the visualization gets created but you're having issues with opening the pdf this is likely not a Detectron issue. It seems that you're running the demo remotely, so you may want to try `scp`ing the pdf and opening it locally for simplicity.

**Comment by partnercloudsupport** [comment]
Thank you. Your were correct. I used sftp command to download pdf to my local system. Thanks for your support.

Take care!

**Comment by manyaafonso** [comment]
Hi @ir413 and @partnercloudsupport , I have the same problem. I am using docker and running the python script with 
nvidia-docker run --rm -it my_detectron:latest python2 tools/infer_simple.py ...

How and where should I use the scp or sftp command to download the result pdfs?
