### ISSUE TITLE
Non-pdf output

### ISSUE THREAD

**Issue by sh0gg0th** [facebookresearch/Detectron#180]
### Expected results
Is there a way to output raw detection results? Ideally, I would like to be able to produce a JSON that would include for each object class the count of detected objects and their share of the total image area - where should I start looking? Thanks.

### Actual results

What did you observe instead?

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by fabito** [comment]
You can create a new script based on [infer_simple.py](https://github.com/facebookresearch/Detectron/blob/master/tools/infer_simple.py#L128) but instead of generating a PDF ( `vis_utils.vis_one_image()` ) you could just print the data you need to a file.

**Comment by kampelmuehler** [comment]
@sh0gg0th after an inference run a file detections.pkl is written to the output folder, which contains all the raw detections.

**Comment by luisriera** [comment]
Hello there,

@kampelmuehler, is there a way to activate `detections.pkl` from `infer_simple.py` or I have to make my own script?

**Comment by kampelmuehler** [comment]
`detections.pkl` is created automatically whenever you run inference. At least as of February 18.

**Comment by javi-clear-image-ai** [comment]
> `detections.pkl` is created automatically whenever you run inference. At least as of February 18.

do you know where exactly? not found in tmp
