### ISSUE TITLE
Anyone who can train the custom dataset successfully?

### ISSUE THREAD

**Issue by nonstop1962** [facebookresearch/Detectron#183]
Hi, I tried several custom dataset to train the retina net (all types like res-101, res-51 ...).

I double checked that my dataset is correctly made in COCO dataset format. 

However, the retinanet detection result of all of the custom datasets is unsatisfied (After training around 90000 iterations, I run test function to the training images again, but it cannot even detect the features on the training images). 
The dataset has around 600 training images. When I train it with YOLO V2, the result is really good (it converges after only around 30 minutes of training).

The number of data of my dataset is not sufficient to train this framework?
Anyone, who get the satisfied result with his/her custom dataset?

**Comment by HilmiK** [comment]
Hi,

I have trained my custom dataset using faster_rcnn_R-50-FPN.yaml . I had 12,628 images with different sizes and achieved around %98 accuracy which is really good for my task without changing any configuration.

**Comment by kampelmuehler** [comment]
Beware of issue #93, if you are training with a number of classes that is different from 81 (coco)

**Comment by rbgirshick** [comment]
FYI, the fix was merged in 1624f810a4e0a5bac924c4e6abe2b31f66a986aa.

**Comment by jwnsu** [comment]
See latest result #188, while improved from the fix, it seems there is still issue somewhere with retinanet.

**Comment by gadcam** [comment]
This issue should be closed.

**Comment by anguoyang** [comment]
@nonstop1962 I have the same problem with you, have you solved it?
