### ISSUE TITLE
Train Faster R-CNN with different backbone

### ISSUE THREAD

**Issue by marinaKollmitz** [facebookresearch/Detectron#184]
Thanks you very much for this great project! Could you please help me training Faster R-CNN with another backbone architecture, for example GoggleNet. I used the pickle_caffe_blobs.py script to convert the pretrained bvlc_googlenet.caffemodel to a .pkl model as mentioned [at issue 77](https://github.com/facebookresearch/Detectron/issues/71). But how can I train with it? Do I need to setup a .py file for the model like the VGG16.py in lib/modeling? Or is there a way to generate this file as well?  Thank you for your help!

**Comment by youngwanLEE** [comment]
+1

**Comment by filipetrocadoferreira** [comment]
+2

**Comment by marinaKollmitz** [comment]
I now implemented the conv body for the network in python and used the converted .pkl file as pretrained weights. To convert the .caffemodel weights to the pickle file, I only kept the conv body part of the network in the deploy.prototxt file. Here is my python implementation, in case anyone is interested. It is a smaller version of the GoogLeNet, called GoogLeNet-xxs, described [here](https://arxiv.org/pdf/1707.05733.pdf). The original network has more inception parts:

    def add_googlenet_xxs_conv5_body(model):
    
        model.Conv('data', 'conv1-7x7_s2', 3, 64, 7, pad=3, stride=2)
        model.Relu('conv1-7x7_s2', 'conv1-7x7_s2')
        model.MaxPool('conv1-7x7_s2', 'pool1-3x3_s2', kernel=3, pad=0, stride=2)     
        model.LRN('pool1-3x3_s2', 'pool1-norm1', size=5, alpha=0.0001, beta=0.75)
    
        #stop gradient?
        #model.StopGradient('pool1-norm1', 'pool1-norm1')
        model.Conv('pool1-norm1', 'conv2-3x3_reduce', 64, 64, 1, pad=0, stride=1) #input size=?
        model.Relu('conv2-3x3_reduce', 'conv2-3x3_reduce')
        model.Conv('conv2-3x3_reduce', 'conv2-3x3', 64, 192, 3, pad=1, stride=1)
        model.Relu('conv2-3x3', 'conv2-3x3')
        model.LRN('conv2-3x3', 'conv2-norm2', size=5, alpha=0.0001, beta=0.75)
        model.MaxPool('conv2-norm2', 'pool2-3x3_s2', kernel=3, stride=2, pad=0)
    
        #inception 3a
        model.Conv('pool2-3x3_s2', 'inception_3a-1x1', 192, 64, 1, pad=0, stride=1)
        model.Relu('inception_3a-1x1', 'inception_3a-1x1')
        model.Conv('pool2-3x3_s2', 'inception_3a-3x3_reduce', 192, 96, 1, pad=0, stride=1)
        model.Relu('inception_3a-3x3_reduce', 'inception_3a-3x3_reduce')
        model.Conv('inception_3a-3x3_reduce', 'inception_3a-3x3', 96, 128, 3, pad=1, stride=1)
        model.Relu('inception_3a-3x3', 'inception_3a-3x3')
        model.Conv('pool2-3x3_s2', 'inception_3a-5x5_reduce', 192, 16, 1, pad=0, stride=1)
        model.Relu('inception_3a-5x5_reduce', 'inception_3a-5x5_reduce')
        model.Conv('inception_3a-5x5_reduce', 'inception_3a-5x5', 16, 32, 5, pad=2, stride=1)
        model.Relu('inception_3a-5x5', 'inception_3a-5x5')
        model.MaxPool('pool2-3x3_s2', 'inception_3a-pool', kernel=3, stride=1, pad=1)
        model.Conv('inception_3a-pool', 'inception_3a-pool_proj', 192, 32, 1, stride=1, pad=0)
        model.Relu('inception_3a-pool_proj', 'inception_3a-pool_proj')
        model.Concat(['inception_3a-1x1','inception_3a-3x3', 'inception_3a-5x5', 'inception_3a-pool_proj'], 'inception_3a-output')
    
        #inception 3b
        model.Conv('inception_3a-output', 'inception_3b-1x1', 256, 128, 1, pad=0, stride=1)
        model.Relu('inception_3b-1x1', 'inception_3b-1x1')
        model.Conv('inception_3a-output', 'inception_3b-3x3_reduce', 256, 128, 1, pad=0, stride=1)
        model.Relu('inception_3b-3x3_reduce', 'inception_3b-3x3_reduce')
        model.Conv('inception_3b-3x3_reduce', 'inception_3b-3x3', 128, 192, 3, pad=1, stride=1)
        model.Relu('inception_3b-3x3', 'inception_3b-3x3')
        model.Conv('inception_3a-output', 'inception_3b-5x5_reduce', 256, 32, 1, pad=0, stride=1)
        model.Relu('inception_3b-5x5_reduce', 'inception_3b-5x5_reduce')
        model.Conv('inception_3b-5x5_reduce', 'inception_3b-5x5', 32, 96, 5, pad=2, stride=1)
        model.Relu('inception_3b-5x5', 'inception_3b-5x5')
        model.MaxPool('inception_3a-output', 'inception_3b-pool', kernel=3, stride=1, pad=1)
        model.Conv('inception_3b-pool', 'inception_3b-pool_proj', 256, 64, 1, pad=0, stride=1)
        model.Relu('inception_3b-pool_proj', 'inception_3b-pool_proj')
        model.Concat(['inception_3b-1x1', 'inception_3b-3x3', 'inception_3b-5x5', 'inception_3b-pool_proj'], 'inception_3b-output')
    
        model.MaxPool('inception_3b-output', 'pool3-3x3_s2', kernel=3, stride=2, pad=0)
    
        #inception 4a
        model.Conv('pool3-3x3_s2', 'inception_4a-1x1', 480, 192, 1, pad=0, stride=1)
        model.Relu('inception_4a-1x1', 'inception_4a-1x1')
        model.Conv('pool3-3x3_s2', 'inception_4a-3x3_reduce', 480, 96, 1, pad=0, stride=1)
        model.Relu('inception_4a-3x3_reduce', 'inception_4a-3x3_reduce')
        model.Conv('inception_4a-3x3_reduce', 'inception_4a-3x3', 96, 208, 3, pad=1, stride=1)
        model.Relu('inception_4a-3x3', 'inception_4a-3x3')
        model.Conv('pool3-3x3_s2', 'inception_4a-5x5_reduce', 480, 16, 1, pad=0, stride=1)
        model.Relu('inception_4a-5x5_reduce', 'inception_4a-5x5_reduce')
        model.Conv('inception_4a-5x5_reduce', 'inception_4a-5x5', 16, 48, 5, pad=2, stride=1)
        model.Relu('inception_4a-5x5', 'inception_4a-5x5')
        model.MaxPool('pool3-3x3_s2', 'inception_4a-pool', kernel=3, stride=1, pad=1)
        model.Conv('inception_4a-pool', 'inception_4a-pool_proj', 480, 64, 1, pool=0, stride=1)
        model.Relu('inception_4a-pool_proj', 'inception_4a-pool_proj')
        blob_out = model.Concat(['inception_4a-1x1', 'inception_4a-3x3', 'inception_4a-5x5', 'inception_4a-pool_proj'], 'inception_4a-output')
   
        return blob_out, 512, 1. / 16.`

I am still curious if there is a way to load a network without implementing the network structure in python. Since issue #339 targets this question a little more in detail, I will close this issue here.

**Comment by marinaKollmitz** [comment]
Short answer: You can download my generated pretrained weights for the GoogLeNet-xxs [here](http://www2.informatik.uni-freiburg.de/~kollmitz/googlenet_xxs.pkl)

Longer answer, how I generated the file: In general, what I did is download the .caffemodel and deploy.prototxt from the caffe model zoo [here](https://github.com/BVLC/caffe/tree/master/models/bvlc_googlenet). Then I deleted everything from the deploy.txt except the convolution part I want to train with. Next I fed it to the detectron/tools/pickle_caffe_blobs.py script. 

Some details: I had to rename the layers in the implementation, because detectron strips off the layer names before the last / when saving the blobs to model_final.pkl. I replaced all "/"s with "-"s in the layer names. As a consequence, I also had to rename the blobs in the pretrained.pkl file. I changed one part in the pickle_caffe_blobs.py script to rename the blobs when saving to file:

    def normalize_googlenet_name(name):
        name = name.replace('/', '-')
        return name

    def pickle_weights(out_file_name, weights):
        blobs = {
            normalize_googlenet_name(blob.name): utils.Caffe2TensorToNumpyArray(blob)
            for blob in weights.protos
        }
        with open(out_file_name, 'w') as f:
            pickle.dump(blobs, f, protocol=pickle.HIGHEST_PROTOCOL)
        print('Wrote blobs:')
        print(sorted(blobs.keys()))

I will upload everything to my fork soon, in the meantime, I hope it helps.

**Comment by filipetrocadoferreira** [comment]
Thank you so much. Good Work. I'll give a try.

**Comment by rohit-toha** [comment]
Hi @marinaKollmitz ,

Awesome work. Thanks for defining CONV body method. Have you also defined a similar method for Fully connected layers? 

Does the method defining fully connected layer scheme has similar structure to that of VGG?

Thanks again

**Comment by marinaKollmitz** [comment]
I just copied the VGG fully connected layers.

**Comment by rohitbhio** [comment]
@marinaKollmitz : Thanks for confirmation. I did use VGG FC layers.

**Comment by srikanth-kilaru** [comment]
Hi @marinaKollmitz 
I did try using the googlenet backbone like in your code example, and I ran into compilation issues. Did you encountering anything like this -
==============================================================
INFO detector.py: 479: Changing learning rate 0.000000 -> 0.001667 at iter 0
I0528 01:35:16.227145 25798 context_gpu.cu:314] GPU 0: 461 MB
I0528 01:35:16.227205 25798 context_gpu.cu:314] GPU 1: 447 MB
I0528 01:35:16.227210 25798 context_gpu.cu:318] Total: 909 MB
I0528 01:35:16.865536 25813 context_gpu.cu:314] GPU 0: 470 MB
I0528 01:35:16.865597 25813 context_gpu.cu:314] GPU 1: 595 MB
I0528 01:35:16.865605 25813 context_gpu.cu:318] Total: 1065 MB
I0528 01:35:16.890810 25813 context_gpu.cu:314] GPU 0: 470 MB
I0528 01:35:16.890851 25813 context_gpu.cu:314] GPU 1: 769 MB
I0528 01:35:16.890856 25813 context_gpu.cu:318] Total: 1239 MB
I0528 01:35:16.918826 25813 context_gpu.cu:314] GPU 0: 574 MB
I0528 01:35:16.918845 25813 context_gpu.cu:314] GPU 1: 856 MB
I0528 01:35:16.918850 25813 context_gpu.cu:318] Total: 1431 MB
I0528 01:35:16.927848 25814 context_gpu.cu:314] GPU 0: 652 MB
I0528 01:35:16.927870 25814 context_gpu.cu:314] GPU 1: 912 MB
I0528 01:35:16.927876 25814 context_gpu.cu:318] Total: 1564 MB
I0528 01:35:16.940279 25818 context_gpu.cu:314] GPU 0: 729 MB
I0528 01:35:16.940299 25818 context_gpu.cu:314] GPU 1: 970 MB
I0528 01:35:16.940304 25818 context_gpu.cu:318] Total: 1699 MB
I0528 01:35:16.958897 25819 context_gpu.cu:314] GPU 0: 807 MB
I0528 01:35:16.959033 25819 context_gpu.cu:314] GPU 1: 1071 MB
I0528 01:35:16.959136 25819 context_gpu.cu:318] Total: 1878 MB
I0528 01:35:16.971148 25815 context_gpu.cu:314] GPU 0: 864 MB
I0528 01:35:16.971170 25815 context_gpu.cu:314] GPU 1: 1143 MB
I0528 01:35:16.971177 25815 context_gpu.cu:318] Total: 2008 MB
I0528 01:35:16.983958 25817 context_gpu.cu:314] GPU 0: 946 MB
I0528 01:35:16.983981 25817 context_gpu.cu:314] GPU 1: 1197 MB
I0528 01:35:16.984001 25817 context_gpu.cu:318] Total: 2143 MB
I0528 01:35:17.016728 25817 context_gpu.cu:314] GPU 0: 1075 MB
I0528 01:35:17.016748 25817 context_gpu.cu:314] GPU 1: 1205 MB
I0528 01:35:17.016753 25817 context_gpu.cu:318] Total: 2280 MB
E0528 01:35:17.107506 25814 net_dag.cc:195] Secondary exception from operator chain starting at '' (type 'SmoothL
1Loss'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:156] . Encountered CUDA error: an illegal memory a
ccess was encountered Error from operator: 
input: "gpu_0/rpn_bbox_pred" input: "gpu_0/rpn_bbox_targets" input: "gpu_0/rpn_bbox_inside_weights" input: "gpu_0
/rpn_bbox_outside_weights" output: "gpu_0/loss_rpn_bbox" name: "" type: "SmoothL1Loss" arg { name: "beta" f: 0.11
1111112 } arg { name: "scale" f: 0.5 } device_option { device_type: 1 cuda_gpu_id: 0 }
E0528 01:35:17.107525 25819 net_dag.cc:195] Secondary exception from operator chain starting at '' (type 'Add'): 
caffe2::EnforceNotMet: [enforce fail at context_gpu.h:156] . Encountered CUDA error: an illegal memory access was
 encountered Error from operator: 
input: "gpu_0/rpn_cls_logits_w_grad" input: "gpu_1/rpn_cls_logits_w_grad" output: "gpu_0/rpn_cls_logits_w_grad" n
ame: "" type: "Add" device_option { device_type: 1 cuda_gpu_id: 0 }
F0528 01:35:17.107550 25814 context_gpu.h:107] Check failed: error == cudaSuccess an illegal memory access was en
countered
*** Check failure stack trace: ***
F0528 01:35:17.107571 25817 context_gpu.h:107] Check failed: error == cudaSuccess an illegal memory access was en
counteredF0528 01:35:17.107580 25818 context_gpu.h:107] Check failed: error == cudaSuccess an illegal memory acce
ss was encounteredF0528 01:35:17.107589 25816 context_gpu.h:107] Check failed: error == cudaSuccess an illegal me
mory access was encounteredF0528 01:35:17.107617 25819 context_gpu.h:107] Check failed: error == cudaSuccess an i
llegal memory access was encountered
*** Check failure stack trace: ***
F0528 01:35:17.107571 25817 context_gpu.h:107] Check failed: error == cudaSuccess an illegal memory access was en
counteredF0528 01:35:17.107580 25818 context_gpu.h:107] Check failed: error == cudaSuccess an illegal memory acce
ss was encounteredF0528 01:35:17.107589 25816 context_gpu.h:107] Check failed: error == cudaSuccess an illegal me
mory access was encounteredF0528 01:35:17.107617 25819 context_gpu.h:107] Check failed: error == cudaSuccess an i
llegal memory access was encountered
Aborted (core dumped)

**Comment by srikanth-kilaru** [comment]
Problem solved by following recommendation at https://github.com/facebookresearch/Detectron/issues/32 to USE_NCCL True

**Comment by johannathiemich** [comment]
Could you please explain how I can make use of that .pkl file you provided?
Just loading the .pkl file without changing anything in the config file does not seem to work. 

I tried adding the code from your post (add_googlenet_xxs_conv5_body(model)) to the FPN.py file and referenced the method in the corresponding config file when using your provided .pkl file. 
But I got an error saying that the blob returned by the add_google_net method does not have attribute "len" therefore an assertion failed. It seems to expect a list of tensors but since the last layer is a Concat layer, only one tensor is returned I think.

So how did you make all of this work? Which changes do I have to make?
