### ISSUE TITLE
Installation error: nvcc fatal   : redefinition of argument 'std'

### ISSUE THREAD

**Issue by hazirbas** [facebookresearch/Detectron#185]
Hi,
I m trying to compile the detectron with CUDA 8 and CUDNN 6.0.21 on UBUNTU (GTX 1080).
Although I can successfully compile caffe2, detectron ops are not compiled.

cmake conf. and the error:

-- Caffe2: Cannot find gflags automatically. Using legacy find.
-- Caffe2: Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Caffe2: CUDA detected: 8.0
-- Found cuDNN: v6.0.21  (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Added CUDA NVCC flags for: sm_60 sm_61
-- CUDA detected: 8.0
-- Added CUDA NVCC flags for: sm_60 sm_61
-- Found libcuda: /usr/local/cuda-8.0/lib64/stubs/libcuda.so
-- Found libnvrtc: /usr/local/cuda-8.0/lib64/libnvrtc.so
-- Found cuDNN: v6.0.21  (include: /usr/local/cuda-8.0/include, library: /usr/local/cuda-8.0/lib64/libcudnn.so)
-- Summary:
--   CMake version        : 3.5.1
--   CMake command        : /usr/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 5.4.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.1
--   Caffe2 include path  : /work/libs/caffe2/install/include
--   Have CUDA            : TRUE
--     CUDA version       : 8.0
--     CuDNN version      : 6.0.21
-- Configuring done
-- Generating done
-- Build files have been written to: /work/detectron/lib/build

[ 20%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
make[3]: Leaving directory '/work/detectron/lib/build'
[ 60%] Built target caffe2_detectron_custom_ops
**nvcc fatal   : redefinition of argument 'std'
CMake Error at caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o.cmake:203 (message):
  Error generating**
  /work/detectron/lib/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/./caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

Looking forward to your response!

**Comment by hazirbas** [comment]
I also have to add the arch_name flag for cmake;

cmake .. -DCMAKE_PREFIX_PATH=/work/libs/caffe2/install -DCUDA_ARCH_NAME=Pascal

**Comment by hazirbas** [comment]
Yes, you are right. I wasn't on the right branch for the ops. 
However, if one doesnt install caffe2 globally, he/she should copy <caffe2_install_path>/lib/lib* files into <caffe2_install_path>/lib/python2.7/site-packages/lib folder.

Thanks for the help.

**Comment by Erotemic** [comment]
@kampelmuehler I don't see how detectron doesn't build anything. In the Detectron/lib folder there is a CMakeLists.txt that is referenced by the Makefile also included. Without building the items in the lib folder there is no reference to the `caffe2_detectron_custom_ops_gpu.so` library. 

However, I was able to work around this issue and get this library to build. I did this by commenting out line 208 in `Detectron/lib/cmake/Cuda.cmake`:

```cmake
  #list(APPEND CUDA_NVCC_FLAGS "-std=c++11")
```

which seemed to cause the redefinition error. I'm not a C++ master by any means, so I don't know how fragile of a fix this is. I'm using gcc 5.4.0.

**Comment by yanxiangyi** [comment]
@Erotemic This works on my machine! Thanks a lot!
