### ISSUE TITLE
Conda caffe2 and libcaffe2_detectron_ops_gpu.so not where it should be

### ISSUE THREAD

**Issue by baristahell** [facebookresearch/Detectron#187]
So, i installed Caffe2 on a CentOS computer using Conda, but the detectron module can't be found.

`AssertionError: Detectron ops lib not found at '/home/usr/anaconda3/envs/p2/lib/python2.7/site-packages/lib/libcaffe2_detectron_ops_gpu.so'; make sure that your Caffe2 version includes Detectron module`

I checked and it's actually there, but not at the right path : 
`/home/usr/anaconda3/envs/p2/lib/libcaffe2_detectron_ops_gpu.so`

How can i solve this and make it so the module is found? I tried playing with PYTHONPATH and LD_LIBRARY_PATH but can't seem to find a workaround.
Thank you.

**Comment by ir413** [comment]
Hi @baristahell, rebasing on 92f6cd6 may resolve your issue. Alternatively, setting your` PYTHONPATH` to point to the Caffe2 build directory (`/path/to/caffe2/build`) should allow Detectron to find the ops lib.

**Comment by baristahell** [comment]
Thanks, i ended up building the docker image but it's noted if i need to reinstall everything! ;)

**Comment by ZeyuFu** [comment]
I have the same issue with ya, how did you address that?

Thanks
