### ISSUE TITLE
retinet (or focal loss) accuracy issue (was issue #93)

### ISSUE THREAD

**Issue by jwnsu** [facebookresearch/Detectron#188]
didn't find a way to reopen #93 issue, so create a new one here.

-----
Thx for committed fix, accuracy is much improved on a non-coco dataset, VOC2012 mean mAP from ~0.5 to >0.75, with ResNet50 backbone. 

However, there are still 4 objects with 0 mAP (reduced from 7  0-mAP objects previously), those 4 objects all have >0.9 mAP with faster rcnn model in this repository using identical dataset setup. Tried a different ResNxt 32x8 backbone with Retinanet, the same 4 objects still have 0 mAP.  It seems either retinanet's training data generation or focus training does not generate training for those 4 objects. The 4 0-mAP objects have id 3,4,5,8 -- they are neither beginning nor ending ids.

Due to the issue, accuracy of this repository's retinanet (with 800x1333 scale size) on tested non-coco dataset is below other single-stage detectors (e.g. SSD, Yolov2, they have much smaller scale sizes).

**Comment by EgorAntonovich** [comment]
Hi, how  run a script to receive the accuracy of my model?

**Comment by jwnsu** [comment]
Figured out it's due to retinanet has different logic to generate anchors from faster rcnn. The issue is now resolved with change.

**Comment by TinaLiuCV** [comment]
@jwnsu could you share the changes you made for the training? I got the 0mAP for my own dataset. Thanks!
