### ISSUE TITLE
ImportError: cannot import name task_evaluation

### ISSUE THREAD

**Issue by zhangjinsong3** [facebookresearch/Detectron#20]
Traceback (most recent call last):
  File "tools/infer_simple.py", line 42, in <module>
    import core.test_engine as infer_engine
  File "/home/user523/zjs/detectron/lib/core/test_engine.py", line 36, in <module>
    from datasets import task_evaluation
ImportError: cannot import name task_evaluation

I have added ``detectron/lib`` to pythonpath,but it still can not work.

**Comment by jungalwala** [comment]
I have the same issue.

**Comment by ir413** [comment]
Hi @zhangjinsong3 and @jungalwala, we're unable to reproduce this issue on our side.

Could you please both provide us with more information, which might help us identify the issue?

In particular:

- Operating system: ?
- Python version: ?
- Python environment: ? (if applicable)
- `setuptools` version: ?
- `Cython` version: ?
- Anything else that seems relevant: ?

**Comment by XYAskWhy** [comment]
Hi @ir413 , I have the same issue as well. Ubuntu16.04, Python2.7.12, setuptools 38.4.0, Cython 0.27.3. It seems really odd, because Pycharm doesn't give any warning or raise error.

**Comment by Labyrins** [comment]
I am in the same trouble.
The problem is that...
even though I have set ``detectron/lib`` in PATHONPATH and check it fine by ``echo $PYTHONPATH``,
py files in ``detectron/lib`` does not be imported.

**Comment by XYAskWhy** [comment]
@Labyrins , maybe you just forgot to do “cd $DETECTRON/lib && make” in the INSTALL.md.

**Comment by Labyrins** [comment]
@XYAskWhy Nope. I already did that and does not work.. thanks for your comment.

**Comment by zhangjinsong3** [comment]
Hi @ir413 ,my computer is Ubuntu 16.04 ,python 2.7 , setuptools 38.4.0, Cython 0.23.4, opencv-python 3.4.0.12..thanks for your comment.

**Comment by withyou1771** [comment]
I have the same issue.

**Comment by assafmus** [comment]
I had the same issue. I've solved the problem by removing tensorflow from the python path.
I assume this might also be the case for some of you who are having this problem.

**Comment by ir413** [comment]
Hi @XYAskWhy and @zhangjinsong3, thank you for the details. We are not able to reproduce this issue using the system/package versions you posted above.

Could you please provide information about the exact installation steps you took (w/ commands) and the command you are running when seeing this error? Please also include the complete output of running `make` under `$DETECTRON/lib`.

Additionally, please include the output of the following two commands:
```
python2 -c "from distutils import sysconfig; print(sysconfig.get_python_lib())"
python2 -c "from distutils import sysconfig; print(sysconfig.get_python_inc())"
```

**Comment by jungalwala** [comment]
@assafmus That was the cause of my issue, too!

**Comment by slavikf** [comment]
75

**Comment by zhangjinsong3** [comment]
@assafmus It works for me too，although I don't know why.Thanks very much!

**Comment by Labyrins** [comment]
@assafmus Thank you so much for your tip! Now, it works!

**Comment by XYAskWhy** [comment]
@assafmus It works well for me, many thanks. For the record, @ir413 , I removed `models/research` and `models/research/slim` from the python path, which are required by TensorFlow's Object Detection API. Does this mean Google and Facebook even compete in the PYTHONPATH? Just kidding, hope this issue could be solved soon.

**Comment by ppwwyyxx** [comment]
There is a "datasets" submodule in slim: https://github.com/tensorflow/models/tree/master/research/slim/datasets.

**Comment by XYAskWhy** [comment]
@ppwwyyxx  exactly

**Comment by ir413** [comment]
Thanks all. `datasets` is likely a common module name, which could lead to import conflicts as in the case of tensorflow many of you encountered. We will add a note about this to the troubleshooting section and look into addressing this further.
