### ISSUE TITLE
One Question about the RPN Labels

### ISSUE THREAD

**Issue by lwher** [facebookresearch/Detectron#203]
Hello,
in lib/roi_data/rpn.py , I find this code may be used to generate the label of rpn anchors.
However, in line 259 - 260, I see:
H = foa.field_size
W = foa.field_size

H and W means the labels shape should be (1, H, W, A). This requests the input scale of image should be square, but I can't find the resize part. Is there something wrong in my understanding?

Thanks for your helps!

**Comment by rbgirshick** [comment]
The RPN training labels are generated on a square that is at least as large as the largest training sample. The label array is then "narrowed" down to the appropriate (likely non-square) size using the `SpatialNarrowAs` op. See, for example: https://github.com/facebookresearch/Detectron/blob/05d04d3a024f0991339de45872d02f2f50669b3d/lib/modeling/rpn_heads.py#L127

**Comment by lwher** [comment]
@rbgirshick  Get! Thanks a lot!
