### ISSUE TITLE
how to create my own coco-like dataset?

### ISSUE THREAD

**Issue by Vivianyzw** [facebookresearch/Detectron#204]
1. Is there any API able to make coco-like annotations? I have used labelme, but it can just generate single json file and the contains is not similar with coco, like info, segmentation, and so on.

2. I have a set of data with Pascal format, is there any  API able to transform Pascal format to coco format directly? It has the same problem that I just have single xml file and maskpng file, but I found that coco-like annotations that detectron used are combined, instances_train_2017.json

If you create coco-like dataset successfully, could you please give me some advice?

I appreciate it in advance!

**Comment by Lydia0402** [comment]
Why not write a script yourself to combine the single files together?

**Comment by soumenms2015** [comment]
@Lydia0402 : Are you able to run Mask RCNN without any issue of Loss is NaN?

**Comment by Vivianyzw** [comment]
@Lydia0402 Do you have any idea that which attributes of the coco-like json file are necessary to train a model?  Such as info ,description, url, version, year,contributor, data_created, images (license,coco_url...)

**Comment by kampelmuehler** [comment]
Since this is highly dependent on your data, it is best to first take a look at converted datasets here: http://cocodataset.org/#external . There you can find eg. ImageNet or VOC in COCO format. This should then give you an idea of how to convert. The format is described here: http://cocodataset.org/#download , although I have to admit that it is a little confusing at first.

**Comment by Vivianyzw** [comment]
@kampelmuehler That is so kind of you. It helps a lot. I will try it step by step. Thanks for your advice!

**Comment by Vivianyzw** [comment]
@kampelmuehler Hi, I succeeded in creating coco-like json file now. I replaced VOC2012 to my own data with only "vehicle" class, and also change "NUM CLASSES 21" into 1 in yaml file. But I got an error like this:
```
Traceback (most recent call last):
  File "tools/train_net.py", line 358, in <module>
    main()
  File "tools/train_net.py", line 196, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 210, in train_model
    setup_model_for_training(model, output_dir)
  File "tools/train_net.py", line 308, in setup_model_for_training
    add_model_training_inputs(model)
  File "tools/train_net.py", line 332, in add_model_training_inputs
    cfg.TRAIN.DATASETS, cfg.TRAIN.PROPOSAL_FILES
  File "/mnt/data1/detectron/lib/datasets/roidb.py", line 71, in combined_roidb_for_training
    _compute_and_log_stats(roidb)
  File "/mnt/data1/detectron/lib/datasets/roidb.py", line 180, in _compute_and_log_stats
    classes = roidb[0]['dataset'].classes
IndexError: list index out of range
```

Could you please tell me how to deal with this problem? Thanks in advance!

**Comment by gemfield** [comment]
There is a python script that can translate original PASCAL VOC xml to json format: https://github.com/CivilNet/Gemfield/blob/master/src/python/pascal_voc_xml2json/pascal_voc_xml2json.py

And, there also has a related blog for Chinese readers: https://zhuanlan.zhihu.com/p/34036460

**Comment by hanskrupakar** [comment]
I've created a very simple GUI-based widget to create polygon masks and store it in the same JSON format as COCO's annotation file to create a dataset from scratch. Here's the link: [https://github.com/Deep-Magic/COCO-Style-Dataset-Generator-GUI](https://github.com/Deep-Magic/COCO-Style-Dataset-Generator-GUI). Hopefully it can be of some use.

**Comment by soumenms2015** [comment]
@gemfield , did you try to load the generated data into pycocotools api as it was not able to as there is binary mask .

**Comment by soumenms2015** [comment]
My question is , did you visualize the converted json data in pycocotools? Did you successfully able to run any model in your json dataset?

**Comment by gemfield** [comment]
@soumenms2015  Yes, I did successfully train my model based on the json dataset.

**Comment by sharoseali** [comment]
gemfield  i have to convert my xml annotated files written in pascal voc to coco data set for YOLO object detection. Is the file you have mentioned above will really work for me ????
i am asking bcz i have very short time. and i don't want to waste it kindly please reply.....
THanxxxx in advance

**Comment by BanuSelinTosun** [comment]
@gemfield I see you did a great explaination on your blog post for detectron here: https://zhuanlan.zhihu.com/p/34036460
Would you please write a version of the same thing in English? I don't speak Chinese and I am not sure I can trust Google translation on this subject. :) It would be great if you can share your knowledge. 

Thanks,
Selin

**Comment by adjagetia** [comment]
Manually tagging the data is not more a hurdle. Check this out,
https://www.youtube.com/watch?v=tYqnsp-OcLQ
https://www.youtube.com/watch?v=xkSEnDIlvhI
you can quickly create your own image and video segmentation data in no time!!

Neurala’s Brain Builder Tool: https://hubs.ly/H0dkvRK0

**Comment by jsbroks** [comment]
I'm working on a [python library](https://github.com/jsbroks/imantics) that can help convert and mange between different datasets (including COCO and VOC).

**Comment by Manishsinghrajput98** [comment]
How to make coco dataset from scratch complete tutorial

https://www.youtube.com/watch?v=MrXlCD3UfZY
