### ISSUE TITLE
Can mask rcnn achieve the similar result when trained by end-to-end manner compared with alternative one?

### ISSUE THREAD

**Issue by mks0601** [facebookresearch/Detectron#207]
I noticed that there are also config files for end-to-end training, but there it is not mentioned that end-to-end training achieves similar result compared with alternatively trained ones. 

Can mask rcnn achieve the similar result when trained by end-to-end manner compared with alternative one? I`m especially curious whether end-to-end training gives accurate keypoint localization result compared with alternative ones or not.

**Comment by KaimingHe** [comment]
The end-to-end results are in: https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#end-to-end-faster--mask-r-cnn-baselines

Comparing this table with the table above (step-wise training), all numbers are improved by e2e training.

**Comment by siyiding1216** [comment]
I tried to use 12_2017_baselines/e2e_mask_rcnn_R-101-FPN_1x.yaml  for e2e training but I only got 22mAP on bbox
INFO json_dataset_evaluator.py: 232: ~~~~ Summary metrics ~~~~
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.223
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.415
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.215
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.099
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.236
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.319
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.220
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.351
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.373
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.179
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.408
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.515
INFO json_dataset_evaluator.py: 199: Wrote json eval results to: /home/local/ANT/siyiding/detectron-train/test/coco_2014_minival/generalized_rcnn/detection_results.pkl
INFO task_evaluation.py:  61: Evaluating bounding boxes is done!
INFO task_evaluation.py: 180: copypaste: Dataset: coco_2014_minival
INFO task_evaluation.py: 182: copypaste: Task: box
INFO task_evaluation.py: 185: copypaste: AP,AP50,AP75,APs,APm,APl
INFO task_evaluation.py: 186: copypaste: 0.2227,0.4151,0.2155,0.0995,0.2364,0.3186

**Comment by rbgirshick** [comment]
@siyiding1216 did you happen to change `NUM_GPUS` and not adjust the training schedule accordingly?

**Comment by vsd550** [comment]
@siyiding1216 How did Generate the metrics for this case.
Please refer to my issue here : [#92](https://github.com/roytseng-tw/Detectron.pytorch/issues/92)
Thanks
