### ISSUE TITLE
Undefined Symbol Error when running test_spatial_narrow_as_op.py

### ISSUE THREAD

**Issue by StymieG101** [facebookresearch/Detectron#216]
* Operating system: Ubuntu 16.04
* Compiler version: 5.4.1
* CUDA version: 8.0.61
* cuDNN version: 6.0.21
* NVIDIA driver version: 387.34
* GPU models (for all devices if they are not all the same): Geforce GTX 1080Ti
* `PYTHONPATH` environment variable: /usr/local/lib/python2.7
* `python --version` output: 2.7.14 ::Anaconda custom (64-bit)

Hi,

I'm getting the following undefined symbol error when testing out Detectron.

Command:
`~/detectron/tests$ python test_spatial_narrow_as_op.py`

**Output:**
E0301 11:11:18.623095 27298 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0301 11:11:18.623112 27298 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0301 11:11:18.623117 27298 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "test_spatial_narrow_as_op.py", line 88, in <module>
    utils.c2.import_detectron_ops()
  File "/home/rschAsst/detectron/lib/utils/c2.py", line 42, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/home/rschAsst/caffe2/build/caffe2/python/dyndep.py", line 50, in InitOpsLibrary
    _init_impl(name)
  File "/home/rschAsst/caffe2/build/caffe2/python/dyndep.py", line 63, in _init_impl
    ctypes.CDLL(path)
  File "/home/rschAsst/yes/envs/python2.7-evan/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe213MessageLoggerC1EPKcii

I tested Caffe2 by running the command stated from [INSTALL.md](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md) and it passed.
Any suggestions on the culprit of this error?

**Comment by niaoyu** [comment]
just the same question, have you solved the questiion?

**Comment by datamonday** [comment]
Got it!

I export the python path like /home/chopin/anaconda3/envs/caffe2/caffe2/build/caffe2/python to ~/.bashrc and then pip install utils .

Now, it's running! I hope this will help you.

**Comment by gadcam** [comment]
I think this issue could be closed.
