### ISSUE TITLE
TEST.SCALE and TRAIN.SCALE

### ISSUE THREAD

**Issue by rbruga** [facebookresearch/Detectron#218]
Hello 

In the config files for the different pretrained models there are two scale parameters for train and test.
Do the TEST.SCALE always need to match the TRAIN.SCALE?

TRAIN:
  SCALES: (800,)
  MAX_SIZE: 1333
TEST:
  SCALES: (800,)
  MAX_SIZE: 1333

I am doing inference with **infer_simple.py** with input images of different sizes. 
I have observed what is mentioned in the readme that if the input image matches closely the SCALE values the inference is faster because there is no resizing.

On a separate test I have modified TEST.SCALE to match my image size and run inference with infer_simple.py and a pretrained model (that was trained with a different value of TRAIN.SCALE) and the model executes properly.
My understanding is that TRAIN.SCALE is the input size to the CNN (referred in mask rcnn paper as the backbone architecture). If that is true, shouldn't all input images during inference be resized to fit TRAIN.SCALE rather than TEST.SCALE? 
Thanks!

**Comment by rbgirshick** [comment]
If `TRAIN.SCALES` lists multiple scales, then they are used for random scale data augmentation during training. `TEST.SCALE` is the one scale to use at inference time (test-time augmentation can be used in addition to that; see `lib/core/config.py` for documentation). If you're using a single scale during training and testing, it makes sense that they should match. Using scale augmentation during training can lead to better results (see 'bells & whistles' model in the model zoo).
