### ISSUE TITLE
libglog.so.0: undefined reference to `google::FlagRegisterer::FlagRegisterer

### ISSUE THREAD

**Issue by SniperZhao** [facebookresearch/Detectron#22]
I try to install caffe2 by following the instructions: https://caffe2.ai/docs/getting-started.html?platform=centos&configuration=cloud
At the step of installing glog, I got lots of error, something like: "libglog.so.0: undefined reference to `google::FlagRegisterer::FlagRegisterer" or "undefined reference to `google::FlagSaver::FlagSaver()"

Any solution?

**Comment by ir413** [comment]
Hi @SniperZhao, I see you opened an equivalent issue on the [Caffe2 page](https://github.com/caffe2/caffe2/issues/1798) and I think this question is better suited for the Caffe2 team.

**Comment by SniperZhao** [comment]
@ir413 yes I realized it and open that issue on Caffe2 page and thank you.
