### ISSUE TITLE
Remove the 2 from python2 in INSTALL.md

### ISSUE THREAD

**Issue by Erotemic** [facebookresearch/Detectron#222]
The install instructions explicitly state python2 in the bash instructions. For those of us running python3, it prevents simple copy/paste of the instructions. Removing the 2 and simply using `python` would be compatible between both versions (given you are using some virtualenv/conda-env). 

Also the same is true about the contents of lib/Makefile

**Comment by gadcam** [comment]
There is a pull request for that : see #110

**Comment by rbgirshick** [comment]
@Erotemic at this time detectron only supports python 2, so we are making that explicit to help prevent problems with people attempting to use python 3.

**Comment by Erotemic** [comment]
Fair enough, sorry for the noise.

I hope PR #110 goes through soon.
