### ISSUE TITLE
Rename or nest the utils module in a detectron python module. 

### ISSUE THREAD

**Issue by Erotemic** [facebookresearch/Detectron#228]
In the current state of detectron the setup.py file installs a module called `utils` to site-packages. The name utils is uninformative and very likely to conflict with another module. Instead there should be a python package named `detectron`, which has a subpackage `detectron.utils`.

**Comment by rbgirshick** [comment]
This was indeed a mistake. We plan to address it by putting non-tool scripts into a proper package.

**Comment by Erotemic** [comment]
I've made a PR #265 that attempts to address this issue.

**Comment by rbgirshick** [comment]
Addressed by 261f7db56fa19f2a6e284e69ebb16382835e0cb3.
