### ISSUE TITLE
Add new class

### ISSUE THREAD

**Issue by EgorAntonovich** [facebookresearch/Detectron#235]
Hi, i want to train pretrained model on my dataset and add new classes . how can i do this?

**Comment by kampelmuehler** [comment]
You'll have to create your own dataset, and adjust the configuration options in the `.yaml` files (specifically `MODEL.NUM_CLASSES`) accordingly. See also  #204

**Comment by kampelmuehler** [comment]
You'll have to create your own dataset and edit the `.yaml` config files of your model, specifically adjust `model.NUM_CLASSES`. See also #204

**Comment by EgorAntonovich** [comment]
@kampelmuehler thanks! and i think, that my dataset annotation should be n coco format?

**Comment by kampelmuehler** [comment]
Correct, coco `.json` format is required to avoid substantial recoding.
