### ISSUE TITLE
No opencv_python>=3.2 for python2

### ISSUE THREAD

**Issue by wadefelix** [facebookresearch/Detectron#238]
there is no opencv_python>=3.2 for python2 ,see https://pypi.python.org/pypi/opencv-python

INSTALL.md
> **Requirements:**
> - NVIDIA GPU, Linux, Python2

> Other Dependencies
> Install Python dependencies:
> ``` pip install numpy>=1.13 pyyaml>=3.12 matplotlib opencv-python>=3.2 setuptools Cython mock scipy```

**Comment by wadefelix** [comment]
#222 
#110

**Comment by rbgirshick** [comment]
3.4 certainly seems >= 3.2. Maybe try with quotes, as in `pip install "opencv-python>=3.2"`?

**Comment by wadefelix** [comment]
opencv-python>=3.2 is for python3.
but the INSTALL.md only declared python2 required.
It's a conflict.
