### ISSUE TITLE
predicting oriented bounding box with either (x1,y1,x2,y2,x3,y3,x4,y4) or (cx,cy,w,h,angle)

### ISSUE THREAD

**Issue by smajida** [facebookresearch/Detectron#241]
### Expected results

What did you expect to see? Rotated bounding boxes

### Actual results

What did you observe instead? no detected bounding box

I have provided the network with either gt boxes with (x1,y1,x2,y2,x3,y3,x4,y4) format or (cx,cy,w,h,angle), but the network is not producing any bounding box without any errors. I have searched a lot and looked for similar issues, but could not find any helpful information. how to predict oriented bbox with R-FCN and RPN? 

### System information

* Operating system: ? Ubuntu 16.04
* CUDA version: ? 8.0
* cuDNN version: ? 6.0
* GPU models (for all devices if they are not all the same): ? Titan X Pascal
* `python --version` output: ? 2.7

![screenshot from 2018-03-06 23-06-17](https://user-images.githubusercontent.com/12903362/37065982-92665328-21a3-11e8-9b48-5e1219f55bd5.png)

**Comment by vsd550** [comment]
Please reply on this as to how to modify its bounding boxes regression part to regress oriented bounding boxes.
I am having the same problem
Thanks

**Comment by gadcam** [comment]
@smajida, @vsd550 as far as I know, this is not supported currently and the internal format is specified here
https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/utils/boxes.py#L23-L40

Looks like https://arxiv.org/ftp/arxiv/papers/1706/1706.09579.pdf or https://arxiv.org/pdf/1712.02294.pdf could help you for the RPN part.

**Comment by ir413** [comment]
As @gadcam noted, this is not supported at this time. Sorry for the inconvenience.

**Comment by HappyKerry** [comment]
@vsd550 @smajida I have the same problem，how to modify faster rcnn？
