### ISSUE TITLE
softmax_focal_loss_op.cu(80): error : identifier "pow<double, float> " is undefined in device code

### ISSUE THREAD

**Issue by juxiangwu** [facebookresearch/Detectron#25]
Compile with CUDA 9.0 + cudnn 7.0 + windowns 10 x64 + VISUAL STUDIO 14 2015

compile error:
D:/Develop/DL/temp/caffe2/modules/detectron/softmax_focal_loss_op.cu(80): error : calling a __host__ function("pow<double, float> ") from a __global__ function("caffe2::_NV_ANON_NAMESPACE::SoftmaxFocalLossKernel") is not allowed
D:/Develop/DL/temp/caffe2/modules/detectron/softmax_focal_loss_op.cu(80): error : identifier "pow<double, float> " is undefined in device code

here is the cmake output results:
Need to define long as a separate typeid.
Current compiler supports avx2 extention. Will build perfkernels.
CMake Warning (dev) at cmake/MiscCheck.cmake:108 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:64 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at build_host_protoc/cmake/protobuf-config-version.cmake:52 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  cmake/ProtoBuf.cmake:55 (find_package)
  cmake/Dependencies.cmake:8 (include)
  CMakeLists.txt:81 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

The BLAS backend of choice:Eigen
OpenCV found (D:/Develop/DL/tools/opencv/build/x64/vc14/lib)
Found system Eigen at D:/Develop/libs/Eigen3/include/eigen3
Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR) 
Could NOT find MPI_C (missing:  MPI_C_LIBRARIES MPI_C_INCLUDE_PATH) 
Could NOT find MPI_CXX (missing:  MPI_CXX_LIBRARIES MPI_CXX_INCLUDE_PATH) 
CMake Warning at cmake/Dependencies.cmake:300 (message):
  Not compiling with MPI.  Suppress this warning with -DUSE_MPI=OFF
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

CUDA detected: 9.0
Added CUDA NVCC flags for: sm_30 sm_35 sm_50 sm_52 sm_60 sm_61 sm_70
Found libcuda: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cuda.lib
Found libnvrtc: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/nvrtc.lib
Found cuDNN: v7.0.4  (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v9.0/lib/x64/cudnn.lib)
CMake Warning at cmake/Dependencies.cmake:371 (message):
  NCCL is currently only supported under Linux.
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

Could NOT find CUB (missing: CUB_INCLUDE_DIR) 
CMake Warning at cmake/Dependencies.cmake:393 (message):
  Gloo can only be used on Linux.
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

CMake Warning at cmake/Dependencies.cmake:473 (message):
  Metal is only used in ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:81 (include)

NCCL operators skipped due to no CUDA support
Including image processing operators
Excluding video processing operators due to no opencv
Excluding mkl operators as we are not using mkl
MPI operators skipped due to no MPI support
CMake Warning (dev) at cmake/Utils.cmake:176 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  cmake/Utils.cmake:193 (caffe_add_whole_archive_flag)
  caffe2/CMakeLists.txt:103 (caffe_add_linker_flag)
This warning is for project developers.  Use -Wno-dev to suppress it.

******** Summary ********
General:
  CMake version         : 3.7.0
  CMake command         : C:/Program Files/CMake/bin/cmake.exe
  Git version           : v0.8.1-978-g6a938bb2-dirty
  System                : Windows
  C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/x86_amd64/cl.exe
  C++ compiler version  : 19.0.24210.0
  Protobuf compiler     : D:\Develop\DL\temp\caffe2\build_host_protoc\bin\protoc.exe
  Protobuf include path : 
  Protobuf libraries    : 
  CXX flags             : /DWIN32 /D_WINDOWS /W3 /GR /EHsc /MP /bigobj
  Build type            : Release
  Compile definitions   : 

  BUILD_BINARY          : ON
  BUILD_DOCS            : OFF
  BUILD_PYTHON          : OFF
  BUILD_SHARED_LIBS     : OFF
  BUILD_TEST            : OFF
  USE_ATEN              : OFF
  USE_ASAN              : OFF
  USE_CUDA              : ON
    CUDA version        : 9.0
    CuDNN version       : 7.0.4
  USE_EIGEN_FOR_BLAS    : 1
  USE_FFMPEG            : OFF
  USE_GFLAGS            : OFF
  USE_GLOG              : OFF
  USE_GLOO              : OFF
  USE_LEVELDB           : OFF
  USE_LITE_PROTO        : OFF
  USE_LMDB              : OFF
  USE_METAL             : OFF
  USE_MKL               : 
  USE_MOBILE_OPENGL     : OFF
  USE_MPI               : OFF
  USE_NCCL              : OFF
  USE_NERVANA_GPU       : OFF
  USE_NNPACK            : OFF
  USE_OBSERVERS         : OFF
  USE_OPENCV            : ON
    OpenCV version      : 3.4.0
  USE_OPENMP            : OFF
  USE_PROF              : OFF
  USE_REDIS             : OFF
  USE_ROCKSDB           : OFF
  USE_THREADS           : ON
  USE_ZMQ               : OFF
CMake Warning at CMakeLists.txt:206 (message):
  Generated cmake files are only fully tested if one builds with system glog,
  gflags, and protobuf.

CMake Warning at CMakeLists.txt:239 (message):
  Generated cmake files are only available when building shared libs.

Configuring done
Generating done

**Comment by rbgirshick** [comment]
@juxiangwu: we do not plan to support building or running on Windows at this time.

**Comment by Yangqing** [comment]
Assigning myself for future check - Windows support from caffe2 is ongoing so it may come in the future, but no binding contract yet.
