### ISSUE TITLE
PyTorch version of detectron (work in progress)

### ISSUE THREAD

**Issue by ignacio-rocco** [facebookresearch/Detectron#250]
Hi, 

I'm working on a PyTorch version of Detectron [here](https://github.com/ignacio-rocco/detectorch).

@rbgirshick Could it be referred to [here](https://github.com/facebookresearch/Detectron/issues/70)? This thread is locked and I cannot post. Thanks!

I'm sorry if this is not the correct place for this announcement, feel free to close this issue.

**Comment by rbgirshick** [comment]
Done (also see my comment on why that thread is closed)! Looking forward to seeing your progress.
