### ISSUE TITLE
andriod  detectron e2e_faster_rcnn_R-50-C4_1x  init_net.pb predict_net.pb

### ISSUE THREAD

**Issue by zyxcambridge** [facebookresearch/Detectron#252]
andriod project：
   https://github.com/caffe2/AICamera
model：
https://github.com/caffe2/models/tree/master/detectron/e2e_faster_rcnn_R-50-C4_1x

but use the model from the AICamera-Style-Transfer is  ok 
https://github.com/caffe2/AICamera-Style-Transfer

loadToNetDef(mgr, &_initNet,   "init_net.pb");
    loadToNetDef(mgr, &_predictNet,"predict_net.pb");
log as fllows:

03-08 21:13:50.756 23861-23907/facebook.f8demo E/F8DEMO: start load neural network.
03-08 21:13:50.757 23861-23907/facebook.f8demo E/F8DEMO: Attempting to load protobuf netdefs...
03-08 21:13:50.757 23861-23907/facebook.f8demo E/F8DEMO: Couldn't parse net from data.
03-08 21:13:50.757 23861-23907/facebook.f8demo E/F8DEMO: Couldn't parse net from data.
03-08 21:13:50.757 23861-23907/facebook.f8demo E/F8DEMO: success load protobuf netdefs done.
03-08 21:13:50.757 23861-23907/facebook.f8demo E/F8DEMO: Instantiating predictor...

**Comment by rbgirshick** [comment]
Unclear issue report. Maybe see #134 and/or #199? Feel free to reopen if you wish to add more details.
