### ISSUE TITLE
How to set weight decay for each operator?

### ISSUE THREAD

**Issue by terrychenism** [facebookresearch/Detectron#266]
We can use StopGradient for lr mult = 0, how to set weight decay mult = 0 during the creation of the parameters?

**Comment by ppwwyyxx** [comment]
You can modify the code here: https://github.com/facebookresearch/Detectron/blob/958b0ad2d8e97a30e44cf63fd12bdffcefae98df/lib/modeling/optimizer.py#L115-L118

**Comment by terrychenism** [comment]
Got it! Thanks @ppwwyyxx
