### ISSUE TITLE
Training using my custom data

### ISSUE THREAD

**Issue by Hwang-dae-won** [facebookresearch/Detectron#268]
Hi.

As I know, The Mask R-CNN framework is shown below.

What I want to do is to train using my custom data, and in the learning process I want to fix the variables in the blue box in the figure below and update only the variables in the red box.(=update only segmentation network)

How can I do this?
![figure1](https://user-images.githubusercontent.com/22520046/37240473-1cbda146-248f-11e8-8893-e4512dbb7631.png)

**Comment by kampelmuehler** [comment]
See  #143

**Comment by ir413** [comment]
Hi @Hwang-dae-won - as suggested in #143, you can use the [`StopGradient`](https://caffe2.ai/docs/operators-catalogue.html#stopgradient) op to accomplish that. You can find the implementation of the classification and bounding box heads [here](https://github.com/facebookresearch/Detectron/blob/master/lib/modeling/fast_rcnn_heads.py).

**Comment by csbotos** [comment]
The reference implementation mentioned in #143 Issue and in answer of @ir413 is obsolete.

Maybe [this](https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/modeling/keypoint_rcnn_heads.py) can help for now

**Comment by ir413** [comment]
Thanks for noting the broken links @csbotos. The links in both #143 and above are now fixed.
