### ISSUE TITLE
visualize_results.py

### ISSUE THREAD

**Issue by XiaSunny** [facebookresearch/Detectron#269]
When i run the command:
python2 tools/visualize_results.py  --detections /tmp/detectron-output/test/coco_2014_minival/generalized_rcnn/detections.pkl --thresh 0.5 --first 100

ValueError: cannot reshape array of size 0 into shape (139711036373896,139711036373896,0)
Thanks!

**Comment by qwert1337** [comment]
Exactly the same problem here.

**Comment by ir413** [comment]
Thanks for reporting @XiaSunny and @qwert1337. We addressed this issue in 80f3295, please rebase.
