### ISSUE TITLE
Is TITAN X Pascal supported

### ISSUE THREAD

**Issue by deeprun** [facebookresearch/Detectron#271]
When I built the ops, I got the following error:

CMake Error at cmake/Cuda.cmake:32 (message):
  Invalid CUDA_ARCH_NAME, supported values: Kepler, Maxwell, Pascal, Volta,
  All, Manual.  Got Auto

I am currently have a TITAN X Pascal, is that supported?

**Comment by rbgirshick** [comment]
Duplicate of #251.
