### ISSUE TITLE
Debugging python layers

### ISSUE THREAD

**Issue by kampelmuehler** [facebookresearch/Detectron#279]
Has anyone managed to debug python layers, such as `lib/ops/generate_proposals.py`. I'm using pycharm to debug python code. When executing a test run of e.g. FasterRCNN and setting a breakpoint inside `forward()`, that breakpoint is never reached during execution.

Has anyone successfully been able to debug into the forward pass of a python layer, or thought on how I might be able to make it work?

**Comment by rbgirshick** [comment]
I usually use `from IPython import embed; embed()` to get an interactive IPython environment for inspecting variables.
