### ISSUE TITLE
How to use Adam as optimizer

### ISSUE THREAD

**Issue by jingtong1993** [facebookresearch/Detectron#282]
Hello, I was trying to using Adam instead of SGD to train a model, I changed the function in /detectron/lib/modeling/optimizer.py to something like this:
```
def add_single_gpu_param_update_ops(model, gpu_id):
    # Learning rate of 0 is a dummy value to be set properly at the
    # start of training
    lr = model.param_init_net.ConstantFill(
        [], 'lr', shape=[1], value=0.0
    )
    iteration = model.param_init_net.ConstantFill(
        [], 'optimizer_iteration', shape=[1], value=0.0)

    one = model.param_init_net.ConstantFill(
        [], 'one', shape=[1], value=1.0
    )
    wd = model.param_init_net.ConstantFill(
        [], 'wd', shape=[1], value=cfg.SOLVER.WEIGHT_DECAY
    )
    for param in model.TrainableParams(gpu_id=gpu_id):
        
        logger.debug('param ' + str(param) + ' will be updated')
        param_grad = model.param_to_grad[param]
        # Initialize momentum vector
        m1 = model.param_init_net.ConstantFill(
            [param], param + "_first_moment", value=0.0
        )
        m2 = model.param_init_net.ConstantFill(
            [param], param + "_second_moment", value=0.0
        )

        
        if param in model.biases:
            # Special treatment for biases (mainly to match historical impl.
            # details):
            # (1) Do not apply weight decay
            # (2) Use a 2x higher learning rate
            model.Scale(param_grad, param_grad, scale=2.0)
        elif cfg.SOLVER.WEIGHT_DECAY > 0:
            # Apply weight decay to non-bias weights
            model.WeightedSum([param_grad, one, param, wd], param_grad)
        # Update param_grad and param_momentum in place
        model.net.Adam(
            [param, m1, m2, param_grad, lr, iteration],
            [param, m1, m2]
        )
```
But it's not working, I got an error like this:

Traceback (most recent call last):
File "tools/train_net.py", line 281, in 
main()
File "tools/train_net.py", line 119, in main
checkpoints = train_model()
File "tools/train_net.py", line 133, in train_model
setup_model_for_training(model, output_dir)
File "tools/train_net.py", line 238, in setup_model_for_training
nu.broadcast_parameters(model)
File "/home/detectron/lib/utils/net.py", line 192, in broadcast_parameters
_do_broadcast([b + '_momentum' for b in model.TrainableParams()])
File "/home/detectron/lib/utils/net.py", line 184, in _do_broadcast
data = workspace.FetchBlob(blobs[0])
File "/home/caffe2/build/caffe2/python/workspace.py", line 346, in FetchBlob
return C.fetch_blob(StringifyBlobName(name))
RuntimeError: [enforce fail at pybind_state.cc:173] ws->HasBlob(name). Can't find blob: gpu_0/res3_0_branch2a_w_momentum

Can we use Adam instead of SGD in detectron? If so, can I have some examples? Thank you very much!

**Comment by softmicro929** [comment]
Do you have solution now?

**Comment by nathlacroix** [comment]
Any update on this ?

**Comment by ir413** [comment]
Hi @jingtong1993, you are getting an error when trying to broadcast momentum blobs (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/net.py#L195)). It should be safe to remove that line in your setup.

Note also that you will likely hit issues with your current implementation due to the `iteration` blob not being on the CPU. See #676 for discussion and a potential solution.
