### ISSUE TITLE
 'caffe2::EnforceNotMet' error: filter.dim32(1) dismatch C / group_ in conv_op_cudnn.cc

### ISSUE THREAD

**Issue by blateyang** [facebookresearch/Detectron#287]
I try to use caffe2.python to build a DenseNet according to origianl DenseNet paper and ResNet implementation in Detectron. However, when I finished codes and try to run it, I met flowing exception:
```
<modeling.detector.DetectionModelHelper object at 0x7fd8f58f0090>
INFO detector.py: 436: Changing learning rate 0.000000 -> 0.000833 at iter 0
I0314 17:17:05.999729 16782 context_gpu.cu:321] GPU 0: 420 MB
I0314 17:17:05.999761 16782 context_gpu.cu:325] Total: 420 MB
I0314 17:17:06.192387 16792 context_gpu.cu:321] GPU 0: 559 MB
I0314 17:17:06.192400 16792 context_gpu.cu:325] Total: 559 MB

terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at conv_op_cudnn.cc:333] filter.dim32(1) == C / group_. 128 vs 64 Error from operator: 
input: "gpu_0/relu2_1/x2/bn" input: "gpu_0/conv2_1/x2_w" output: "gpu_0/conv2_1/x2" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1521019026 (unix time) try "date -d @1521019026" if you are using GNU date ***
PC: @     0x7fd94d704428 gsignal
*** SIGABRT (@0x3ea00004172) received by PID 16754 (TID 0x7fd8bdffb700) from PID 16754; stack trace: ***
    @     0x7fd94daaa390 (unknown)
    @     0x7fd94d704428 gsignal
    @     0x7fd94d70602a abort
    @     0x7fd946fea84d __gnu_cxx::__verbose_terminate_handler()
    @     0x7fd946fe86b6 (unknown)
    @     0x7fd946fe8701 std::terminate()
    @     0x7fd947013d38 (unknown)
    @     0x7fd94daa06ba start_thread
    @     0x7fd94d7d641d clone
    @                0x0 (unknown)
```

### Expected results

I expecte filter.dim32(1) should equal to C / group_. (128==128) in conv_op_cudnn.cc

### Actual results

filter.dim32(1) == C / group_. 128 vs 64
When I changed filter.dim32(1) into 64, 192, 256,  I got 64 vs 96, 192 vs 64, 256 vs 64, respectively.

I guess C represent number of Input channels, but I can't figure out what is 'group_' meaning.
I have searched on google for a long time but can't find any helpful information. I can't figure out why this error happened and how to solve it. Can anyone who knows it help me? Thanks in advance. 

### Detailed steps to reproduce

The command I use is:
```
python tools/train_net.py/ --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml
OUTPUT_DIR /tmp/detectron-output
```
I modified the 'tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml ' by replacing  pkl file of WEIGHTS (use pickle_caffe_blobs.py) and CONV_BODY configuration.

Related codes about DenseNet I implemented:
```
def add_conv_block(
        model,
        prifix,
        blob_in,
        dim_in,
        dim_out,
        dim_inner,
        ):
    """Apply BatchNorm, Relu, bottleneck 1*1 Conv, 3*3 Conv"""
    layer_x1 = model.AffineChannel(blob_in, 'conv'+prifix+'/x1/bn', 
                                   dim_in)
    layer_x1 = model.Relu(layer_x1, 'relu'+prifix+'/x1/bn')
    layer_x1 = model.Conv(layer_x1, 'conv'+prifix+'/x1', dim_in, 
                         dim_inner, kernel=1, pad=0, no_bias=1)
    
    layer_x2 = model.AffineChannel(blob_in, 'conv'+prifix+'/x2/bn', 
                                   dim_inner)
    layer_x2 = model.Relu(layer_x2, 'relu'+prifix+'/x2/bn')
    layer_x2 = model.Conv(layer_x2, 'conv'+prifix+'/x2', dim_inner, 
                         dim_out, kernel=3, pad=1, no_bias=1)
    return layer_x2
```

### System information

* Operating system: Ubuntu16.04
* Compiler version: gcc 5.4.0
* CUDA version: 8.0
* cuDNN version: 5.0
* NVIDIA driver version: 384.111
* GPU models (for all devices if they are not all the same): 
* `PYTHONPATH` environment variable: /usr/local /home/ygj/caffe2/build
* `python --version` output: Python 2.7.12
* Anything else that seems relevant: ?

**Comment by blateyang** [comment]
I have stucked on this issue for more than a week. I think in `filter.dim32(1) == C/group_`, filter.dim32(1) represents input dim of conv filter, C represents output dim of the former operator and group_ is a param(=1 in default) in Conv function. But I really can't figure out why filter.dim32(1) unmatched C/group_, I try to print out C and group_ but don't know how to do it. Can anybody who is experienced in programming and caffe2 help me ? I can't thank you enough. @Yangqing

**Comment by blateyang** [comment]
I have figured out this problem. It's all my faults.  Filter.dim(1)==C/group_ 128 vs 64 is because I inputed wrong blob name, it should be layer_x1 rather than blob_in. I should find this mistake early. Anyhow, I finally solved it. :)

**Comment by FANCYboom** [comment]
Hi,blateyang
I'm facing a similar problem and don't know how to resolve it yet.Here is my error:

RuntimeError: [enforce fail at conv_op_cudnn.cc:546] filter.dim32(1) == C / group_. 3 vs 224 Error from operator: 
input: "imonaboat/data" input: "imonaboat/conv1_w" input: "imonaboat/conv1_b" output: "imonaboat/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
......................................................................................
I am trying to achieve caffe2 tutorials Multi-GPU_Training.ipynb.Here is it
https://github.com/caffe2/tutorials/blob/master/Multi-GPU_Training.ipynb
or can you give me your emaildress? So I can send you my code.Thank you!

**Comment by YuanLeung** [comment]
@FANCYboom 
I got the same problem as yours. Have you figure out it?

**Comment by FANCYboom** [comment]
I have forgotten the details of that problem, but I suggest you to check up your GPU.


On 10/06/2018 12:51, 梁远 wrote:

@FANCYboom
I got the same problem as yours. Have you figure out it?
