### ISSUE TITLE
Multi GPU training will close my ubuntu server

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/Detectron#29]

**Comment by gaopeng-eugene** [comment]
ssh: connect to host cdcgwb.ie.cuhk.edu.hk port 2180: No route to host

I train 8 GPU Mask RCNN model. The training is right at the beginning. Then, Detrctron will close my Server. I can not catch any mistake.

**Comment by gaopeng-eugene** [comment]
I train 8 GPU Mask RCNN model. The training is right at the beginning. Then, Detrctron will close my Server. I can not catch any mistake.

**Comment by rbgirshick** [comment]
Can you provide any more information? Can you clarify what you mean by "close" (e.g., does the server reboot / power off?)

**Comment by terrychenism** [comment]
I meet the same problem using docker on 8 gpus, need to restart server. @rbgirshick  Could you provide caffe2 with a specific commit.

**Comment by gaopeng-eugene** [comment]
Server power off never reboot.
Eight Titan X
configs/12_2017_baselines/mask_rcnn_X-101-32x8d-FPN_1x.yaml

**Comment by rbgirshick** [comment]
@gaopeng-eugene: that sounds like a specific hardware issue and not something that we can debug or address. Maybe the system has insufficient cooling or are you overclocking the GPUs too aggressively? These are just random guesses. You could also try upgrading your GPU drivers, if there are upgrades available. Hope you are able to figure it out.

**Comment by huohuoR** [comment]
Hi  @gaopeng-eugene , @rbgirshick ,  have you fix the problem? I met the same problem when using two gpu (Titan X & XP) during training. My ubuntu 14.04 may rebbot frequently.
