### ISSUE TITLE
out of memory Error from operator  GeForce GTX 1080 on e2e_keypoint training

### ISSUE THREAD

**Issue by stanciuflorina** [facebookresearch/Detectron#296]
hi, i tried to do the e2e training for keypoint using 1 GPU GeForce GTX 1080, but i keep getting this error:

json_stats: {"accuracy_cls": 0.855469, "eta": "53 days, 17:05:28", "iter": 0, "loss": 9.700206, "loss_bbox": 0.024973, "loss_cls": 0.494652, "loss_kps": 8.472142, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.006159, "loss_rpn_bbox_fpn5": 0.004879, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.540464, "loss_rpn_cls_fpn3": 0.109880, "loss_rpn_cls_fpn4": 0.036009, "loss_rpn_cls_fpn5": 0.011047, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000833, "mb_qsize": 64, "mem": 6298, "time": 4.462239}
I0316 12:46:57.828959  9759 context_gpu.cu:321] GPU 0: 6339 MB
I0316 12:46:57.828974  9759 context_gpu.cu:325] Total: 6339 MB
I0316 12:46:57.853865  9777 context_gpu.cu:321] GPU 0: 6471 MB
I0316 12:46:57.853888  9777 context_gpu.cu:325] Total: 6471 MB
I0316 12:46:57.875710  9777 context_gpu.cu:321] GPU 0: 6616 MB
I0316 12:46:57.875726  9777 context_gpu.cu:325] Total: 6616 MB
I0316 12:46:57.902776  9776 context_gpu.cu:321] GPU 0: 6754 MB
I0316 12:46:57.902808  9776 context_gpu.cu:325] Total: 6754 MB
I0316 12:46:57.928117  9776 context_gpu.cu:321] GPU 0: 6883 MB
I0316 12:46:57.928133  9776 context_gpu.cu:325] Total: 6883 MB
I0316 12:46:57.959914  9776 context_gpu.cu:321] GPU 0: 7015 MB
I0316 12:46:57.959928  9776 context_gpu.cu:325] Total: 7015 MB
I0316 12:46:57.991092  9776 context_gpu.cu:321] GPU 0: 7147 MB
I0316 12:46:57.991104  9776 context_gpu.cu:325] Total: 7147 MB
I0316 12:46:58.021169  9776 context_gpu.cu:321] GPU 0: 7301 MB
I0316 12:46:58.021184  9776 context_gpu.cu:325] Total: 7301 MB
I0316 12:46:58.069684  9778 context_gpu.cu:321] GPU 0: 7443 MB
I0316 12:46:58.069702  9778 context_gpu.cu:325] Total: 7443 MB
I0316 12:46:58.155489  9779 context_gpu.cu:321] GPU 0: 7581 MB
I0316 12:46:58.155503  9779 context_gpu.cu:325] Total: 7581 MB
I0316 12:46:58.342164  9778 context_gpu.cu:321] GPU 0: 7709 MB
I0316 12:46:58.342178  9778 context_gpu.cu:325] Total: 7709 MB
I0316 12:46:58.403837  9777 context_gpu.cu:321] GPU 0: 7841 MB
I0316 12:46:58.403857  9777 context_gpu.cu:325] Total: 7841 MB
I0316 12:46:58.461297  9778 context_gpu.cu:321] GPU 0: 7974 MB
I0316 12:46:58.461314  9778 context_gpu.cu:325] Total: 7974 MB
I0316 12:46:58.533831  9778 context_gpu.cu:321] GPU 0: 8104 MB
I0316 12:46:58.533846  9778 context_gpu.cu:325] Total: 8104 MB
I0316 12:46:58.611078  9778 context_gpu.cu:321] GPU 0: 8233 MB
I0316 12:46:58.611091  9778 context_gpu.cu:325] Total: 8233 MB
I0316 12:46:58.715821  9777 context_gpu.cu:321] GPU 0: 8362 MB
I0316 12:46:58.715834  9777 context_gpu.cu:325] Total: 8362 MB
I0316 12:46:59.005865  9759 context_gpu.cu:321] GPU 0: 8490 MB
I0316 12:46:59.005882  9759 context_gpu.cu:325] Total: 8490 MB
I0316 12:47:00.762010  9776 context_gpu.cu:321] GPU 0: 8628 MB
I0316 12:47:00.762029  9776 context_gpu.cu:325] Total: 8628 MB
I0316 12:47:00.868399  9776 context_gpu.cu:321] GPU 0: 8759 MB
I0316 12:47:00.868427  9776 context_gpu.cu:325] Total: 8759 MB
I0316 12:47:00.943491  9776 context_gpu.cu:321] GPU 0: 8889 MB
I0316 12:47:00.943506  9776 context_gpu.cu:325] Total: 8889 MB
I0316 12:47:01.022756  9777 context_gpu.cu:321] GPU 0: 9028 MB
I0316 12:47:01.022770  9777 context_gpu.cu:325] Total: 9028 MB
I0316 12:47:01.176020  9779 context_gpu.cu:321] GPU 0: 9166 MB
I0316 12:47:01.176033  9779 context_gpu.cu:325] Total: 9166 MB
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /home/fstanciu/git/caffe2/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/fpn_res2_2_sum" input: "gpu_0/keypoint_rois_fpn2" input: "gpu_0/__m6_shared" output: "gpu_0/__m7_shared" name: "" type: "RoIAlignGradient" arg { name: "pooled_h" i: 14 } arg { name: "sampling_ratio" i: 2 } arg { name: "spatial_scale" f: 0.25 } arg { name: "pooled_w" i: 14 } device_option { device_type: 1 cuda_gpu_id: 0 } is_gradient_op: true
*** Aborted at 1521197221 (unix time) try "date -d @1521197221" if you are using GNU date ***
PC: @     0x7f6eeac56428 gsignal
*** SIGABRT (@0x3e80000258f) received by PID 9615 (TID 0x7f6d58ffc700) from PID 9615; stack trace: ***
    @     0x7f6eeac564b0 (unknown)
    @     0x7f6eeac56428 gsignal
    @     0x7f6eeac5802a abort
    @     0x7f6ee477784d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f6ee47756b6 (unknown)
    @     0x7f6ee4775701 std::terminate()
    @     0x7f6ee47a0d38 (unknown)
    @     0x7f6eeaff26ba start_thread
    @     0x7f6eead2841d clone
    @                0x0 (unknown)
Aborted (core dumped)
System information
Ubuntu16.04, cuda  V8.0.61, cudnn 6.0.21, GPU GeForce GTX 1080, python 2.7.12.
The command i'm running is the following:

python2 tools/train_net.py \
>     --cfg  /home/fstanciu/git/detectron/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml \
>     OUTPUT_DIR /tmp/detectron_result

Is is possible that my GPU is not powerful enough?

**Comment by ir413** [comment]
Hi @stanciuflorina, this seems like an out of memory error. The e2e ResNet-101-FPN keypoint model you're using requires ~10.6 GB of memory for the baseline config settings.
