### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by rajiv235** [facebookresearch/Detectron#297]
I tried testing few end-to-end model using faster rcnn on AWS P2 instance(K10 GPU). However I see much increased inference time when using infer_simple.py. For instance, when I tested Resnet-101 + FPN model with faster rcnn I see ~0.35sec/image vs 0.120 + 0.004sec/image.

Is anyone seeing similar thing?

**Comment by YoungMagic** [comment]
I found the same thing. I think it's because some pre-processing has done the trick. Such as loading all the test images into memory before infering. However, infer.py needs to loads image one by one.

**Comment by ir413** [comment]
Hi @rajiv235 and @YoungMagic, please see the explanation printed by `infer_simple` [here](https://github.com/facebookresearch/Detectron/blob/master/tools/infer_simple.py#L124-L127).
