### ISSUE TITLE
Detectron support Synchronous BN or not

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/Detectron#3]

**Comment by rbgirshick** [comment]
@gaopeng-eugene: multi-device synchronous BN is not supported at the moment. It will likely be supported in the future after the Caffe2 multi-device BN implementation is finished. For now, all models use fixed `AffineChannel` ops to replace the BN op from the original pretraining network.

**Comment by yelantingfeng** [comment]
Is that supported now?
