### ISSUE TITLE
about  Detecting and Recognizing Human-Object Interactions implementation

### ISSUE THREAD

**Issue by wm901115nwpu** [facebookresearch/Detectron#30]
Could you point out the implementation of the paper about Detecting and Recognizing Human-Object Interactions, I can't find it.

**Comment by rbgirshick** [comment]
This code release does not contain an implementation for InteractNet yet (the method from that paper). We plan to release it in the future, but cannot give an ETA yet.

**Comment by rebeen** [comment]
I hope to code will be available soon

**Comment by Andre1998Shuvam** [comment]
Has the code been released yet?

**Comment by csEylLee** [comment]
Where? Where?
