### ISSUE TITLE
No output for Demo code execution. No errors reported as well: Detectron 

### ISSUE THREAD

**Issue by chandanv2** [facebookresearch/Detectron#302]
After runnning the mask rcnn demo inference command, the output is as follows:
![detectron](https://user-images.githubusercontent.com/35568838/37696552-82bbe496-2cfd-11e8-9a48-ead5cd2b2258.png)
What could have happened?
I checked for memory utilization as well, it was like around 40%. So it excludes the possibility of insufficient memory.
System Details:
Running this on Jetson TX2 Board with Jetpack 3.2 (L4T R28.2, Cuda 9.0, cuDNN 7.0.5, OpenCV 3.3.1)

**Comment by gadcam** [comment]
Could you try it again with <code>--image-ext jpg</code> ?
Cf https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md#1-directory-of-image-files
