### ISSUE TITLE
Infer_simple error but detectron install  passed

### ISSUE THREAD

**Issue by sdalxn** [facebookresearch/Detectron#304]
python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo

### Expected results
 Run correctly!

What did you expect to see?
### Actual results
[============================================================] 100.0% of 170.2  [============================================================] 100.0% of 170.2  [============================================================] 100.0% of 170.2  [============================================================] 100.0% of 170.2MB file  
WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  57: Loading weights from: https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
Traceback (most recent call last):
  File "tools/infer_simple.py", line 146, in <module>
    main(args)
  File "tools/infer_simple.py", line 98, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "/home/lxn/detectron/lib/core/test_engine.py", line 316, in initialize_model_from_cfg
    model, weights_file, gpu_id=gpu_id,
  File "/home/lxn/detectron/lib/utils/net.py", line 59, in initialize_gpu_from_weights_file
    with open(weights_file, 'r') as f:
IOError: [Errno 2] No such file or directory: 'https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl'

### Detailed steps to reproduce

`python2 $DETECTRON/tests/test_spatial_narrow_as_op.py`

----------------------------------------------------------------------
Ran 3 tests in 0.911s

OK

### System information

* Operating system:ubuntu1404
* Compiler version:gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
* CUDA version: CUDA 8
* cuDNN version: cudNN 6
* NVIDIA driver version: 390.42
* GPU models (for all devices if they are not all the same): NVIDIA Corporation Device 1b00 (rev a1), TiTAN X pascal
* `PYTHONPATH` environment variable:/usr/local:/home/lxn/caffe2/build
* `python --version` output: Python 2.7.6
* Anything else that seems relevant: It can download the file from the website. but It can load this file.

**Comment by rbgirshick** [comment]
Thanks for reporting this issue. We will fix it shortly.

**Comment by rbgirshick** [comment]
This should be fixed by e7ad1b4801dcb31e072a438c1def657f959e4622.

**Comment by sdalxn** [comment]
@rbgirshick 
Thanks.
 It works.
