### ISSUE TITLE
如何用自己的数据集训练

### ISSUE THREAD

**Issue by pangpanghuahuamaomi** [facebookresearch/Detectron#306]
大神你好，我想问下具体的训练的数据集格式，我自己用labelme-master工具打出的标签是每张图一个json文件，但是看官方资料的coco数据集是所有的数据集放在一个json文件，有些疑惑，等待您的回复

**Comment by hf200012** [comment]
使用Detectron进行目标检测
https://zhuanlan.zhihu.com/p/34036460
参考这个
