### ISSUE TITLE
Whether to change some parameters when I train a small dataset about 10k images with RetinaNet?

### ISSUE THREAD

**Issue by fxs628** [facebookresearch/Detectron#310]
Hi,
       I wonder that whether to change some parameters in yaml file or config.py when I train a small dataset about 10k images with RetinaNet?
Appreciate any help!

**Comment by ir413** [comment]
Hi @fxs628, when training with a different amount of data it is at least necessary to change the number of iterations. For 10k images, a good place to start may be to try the 0.1x schedule (6/8/9k iterations). Note that this is not to be confused with "[linear scaling rule](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md#2-multi-gpu-training)" for adjusting the learning rate schedule.
