### ISSUE TITLE
[Multi-GPU training error] risk to server

### ISSUE THREAD

**Issue by XiongweiWu** [facebookresearch/Detectron#312]
As claimed in #219 #83 #32 , the same problem appears in my side. My server is DGX-1(V100). I have tried all your config models and the programs stuck when using more than 2 cards w / or w / o NCCL. Further, I notice if I tried multiple times, it will do harm to the server itself. When checking the cards using  
`nvvs --configless`

it reports
                Memory GPU0 ....................................... PASS
		Memory GPU1 ....................................... PASS
		Memory GPU2 ....................................... PASS
		Memory GPU3 ....................................... PASS
		Memory GPU4 ....................................... PASS
		Memory GPU5 ....................................... PASS
		Memory GPU6 ....................................... FAIL
		   *** Unable to create CUDA context
		   *** Memory test initialization failed.
		Memory GPU7 ....................................... PASS

Though reboot can fix the error card.

I wonder whether u can reproduce the issue and also whether you can fix the multi-gpu training bug? attached my server infomation

* Operating system: Ubuntu 16.04.4 LTS
* Compiler version: gcc/g++ 5.4.0
* CUDA version: 9.0
* cuDNN version: 7.1.1.5-1+cuda9.0
* NVIDIA driver version: 384.111
* GPU: Tesla V100-SXM2-16GB
* `python --version` output: 2.7.12
* Anything else that seems relevant: See nvvs result above

**Comment by rbgirshick** [comment]
Closing to consolidate the reports into #219.

**Comment by ambigus9** [comment]
@XiongweiWu Did you solve this issue? I'm trying to use multiple gpu to train models and my server always getting stuck

**Comment by rbgirshick** [comment]
Please update your nvidia driver to 396.26. We have confirmed that it avoids this deadlock issue when using V100s with cuda >= 9.

**Comment by ambigus9** [comment]
@rbgirshick I have GTX 1080Ti, so I think that version isn't avaible right now.

![imagen](https://user-images.githubusercontent.com/16579856/41983974-1497da98-79f5-11e8-9c09-21a3411961d6.png)

Currently the version of my driver is 384.130.

![imagen](https://user-images.githubusercontent.com/16579856/41984042-413979ee-79f5-11e8-9098-eb0206838f10.png)

If I update to 390.67 this issue will fixed?
