### ISSUE TITLE
Run COCO Dataset in e2e_faster_rcnn_R-101-FPN_1x.yaml shows an error

### ISSUE THREAD

**Issue by Paylet** [facebookresearch/Detectron#325]
I used e2e_faster_rcnn_R-101-FPN_1x.yaml to run a model with class of 2(person and background) in coco, I only modified NUM_CLASS & NUM_GPU(=1), but I met a problem as figure shows. What can I do to fix this?
![screenshot from 2018-03-28 10-48-38](https://user-images.githubusercontent.com/28921771/38006011-dbe7751c-3275-11e8-94e3-fed3ea1bc89e.png)
![screenshot from 2018-03-28 10-47-50](https://user-images.githubusercontent.com/28921771/38006019-e359bc92-3275-11e8-80ea-2d8af8abfe08.png)

**Comment by ir413** [comment]
Hi @Paylet, the shapes of the output blobs for the classification ('cls_score') and the bounding box ('bbox_pred') heads are class-dependent. Hence, to use a pre-trained Faster R-CNN model with a different number of classes you need to address this (e.g. when loading the weights).

Alternatively, you could consider using one of the pretrained keypoint models (w/o the keypoint head) as a person detector. See also #156 for how to extract the per-category detection results.
