### ISSUE TITLE
Train custom db, 1000 categories

### ISSUE THREAD

**Issue by ps254** [facebookresearch/Detectron#327]
Hi!
Help me!

### Expected results

Completion of training

### Actual results

INFO test_engine.py: 222: im_detect: range [1, 49000] of 49000: 48991/49000 0.153s + 0.043s (eta: 0:00:01)
INFO test_engine.py: 255: Wrote detections to: /home/tomcat/git_repos/detectron/test/coco_2014_minival/generalized_rcnn/detections.pkl
INFO test_engine.py: 108: Total inference time: 10512.602s
INFO task_evaluation.py:  75: Evaluating detections
INFO json_dataset_evaluator.py: 162: Writing bbox results json to: /home/tomcat/git_repos/detectron/test/coco_2014_minival/generalized_rcnn/bbox_coco_2014_minival_results.json
Loading and preparing results...
DONE (t=0.01s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
Killed

In the logs I see

[Thu Mar 29 01:45:59 2018] Out of memory: Kill process 2032 (python2) score 982 or sacrifice child
[Thu Mar 29 01:45:59 2018] Killed process 2032 (python2) total-vm:59083816kB, anon-rss:31922228kB, file-rss:80068kB, shmem-rss:28480kB

Advise how to optimize memory consumption?

### Detailed steps to reproduce
I execute the command

 python2 tools/test_net.py      --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_1x.yaml    TEST.WEIGHTS /tmp/detectron-output/train/coco_2014_train/generalized_rcnn/model_final.pkl    NUM_GPUS 1  

### System information

* Operating system: 
NAME="CentOS Linux"
VERSION="7 (Core)"
* CUDA version: 
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

* NVIDIA driver version: 
[tomcat@neur ~]$ nvidia-smi
Thu Mar 29 09:47:15 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.25                 Driver Version: 390.25                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|   0  GeForce GTX 105...  Off  | 00000000:02:00.0 Off |                  N/A |
| 35%   28C    P0    N/A /  75W |      0MiB /  4039MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |

|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

* `python --version` output: 
Python 2.7.5

**Comment by gadcam** [comment]
What is important is here is
```
[Thu Mar 29 01:45:59 2018] Out of memory: Kill process 2032 (python2) score 982 or sacrifice child
```

So I would the 4 Go of RAM of your GeForce GTX 1050 (Ti ?) are not enough to train.

See #21 also.

**Comment by ps254** [comment]
And what is the minimum memory required?
And which teaching method should I use on my computer settings?

**Comment by ambigus9** [comment]
@ps254 I think the minimum memory required depends on the base_line model . With 11 GB VRAM I could run e2e_mask_rcnn_X-101-32x8d-FPN_2x without problems, please see [MODEL_ZOO](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md)

**Comment by gadcam** [comment]
This issue could be closed.
