### ISSUE TITLE
Train my own dataset, got " Error in `python2': corrupted double-linked list:"

### ISSUE THREAD

**Issue by sdalxn** [facebookresearch/Detectron#329]
### Expected results

Expected train process completed.

### Actual results

>json_stats: {"accuracy_cls": 1.000000, "eta": "0:54:06", "iter": 34340, "loss": 0.005230, "loss_bbox": 0.001093, "loss_cls": 0.003716, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000288, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000001, "loss_rpn_cls_fpn4": 0.000002, "loss_rpn_cls_fpn5": 0.000025, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000250, "mb_qsize": 64, "mem": 2262, "time": 0.126512}
json_stats: {"accuracy_cls": 0.998047, "eta": "0:54:03", "iter": 34360, "loss": 0.006325, "loss_bbox": 0.001232, "loss_cls": 0.004837, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000195, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000001, "loss_rpn_cls_fpn4": 0.000003, "loss_rpn_cls_fpn5": 0.000026, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000250, "mb_qsize": 64, "mem": 2262, "time": 0.126512}
json_stats: {"accuracy_cls": 0.998047, "eta": "0:54:01", "iter": 34380, "loss": 0.005815, "loss_bbox": 0.001315, "loss_cls": 0.003623, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000297, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000001, "loss_rpn_cls_fpn4": 0.000003, "loss_rpn_cls_fpn5": 0.000032, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000250, "mb_qsize": 64, "mem": 2262, "time": 0.126511}
json_stats: {"accuracy_cls": 0.996094, "eta": "0:53:58", "iter": 34400, "loss": 0.009146, "loss_bbox": 0.001249, "loss_cls": 0.007778, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000294, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000001, "loss_rpn_cls_fpn4": 0.000003, "loss_rpn_cls_fpn5": 0.000039, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000250, "mb_qsize": 64, "mem": 2262, "time": 0.126510}
json_stats: {"accuracy_cls": 0.998047, "eta": "0:53:56", "iter": 34420, "loss": 0.006891, "loss_bbox": 0.001482, "loss_cls": 0.004996, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000352, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000001, "loss_rpn_cls_fpn4": 0.000003, "loss_rpn_cls_fpn5": 0.000023, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000250, "mb_qsize": 64, "mem": 2262, "time": 0.126512}
*** Error in `python2': corrupted double-linked list: 0x00007fcb0c2c1ae0 ***
Aborted (core dumped)

### Detailed steps to reproduce

I have prepared a personal data set.
The data set is just for play and only has 5 kinds of object. Each category has 300 pictures and each picture has only one instance out of the 5 categories. 
 I have created the json file for this data set according coco format requirement and I have done simple tests about this json file. It is OK.

I modified the file "tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml":
`NUM_CLASSES: 6`
That means I modified NUM_CALSSES from 81 to 6.
Except this , the file is unchanged.

BTW, in the instance json files, my category id is from 82. That means my categories numbers are 81,83,84,85,86 respectively.

```
The command that I ran
`python2 tools/train_net.py     --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml     OUTPUT_DIR /tmp/detectron-output`


### System information

*Operating system:ubuntu1404

- Compiler version:gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904
- CUDA version: CUDA 8
- cuDNN version: cudNN 6
- NVIDIA driver version: 390.42
- GPU models (for all devices if they are not all the same): NVIDIA Corporation Device 1b00 (rev a1), TiTAN X pascal
- PYTHONPATH environment variable:/usr/local:/home/lxn/caffe2/build
- python --version output: Python 2.7.6
- Anything else that seems relevant:  I am a newer and do not know why it happens.

**Comment by manketon** [comment]
I have encountered the same problem when training on coco_train2014 dataset

**Comment by dennissv** [comment]
I'm experiencing the same problem with a very similar setup. Custom dataset, only 2 classes.

`*** Error in `python': malloc(): smallbin double linked list corrupted: 0x00007fe2b40623a0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fe4ec9a37e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x82651)[0x7fe4ec9ae651]
/lib/x86_64-linux-gnu/libc.so.6(__libc_malloc+0x54)[0x7fe4ec9b0184]
/usr/lib/nvidia-390/tls/libnvidia-tls.so.390.30(+0x24c0)[0x7fe4a819a4c0]
`

**Comment by sdalxn** [comment]
I changed the model to "Detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml" and modified some field.
Now it can works.

**Comment by dennissv** [comment]
Glad that you got it to work, could you please explain 'and modified some field' in more detail?

**Comment by sdalxn** [comment]
very simple, just modified "Detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml"
1)NUM_CLASSES = number of your category + 1;
2)NUM_GPUS = 1
3)DATASETS: ('coco_2014_train', 'coco_2014_valminusminival')  ->DATASETS: ('coco_2014_train', )
4)DATASETS: ('coco_2014_minival',)-->DATASETS: ('coco_2014_val',)  #there  I test my valid images. you can modified according to your task.
