### ISSUE TITLE
When will you release the panoptic segmentation evaluation code?

### ISSUE THREAD

**Issue by gaopeng-eugene** [facebookresearch/Detectron#33]
As the title implied

**Comment by rbgirshick** [comment]
@pdollar: any comments? ;)

**Comment by pdollar** [comment]
That's probably a better question for the https://github.com/cocodataset/cocoapi repo. That being said -- it's on our todo but it will take a while (a few months).

also @alexander-kirillov

**Comment by gaopeng-eugene** [comment]
After or before ECCV deadline ?

**Comment by pdollar** [comment]
Realistically I think it is rather unlikely to be before ECCV. 

That being said, Alex may be able to share some evaluation scripts unofficially, but you'd have to talk to him directly about that, not sure if it's feasible...

@alexander-kirillov

**Comment by gaopeng-eugene** [comment]
Thank you so much for your reply

**Comment by alexander-kirillov** [comment]
We have released the panoptic segmentation evaluation code. Please see [panopticAPI](https://github.com/cocodataset/panopticapi) for COCO dataset.
