### ISSUE TITLE
Any plan to migrate detectron to pytorch?

### ISSUE THREAD

**Issue by yuzcccc** [facebookresearch/Detectron#333]
Since Caffe2 is now moved to the pytorch repo as its backend, is there any plan to migrate Detectron to Pytorch? : )

**Comment by gadcam** [comment]
You can follow the "merge" here https://github.com/caffe2/caffe2/issues/2439.

**Comment by ahkarami** [comment]
Dear @gadcam,
You can refer to [PyTorch version of Detectron](https://github.com/ignacio-rocco/detectorch).

**Comment by roytseng-tw** [comment]
I have made a [pytorch implementation](https://github.com/roytseng-tw/mask-rcnn.pytorch) that could do training on multi-gpu.

**Comment by rbgirshick** [comment]
We will be looking into porting the code the use the pytorch frontend as caffe2 and pytorch merging progresses.

**Comment by MhLiao** [comment]
@rbgirshick Thank you for your great efforts! Any progress about the Pytorch frontend now?

**Comment by bjornamr** [comment]
@rbgirshick Any further progress on porting Detectron to pytorch?
