### ISSUE TITLE
Wrong argument number in convert_pkl_to_pb.py

### ISSUE THREAD

**Issue by daquexian** [facebookresearch/Detectron#337]
### Expected results

`convert_pkl_to_pb.py` runs successfully 

### Actual results

`TypeError: initialize_model_from_cfg() takes at least 1 argument (0 given)`

Obviously [this function](https://github.com/facebookresearch/Detectron/blob/master/lib/core/test_engine.py#L324) takes at least 1 argument, but actually [no argument is given](https://github.com/facebookresearch/Detectron/blob/master/tools/convert_pkl_to_pb.py#L336)

What makes me more confused is that even though `convert_pkl_to_pb.py` can't run, there is a PR(#334 ) about this file(which don't fix this bug). So is the PR proposed without even trying to run it once?  :|

### System information

* Operating system: cuda9.0 detectron docker

**Comment by daquexian** [comment]
@ir413 Thanks for your early reply! I have submitted a PR which fixed this issue and converted a model correctly. You might want to merge it if there is nothing wrong with the PR. :)

**Comment by ir413** [comment]
Thanks for the PR @daquexian. I submitted a PR internally when I wrote my initial comment above but it took some time for it to get published on github (1d67750). Sorry for the inconvenience.

**Comment by daquexian** [comment]
@ir413 All right :)
