### ISSUE TITLE
I want to classify only human class

### ISSUE THREAD

**Issue by Hwang-dae-won** [facebookresearch/Detectron#34]
I want to classify only human class

As a result of running infer_simply.py, i want to a image that contains only human class and human segmentation (does not contain other class)

How can i do this?

**Comment by rbgirshick** [comment]
For now, we have person(human)-only models for keypoint detection. For example if you run

```
python2 tools/infer_simple.py --cfg configs/12_2017_baselines/e2e_keypoint_rcnn_X-101-32x8d-FPN_s1x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/37732318/12_2017_baselines/e2e_keypoint_rcnn_X-101-32x8d-FPN_s1x.yaml.16_55_09.Lx8H5JVu/output/train/keypoints_coco_2014_train:keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
```

You should get output like this:

![image](https://user-images.githubusercontent.com/1190634/35399998-85205772-01aa-11e8-8588-af0284558c19.png)

In the future we will release person-only models that jointly predict detections, keypoints, and segmentation masks.
