### ISSUE TITLE
different kernel type,MSRAFill and GaussianFill

### ISSUE THREAD

**Issue by oujieww** [facebookresearch/Detectron#341]
I can not find doc about MSRAFill,anyone have some imformation?thanks!!!

**Comment by ir413** [comment]
Hi @oujieww, you can find the Caffe2 `MSRAFillOp` definition [here](https://github.com/pytorch/pytorch/blob/master/caffe2/operators/filler_op.h#L445-L463) and refer to [this](https://arxiv.org/abs/1502.01852) paper for the description of the initialization scheme it implements.
