### ISSUE TITLE
Write Output File as JPG instead of PDF

### ISSUE THREAD

**Issue by chandanv2** [facebookresearch/Detectron#344]
How to make the models to write the output of inference as a jpg or a png file instead of pdf file?

**Comment by ir413** [comment]
Hi @chandanv2, you can set the `ext` argument of the [`vis_one_image`](https://github.com/facebookresearch/Detectron/blob/master/lib/utils/vis.py#L251L254) function to `png`/`jpg` to overwrite its default `pdf` value.

**Comment by kp421** [comment]
is it possible to write output file in .npy format?
