### ISSUE TITLE
Inference with Pretrained Models OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe211OperatorDef17default_instance_E

### ISSUE THREAD

**Issue by IgorKasianenko** [facebookresearch/Detectron#345]
### Expected results

Running inference on demo data accordind to [tutorial](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md)

### Actual results & Detailed steps to reproduce

` ~/projects/Detectron$ python2 tools/infer_simple.py \
>     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
>     --output-dir /tmp/detectron-visualizations \
>     --image-ext jpg \
>     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
>     demo
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
Traceback (most recent call last):
  File "tools/infer_simple.py", line 51, in <module>
    c2_utils.import_detectron_ops()
  File "/home/user/projects/Detectron/lib/utils/c2.py", line 42, in import_detectron_ops
    dyndep.InitOpsLibrary(detectron_ops_lib)
  File "/home/user/anaconda2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 35, in InitOpsLibrary
    _init_impl(name)
  File "/home/user/anaconda2/lib/python2.7/site-packages/caffe2/python/dyndep.py", line 48, in _init_impl
    ctypes.CDLL(path)
  File "/home/user/anaconda2/lib/python2.7/ctypes/__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/local/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZN6caffe211OperatorDef17default_instance_E `

### System information

* Operating system: Ubuntu 16.04
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* CUDA version: V9.0.176
* cuDNN version: libcudnn7_7.1.2.21-1+cuda9.0_amd64
* NVIDIA driver version: 390.48
* GPU models (for all devices if they are not all the same): v100
* `PYTHONPATH` environment variable: blank
* `python --version` output: Python 2.7.14 :: Anaconda, Inc.
* Anything else that seems relevant: I've reinstalled all nvidia drivers and libraries today. Biggest issue was with CUDA, as for some tests like cheking caffe2 or nvidia installations I had errors pointing to CUDA 9.1 while I set explicite to use CUDA 9.0

**Comment by datamonday** [comment]
same error ...would you like to share the method?

**Comment by datamonday** [comment]
Got it!

I export the python path like /home/chopin/anaconda3/envs/caffe2/caffe2/build/caffe2/python to ~/.bashrc and then pip install utils .

Now, it's running! I hope this will help you.

**Comment by IgorKasianenko** [comment]
> I export the python path like /home/chopin/anaconda3/envs/caffe2/caffe2/build/caffe2/python to ~/.bashrc and then pip install utils .

I did this,
`export $PYTHONPATH=/home/user/caffe2/build/caffe2/python`
 and got `pip
-bash: /usr/local/bin/pip: /usr/bin/python: bad interpreter: No such file or directory`

looks like my caffe2 is installed in user/caffe2 and not in conda env. I don't understand why [caffe2 guide](https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile)
`cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" \|\| echo "Failure"
--`
returns "Success", but Detectron fails like described in first post

**Comment by datamonday** [comment]
yes

**Comment by IgorKasianenko** [comment]
Do you run it on CUDA version: V9.0 and cuDNN version: libcudnn7 ?
