### ISSUE TITLE
E2E Training No Proposal File Custom Dataset

### ISSUE THREAD

**Issue by CoolComputerGuy123** [facebookresearch/Detectron#348]
When running train_net.py on a custom dataset I received the error:

cfg.TEST.PROPOSAL_FILES = cfg.TEST.PROPOSAL_FILES{i]
IndexError: tuple index out of range

The model was set as "generalized_rcnn", 50 layers, with FASTER:off and FPN on. Was the model supposed to be end-to-end trained, and this is an error, or is the end-to-end training only for COCO?

### Expected results

Proposal file automatically produced.

### Actual results

Error caused by lack of proposal file

### Detailed steps to reproduce

```
train_net.py
```
on a custom dataset

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 5.4
* CUDA version: release 8.0, V8.0.61
* cuDNN version: 7
* NVIDIA driver version: 384.111
* GPU models (for all devices if they are not all the same): GTX 970
* `python --version` output: 2.7.14

**Comment by ir413** [comment]
Hi @CoolComputerGuy123, please read the description of the `MODEL.FASTER_RCNN` option [here](https://github.com/facebookresearch/Detectron/blob/master/lib/core/config.py#L448L458) and see e2e [baseline configs](https://github.com/facebookresearch/Detectron/tree/master/configs/12_2017_baselines) for examples of end-to-end training configs.
