### ISSUE TITLE
Desktop freezing while Training Getting Started Model

### ISSUE THREAD

**Issue by ambigus9** [facebookresearch/Detectron#350]
### Expected results

What did you expect to see?
Model_final.pkl trained OK

### Actual results
My Desktop is just freezing, suppose because RAM it's full (I have 8 GB)

What did you observe instead?
Models trained

### Detailed steps to reproduce

E.g.:

```
python2 tools/train_net.py \
    --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml \
    OUTPUT_DIR /tmp/detectron-output
```

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 5.4.0
* CUDA version: 8.0
* cuDNN version: 7.1.1
* NVIDIA driver version: 384.111
* GPU models (for all devices if they are not all the same): Nvidia GTX 1050Ti
* `PYTHONPATH` environment variable: /usr/local/caffe2_build:
* `python --version` output: 2.7.12
* Anything else that seems relevant: 
* CPU: Intel Core 2 Duo E7200 at 2.53 GHz
* RAM: 8 GB at 18333 MHz

Aditional to this issue, I would like to know any advice to the workflow to train a model. Wich is the structure of annotations? How can I train a model with my own images?

Thanks.

**Comment by rbgirshick** [comment]
Not enough memory; little that we can do here.
