### ISSUE TITLE
"MAX_ITER" is for one GPU or for multiple GPUs

### ISSUE THREAD

**Issue by tianzq** [facebookresearch/Detectron#354]
I am not sure how to set "MAX_ITER" for 8 GPUs.

If I set MAX_ITER=80000, each GPU iterates 10000 or 80000?

**Comment by ir413** [comment]
Hi @tianzq, Detectron uses synchronous SGD so each GPU will perform `TRAIN.MAX_ITER` iterations with `TRAIN.IMS_PER_GPU` images (e.g. see [this](https://caffe2.ai/docs/SynchronousSGD.html) for more info).
