### ISSUE TITLE
.pdf format

### ISSUE THREAD

**Issue by moulei007** [facebookresearch/Detectron#357]
I want to  save my results in .jpg format, then , where should I change in the source code?

**Comment by moulei007** [comment]
After a careful view at source code, I finally  convert .pdf format into .png format.

**Comment by ir413** [comment]
Duplicate of #344

**Comment by aishoushi** [comment]
Hi, when I use infer_simple.py, it turns out such problem:
I/O Error: Couldn't open file 'infer_outputs/.pdf': No such file or directory.
Syntax Error: Could not merge damaged documents ('infer_outputs/.pdf')
why is it? @gadcam
