### ISSUE TITLE
CPU prediction support

### ISSUE THREAD

**Issue by lczarne** [facebookresearch/Detectron#36]
Is it possible to use Detectron models in CPU mode for prediction?

**Comment by rbgirshick** [comment]
Not at this time.

In the future, we will be releasing a tool that will export a standalone model that can be executed directly by the Caffe2 runtime without any additional code (i.e. no Python). It will support CUDA, CPU, and mobile devices. Initially it will only support a limited set of models, but we plan to increase coverage over time.

**Comment by manyaafonso** [comment]
@rbgirshick any news/update on this tool?
