### ISSUE TITLE
convert_cityscapes_to_coco.py error:ValueError: too many values to unpack

### ISSUE THREAD

**Issue by wuqi930907** [facebookresearch/Detectron#361]
When I used convert_cityscapes_to_coco.py to convert cityscape to coco format,I got an error:
in instances2dict_with_polygons
    contour, hier = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
ValueError: too many values to unpack

Thanks

**Comment by ir413** [comment]
Hi @wuqi930907, `cv2.findContours` API changed in OpenCV 3.2 (see #9 for more info)

> Since OpenCV 3.2, findContours() no longer modifies the source image but returns a modified image as the first of three return parameters.

So if you're using OpenCV >= 3.2 try something like:

```
_, contour, hier = cv2.findContours(...)
```

**Comment by wuqi930907** [comment]
My opencv's version is 3.4.12, I have modified the code to "_, contour, hier = cv2.findContours(mask.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)", but when I used convert_cityscapes_to_coco.py again, I also got an Warning: invalid contours.
Is something wrong？
Thanks @ir413

**Comment by krumo** [comment]
@wuqi930907 Hi, I also get Warning: invalid contours. Did you solve this problem? Thank you!

**Comment by sidnav** [comment]
@wuqi930907 could you fix the `invalid contours` issue?

**Comment by gittigxuy** [comment]
@wuqi930907 ,same question:
Processed 0 images, 0 annotations
Traceback (most recent call last):
  File "tools/convert_cityscapes_to_coco_bddFormat.py", line 212, in <module>
    convert_cityscapes_instance_only(datadir, outdir)
  File "tools/convert_cityscapes_to_coco_bddFormat.py", line 168, in convert_cityscapes_instance_only
    if obj['contours'] == []:
KeyError: u'contours'

**Comment by Luodian** [comment]
will this "invalid contours warning" affect the transformed dataset?

**Comment by hoonkai** [comment]
@Luodian I'd like to know that too.

**Comment by dhananjaisharma10** [comment]
A contour is defined as the pixel positions enclosing a shape. An invalid contour is formed when you combine <= 4 such pixels given the function `cv2.findContours` was provided with `cv2.CHAIN_APPROX_NONE` as one of the arguments. Such a shape would resemble either a single pixel, a line, a triangle or a square with no pixels nothing inside them.

[This](https://github.com/facebookresearch/maskrcnn-benchmark/pull/1088#issuecomment-536551756) might be helpful too. For more information about `cv2.findContours`, check [this](https://docs.opencv.org/master/d4/d73/tutorial_py_contours_begin.html). Overall, these instances are meaningless and so are discarded. Hope it helps!
