### ISSUE TITLE
How to get inference results in coco json format?

### ISSUE THREAD

**Issue by KimSangYeon-DGU** [facebookresearch/Detectron#364]
## PLEASE FOLLOW THESE INSTRUCTIONS BEFORE POSTING
1. Please thoroughly read README.md, INSTALL.md, GETTING_STARTED.md, and FAQ.md
2. Please search existing *open and closed* issues in case your issue has already been reported
3. Please try to debug the issue in case you can solve it on your own before posting

## After following steps 1-3 above and agreeing to provide the detailed information requested below, you may continue with posting your issue
I want to get json results like coco json format at the end of inference stage, but I just can get processed images. I tried to find methods that provide that function at tutorials, and source code, however I didn't find it. If you know about it, please let me know

### Expected results

What did you expect to see?

### Actual results

What did you observe instead?

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @KimSangYeon-DGU, we currently don't provide a function for converting detections to json format. To do that, you can try using the following function:
```
def convert_dets_to_anns(dataset_name, dets_file, out_dir):
    """Converts detections to json annotations."""

    # Load the detections
    with open(dets_file, 'r') as f:
      all_boxes = pickle.load(f)['all_boxes']

    # Generate annotations from the detections
    anns = []
    
    # We assume that detections are for the given dataset
    test_dataset = JsonDataset(dataset_name)
    test_roidb = test_dataset.get_roidb()

    for cls_ind, cls in enumerate(test_dataset.classes):
        if cls == '__background__':
            continue
        assert cls_ind <= len(all_boxes)

        logger.info('Generating {} annotations ({:d}/{:d})'.format(
            cls, cls_ind, len(all_boxes) - 1))

        # Use original cat ids
        cat_id = test_dataset.category_to_id_map[cls]

        # Extract the boxes for the current category
        cls_boxes = all_boxes[cls_ind]
        assert len(cls_boxes) == len(test_roidb)

        for i, entry in enumerate(test_roidb):
            # Skip images that have no detections for the current class
            if len(cls_boxes[i]) == 0:
                continue

            boxes = cls_boxes[i].astype(np.float)
            xs = boxes[:, 0]
            ys = boxes[:, 1]
            ws = boxes[:, 2] - xs + 1
            hs = boxes[:, 3] - ys + 1
            areas = ws * hs

            # Construct annotations for instances detected in the ith image
            for j in range(boxes.shape[0]):
                # Construct the instance annotation with box info
                ann_i_j = {
                    'id': len(anns),
                    'image_id': entry['id'],
                    'category_id': cat_id,
                    'segmentation': [],
                    'area': areas[j],
                    'bbox': [xs[j], ys[j], ws[j], hs[j]],
                    'score': boxes[j, 4],
                    'iscrowd': 0
                }
                anns.append(ann_i_j)

    # Use categories from the given dataset
    cat_ids = test_dataset.COCO.getCatIds()
    cats = test_dataset.COCO.loadCats(cat_ids)

    # Include the image metadata
    img_ids = test_dataset.COCO.getImgIds()
    imgs = test_dataset.COCO.loadImgs(img_ids)

    # Construct a coco-style dataset object
    gen_dataset_obj = {
        'annotations': anns,
        'images': imgs,
        'categories': cats
    }

    # Save the generated annotations
    out_name = 'gen_anns_{}.json'.format(test_dataset.name)
    out_file = os.path.join(out_dir, out_name)

    with open(out_file, 'w') as f:
        json.dump(gen_dataset_obj, f)
```

Please note that I have not tested this function but it should work (perhaps with small modifications). 
This is derived from a similar function we used for data distillation (https://arxiv.org/abs/1712.04440).

**Comment by KimSangYeon-DGU** [comment]
Oh... thank you so much. It is very big help for me!! I will try to test the code!!  :D

**Comment by AruniRC** [comment]
@ir413  could you give any implementation suggestions on efficiently loading the soft-labels used in distillation ('score') into the roidb, so that it can be used in a distillation-style loss?

**Comment by Walter0807** [comment]
Hi, how can I get keypoints detection results in COCO json format like [this](https://dl.fbaipublicfiles.com/detectron/37697547/12_2017_baselines/e2e_keypoint_rcnn_R-50-FPN_1x.yaml.08_42_54.kdzV35ao/output/test/keypoints_coco_2014_minival/generalized_rcnn/keypoints_keypoints_coco_2014_minival_results.json)? Thanks!

**Comment by wendeehsu** [comment]
> Hi, how can I get keypoints detection results in COCO json format like [this](https://dl.fbaipublicfiles.com/detectron/37697547/12_2017_baselines/e2e_keypoint_rcnn_R-50-FPN_1x.yaml.08_42_54.kdzV35ao/output/test/keypoints_coco_2014_minival/generalized_rcnn/keypoints_keypoints_coco_2014_minival_results.json)? Thanks!

Maybe [this answer](https://github.com/cocodataset/cocoapi/issues/39#issuecomment-456641698) will work for you.
