### ISSUE TITLE
installing python modules after installing caffe2

### ISSUE THREAD

**Issue by zneha** [facebookresearch/Detectron#366]
### Expected results

Do not know how the output should look like?

### Actual results

neha@neha-Aspire-A515-51:~$ cd Downloads
neha@neha-Aspire-A515-51:~/Downloads$ cd cocoapi
neha@neha-Aspire-A515-51:~/Downloads/cocoapi$ cd PythonAPI
neha@neha-Aspire-A515-51:~/Downloads/cocoapi/PythonAPI$ cd detectron/lib && makepython2 setup.py develop --user
Traceback (most recent call last):
  File "setup.py", line 20, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
Makefile:17: recipe for target 'dev' failed
make: *** [dev] Error 1

### Detailed steps to reproduce

E.g.:

```
The command that you ran

cd detectron/lib && make

### System information

* Operating system: ubuntu 16.04
* Compiler version: ?
* CUDA version: 9.0
* cuDNN version: 7
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @zneha, please see the [installation instructions](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#other-dependencies) for how to install python dependencies.

>Install Python dependencies:
>
>pip install numpy>=1.13 pyyaml>=3.12 matplotlib opencv-python>=3.2 setuptools Cython mock scipy
