### ISSUE TITLE
Mini-batch validation when training keypoint model in end-to-end manner

### ISSUE THREAD

**Issue by mks0601** [facebookresearch/Detectron#367]
When training keypoint model in end-to-end manner, the mini-batch is only validated in lib/roi_data/minibatch.py. However, as the RPN.RPN_ON is True, 'valid' variable is always assigned to be True (add_rpn_blobs always returns True). 

add_fast_rcnn_blobs function validate the minibatch considering keypoints, however it is in the lib/ops/collect_and_distribute_fpn_rpn_proposals.py which is called in add_generic_rpn_outputs. As the add_generic_rpn_outputs function is called in lib/modeling/model_builder.py, it cannot validate the minibatch in an online manner. 

This causes the error https://github.com/facebookresearch/Detectron/issues/347. Although the len(roi)==0, detectorn consider this batch is valid batch because add_rpn_blobs always returns True.

**Comment by rbgirshick** [comment]
Closing this issue to consolidate reports into #347.

**Comment by zamponotiropita** [comment]
@mks0601 did you manage to solve the problem?
