### ISSUE TITLE
Save model for inference. How to generate *.prototxt?

### ISSUE THREAD

**Issue by IgorKasianenko** [facebookresearch/Detectron#373]
Hello, my goal is to run Maks R-CNN inference independently without depending on Detectron code base.

First approach was to convert model to *.pb, but at the moment [FPN is not supported](https://github.com/facebookresearch/Detectron/issues/134) even that [caffe2 team is working on it](https://github.com/pytorch/pytorch/pull/6645). 

Meanwhile I'd like to run the model in C++, according to [nVidia guide](https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#fasterrcnn_sample). Their sample uses FasterRCNN, from this source [py-faster-rcnn](https://github.com/rbgirshick/py-faster-rcnn) that has been deprecated and leads to Detectron repo. Nevertheless, py-faster-rcnn has very useful file [test.prototxt](https://github.com/rbgirshick/py-faster-rcnn/blob/master/models/pascal_voc/VGG16/faster_rcnn_end2end/test.prototxt), with all layers description. That file is needed to write cpp plugins for custom layers, that can't be translated.

My question is how can I generate or find maskrcnn.prototxt file for Detectron, for two solutions, VGG16 and ResNet101?

I assume in case of ResNet101 it would be much bigger, as Detectron is not only adding masking to FasterRCNN, but also adds Feature Pyramid Networks.

**Comment by rbgirshick** [comment]
The only viable route is to use the `convert_pkl_to_pb.py` script, but as you noted it does not yet support the full set of models that Detectron can train.
