### ISSUE TITLE
Constructing the network

### ISSUE THREAD

**Issue by Yuliang-Zou** [facebookresearch/Detectron#374]
I want to understand the order of network construction. For example, I am using the Mask R-CNN (ResNet-50+FPN), I notice that we construct the network first, and then we deal with the data pipeline. 

However, in this [file](https://github.com/facebookresearch/Detectron/blob/master/lib/modeling/ResNet.py#L89), we already use `data` when constructing the first conv layer. I wonder where did you define `data` in the workspace?

**Comment by rbgirshick** [comment]
Caffe2 is declarative. The functions in that file say _how_ to the build the execution graph, but _do not run it_. Thus the code can refer to tensors, like `data`, that do not yet exist. What is required is that when a graph is run (e.g., `workspace.RunNet(...)`) the data that it depends on must be in the workspace.
