### ISSUE TITLE
Why I can't get the similar result as reported in model zoo when training on 1 GPU

### ISSUE THREAD

**Issue by theFoxofSky** [facebookresearch/Detectron#377]
### Expected results

What did you expect to see?

I expect to get results similar to those reported in model zoo.

### Actual results

What did you observe instead?

When I training e2e_faster_rcnn_R-50-C4_1x on coco, I just get mAP[0.5:0.9] = 0.244. 

### Detailed steps to reproduce

I change the base_lr to 0.001 (the original setting is 0.01). And then, run the command:

python2 tools/train_net.py --cfg configs/12_2017_baselines/e2e_faster_rcnn_R-50-C4_1x.yaml  NUM_GPUS 1 OUTPUT_DIR ~/Documents/Python/iou_reg/e2e_faster_rcnn_R-50-C4_1x_origin_low_lr

### System information

* Operating system: ubuntu 16.04
* CUDA version: CUDA 8.0
* cuDNN version: cuDNN 7.5
* NVIDIA driver version: NVIDIA-Linux-x86_64-381.22
* `python --version` output: Python 2.7.12

**Comment by ppwwyyxx** [comment]
For e2e_faster_rcnn_R-50-C4_1x, if you attempt to get similar performance with one GPU, you'll need to:
* change base_lr to 0.00125
* change steps to [0, 960000, 1280000]
* change max_iter to 1440000
Training will take at least one week. So we have never tried this.

**Comment by theFoxofSky** [comment]
@ppwwyyxx Thanks，I'll try it again.

**Comment by theFoxofSky** [comment]
@
