### ISSUE TITLE
Duplicate the detector

### ISSUE THREAD

**Issue by Yuliang-Zou** [facebookresearch/Detectron#378]
I want to perform detection on a video. And if I want to enforce some temporal consistency, I would like to use some feature tensors from the previous frame when detecting the current frame (via LSTM or warping the feature).

I wonder how to do this. Is there anything similar to `reuse_variables` in TensorFlow?

**Comment by rbgirshick** [comment]
This is of course possible, but will have to be done at a lower level using the appropriate operators. Just think about things in terms of workspaces, "blobs" (tensors), and execution graphs.
