### ISSUE TITLE
Wrongly localized the bounding box 

### ISSUE THREAD

**Issue by soumenms2015** [facebookresearch/Detectron#381]
Hello, 
I converted my pascal voc xml annotation into  json format coco like annotation. During training, I tried to visualize how model got trained by generating bounding box and it shows that the all bonudning box is shifted up or down. Hence it is not correctly localized. Any idea? Where could be the error in generating json file or in some scaling issue in model. 
Any idea would be highly appreciated.

**Comment by rbgirshick** [comment]
I don't think there's enough information in the issue report for anyone to help. Re-open if you want to provide more details.
