### ISSUE TITLE
Pascal 2007 inference with coco classes

### ISSUE THREAD

**Issue by tony-mtz** [facebookresearch/Detectron#385]
Currently infer_simple.py uses dummy_datasets that list coco classes.  This doesn't work with the Pascal dataset.  Perhaps a parameter could be used to specify the appropriate classes.  If we are meant to modify the code directly then please ignore.  Thanks.

**Comment by rbgirshick** [comment]
The `infer_simple` demo code is just for COCO for now, so you will need to modify the code.

**Comment by mamunir** [comment]
I have asked this question on issue#559, please respond here or there. @tony-mtz thanks!
"I have successfully trained Retina net on Pascal VoC (annotations are used as given in official link from coco) and mAP shows 0.656. I found all train is labeled as sheep during inference and confidence is also high. I have manually analyzed each text files, there specific and most of the labels are correct with high confidence but problem is at infernce time, while display as pdf image file. Confidence score is also changed as in text file. Please let me know what would the exact issue? Is there any issue with annotation file? I do not think so as mAP is quite reasonable (AP train = 0.72, sheep =0.52)"
