### ISSUE TITLE
assert not cfg.MODEL.MASK_ON, "Mask model not supported." convert_pkl_to_pb.py

### ISSUE THREAD

**Issue by IgorKasianenko** [facebookresearch/Detectron#387]
### Expected results

Exported .pb model

### Actual results & Detailed steps to reproduce

From detectron folder I run
```
export cfg=configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml
export net_name=e2e_mask_rcnn_R-101-FPN_2x
python tools/convert_pkl_to_pb.py --use_nnpack 0 --net_name "${net_name}" \
--cfg "${cfg}" --out_dir "models/pb_output/"
...
...
Traceback (most recent call last):
  File "tools/convert_pkl_to_pb.py", line 574, in <module>
    main()
  File "tools/convert_pkl_to_pb.py", line 527, in main
    assert not cfg.MODEL.MASK_ON, "Mask model not supported."
AssertionError: Mask model not supported.
```

### Additional info

I'd like to export MaskRCNN model to .pb file. I run convert_pkl_to_pb as described, with parameters from [Detectron Getting Started](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md)
I ran demo and all works great.

I saw similar [issue](https://github.com/pytorch/pytorch/pull/6645), and solution came from caffe2 itself. Should I address this issue to caffe2 repo?
If there is a way to implement it, I'd be happy to work on it, it is key task for me at the moment.

**Comment by daquexian** [comment]
Hi :) Please try #372 (and also https://github.com/pytorch/pytorch/pull/7091). I just make fpn fully correct today. But I'm afraid the convert script only convert the bbox branch. By some little modification the mask branch may be converted,  mask branch has no detectron-specific layers

**Comment by enjoykcc456** [comment]
Hi @IgorKasianenko have u successfully converted the model? Thank you.

**Comment by IgorKasianenko** [comment]
Hi @enjoykcc456 
I didn't convert the model. But if you want to use it today, it is as easy as importing it from torchvision, follow this example https://pytorch.org/tutorials/intermediate/torchvision_tutorial.html
