### ISSUE TITLE
CPU only?

### ISSUE THREAD

**Issue by adv1023** [facebookresearch/Detectron#39]
How would I train the model with no GPU's. I am on a system with no GPU's, however, I have access to more than 16 CPU's. 
Would the instructions be similar, to those for faster-rcnn? 
Thank you.

"
Set USE_GPU_NMS in ./lib/fast_rcnn/config.py (or your YAML file) to False.
In ./tools/test_net.py / train_net.py, replace caffe.set_mode_gpu() with caffe_set_mode_cpu().
Plus, if you do not have a GPU, you can compile Caffe in CPU_ONLY mode (and also ignore the GPU nms code).
"

https://github.com/rbgirshick/py-faster-rcnn/issues/123

**Comment by rbgirshick** [comment]
We do not plan to support CPU-only training. Some ops are currently only implemented for GPUs at this time and training will likely be too slow unless it is distributed over >>100 of CPUs. For CPU-only inference see #24.

**Comment by hxw111** [comment]
@rbgirshick You said that some ops are currently only implemented for GPUs . What about the 
"AffineChannel" op? Is it implemented only for GPUs  too?
