### ISSUE TITLE
empty blobs when call add_roi_pose_head_v1convX

### ISSUE THREAD

**Issue by nebuladream** [facebookresearch/Detectron#392]
I train the model without pre-trained model, the code crash after some iter. the problem is input blobs size is zero. How can I avoid this error?
RuntimeError: [enforce fail at conv_pool_op_base.h:237] input.size() > 0.  Error from operator: 
input: "gpu_0/_[pose]_roi_feat" input: "gpu_0/conv_fcn1_w" input: "gpu_0/conv_fcn1_b" output: "gpu_0/conv_fcn1" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
^C*** Aborted at 1524668011 (unix time) try "date -d @1524668011" if you are using GNU date ***
PC: @     0x7f7883078050 sem_wait
*** SIGTERM (@0x46400014b23) receive

**Comment by nebuladream** [comment]
I find when detector generate  zero proposal, krcnn branch will not stop this invalid batch.

**Comment by rbgirshick** [comment]
Closing this issue to consolidate reports into #347.
