### ISSUE TITLE
Question about cross boundary anchors

### ISSUE THREAD

**Issue by twmht** [facebookresearch/Detectron#393]
Hello,

In Section 5.1 of FPN paper, you mentioned

> we include the anchor boxes that are outside the image for training

But from the training config and default configs, you don't include such anchor boxes when training.

Here is the default config
https://github.com/facebookresearch/Detectron/blob/master/lib/core/config.py#L170

Here is the training config without setting `TRAIN.RPN_STRADDLE_THRESH`
https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/rpn_R-50-FPN_1x.yaml

Why the implementation is different from the paper?

by the way, from the faster rcnn paper, you mentioned

> With the cross-boundary anchors ignored, there are about 6000 anchors per image for training. If the boundary-crossing outliers are not ignored in training,they introduce large, difficult to correct error terms in the objective, and training does not converge

When training FPN with cross-boundary anchors, why this issue not happened?

thank you

**Comment by rbgirshick** [comment]
It seems that this choice does not really matter. I have tried both (for a few limited models) and found very similar performance. The original observation from the Faster R-CNN and FPNs paper may have been due to implementation issues, not fundamental problems.
