### ISSUE TITLE
A Bug in lib/datasets/json_dataset.py

### ISSUE THREAD

**Issue by Musicwire** [facebookresearch/Detectron#397]
Lines from 178 to 180

`obj['segmentation'] = [p for p in obj['segmentation'] if len(p) >= 6]`

For example, if the segmentation is [[26, 31, 50, 31]], then it would be [] after that.
And then it may cause an ERROR at line 125 in lib/utils/segms.py

**Comment by rbgirshick** [comment]
A polygon with 4 numbers (e.g., `[[26, 31, 50, 31]]`) specifies only 2 points and hence has no area (it's a line). This is a rudimentary check to ensure the polygon has at least three points (though it does not test that they are not co-linear, which would be more correct).

**Comment by Musicwire** [comment]
@rbgirshick Thanks for replying.
But what you said was just an explanation for lines from 178 to 180 in json_dataset.py.

And now here I have an image with just one instance and I don't know why the polygon computed from the mask annotation is `[26, 31, 50, 31]`, as you said are only 2 points.
So in theory it should be discard, as the codes indicating from 178 to 180.

But after that, the segmentation became [] from `[[26, 31, 50, 31]]`.
And it cause an ERROR at line 125 in lib/utils/segms.py.

I think there should be an check after line 180, like
```
if not len(obj['segmentation']):  
       continue
```
