### ISSUE TITLE
make ops failed

### ISSUE THREAD

**Issue by nangongtianyi** [facebookresearch/Detectron#402]
I have installed the caffe2 successfully.When I try to run the commands 'cd $DETECTRON/lib && make ops', the error appears and is showed as follows:
`[ 20%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
nvcc fatal   : redefinition of argument 'std'
CMake Error at caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o.cmake:203 (message):
  Error generating
  /home/flyfree/detectron/lib/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/./caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:63: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o] Error 1
make[3]: Leaving directory '/home/flyfree/detectron/lib/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: *** 正在等待未完成的任务....
make[3]: Leaving directory '/home/flyfree/detectron/lib/build'
[ 60%] Built target caffe2_detectron_custom_ops
make[2]: Leaving directory '/home/flyfree/detectron/lib/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/flyfree/detectron/lib/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2`
What should I do to solve the problem?

**Comment by wenzige** [comment]
Hi, I met with the same problem. What is the solution please?

**Comment by ir413** [comment]
It is hard to tell what the the solution/issue is without have more info about the setup. As noted earlier, please make sure you're using the latest master and provide the info requested in the [issue template](https://github.com/facebookresearch/Detectron/blob/master/.github/issue_template.md).
