### ISSUE TITLE
How to fetch labels from the 'labels' blob?

### ISSUE THREAD

**Issue by Kongsea** [facebookresearch/Detectron#403]
Previous to [line 72 of 'fast_cnn_heads.py'](https://github.com/facebookresearch/Detectron/blob/master/lib/modeling/fast_rcnn_heads.py#L72), I want to fetch the labels of the batch before calculating the softmax loss.
I think I can use the following code to do so:

```
from caffe2.python import workspace
labels = workspace.FetchBlob('labels_int32')
```

However, it raised an error:

> {RuntimeError}[enforce fail at pybind_state.cc:174] ws->HasBlob(name). Can't find blob: labels_int32

So how to fetch the labels of the batch? Please give me some advice, thank you.

**Comment by ir413** [comment]
Hi @Kongsea, the blob name you are trying to fetch is likely scoped (e.g. `gpu_0/labels_int32` rather than `labels_int32`). To retrieve the blob you can can use the `ScopedName` function as is done [here](https://github.com/facebookresearch/Detectron/blob/master/lib/core/test.py#L162). Additionally, you can see how training blobs are loaded [here](https://github.com/facebookresearch/Detectron/blob/master/lib/roi_data/loader.py#L178) and find some Caffe2 helper functions [here](https://github.com/facebookresearch/Detectron/blob/master/lib/utils/c2.py).

**Comment by PacteraKun** [comment]
@Kongsea 
Hi, Kongsea, I have the same problem happened when I want to fetch the labels of the batch. May I ask how do you solve this? Thanks.

**Comment by Kongsea** [comment]
@PacteraKun Do you understand Chinese? If so, you can read and refer to my blog where I have written my method to process the problem.

**Comment by PacteraKun** [comment]
@Kongsea  Sure. Could you please offer me the link to your blog? Thanks so much.

**Comment by Kongsea** [comment]
**my blog** in the last comment is the exact link.

**Comment by PacteraKun** [comment]
@Kongsea 
Thanks. You have done a great work. But I still can't fetch the labels_int32 blob, which I need to change during the training process. Do you have any other suggestions?

**Comment by Kongsea** [comment]
I think links @ir413 suggested will be helpful to you.
You can replace `lib` with `detectron` in the links he posted to access them.
For example, one link he posted is `https://github.com/facebookresearch/Detectron/blob/master/lib/core/test.py#L162`, you can access `https://github.com/facebookresearch/Detectron/blob/master/detectron/core/test.py#L162` instead.

**Comment by PacteraKun** [comment]
Thanks for the link. It helps me a lot. But the problem still exists after adding **core.ScopedName**. The blob **labels_int32** is the output of the network not the input of the network. And I need to first fetch the blob **labels_int32** to create my own box classes for the predicted bounding boxes.   

And I also try to add **workspace.RunNetOnce(model.param_init_net)** before I want to fetch the blob **labels_int32**, but it doesn't work at all. Do you have any other suggestions to solve this issue? Thanks in advance. @ir413 @Kongsea
