### ISSUE TITLE
Minibatch Queue Always Empty

### ISSUE THREAD

**Issue by wuharvey** [facebookresearch/Detectron#408]
Hello! I'm training on my own dataset, but training seems to be very slow, as the mini batch queue is always empty.

### Expected results
mb_qsize > 0.

### Actual results
mb_qsize consistently zero after first 60 iterations. GPU usage is consistently zero upon checking nvidia-smi. "time" is also monotonically increasing.

Example from train_net.py:
json_stats: {"accuracy_cls": 0.973633, "eta": "4:53:19", "iter": 660, "loss": 0.735692, "loss_bbox": 0.006042, "loss_cls": 0.116962, "loss_rpn_bbox_fpn2": 0.112087, "loss_rpn_bbox_fpn3": 0.018113, "loss_rpn_bbox_fpn4": 0.000688, "loss_rpn_bbox_fpn5": 0.000000, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.290812, "loss_rpn_cls_fpn3": 0.083534, "loss_rpn_cls_fpn4": 0.012439, "loss_rpn_cls_fpn5": 0.001868, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.002500, "mb_qsize": 0, "mem": 4099, "time": 1.884333}
### Detailed steps to reproduce

All hyperparameters besides dataset specific (num classes) are the same as tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml 

### System information

* Operating system: Ubuntu 16.04.
* Compiler version: 
* CUDA version: 9.0
* cuDNN version: 7.1
* NVIDIA driver version: 384.111
* GPU models (for all devices if they are not all the same): P100

**Comment by rbgirshick** [comment]
This means that data loading is taking too long. Where are the images stored? Is it slow to read from? Did you make any changes to the data loader? You'll need to do some profiling and debugging to figure out what's going on. Using `tests/data_loader_benchmark.py` can be very helpful for understanding data loader issues without running training.

**Comment by wuharvey** [comment]
Great - thanks for the help!!

**Comment by geyuying** [comment]
Did you solve the problem? I meet the same problem that minibatch queue is empty and training is very slow.
