### ISSUE TITLE
Error: train mask rcnn on my own data

### ISSUE THREAD

**Issue by Vivianyzw** [facebookresearch/Detectron#409]
when I train my own data, I meet the following error after 25520 iterations. I have no idea to locate the errors. Is there any one meet the same error, and what is your solution? Thank you in advance!

`
E0503 12:05:50.852013 13086 pybind_state.h:409] Exception encountered running PythonOp function: ValueError: column index exceeds matrix dimensions

At:
  /usr/lib/python2.7/dist-packages/scipy/sparse/coo.py(238): _check
  /usr/lib/python2.7/dist-packages/scipy/sparse/coo.py(182): __init__
  /usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py(936): tocoo
  /usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py(940): toarray
  /mnt/data1/detectron/lib/datasets/json_dataset.py(436): _add_class_assignments
  /mnt/data1/detectron/lib/datasets/json_dataset.py(344): add_proposals
  /mnt/data1/detectron/lib/ops/collect_and_distribute_fpn_rpn_proposals.py(55): forward
E0503 12:05:50.858925 13086 net_dag.cc:195] Exception from operator chain starting at 'CollectAndDistributeFpnRpnProposalsOp:gpu_0/rpn_rois_fpn2,gpu_0/rpn_rois_fpn3,gpu_0/rpn_rois_fpn4,gpu_0/rpn_rois_fpn5,gpu_0/rpn_rois_fpn6,gpu_0/rpn_roi_probs_fpn2,gpu_0/rpn_roi_probs_fpn3,gpu_0/rpn_roi_probs_fpn4,gpu_0/rpn_roi_probs_fpn5,gpu_0/rpn_roi_probs_fpn6,gpu_0/roidb,gpu_0/im_info' (type 'Python'): caffe2::EnforceNotMet: [enforce fail at pybind_state.h:410] . Exception encountered running PythonOp function: ValueError: column index exceeds matrix dimensions

At:
  /usr/lib/python2.7/dist-packages/scipy/sparse/coo.py(238): _check
  /usr/lib/python2.7/dist-packages/scipy/sparse/coo.py(182): __init__
  /usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py(936): tocoo
  /usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py(940): toarray
  /mnt/data1/detectron/lib/datasets/json_dataset.py(436): _add_class_assignments
  /mnt/data1/detectron/lib/datasets/json_dataset.py(344): add_proposals
  /mnt/data1/detectron/lib/ops/collect_and_distribute_fpn_rpn_proposals.py(55): forward
 Error from operator:
input: "gpu_0/rpn_rois_fpn2" input: "gpu_0/rpn_rois_fpn3" input: "gpu_0/rpn_rois_fpn4" input: "gpu_0/rpn_rois_fpn5" input: "gpu_0/rpn_rois_fpn6" input: "gpu_0/rpn_roi_probs_fpn2" input: "gpu_0/rpn_roi_probs_fpn3" input: "gpu_0/rpn_roi_probs_fpn4" input: "gpu_0/rpn_roi_probs_fpn5" input: "gpu_0/rpn_roi_probs_fpn6" input: "gpu_0/roidb" input: "gpu_0/im_info" output: "gpu_0/rois" output: "gpu_0/labels_int32" output: "gpu_0/bbox_targets" output: "gpu_0/bbox_inside_weights" output: "gpu_0/bbox_outside_weights" output: "gpu_0/mask_rois" output: "gpu_0/roi_has_mask_int32" output: "gpu_0/masks_int32" output: "gpu_0/rois_fpn2" output: "gpu_0/rois_fpn3" output: "gpu_0/rois_fpn4" output: "gpu_0/rois_fpn5" output: "gpu_0/rois_idx_restore_int32" output: "gpu_0/mask_rois_fpn2" output: "gpu_0/mask_rois_fpn3" output: "gpu_0/mask_rois_fpn4" output: "gpu_0/mask_rois_fpn5" output: "gpu_0/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_0/rpn_rois_fpn2,gpu_0/rpn_rois_fpn3,gpu_0/rpn_rois_fpn4,gpu_0/rpn_rois_fpn5,gpu_0/rpn_rois_fpn6,gpu_0/rpn_roi_probs_fpn2,gpu_0/rpn_roi_probs_fpn3,gpu_0/rpn_roi_probs_fpn4,gpu_0/rpn_roi_probs_fpn5,gpu_0/rpn_roi_probs_fpn6,gpu_0/roidb,gpu_0/im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:5" } arg { name: "grad_output_indices" } device_option { device_type: 0 }Error from operator:
input: "gpu_0/rpn_rois_fpn2" input: "gpu_0/rpn_rois_fpn3" input: "gpu_0/rpn_rois_fpn4" input: "gpu_0/rpn_rois_fpn5" input: "gpu_0/rpn_rois_fpn6" input: "gpu_0/rpn_roi_probs_fpn2" input: "gpu_0/rpn_roi_probs_fpn3" input: "gpu_0/rpn_roi_probs_fpn4" input: "gpu_0/rpn_roi_probs_fpn5" input: "gpu_0/rpn_roi_probs_fpn6" input: "gpu_0/roidb" input: "gpu_0/im_info" output: "gpu_0/rois" output: "gpu_0/labels_int32" output: "gpu_0/bbox_targets" output: "gpu_0/bbox_inside_weights" output: "gpu_0/bbox_outside_weights" output: "gpu_0/mask_rois" output: "gpu_0/roi_has_mask_int32" output: "gpu_0/masks_int32" output: "gpu_0/rois_fpn2" output: "gpu_0/rois_fpn3" output: "gpu_0/rois_fpn4" output: "gpu_0/rois_fpn5" output: "gpu_0/rois_idx_restore_int32" output: "gpu_0/mask_rois_fpn2" output: "gpu_0/mask_rois_fpn3" output: "gpu_0/mask_rois_fpn4" output: "gpu_0/mask_rois_fpn5" output: "gpu_0/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_0/rpn_rois_fpn2,gpu_0/rpn_rois_fpn3,gpu_0/rpn_rois_fpn4,gpu_0/rpn_rois_fpn5,gpu_0/rpn_rois_fpn6,gpu_0/rpn_roi_probs_fpn2,gpu_0/rpn_roi_probs_fpn3,gpu_0/rpn_roi_probs_fpn4,gpu_0/rpn_roi_probs_fpn5,gpu_0/rpn_roi_probs_fpn6,gpu_0/roidb,gpu_0/im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:5" } arg { name: "grad_output_indices" } device_option { device_type: 1 cuda_gpu_id: 0 }
WARNING workspace.py: 185: Original python traceback for operator `219` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 190:   File "tools/train_net.py", line 358, in <module>
WARNING workspace.py: 190:   File "tools/train_net.py", line 196, in main
WARNING workspace.py: 190:   File "tools/train_net.py", line 205, in train_model
WARNING workspace.py: 190:   File "tools/train_net.py", line 283, in create_model
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/model_builder.py", line 117, in create
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/model_builder.py", line 222, in build_generic_detection_model
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/optimizer.py", line 38, in build_data_parallel_model
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/optimizer.py", line 60, in _build_forward_graph
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/model_builder.py", line 182, in _single_gpu_build_func
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/rpn_heads.py", line 46, in add_generic_rpn_outputs
WARNING workspace.py: 190:   File "/mnt/data1/detectron/lib/modeling/FPN.py", line 400, in add_fpn_rpn_losses
Traceback (most recent call last):
  File "tools/train_net.py", line 358, in <module>
    main()
  File "tools/train_net.py", line 196, in main
    checkpoints = train_model()
  File "tools/train_net.py", line 217, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/mnt/data1/pytorch/build/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/mnt/data1/pytorch/build/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at pybind_state.h:410] . Exception encountered running PythonOp function: ValueError: column index exceeds matrix dimensions

At:
  /usr/lib/python2.7/dist-packages/scipy/sparse/coo.py(238): _check
  /usr/lib/python2.7/dist-packages/scipy/sparse/coo.py(182): __init__
  /usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py(936): tocoo
  /usr/lib/python2.7/dist-packages/scipy/sparse/compressed.py(940): toarray
  /mnt/data1/detectron/lib/datasets/json_dataset.py(436): _add_class_assignments
  /mnt/data1/detectron/lib/datasets/json_dataset.py(344): add_proposals
  /mnt/data1/detectron/lib/ops/collect_and_distribute_fpn_rpn_proposals.py(55): forward
 Error from operator:
input: "gpu_0/rpn_rois_fpn2" input: "gpu_0/rpn_rois_fpn3" input: "gpu_0/rpn_rois_fpn4" input: "gpu_0/rpn_rois_fpn5" input: "gpu_0/rpn_rois_fpn6" input: "gpu_0/rpn_roi_probs_fpn2" input: "gpu_0/rpn_roi_probs_fpn3" input: "gpu_0/rpn_roi_probs_fpn4" input: "gpu_0/rpn_roi_probs_fpn5" input: "gpu_0/rpn_roi_probs_fpn6" input: "gpu_0/roidb" input: "gpu_0/im_info" output: "gpu_0/rois" output: "gpu_0/labels_int32" output: "gpu_0/bbox_targets" output: "gpu_0/bbox_inside_weights" output: "gpu_0/bbox_outside_weights" output: "gpu_0/mask_rois" output: "gpu_0/roi_has_mask_int32" output: "gpu_0/masks_int32" output: "gpu_0/rois_fpn2" output: "gpu_0/rois_fpn3" output: "gpu_0/rois_fpn4" output: "gpu_0/rois_fpn5" output: "gpu_0/rois_idx_restore_int32" output: "gpu_0/mask_rois_fpn2" output: "gpu_0/mask_rois_fpn3" output: "gpu_0/mask_rois_fpn4" output: "gpu_0/mask_rois_fpn5" output: "gpu_0/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_0/rpn_rois_fpn2,gpu_0/rpn_rois_fpn3,gpu_0/rpn_rois_fpn4,gpu_0/rpn_rois_fpn5,gpu_0/rpn_rois_fpn6,gpu_0/rpn_roi_probs_fpn2,gpu_0/rpn_roi_probs_fpn3,gpu_0/rpn_roi_probs_fpn4,gpu_0/rpn_roi_probs_fpn5,gpu_0/rpn_roi_probs_fpn6,gpu_0/roidb,gpu_0/im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:5" } arg { name: "grad_output_indices" } device_option { device_type: 0 }Error from operator:
input: "gpu_0/rpn_rois_fpn2" input: "gpu_0/rpn_rois_fpn3" input: "gpu_0/rpn_rois_fpn4" input: "gpu_0/rpn_rois_fpn5" input: "gpu_0/rpn_rois_fpn6" input: "gpu_0/rpn_roi_probs_fpn2" input: "gpu_0/rpn_roi_probs_fpn3" input: "gpu_0/rpn_roi_probs_fpn4" input: "gpu_0/rpn_roi_probs_fpn5" input: "gpu_0/rpn_roi_probs_fpn6" input: "gpu_0/roidb" input: "gpu_0/im_info" output: "gpu_0/rois" output: "gpu_0/labels_int32" output: "gpu_0/bbox_targets" output: "gpu_0/bbox_inside_weights" output: "gpu_0/bbox_outside_weights" output: "gpu_0/mask_rois" output: "gpu_0/roi_has_mask_int32" output: "gpu_0/masks_int32" output: "gpu_0/rois_fpn2" output: "gpu_0/rois_fpn3" output: "gpu_0/rois_fpn4" output: "gpu_0/rois_fpn5" output: "gpu_0/rois_idx_restore_int32" output: "gpu_0/mask_rois_fpn2" output: "gpu_0/mask_rois_fpn3" output: "gpu_0/mask_rois_fpn4" output: "gpu_0/mask_rois_fpn5" output: "gpu_0/mask_rois_idx_restore_int32" name: "CollectAndDistributeFpnRpnProposalsOp:gpu_0/rpn_rois_fpn2,gpu_0/rpn_rois_fpn3,gpu_0/rpn_rois_fpn4,gpu_0/rpn_rois_fpn5,gpu_0/rpn_rois_fpn6,gpu_0/rpn_roi_probs_fpn2,gpu_0/rpn_roi_probs_fpn3,gpu_0/rpn_roi_probs_fpn4,gpu_0/rpn_roi_probs_fpn5,gpu_0/rpn_roi_probs_fpn6,gpu_0/roidb,gpu_0/im_info" type: "Python" arg { name: "grad_input_indices" } arg { name: "token" s: "forward:5" } arg { name: "grad_output_indices" } device_option { device_type: 1 cuda_gpu_id: 0 }
`

**Comment by nemonameless** [comment]
@Vivianyzw Hi,how did you solve it?

**Comment by Vivianyzw** [comment]
@nemonameless I rebooted the server and restart to train the model, the error disappeared. I have no idea about the reason.
