### ISSUE TITLE
mini-batch size for RetinaNet.

### ISSUE THREAD

**Issue by nonstop1962** [facebookresearch/Detectron#41]
Hi, I want to train the retinaNet with retinanet_R-50-FPN_1x.yaml configuration setting.

I want to ask where can I set the mini-batch size for training. 
I think there is no information of the batch size in .yaml file, and it is hard to find that information on the train_net.py either.

**Comment by rbgirshick** [comment]
For questions like this, please consult `lib/core/config.py` (e.g., https://github.com/facebookresearch/Detectron/blob/master/lib/core/config.py#L92).

**Comment by austinmw** [comment]
@rbgirshick I have the same question and this link is broken

**Comment by ir413** [comment]
Thanks for reporting @austinmw. The link is now fixed.
