### ISSUE TITLE
Save masks and bounding boxes

### ISSUE THREAD

**Issue by ciolo** [facebookresearch/Detectron#422]
Hi,
I'd like to know if it's possible and how to save masks and bounding boxes on disk.
Thank u.

**Comment by ir413** [comment]
Hi @ciolo, detections are being saved to disk when testing detectron models on datasets (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/test_engine.py#L312-L320)). You can save detection to disk from elsewhere (e.g. `infer_simple` demo tool) in the same way.

**Comment by gadcam** [comment]
If you use <code>infer_simple.py</code> you can save the bounding boxes in a CSV file by adding this code at the end of the <code>for i, im_name in enumerate(im_list):</code> loop

```py
with open(os.path.join(args.output_dir, CSV_NAME), "a+", newline='') as csv_out:
    csv_writer = csv.writer(csv_out, delimiter=';', quotechar='"')
    # Save one box per line
    for box in cls_boxes[1]:
            row = [im_name.split(os.path.sep)[-1]]

            # Format box x1, y1, x2, y2, p
		for coord in box[:4]:
			row.append(int(round(coord)))
		row.append(round(box[4], 3))
		csv_writer.writerow(row)
````

I think you can take the exact same approach for masks.

**Comment by iPsych** [comment]
> ```python
> for box in cls_boxes
> ```

Hello, I adopted the lines, but it saves only one or two bounding boxes per image. 
Also, is there any way to save each masks one by one as .png or other image format?
