### ISSUE TITLE
coco_2014_minival

### ISSUE THREAD

**Issue by natasasdj** [facebookresearch/Detectron#423]
In the Getting_Started tutorial there is the following sentence:
"As configured, this will run inference on all images in coco_2014_minival (which must be properly installed)."
So, how do I install coco_2014_minival dataset?

**Comment by ir413** [comment]
As noted in the [installation instructions](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#datasets), instructions for setting up the datasets are given on [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/data/README.md) page.

**Comment by natasasdj** [comment]
Yes, what is not clear to me is that from where can I download coco_2014_minival dataset? 
In the tutorial it states:
"Please note that minival is exactly equivalent to the recently defined 2017 val set." 
So, is coco_2014_minival equal to 2017_val? If yes, after the download, should I save it under coco_val2017 or coco_val2014 or coco_2014_minival?

**Comment by ir413** [comment]
Please read the instructions on the page I linked above carefully. The instructions contain a download link for the coco `minival` and `valminusminival` annotations (see the first sentence of [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/data/README.md#coco-minival-annotations) section).

**Comment by lbingbing** [comment]
> Please read the instructions on the page I linked above carefully. The instructions contain a download link for the coco `minival` and `valminusminival` annotations (see the first sentence of [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/data/README.md#coco-minival-annotations) section). The same section also describes how coco 2014 splits related to the coco 2017 splits.

It looks like 2014_minival mentioned in that link is different from val2017:
http://images.cocodataset.org/annotations/annotations_trainval2017.zip
https://dl.fbaipublicfiles.com/detectron/coco/coco_annotations_minival.tgz

Did I miss anything?
