### ISSUE TITLE
modeling/detector.py  AffineChannel

### ISSUE THREAD

**Issue by 994374821** [facebookresearch/Detectron#426]
when I read the code of AffineChannel function in the file 'detector.py', I have some confusion. What is the difference when parameter inplace is one and zero？In other words, what is the purpose of setting the inplace parameter? Does it have an effect on back propagation? Thank you !

the original code is as following:

`    def AffineChannel(self, blob_in, blob_out, dim, inplace=False):
        """Affine transformation to replace BN in networks where BN cannot be
        used (e.g., because the minibatch size is too small).

        The operations can be done in place to save memory.
        """
        blob_out = blob_out or self.net.NextName()
        param_prefix = blob_out

        scale = self.create_param(
            param_name=param_prefix + '_s',
            initializer=initializers.Initializer("ConstantFill", value=1.),
            tags=ParameterTags.WEIGHT,
            shape=[dim, ],
        )
        bias = self.create_param(
            param_name=param_prefix + '_b',
            initializer=initializers.Initializer("ConstantFill", value=0.),
            tags=ParameterTags.BIAS,
            shape=[dim, ],
        )
        if inplace:
            return self.net.AffineChannel([blob_in, scale, bias], blob_in)
        else:
            return self.net.AffineChannel([blob_in, scale, bias], blob_out)
`

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @994374821, setting the `inplace` parameter to `True` means that the operation will be performed in place (i.e. the memory locations storing the input values will be modified directly). This is useful for reducing memory usage. Setting the `inplace` parameter to `False` means that a new chunk of memory will be allocated to store the resulting values. Note that it is not always possible to perform an operation in place (see [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/ResNet.py#L320-L331) for an example).
