### ISSUE TITLE
AttributeError: 'module' object has no attribute 'ocl'

### ISSUE THREAD

**Issue by xieydd** [facebookresearch/Detectron#43]
when i run this：

`python2 tools/infer_simple.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl     demo`

i got an error：

Traceback (most recent call last):
  File "tools/infer_simple.py", line 51, in <module>
    cv2.ocl.setUseOpenCL(False)
AttributeError: 'module' object has no attribute 'ocl'

**Comment by rbgirshick** [comment]
Duplicate; please search closed issues before posting.

**Comment by xieydd** [comment]
`
#进入当前python环境
import cv2
cv2.__file__
`
得到'/usr/lib/python2.7/dist-packages/cv2.x86_64-linux-gnu.so'
在之前安装openbuild的build文件夹中的/lib/中  

`
$ sudo mv cv2.x86_64-linux-gnu.so cv2.x86_64-linux-gnu.so.temple
$ sudo ln -sf /software/opencv-3.4.0/build/lib/cv2.so cv2.x86_64-linux-gnu.so
`
