### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED Error from operator: 

### ISSUE THREAD

**Issue by youngxiao** [facebookresearch/Detectron#433]
## RuntimeError: [enforce fail at context_gpu.h:91] status == CUDNN_STATUS_SUCCESS.
I download the `model_final.pkl`  which mentioned in [GETTING_STARTED.md](https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md) . When I execute the following command, 
```
young@yang-xiao:~/DeepLearning/detectron$ python2 tools/infer_simple.py --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml --output-dir /tmp/detectron-visualizations --image-ext jpg --wts model_final.pkl demo
```

it shows:
```
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0516 13:59:23.310196  7699 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0516 13:59:23.310217  7699 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0516 13:59:23.310220  7699 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  59: Loading weights from: model_final.pkl
I0516 13:59:23.918537  7699 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000186922 secs
I0516 13:59:23.918802  7699 net_dag.cc:46] Number of parallel execution chains 63 Number of operators = 402
I0516 13:59:23.937835  7699 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000157147 secs
I0516 13:59:23.938082  7699 net_dag.cc:46] Number of parallel execution chains 30 Number of operators = 358
I0516 13:59:23.939689  7699 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.2733e-05 secs
I0516 13:59:23.939733  7699 net_dag.cc:46] Number of parallel execution chains 5 Number of operators = 18
INFO infer_simple.py: 113: Processing demo/16004479832_a748d55f21_k.jpg -> /tmp/detectron-visualizations/16004479832_a748d55f21_k.jpg.pdf
E0516 13:59:23.963366  7716 net_dag.cc:195] Exception from operator chain starting at '' (type 'Conv'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:91] status == CUDNN_STATUS_SUCCESS. 1 vs 0. , Error at: /home/young/pytorch/caffe2/core/context_gpu.h:91: CUDNN_STATUS_NOT_INITIALIZED Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
WARNING workspace.py: 185: Original python traceback for operator `0` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 149, in <module>
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 101, in main
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/core/test_engine.py", line 328, in initialize_model_from_cfg
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/model_builder.py", line 229, in build_generic_detection_model
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/optimizer.py", line 54, in build_data_parallel_model
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/model_builder.py", line 169, in _single_gpu_build_func
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/FPN.py", line 63, in add_fpn_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/FPN.py", line 104, in add_fpn_onto_conv_body
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/ResNet.py", line 48, in add_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/ResNet.py", line 98, in add_ResNet_convX_body
WARNING workspace.py: 190:   File "/home/young/DeepLearning/detectron/detectron/modeling/ResNet.py", line 251, in basic_bn_stem
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/cnn.py", line 97, in Conv
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/brew.py", line 107, in scope_wrapper
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/helpers/conv.py", line 186, in conv
WARNING workspace.py: 190:   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/helpers/conv.py", line 139, in _ConvBase
Traceback (most recent call last):
  File "tools/infer_simple.py", line 149, in <module>
    main(args)
  File "tools/infer_simple.py", line 119, in main
    model, im, None, timers=timers
  File "/home/young/DeepLearning/detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/young/DeepLearning/detectron/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:91] status == CUDNN_STATUS_SUCCESS. 1 vs 0. , Error at: /home/young/pytorch/caffe2/core/context_gpu.h:91: CUDNN_STATUS_NOT_INITIALIZED Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
```

## Before getting start with detectron, I have made everything OK.

1. I tested the caffe2, also GPU support.   
```
young@yang-xiao:~/DeepLearning/detectron$ python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure"
Success
```
```
young@yang-xiao:~/DeepLearning/detectron$ python2 -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'
1
```
2. I installed the python dependencies and COCO API with no errors.

3. I cloned the Detectron. After `make`, I tested it. It worked well.
```
young@yang-xiao:~/DeepLearning/detectron$ python2 detectron/tests/test_spatial_narrow_as_op.py 
E0516 14:34:02.396867  8258 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0516 14:34:02.396888  8258 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0516 14:34:02.396890  8258 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
...
----------------------------------------------------------------------
Ran 3 tests in 0.815s

OK
```
### I'm not sure whether it is a version problem? But I install the recommended cuDNN 6.0. I am confused now. 
```
young@yang-xiao:~$ nvidia-smi
Wed May 16 14:40:51 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.130                Driver Version: 384.130                   |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0  On |                  N/A |
| 19%   29C    P8   ERR! /  80W |    502MiB /  4037MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0       907      G   /usr/lib/xorg/Xorg                           269MiB |
|    0      1266      G   compiz                                       170MiB |
|    0      1839      G   ...-token=EC35F4039AD9FEB344BD71D4379A4999    60MiB |
+-----------------------------------------------------------------------------+
```

```
young@yang-xiao:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61
```

```
young@yang-xiao:~$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      6
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 21
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```

#### My env.
* Operating system: Ubuntu 16.04 LTS
* CUDA version: v8.0.61
* cuDNN version: v6.0.21
* NVIDIA driver version: 384
* A stupid GPU: GTX1050

**Comment by CPFelix** [comment]
I almost have the same problem when I try to train MaskRCNN(with Keypoints) with my own dateset:
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = utils.train.train_model()
  File "/home/scau2/Downloads/detectron/lib/utils/train.py", line 66, in train_model
    workspace.RunNet(model.net.Proto().name)
  File "/home/scau2/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/scau2/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.h:90] status == CUDNN_STATUS_SUCCESS. 4 vs 0. , Error at: /home/scau2/Downloads/pytorch/caffe2/core/context_gpu.h:90: CUDNN_STATUS_INTERNAL_ERROR Error from operator: 
input: "gpu_0/data" input: "gpu_0/conv1_w" output: "gpu_0/conv1" name: "" type: "Conv" arg { name: "kernel" i: 7 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 2 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"

**Comment by youngxiao** [comment]
@CPFelix I am sorry for replying too late. I think the issue `CUDNN_STATUS_INTERNAL_ERROR ` you got is not the same with me. I just forgot to re `make` my caffe2 after reinstall cnDNN for version 6.0. So I re make my caffe2 and Detectron. It fixed.

**Comment by Crossady** [comment]
Same Issue here, while I am in cuda9.0.
I sovled the problem beacause I found the cudnn in my machine is for cuda9.1. After I replaced it with correct cudnn version the problem were gone. I hope this helps. @youngxiao @travis0925

**Comment by Tetsujinfr** [comment]
I have the same issue. I did compile caffe2, detectron and Densepose successfully. I initially had lots of difficulties with CuDNN version but after cleaning up a lot, I managed to compile caffe with CuDNN 6.0.21. But when trying to execute the infer_simple script I got the same error message as above.
Does anyone know how to check which CuDNN version is used at run time? I have a feeling that somehow I compiled with CuDNN 6 but that the CuDNN used at runtime is maybe different (although I checked mu file system and I could find only one instance of CuDNN 6 .so and same for the .h header file).
Please help!!!! Caffe2 is such a pain to compile properly.

**Comment by travis0925** [comment]
Thanks a lot for your attention.

**Comment by SuperMisswei** [comment]
I have get the same problem,but my cudnn version is true,other compile is success.I don't know why,need help.

**Comment by Tetsujinfr** [comment]
Maybe check where your cudnn libs are (the .so files) and make sure this folder is referenced in your cuda path. Check there is no other cudnn .so versions in the same folder too. Make sure if you are using a virtual environment that it points to the cudnn lib folder, sometimes it has a tendency to point to some alternate lib folder.
Fyi I managed to get Densepose working properly after re-installing a specifi version of the nvidia video drivers (v384 from memory), and possibly some other changes. But then, after a PC reboot, I could not log anymore into my machine, probably due to some Asus UEFI bios conflicts that I did not know about at the time. So check which version of your nvidia drivers you are using right now, which version of cuda and which version of cudnn.

**Comment by SuperMisswei** [comment]
thank you for your reply，the following is my system information

Operating system: ubuntu16.04

Compiler version: python2.7

CUDA version: cuda9.0

cuDNN version: cudnn7.0.5

NVIDIA driver version: 384.130

GPU models (for all devices if they are not all the same): TITAN X

python --version output: 2.7





------------------ Original ------------------

**Comment by Tetsujinfr** [comment]
On caffe2 instalation instructions, they mention that you need CUDA 8 and CuDNN v5 or v6.
https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-with-gpu-support

So I think your install with CUDA 9 and CuDNN v7 may nit be a working combination.

**Comment by SuperMisswei** [comment]
Oh，maybe.. I have got it,but I already have cuda9，so i try it,everything compiled success.In addition,i ran the code while the all gpus be occupied,i don't know if it matters.




------------------ Original ------------------

**Comment by Tetsujinfr** [comment]
Maybe it will work with cuda9 but try to compile with CuDNN v7.

**Comment by SuperMisswei** [comment]
my cudnn version is just what you said.
cuda=9.0.176
cudnn=7.0.5




------------------ 原始邮件 ------------------
发件人: "Tetsujinfr"<notifications@github.com>;
发送时间: 2019年7月19日(星期五) 凌晨4:16
收件人: "facebookresearch/Detectron"<Detectron@noreply.github.com>;
抄送: "风掠无影wsj"<weishaojie1995.com@qq.com>;"Comment"<comment@noreply.github.com>;
主题：  回复：[facebookresearch / Detectron] CUDNN_STATUS_NOT_INITIALIZED运算符错误：（＃433）




也许它适用于cuda9但尝试使用CuDNN v7进行编译。
  
- 
你收到这个是因为你发表了评论。
直接回复此电子邮件，在GitHub上查看，或将该线程静音。

**Comment by Tetsujinfr** [comment]
Sorry, I meant CuDnn v6
