### ISSUE TITLE
Docker: errors with caffe2

### ISSUE THREAD

**Issue by wenting-zhao** [facebookresearch/Detectron#440]
Hi all,

So when `` docker build -t detectron:c2-cuda9-cudnn7`` is executed, step 1 is run without a problem, but in step 2/13, caffe2 is not found under ``/usr/local/``, so the build fails at this step.  In particular, I'm getting a bunch of ``mv: cannot remove '/usr/local/caffe2*': No such file or directory``.

Based on my understanding, this docker build already includes an image for caffe2, and thus no further actions are required prior to running `` docker build -t detectron:c2-cuda9-cudnn7``.  Am I mistaken?  What am I missing here?

Thanks in advance for any assistance or comments anyone might be able to offer!

**Comment by ir413** [comment]
Hi @wenting-zhao, building and running the docker image on latest master seems to work fine for me. Could you please confirm that you have not modified the docker file and provide the full output of running the docker build?

**Comment by wenting-zhao** [comment]
The problem was fixed by rebooting my machine.  Sorry for the false alarm.
