### ISSUE TITLE
Using two models at the same time ：e2e_keypoint_rcnn_R-101-FPN_s1x/model_final.pkl e2e_faster_rcnn_R-101-FPN_1x/model_final.pkl

### ISSUE THREAD

**Issue by jobbofhe** [facebookresearch/Detectron#442]
`(caf2_py2) [root@localhost detectron]# python tools/sc_infer.py 
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0523 17:29:41.191484  3767 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0523 17:29:41.191512  3767 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0523 17:29:41.191519  3767 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.

{u'cfg': u'/detectron/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml', u'weights': u'/model/detectron/e2e_keypoint_rcnn_R-101-FPN_s1x/model_final.pkl', u'output_dir': u'/tmp/detectron-visualizations', u'image_ext': u'jpg', u'im_or_folder': u'/icooper/media/body_phone'}
start detect...

cfg path
/icooper/dev/detectron/configs/12_2017_baselines/e2e_keypoint_rcnn_R-101-FPN_s1x.yaml
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
WARNING model_builder.py: 138: Remapping old function name: head_builder.add_roi_2mlp_head -> fast_rcnn_heads.add_roi_2mlp_head
INFO net.py:  57: Loading weights from: /icooper/model/detectron/e2e_keypoint_rcnn_R-101-FPN_s1x/model_final.pkl
I0523 17:29:43.692709  3767 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000147461 secs
I0523 17:29:43.692991  3767 net_dag.cc:46] Number of parallel execution chains 63 Number of operators = 402
I0523 17:29:43.712771  3767 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000121198 secs
I0523 17:29:43.713016  3767 net_dag.cc:46] Number of parallel execution chains 30 Number of operators = 358
I0523 17:29:43.715103  3767 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.2319e-05 secs
I0523 17:29:43.715139  3767 net_dag.cc:46] Number of parallel execution chains 5 Number of operators = 24
INFO sc_infer.py: 192: Processing /icooper/media/body_phone/1_01_20180521095907653.jpg -> /tmp/detectron-visualizations/1_01_20180521095907653.jpg
INFO sc_infer.py: 201: Inference time: 4.204s
INFO sc_infer.py: 203:  | load_model: 2.517s
INFO sc_infer.py: 203:  | im_detect_bbox: 1.126s
INFO sc_infer.py: 203:  | im_detect_keypoints: 0.069s
INFO sc_infer.py: 203:  | misc_keypoints: 0.477s
INFO sc_infer.py: 203:  | misc_bbox: 0.000s
INFO sc_infer.py: 206:  \ Note: inference on the first image will be slower than the rest (caches and auto-tuning need to warm up)
INFO sc_infer.py: 192: Processing /icooper/media/body_phone/2_01_20180521095953228.jpg -> /tmp/detectron-visualizations/2_01_20180521095953228.jpg
INFO sc_infer.py: 201: Inference time: 5.490s
INFO sc_infer.py: 203:  | load_model: 2.517s
INFO sc_infer.py: 203:  | im_detect_bbox: 0.734s
INFO sc_infer.py: 203:  | im_detect_keypoints: 0.059s
INFO sc_infer.py: 203:  | misc_keypoints: 0.555s
INFO sc_infer.py: 203:  | misc_bbox: 0.000s
INFO sc_infer.py: 192: Processing /icooper/media/body_phone/3_01_2018052110013814.jpg -> /tmp/detectron-visualizations/3_01_2018052110013814.jpg
INFO sc_infer.py: 201: Inference time: 6.805s
INFO sc_infer.py: 203:  | load_model: 2.517s
INFO sc_infer.py: 203:  | im_detect_bbox: 0.595s
INFO sc_infer.py: 203:  | im_detect_keypoints: 0.065s
INFO sc_infer.py: 203:  | misc_keypoints: 0.593s
INFO sc_infer.py: 203:  | misc_bbox: 0.000s

{u'cfg': u'/detectron/configs/12_2017_baselines/e2e_faster_rcnn_R-101-FPN_1x.yaml', u'weights': u'/model/detectron/e2e_faster_rcnn_R-101-FPN_1x/model_final.pkl', u'output_dir': u'/tmp/detectron-visualizations', u'image_ext': u'jpg', u'im_or_folder': u'/icooper/media/body_phone'}
start detect...

cfg path
/icooper/dev/detectron/configs/12_2017_baselines/e2e_faster_rcnn_R-101-FPN_1x.yaml
Traceback (most recent call last):
  File "tools/sc_infer.py", line 317, in <module>
    main(args2)
  File "tools/sc_infer.py", line 166, in main
    cfg.NUM_GPUS = 1
  File "/icooper/dev/detectron/lib/utils/collections.py", line 49, in __setattr__
    format(name, value)
AttributeError: Attempted to set "NUM_GPUS" to "1", but AttrDict is immutable`

- Can I use two models for testing at the same time? My machine has only one GPU.

**Comment by ir413** [comment]
Hi @jobbofhe, I assume that you want to combine/ensemble predictions from two different models? If so, an easy way to do that would be to compute the predictions with each of the models individually and then write a tool that combines the predictions (stored in the pkl files as output by detectron).

**Comment by JiahuanChen** [comment]
Hi, @jobbofhe. This works in my situation.
 "assert_and_infer_cfg(make_immutable=False)"

**Comment by ir413** [comment]
Thanks for clarifying @jobbofhe. This functionality is not supported at this time but can be implemented in Detectron. If you haven't seen it already, you may also want to check out [this](https://arxiv.org/abs/1704.07333) related paper.

**Comment by jobbofhe** [comment]
@ir413 OK, Thanks for your help.

**Comment by saivineethkumar** [comment]
Hi @jobbofhe 
I am also facing the same issue, did you solve the problem?

**Comment by dsrivallabha** [comment]
Hi @JiahuanChen,

using  "assert_and_infer_cfg(make_immutable=False)" are you loading two networks simultaneously or sequentially? 

Thank you.

**Comment by junxiaoge** [comment]
@JiahuanChen How do you load the two models sequentially
