### ISSUE TITLE
I run the example test_net.py successfully. But where are the coco_2014_minival images?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#445]
hi!
 I run the official example test_net.py such as :
`python2 tools/test_net.py 
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    NUM_GPUS  1`

This runs inference on all images(5000) in coco_2014_minival.
but I want to konw where  the coco_2014_minival images are? I only download and add  minival and valminusminival json annotation files.
I downloaded the coco2014 datasets and changed them refer to Detectron/detectron/datasets/data/README.md :
coco
|_ coco_train2014
| |_ .jpg
| |_ ...
| |_ .jpg
|_ coco_val2014
|_ ...
|_ annotations
|_ instances_train2014.json
|_ ...
Then I downloaded the minival and valminusminival annotations, and copied the minival and valminusminival json annotation files to the coco/annotations directory referenced above.  I know minival annotations==val2017 annotations. 

Another question, the results are stored in 5 files: bbox_coco_2014_minival_results.json, segmentations_coco_2014_minival_results.json, detection_results.pkl, detections.pkl,  segmentation_results.pkl.  The first two are detection data results, but  what are the latter three?

**Comment by ir413** [comment]
Hi @lilichu, the `minival` and `valminusminival` json annotation files both refer to images from `coco_val2014` directory. `detections.pkl` file stores the computed detection in format used by Detectron (e.g. see the doc of [this](https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/core/test_engine.py#L368) function for more info on the format). `*_results.pkl` files store the coco evaluation results (the actual `COCOeval` object after performing the evaluation and accumulating per image results; e.g. see [this](https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/datasets/json_dataset_evaluator.py#L115-L122) for segmentation eval).

**Comment by lilichu** [comment]
Thanks! I find that the minival images are from coco_val2014 when debuging.
Besides,  my understanding is : minival==coco_val2017 and it is from coco_val2014, valminusminival + coco_train2014 ==coco_train2017.  is it right?

**Comment by ir413** [comment]
Yes, that's right (some info on the relation between 2014 and 2017 coco splits is also given [here](https://github.com/facebookresearch/Detectron/tree/master/detectron/datasets/data#coco-minival-annotations)).

**Comment by vsd550** [comment]
@ir413 Need your help regarding the **detection.pkl** file mentioned by you above.  Can you please refer to the issue raised by me [#513](https://github.com/facebookresearch/Detectron/issues/513)

Thanks

**Comment by ClaireTun** [comment]
hi @lilichu ,  would you like to share the links of minival and valminusminival 2014 ? I can not log in dropbox  to donwload.  Thanks!!

**Comment by seationasleep** [comment]
@ir413 Hi, could you tell me how to visualize the "detections.pkl" and  "detection_results.pkl"? thanks very much.
