### ISSUE TITLE
TypeError: object of type 'BlobReference' has no len()

### ISSUE THREAD

**Issue by srikanth-kilaru** [facebookresearch/Detectron#448]
I am trying to train Faster RCNN with a new backbone model and I see the following error -
python2 tools/train_net.py --cfg configs/getting_started/ml349_2gpu_e2e_faster_rcnn_Inception_ResNetv2.yaml OUTPUT_DIR /tmp/detectron-output/
...........
.........
INFO train.py: 131: Building model: generalized_rcnn
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will
 be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2
.ai and python/brew.py, python/brew_test.py for more information.
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
  File "tools/train_net.py", line 110, in main
    checkpoints = detectron.utils.train.train_model()
  File "/home/srikilaru/detectron/detectron/utils/train.py", line 53, in train_model
    model, weights_file, start_iter, checkpoints, output_dir = create_model()
  File "/home/srikilaru/detectron/detectron/utils/train.py", line 132, in create_model
    model = model_builder.create(cfg.MODEL.TYPE, train=True)
  File "/home/srikilaru/detectron/detectron/modeling/model_builder.py", line 124, in create
    return get_func(model_type_func)(model)
  File "/home/srikilaru/detectron/detectron/modeling/model_builder.py", line 89, in generalized_rcnn
    freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY
  File "/home/srikilaru/detectron/detectron/modeling/model_builder.py", line 230, in build_generic_detection_mode
l
    optim.build_data_parallel_model(model, _single_gpu_build_func)
  File "/home/srikilaru/detectron/detectron/modeling/optimizer.py", line 40, in build_data_parallel_model
    all_loss_gradients = _build_forward_graph(model, single_gpu_build_func)
  File "/home/srikilaru/detectron/detectron/modeling/optimizer.py", line 63, in _build_forward_graph
    all_loss_gradients.update(single_gpu_build_func(model))
  File "/home/srikilaru/detectron/detectron/modeling/model_builder.py", line 190, in _single_gpu_build_func
    model, blob_conv, dim_conv, spatial_scale_conv
  File "/home/srikilaru/detectron/detectron/modeling/rpn_heads.py", line 40, in add_generic_rpn_outputs
    FPN.add_fpn_rpn_outputs(model, blob_in, dim_in, spatial_scale_in)
  File "/home/srikilaru/detectron/detectron/modeling/FPN.py", line 330, in add_fpn_rpn_outputs
    assert len(blobs_in) == k_max - k_min + 1
TypeError: object of type 'BlobReference' has no len()

### System information

* Operating system: ? Ubunt 16.04 LTS
* Compiler version: ? gcc version 6.4.0 20180424 (Ubuntu 6.4.0-17ubuntu1~16.04)
* CUDA version: ? vcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Wed_Apr_11_23:16:29_CDT_2018
Cuda compilation tools, release 9.2, V9.2.88
* cuDNN version: ? 6.0.21
* NVIDIA driver version: ?
on May 28 00:31:39 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   72C    P8    31W / 149W |      6MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  Tesla K80           Off  | 00000000:00:05.0 Off |                    0 |
| N/A   36C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1992      G   /usr/lib/xorg/Xorg                             4MiB |
+-----------------------------------------------------------------------------+

* GPU models (for all devices if they are not all the same): ? 2 K80 on GCP
* `PYTHONPATH` environment variable: ? /home/srikilaru/pytorch/build
* `python --version` output: ? Python 2.7.12
* Anything else that seems relevant: ? Caffe2 installed as per instructions on Detectron and Caffe2 site

**Comment by mamunir** [comment]
Can you please share the solution
