### ISSUE TITLE
Compile the mask_rcnn in caffe2 c++

### ISSUE THREAD

**Issue by hxw111** [facebookresearch/Detectron#45]
I want to compile the mask_rcnn in "caffe2 c++" and has  saved the network as ".pb" file.
But when I run the net ,I get a error as follow:
         E0126 19:19:52.502368 26315 operator.cc:130] Cannot find operator schema for AffineChannel. Will skip schema checking.terminate called after throwing an instance of 'caffe2::EnforceNotMet'
        what():  [enforce fail at operator.cc:190] op. Cannot create operator of type 'AffineChannel' on the device 'CUDA'. 

Are there any good solutions to solve the problem? This is my c++ code:
        NetDef init_net, predict_net;
        ModelUtil mask_rcnn_model(init_net, predict_net);
        CAFFE_ENFORCE(ReadProtoFromFile(model_dir+"init_net.pb", &init_net));
        CAFFE_ENFORCE(ReadProtoFromFile(model_dir+"predict_net.pb", &predict_net));
        CAFFE_ENFORCE(workspace.RunNetOnce(mask_rcnn_model.init.net));
        CAFFE_ENFORCE(workspace.CreateNet(mask_rcnn_model.predict.net));

Thanks!!!

**Comment by rbgirshick** [comment]
Collapsing into #24.

**Comment by mattdingmeng** [comment]
@hxw111 I am wondering how did you convert the pkl model to .pb model? I am working on the C++ implementation too, but it seems that you need to implementation many mask-rcnn and faster-rnn functions in c++.

**Comment by hxw111** [comment]
@rbgirshick  Sorry, it seems that there's no good solution in #24. The error is clear, that is, there is no cuda support for “AffineChannel” in C++. The "AffineChannel" seems to be implemented by developer of the "Detectron" in python. And should I implement it in C++ too?

**Comment by hxw111** [comment]
@mattdingmeng  Could you find the infer_simple.py? Add this code in the end of the main function:

    from caffe2.python import workspace
    c2_model = model.net.Proto()
    from caffe2.python.predictor import mobile_exporter
    init_net, predict_net = mobile_exporter.Export(workspace, c2_model, c2_model.external_input)
    with open('init_net.pb', "wb") as fopen:
               fopen.write(init_net.SerializeToString())
    with open('predict_net.pb', "wb") as fopen:
              fopen.write(predict_net.SerializeToString())
