### ISSUE TITLE
Can a Caffe version is provided for GroupNormalizationi?

### ISSUE THREAD

**Issue by wzb1005** [facebookresearch/Detectron#452]
Hi,
I have seen the GroupNormalization layer in Caffe2 and pkl file of ResNet model.
however, I want to use GN in caffe, the pkl file can't be transformed into caffemodel file.
Can you provide a   layer defined  with caffe  of GN  ?Or provide the ResNet+GN  model that can be used in Caffe?
Thanks!

**Comment by ppwwyyxx** [comment]
I'm afraid it's not possible to do so because caffe does not support GN.

**Comment by gaowu9595** [comment]
@ppwwyyxx Hi,
Do you know how to load the R-50-GN.pkl to ResNet50? I don't have model class (that means the ResNet with GN ). And I'm using pytorch
