### ISSUE TITLE
Using pickle_caffe_blobs.py failed for converting VGG_CNN_M_1024.caffemodel and VGG_ILSVRC_16_layers.caffemodel both 

### ISSUE THREAD

**Issue by smajida** [facebookresearch/Detectron#453]
### Expected results

Training e2e_faster_rcnn_VGG_CNN_M_1024 using tutorial_1gpu_e2e_faster_rcnn_VGG_CNN_M_1024.yaml based on pretrained 
VGG_CNN_M_1024.pkl

the same goes for VGG_ILSVRC_16_layers

### Actual results

for VGG_CNN_M_1024:
AssertionError: Workspace blob fc6_w with shape (1024, 25088) does not match weights file shape (4096, 18432)

for VGG_ILSVRC_16_layers
AssertionError: Workspace blob fc6_w with shape (1024, 25088) does not match weights file shape (4096, 25088)

### Detailed steps to reproduce

download  VGG_ILSVRC_16_layers and  VGG_CNN_M_1024 model and prototxts from https://github.com/BVLC/caffe/wiki/Model-Zoo

To upgrade protoxt files: run 
In CAFFE_ROOT:  ./upgrade_net_proto_text VGG_ILSVRC_16_layers/deploy.prototxt VGG_ILSVRC_16_layers/deploy_v1.prototxt

and the same for VGG_CNN_M_1024 

run 
 python tools/pickle_caffe_blobs.py --prototxt /home/majid/Myprojects/CAFFE/models/VGG_ILSVRC_16_layers/deploy.prototxt --caffemodel /home/majid/Myprojects/CAFFE/models/VGG_ILSVRC_16_layers/VGG_ILSVRC_16_layers.caffemodel --output VGG_ILSVRC_16_layers.pkl

and the same for VGG_CNN_M_1024 

put

CONV_BODY:  VGG16.add_VGG16_conv5_body
CONV_BODY: VGG_CNN_M_1024.add_VGG_CNN_M_1024_conv5_body
and
VGG_ILSVRC_16_layers.pkl
VGG_CNN_M_1024pkl 

accordingly in appropriate places in .yaml scripts.

replace  NUM_CLASSES: 2 as in my case I am detecting one class + bkg

FPN_ON: False

run

python2 tools/train_net.py --cfg configs/tutorial_1gpu_e2e_faster_rcnn_VGG_CNN_M_1024.yaml OUTPUT_DIR output/tutorial_1gpu_e2e_faster_rcnn_VGG_CNN_M_1024

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 5.4
* CUDA version: 8.0
* cuDNN version: 7.0
* NVIDIA driver version: 3890
* GPU models (for all devices if they are not all the same): Titan XP
* `PYTHONPATH` environment variable: /usr/local:/home/majid/pytorch/build:/home/majid/Myprojects/pytorch/compiled/lib/python2.7/site-packages:/home/majid/Myprojects/Detectron/cocoapi/PythonAPI/build:/home/majid/Myprojects/Detectron/cocoapi/PythonAPI/build/lib.linux-x86_64-2.7
* `python --version` output: ? 2.7

**Comment by smajida** [comment]
@II-Matto great. thanks alot. That is true. I will try it and will let you know afterwards

**Comment by rbgirshick** [comment]
It looks like this is resolved.
