### ISSUE TITLE
when I exec ‘make ops’ I have some error that i can't processed

### ISSUE THREAD

**Issue by zhangxin1995** [facebookresearch/Detectron#456]
Does anyone know how can i handle this situation?
I run `make ops` in $Detectron_ROOT and I have install caffe2 correctly
```
[ 40%] Built target caffe2_detectron_custom_ops
[ 60%] Linking CXX shared library libcaffe2_detectron_custom_ops_gpu.so
/usr/bin/ld: cannot find -lcaffe2::cudnn
collect2: error: ld returned 1 exit status
make[2]: *** [libcaffe2_detectron_custom_ops_gpu.so] Error 1
make[1]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by gadcam** [comment]
The relevant line here is
>/usr/bin/ld: cannot find -lcaffe2::cudnn

So to help <code>ld</code> to find the <code>cudnn</code> lib you need to export a correct <code>LD_LIBRARY_PATH</code> env variable before running <code>make ops</code>.
You can check https://github.com/Theano/Theano/issues/5370 or https://github.com/PrincetonVision/marvin/issues/35 for example.

**Comment by zhangxin1995** [comment]
Thank you for answering my question! but I dose really set right LD_LIBRARY_PATH for the libcudnn.so. And I found when I run `cmake ..` in `build` , the terminal display that:
```
CMake Warning (dev) at /home/zhangxin/.local/share/cmake-3.11/Modules/FindCUDA.cmake:1806 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "caffe2_detectron_custom_ops_gpu" links to target "caffe2::cudnn"
  but the target was not found.  Perhaps a find_package() call is missing for
  an IMPORTED target, or an ALIAS target is missing?
```
I think I have correctly installed `libcudnn.so` in right place, because cmake can set  `CUDNN_LIBRARY ` in CMakeCache.txt :`/usr/local/cuda/lib64/libcudnn.so`, Is there any relations in `libcudnn.so` and `libcaffe2.so` in this question, can i specific some option to handle this question?

**Comment by gadcam** [comment]
I think we need the answer to these 3 questions to know a bit more about the problem :
* What is the exact content of <code>LD_LIBRARY_PATH</code>?
* What command do you run ?
* What is the full CMake output ?

**Comment by zhangxin1995** [comment]
Em.. I think I have solved this problem by deleting *-lcaffe::cudnn* in `MakeFiles/caffe2_detectron_custom_ops_gpu.dir/link.txt`, and my Detectron build success, :),
but I think there are still some wrong options in CMakeLists.txt that doesn't affect the final success.

**Comment by II-Matto** [comment]
Hi, @zhangxin1995. I solve the `-lcaffe::cudnn` problem by modifying Detectron `CMakeLists.txt`. See my comments for details: https://github.com/facebookresearch/Detectron/issues/462#issuecomment-394297017.
