### ISSUE TITLE
GPU spec for running inference with X-152-32x8d-FPN-IN5k

### ISSUE THREAD

**Issue by erickwan** [facebookresearch/Detectron#46]
Question: What is a typical GPU memory requirement for running inference on `X-152-32x8d-FPN-IN5k`?  I tried running it with a relatively small 819x614 jpg image on a 12GB Titan V and it still runs out of memory.

**Comment by rbgirshick** [comment]
I don't have the number on hand, but I can bound it between 12GB and 16GB, because I know it runs on a P100 with 16GB. As mentioned in #21, we plan to improve inference memory efficiency in the future.
