### ISSUE TITLE
How to construst my own network(eg: ResNet-18) base on the official network(ResNet-50)?  

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#460]
hi!
I want to use resnet-18 for faster r-cnn.   There are only resnet-50, resnet-101.  so how should I do to construct resnet-18?
thanks!

ps: I try to use tools/pickle_caffe_blobs.py to conver the faster-rcnn_resnet18(caffe1) to caffe2. But there is  error : Message type "caffe.LayerParameter" has no field named "smooth_l1_loss_param"
I think that it's because  'smooth_l1_loss_param' and 'roi_pooling_layer' are not belong to the original caffe, the caffe is recompile for faster r-cnn.

**Comment by ir413** [comment]
Hi @lilichu, R-18 is not supported at this time but it should be easy to add. You can implement it [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/ResNet.py) analogously to how current models are implemented. Note that you will need to account for different stage widths used in R-18 (`add_ResNet_convX_body` assumes stage widths of R-{50, 101, 152} models) and implement basic transformation (only bottleneck transformation is currently supported).
