### ISSUE TITLE
Problem with proposal files at test time when training on a custom dataset

### ISSUE THREAD

**Issue by netw0rkf10w** [facebookresearch/Detectron#470]
Hello,

I tried training Mask R-CNN with ResNet-50 backbone on my custom dataset but got an error at test time, after the training has finished. It has something to do with proposal files. Please see the details below. 

Thank you very much in advance for any help!

### Expected results

The accuracy on the test set.

### Actual results

This is the end of my terminal output, with an error:

```
json_stats: {"accuracy_cls": 1.000000, "eta": "0:00:27", "iter": 89980, "loss": 
0.287761, "loss_bbox": 0.000001, "loss_cls": 0.039121, "loss_mask": 0.244345, "$
r": 0.000010, "mb_qsize": 64, "mem": 6760, "time": 1.397984}
json_stats: {"accuracy_cls": 1.000000, "eta": "0:00:01", "iter": 89999, "loss": 
0.353617, "loss_bbox": 0.000001, "loss_cls": 0.064978, "loss_mask": 0.263285, "$
r": 0.000010, "mb_qsize": 64, "mem": 6760, "time": 1.397978}
INFO net.py: 140: Saving parameters and momentum to /home/ubuntu/detectron/outp$
t/train/mydataset_train:mydataset_val/generalized_rcnn/model_final.pkl
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 113: Stopping mini-batch loading thread
INFO loader.py: 113: Stopping mini-batch loading thread
INFO loader.py: 113: Stopping mini-batch loading thread
INFO loader.py: 113: Stopping mini-batch loading thread
Traceback (most recent call last):
  File "tools/train_net.py", line 128, in <module>
    main()
File "tools/train_net.py", line 113, in main
    test_model(checkpoints['final'], args.multi_gpu_testing, args.opts)
  File "tools/train_net.py", line 123, in test_model
    check_expected_results=True,
  File "/home/ubuntu/detectron/lib/core/test_engine.py", line 128, in run_infere
nce
    all_results = result_getter()
  File "/home/ubuntu/detectron/lib/core/test_engine.py", line 101, in result_get
ter
    dataset_name, proposal_file = get_inference_dataset(i)
  File "/home/ubuntu/detectron/lib/core/test_engine.py", line 76, in get_infere$
ce_dataset
    'If proposals are used, one proposal file must be specified for ' \
AssertionError: If proposals are used, one proposal file must be specified for e
ach dataset

```

### Detailed steps to reproduce

After converting my custom dataset to the COCO format, I based on the provided `e2e_mask_rcnn_R-50-FPN_1x.yaml` to create my custom configuration file: pointing the `DATASETS` lines to the right datasets (my test set is the same as validation set), and **commenting the two lines starting by `PROPOSAL_FILES:`**, since I have no proposal files.

```
CUDA_VISIBLE_DEVICES=0 python tools/train_net.py --cfg configs/mydataset/mydataset_mask_rcnn_R-50-FPN_1x.yaml  OUTPUT_DIR ./output
```

### System information

* Operating system: Ubuntu 16.04
* Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
* CUDA version: 9.0.176
* cuDNN version: 7.0.5
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): Tesla K80
* `PYTHONPATH` environment variable: None
* `python --version` output: Python 2.7.12
* Anything else that seems relevant: None

**Comment by ir413** [comment]
Hi @netw0rkf10w, the error suggests that your config requires proposals ([this](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/test_engine.py#L72) branch seems taken). Could you double-check that the `MODEL.FASTER_RCNN` option is enabled? If you could share the modified config you are using that would make it easier to diagnose the issue.

**Comment by netw0rkf10w** [comment]
Hi @ir413,

Thank you very much for your reply!

My configuration file, as shown below, is largely based on the provided `configs/12_2017_baselines/e2e_mask_rcnn_R-50-FPN_1x.yaml`. Maybe I should add `FASTER_RCNN: False` under `MODEL:`?

```
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 7
  MASK_ON: True
NUM_GPUS: 1
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.001
  GAMMA: 0.1
  MAX_ITER: 90000
  STEPS: [0, 60000, 80000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_2mlp_head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('mydataset_train', 'mydataset_val')
##  PROPOSAL_FILES: ('https://s3-us-west-2.amazonaws.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_train/generalized_rcnn/rpn_proposals.pkl', 'https://s3-us-west-2.amazonaws.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_valminusminival/generalized_rcnn/rpn_proposals.pkl')
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
TEST:
  DATASETS: ('mydataset_val',)
##  PROPOSAL_FILES: ('https://s3-us-west-2.amazonaws.com/detectron/35998814/12_2017_baselines/rpn_R-50-FPN_1x.yaml.08_06_03.Axg0r179/output/test/coco_2014_minival/generalized_rcnn/rpn_proposals.pkl',)
  PROPOSAL_LIMIT: 1000
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
OUTPUT_DIR: ./output/mydataset_mask_rcnn_R-50-FPN_1x/
```

**Comment by ir413** [comment]
Thanks for sharing the config @netw0rkf10w. From your previous message it sounds like you would like to perform end-to-end training (jointly train the RPN subnetwork and the Mask R-CNN network) in which case you should set the `MODEL.FASTER_RCNN` option to `True` (see [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L455-L465) for more info).
