### ISSUE TITLE
Using second GPU while first is busy

### ISSUE THREAD

**Issue by ambigus9** [facebookresearch/Detectron#474]
### Expected results
Use second GPU while first is busy on another framework

What did you expect to see?

Inference complete.

### Actual results

What did you observe instead?

> RuntimeError: [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /var/lib/jenkins/workspace/caffe2/core/context_gpu.cu:343: out of memory 

### Detailed steps to reproduce

With 2 Nvidia GPU run on the first GPU some process that use 90% of VRAM,

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 5.4.1
* CUDA version: 8.0.61
* cuDNN version: 6.0.21
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): GTX 1080TI
* `python --version` output: 2.7.12

**Comment by gadcam** [comment]
You should change the value of NamedCudaScope.
So for example with infer_simple.py you should change this

https://github.com/facebookresearch/Detectron/blob/6c5835862888e784e861824e0ad6ac93dd01d8f5/tools/infer_simple.py#L117
to
```py
with c2_utils.NamedCudaScope(1):
```
If you want to use the second GPU.

**Comment by rbgirshick** [comment]
You should be able to use the `CUDA_VISIBLE_DEVICES` env variable instead (better than modifying code). See: https://github.com/facebookresearch/Detectron/blob/master/FAQ.md#q-how-do-i-restrict-detectron-to-use-only-a-subset-of-the-gpus-on-a-server.

**Comment by ambigus9** [comment]
@gadcam @rbgirshick  It's possible to use the second GPU to train a model while first is traing another model?

**Comment by ambigus9** [comment]
@gadcam I solved using nvidia-docker,

`NV_GPU=1 nvidia-docker run -ti I <MAGE_ID> /bin/bash`

More info: [GPU Isolation](https://github.com/NVIDIA/nvidia-docker/wiki/GPU-isolation-(version-1.0))

Is this a correct way to solve it?
