### ISSUE TITLE
ImportError: No module named core.config

### ISSUE THREAD

**Issue by saivineethkumar** [facebookresearch/Detectron#475]
Hello

when I run the inference command 

_"sudo python tools/infer_simple.py \--cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \--output-dir demo/output \--image-ext jpg \--wts \https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \demo"_

I am getting the following error:

_Traceback (most recent call last):
  File "tools/infer_simple.py", line 40, in <module>
    from detectron.core.config import assert_and_infer_cfg
ImportError: No module named core.config_

I can see the file config.py in the subfolder core which is in detectron dir, still I am getting the error.
And there are init.py files in both detectron dir and core dir
I am unable to understand where the problem is, can anyone help me with this
thankyou

**Comment by saivineethkumar** [comment]
Hi @ir413 
I could not find lib dir in the Detectron dir, do you have any idea about that?

**Comment by gadcam** [comment]
@saivineethkumar Did you set the <code>PYTHONPATH</code> environment variable so the Python interpreter could find the detectron directory ?

**Comment by gadcam** [comment]
@saivineethkumar 
Do you set it to <code>$DETECTRON_DIR/detectron</code> or only to <code>$DETECTRON_DIR</code> ? Only the first one should work.

**Comment by gadcam** [comment]
@ir413 When you have to build it without root privileges setting the <code>PYTHONPATH</code> var could be mandatory, as far as I experimented at least.
But I digress and you are right : we need more information

**Comment by ir413** [comment]
@gadcam Permissions can be an issue when trying to install Detectron module into global site-packages (which can be done by running [`make install`](https://github.com/facebookresearch/Detectron/blob/master/Makefile#L8)). This is one of the the reasons we made `make` default to the development mode (see [`make dev`](https://github.com/facebookresearch/Detectron/blob/master/Makefile#L16)) which should not have these issues.

**Comment by saivineethkumar** [comment]
thanks @ir413  @gadcam 
I added this line to my python script before importing the modules and now it is working fine
`sys.path.insert(0,'path to DETECTRON_DIR')`
but I dont understand why when I add the same thing to `PYTHONPATH ` , it was showing error but now it works fine, do you guys know why is that so?

**Comment by ir413** [comment]
`sys.path.insert` is not a good way to address this issue. As mentioned above, we recommend following the installation instructions instead. Closing this now since no further information has been provided.

**Comment by gittigxuy** [comment]
@saivineethkumar ,you should make clean detectron build folder,and re-make this.it could be fine for me
