### ISSUE TITLE
cannot creat new python operator in detectron

### ISSUE THREAD

**Issue by LeonJWH** [facebookresearch/Detectron#476]
I tried to creat a new python operator and use it in detectron.
First, I build the python operator as below and put it in _$Detectron/detectron/ops/_.
```
class DecodeBBoxOp(object):
	def __init__(self, train):
		self._train = train
		num_cls = cfg.MODEL.NUM_CLASSES
	def forward(self, inputs, outputs):
		# The inputs contains [bbox_pred, cls_prob, rois]
		# rois --> np.array((num,5)), (batch_idx, x1, y2, x2, y2)
		cls_prob = inputs[0]
		bbox_pred = inputs[1]
		rois = inputs[2]
		rois = rois.astype(bbox_pred.dtype, copy=False)
		assert bbox_pred.shape[0] == len(rois)
		proposals_next = rois[:, 1:5]
		# Use delta with max cls_score as deltas adding to rois
		cls_prob = cls_prob.squeeze()
		cls_idx = cls_prob.argmax(axis=0)
		delta = np.zeros((bbox_pred.shape[0], 4), dtype=bbox_pred.dtype)
		for i in xrange(cls_idx.shape[0]):
			delta[i, :] = bbox_pred[i, i * 4:i * 4 + 4]
		# Add bbox deltas onto rois to generate new rois
		new_rois = box_utils.bbox_transform(proposals_next, bbox_pred, (1.0, 1.0, 1.0, 1.0))
		batch_idxs = rois[:, 0].reshape(rois.shape[0], 1)
		new_rois = np.hstack((batch_idxs,new_rois))
		return new_rois
```
Second, I registered it in _$Detectron/detectron/modeling/detector.py_ as a func of **DetectionModelHelper** as below.
```
def DecodeBBox(self, stage_num):
        # decode cls_prob and bbox_pred feature maps, adding deltas onto rois to generate new rois 
        if stage_num == 2:
            rois_names = ['rois_1st']
            cls_prob_names = ['cls_prob_1st']
            bbox_pred_names = ['bbox_pred_1st']
        elif stage_num == 3:
            rois_names = ['rois_2nd']
            cls_prob_names = ['cls_prob_2nd']
            bbox_pred_names = ['bbox_pred_2nd']
        blobs_in = cls_prob_names + bbox_pred_names + rois_names
        if self.train:
            blobs_in += ['roidb', 'im_info']
        blobs_in = [core.ScopedBlobReference(b) for b in blobs_in]
        name = 'DecodeBBoxOp:' + ','.join(
            [str(b) for b in blobs_in]
        )
        # Prepare output blobs
        if stage_num == 2:
            blobs_out = ['rois_2nd_pre']
        elif stage_num == 3:
            blobs_out = ['rois_3rd_pre']
        blobs_out = [core.ScopedBlobReference(b) for b in blobs_out]
        outputs = self.net.Python(DecodeBBoxOp(self.train).forward
                                  )(blobs_in, blobs_out, name=name)
        return outputs
```
When I tried to run the training progress of maskrcnn with Detectron, an error occured, here are details.

> WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
> Traceback (most recent call last):
>   File "tools/train_net.py", line 128, in <module>
>     main()
>   File "tools/train_net.py", line 110, in main
>     checkpoints = detectron_cascade.utils.train.train_model()
>   File "/home/user/workspace/Detectron/detectron_cascade/utils/train.py", line 55, in train_model
>     model, weights_file, start_iter, checkpoints, output_dir = create_model()
>   File "/home/user/workspace/Detectron/detectron_cascade/utils/train.py", line 134, in create_model
>     model = model_builder.create(cfg.MODEL.TYPE, train=True)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 124, in create
>     return get_func(model_type_func)(model)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 89, in generalized_rcnn
>     freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 230, in build_generic_detection_model
>     optim.build_data_parallel_model(model, _single_gpu_build_func)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/optimizer.py", line 40, in build_data_parallel_model
>     all_loss_gradients = _build_forward_graph(model, single_gpu_build_func)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/optimizer.py", line 63, in _build_forward_graph
>     all_loss_gradients.update(single_gpu_build_func(model))
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 204, in _single_gpu_build_func
>     spatial_scale_conv, cfg.MODEL.NUM_RCNN_STAGE
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 267, in _add_cascade_fast_rcnn_head
>     model.DecodeBBoxOp(i + 2)
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/model_helper.py", line 453, in __getattr__
>     ','.join(workspace.C.nearby_opnames(op_type)) + ']'
> AttributeError: Method DecodeBBoxOp is not a registered operator. Did you mean: []

I use this python operator to build my network.
```
    for i in range(num_rcnn_stage - 1):
        model.DecodeBBoxOp(i + 2)
```

Can you tell me how to creat a new python operator in Detectron?

**Comment by gadcam** [comment]
The operator you added to the class <code>DetectionModelHelper</code> is <code>DecodeBBox</code> and not <code>DecodeBBox**Op**</code>.
So try to build it like this
```py
    for i in range(num_rcnn_stage - 1):
        model.DecodeBBox(i + 2)
```

**Comment by LeonJWH** [comment]
thank you very much, I have noticed the coding error I made. @gadcam
