### ISSUE TITLE
I am stuck at in caffe2 intallation, the No module named caffe2.python problem.

### ISSUE THREAD

**Issue by ouyangkid** [facebookresearch/Detectron#479]
according to the readme, when I EXE the command ' python2 -c 'from caffe2.python import core' 2>/dev/null && echo "Success" || echo "Failure" ', it should return success.
Or I should add the pythonpath into ~/.bashrc 

(the import code works in python environment)

the following is what I added:

export PYTHONPATH=/home/**/anaconda3/envs/my_caffe2/bin/python:$PYTHONPATH

still return failure.

So **# what kinds of environment** should I modify to the **bashrc**??

python path issue

### Expected results

What did you expect to see?

### Actual results

What did you observe instead?

python2 -c 'from caffe2.python import core'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named caffe2.python
### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ubuntu16.04
* Compiler version: ? gcc 5.4
* CUDA version: ? 8.0
* cuDNN version: ? 7
* NVIDIA driver version: ? 384.14
* GPU models (for all devices if they are not all the same): ? Geforce Titan X *2
* `PYTHONPATH` environment variable: ? 
* `python --version` output: ?  Python 3.6.5 :: Anaconda, Inc.
* Anything else that seems relevant: ?

**Comment by gadcam** [comment]
Did you try to set the <code>LD_LIBRARY_PATH</code> env var ?
It should be set to something like <code>/opt/caffe2/lib</code> where the folder is matching your Caffe2 install so the Caffe2 libs can be found.

Can you copy / paste the error message of this ?
```sh
python2 -c 'from caffe2.python import core'

**Comment by ir413** [comment]
In order to be able to import Caffe2 python modules you may need to set the `PYTHONPATH` to `caffe2/build` rather than `caffe2/bin/python`. See this extract from the install instructions:

>If the caffe2 Python package is not found, you likely need to adjust your PYTHONPATH environment variable to include its location (/path/to/caffe2/build, where build is the Caffe2 CMake build directory).

Additionally, please follow the instructions from the [issue template](https://github.com/facebookresearch/Detectron/blob/master/.github/issue_template.md) and provide the requested information (it is hard to diagnose the issue and offer suggestions otherwise).

**Comment by ouyangkid** [comment]
@gadcam as I use the command you advised, the following message output:


` python2 -c 'from caffe2.python import core'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named caffe2.python`

As I use the pre-built binaries, I didn't find any path to the "build"

**Comment by lianglia-apollo** [comment]
@ouyangkid I saw you closed this issue. Could you share how did you fix it? Thanks!

**Comment by ouyangkid** [comment]
@lianglia-apollo this caused by the wrong command of 'python3/python', when the Conda installed python3, the python==python3 just make sure your python version.

**Comment by abdelDebug** [comment]
@ouyangkid  which version of python we need to use. I'm stuck when using python 3.6
