### ISSUE TITLE
How to add own Backbone Network to current Detectron?

### ISSUE THREAD

**Issue by WuZhuoran** [facebookresearch/Detectron#480]
Currently Detectron has Backbone Network such as `ResNet` and `FPN`.

How to add our own designed Backbone Network?

Thank you.

**Comment by ir413** [comment]
Hi @WuZhuoran, you can implement additional backbone models analogously to how currently supported models are implemented (e.g. see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/ResNet.py) for ResNe(X)t models).

**Comment by chansongoal** [comment]
Hi, @WuZhuoran Have you solved this problem? I want to replace backbone with VGG16, could you mind giving me some suggestions ? Thank you!

**Comment by WuZhuoran** [comment]
> Hi, @WuZhuoran Have you solved this problem? I want to replace backbone with VGG16, could you mind giving me some suggestions ? Thank you!

Hi @chansongoal , actually we switch to tf version of Detectron after we found it hard to modify. I think you can both try `Detectron2` or different implementation of this tool.

**Comment by chansongoal** [comment]
Hi, @WuZhuoran I replace the backbone with vgg16 in Detectron2. But the loss cannot converge to a number small then 0.9. So what's the results did you get with vgg16 as backbone?
