### ISSUE TITLE
Failled to run infer_simple.py and test_net.py on my own model

### ISSUE THREAD

**Issue by stanciuflorina** [facebookresearch/Detectron#482]
### Expected results
to run the scrip infer_simple.py and test_net.py
What did you expect to see?

### Actual results
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
E0608 14:53:53.377933 23563 init_intrinsics_check.cc:59] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0608 14:53:53.377946 23563 init_intrinsics_check.cc:59] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0608 14:53:53.377948 23563 init_intrinsics_check.cc:59] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  40: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
WARNING model_builder.py: 138: Remapping old function name: head_builder.add_roi_2mlp_head -> fast_rcnn_heads.add_roi_2mlp_head
INFO net.py:  59: Loading weights from: /home/fstanciu/git/detectron/train/keypoints_coco_2014_train-keypoints_coco_2014_valminusminival/generalized_rcnn/model_final.pkl
I0608 14:53:53.699990 23563 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.8337e-05 secs
I0608 14:53:53.700037 23563 net_dag.cc:61] Number of parallel execution chains 26 Number of operators = 44
I0608 14:53:53.701241 23563 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 8.239e-06 secs
I0608 14:53:53.701262 23563 net_dag.cc:61] Number of parallel execution chains 10 Number of operators = 20
I0608 14:53:53.702364 23563 net_dag_utils.cc:118] Operator graph pruning prior to chain compute took: 1.1507e-05 secs
I0608 14:53:53.702386 23563 net_dag.cc:61] Number of parallel execution chains 3 Number of operators = 22
INFO infer_simple.py: 113: Processing demo/24274813513_0cfd2ce6d0_k.jpg -> /home/fstanciu/git/detectron/detectron/tests/24274813513_0cfd2ce6d0_k.jpg.pdf
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at blob.h:97] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/conv2_1/dw_w.
Error from operator:
input: "gpu_0/conv1/o" input: "gpu_0/conv2_1/dw_w" input: "gpu_0/conv2_1/dw_b" output: "gpu_0/conv2_1/dw" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1528458834 (unix time) try "date -d @1528458834" if you are using GNU date ***
PC: @     0x7f92ab0b4428 gsignal
*** SIGABRT (@0x3e800005c0b) received by PID 23563 (TID 0x7f923d1fc700) from PID 23563; stack trace: ***
    @     0x7f92ab0b44b0 (unknown)
    @     0x7f92ab0b4428 gsignal
    @     0x7f92ab0b602a abort
    @     0x7f92a4bd584d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f92a4bd36b6 (unknown)
    @     0x7f92a4bd3701 std::terminate()
    @     0x7f92a4bfed38 (unknown)
    @     0x7f92ab4506ba start_thread
    @     0x7f92ab18641d clone
    @                0x0 (unknown)
Aborted (core dumped)

### Detailed steps to reproduce
I made my own model for keypoints and i trained accordingly. As a backbone i used only 5 convolutions.

    model.Conv('data', 'conv1', 3, 128,   kernel=3, pad=1, stride=2)
    model.Relu('conv1','conv1/o'),

    model.Conv('conv1/o', 'conv2_1/dw', 128, 128,  kernel=3, pad=1, stride=1)
    model.Relu('conv2_1/dw', 'conv2_1/dw/o')

    model.Conv('conv2_1/dw/o', 'conv2_1/sep', 128, 256,  kernel=1, pad=0, stride=1) 
    model.SpatialBN('conv2_1/sep', 'conv2_1/sep/i', 256, init_scale=1., bias_init=0. , epsilon=1e-5, is_test=False)
    model.Relu('conv2_1/sep/i', 'conv2_1/sep/o') 

    model.Conv('conv2_1/sep/o', 'conv2_2/dw', 256, 256,  kernel=3, pad=1, stride=2)
    model.Relu('conv2_2/dw', 'conv2_2/dw/o') 

    model.Conv('conv2_2/dw/o', 'conv2_2/sep', 256, 512,  kernel=1, pad=0, stride=1) 
    model.SpatialBN('conv2_2/sep', 'conv2_2/sep/i', 512, init_scale=1., bias_init=0. ,epsilon=1e-5, is_test=False)
    model.Relu('conv2_2/sep/i', 'conv2_2/sep/o') 

    model.Conv('conv2_2/sep/o', 'conv3_1/dw', 512, 512,  kernel=3, pad=1, stride=2)
    model.Relu('conv3_1/dw', 'conv3_1/dw/o') 
The command that you ran
```

### System information

* Operating system: Ubuntu 16.04
* Compiler version: ?
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61

* NVIDIA driver version: 390
* GPU models (for all devices if they are not all the same): GeForce GTX 1080
* `PYTHONPATH` environment variable: ?
* `python --version` output: Python 2.7.12
* Anything else that seems relevant: I trained the model with no  weights file.
Thank you for your help.

**Comment by stanciuflorina** [comment]
For future refference: it looks like you don't support "/" in the name of the layers for inference and test, but it's no issue with the name when running the train script. Problem solved.

**Comment by BanuSelinTosun** [comment]
@stanciuflorina Would you be able to give more details about this issue?

**Comment by gadcam** [comment]
@BanuSelinTosun 
> Detectron is claiming to detect people's poses, how is this happening? What inference do I need to run for that?

You need to use "keypoint" models cf https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#keypoint-detection-baselines (see also http://cocodataset.org/#keypoints-challenge2018)

**Comment by BanuSelinTosun** [comment]
@gadcam 
Thank you. Does that mean the out-of-box model works? Or do I need to do a specific training? Change the model? I don't think it is clear from the link you send me. 

Thanks again,
Selin
