### ISSUE TITLE
when I run test_net.py on my own datasets(VOC structure), I encounter AssertionError

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#485]
hi!
I run test_net.py on my own datasets(VOC):
`python ./tools/test_net.py --cfg experiment/configs/tutorial_1gpu_e2e_faster_rcnn_R-18-FPN.yaml TEST.WEIGHTS ./output/detectron-output/R18/train/voc_2007_trainval/generalized_rcnn/model_final.pkl NUM_GPUS 1`

INFO net.py:  59: Loading weights from: ./output/detectron-output/R18/train/voc_2007_trainval/generalized_rcnn/model_final.pkl
I0611 11:14:38.041623  2675 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 8.4868e-05 secs
I0611 11:14:38.041851  2675 net_dag.cc:46] Number of parallel execution chains 63 Number of operators = 128
I0611 11:14:38.045915  2675 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 4.6804e-05 secs
I0611 11:14:38.046047  2675 net_dag.cc:46] Number of parallel execution chains 30 Number of operators = 84
INFO test_engine.py: 287: im_detect: range [1, 2198] of 2198: 1/2198 1.097s + 0.001s (eta: 0:40:13)
INFO test_engine.py: 287: im_detect: range [1, 2198] of 2198: 11/2198 0.174s + 0.001s (eta: 0:06:22)
......
......
INFO test_engine.py: 287: im_detect: range [1, 2198] of 2198: 2181/2198 0.076s + 0.001s (eta: 0:00:01)
INFO test_engine.py: 287: im_detect: range [1, 2198] of 2198: 2191/2198 0.076s + 0.001s (eta: 0:00:00)
INFO test_engine.py: 320: Wrote detections to: /home/user/lichu/detectron/test/voc_2007_test/generalized_rcnn/detections.pkl
INFO test_engine.py: 162: Total inference time: 278.022s
INFO task_evaluation.py:  76: Evaluating detections
Traceback (most recent call last):
  File "./tools/test_net.py", line 116, in <module>
    check_expected_results=True,
  File "/home/user/lichu/detectron/detectron/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/home/user/lichu/detectron/detectron/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/home/user/lichu/detectron/detectron/core/test_engine.py", line 164, in test_net_on_dataset
    dataset, all_boxes, all_segms, all_keyps, output_dir
  File "/home/user/lichu/detectron/detectron/datasets/task_evaluation.py", line 60, in evaluate_all
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/home/user/lichu/detectron/detectron/datasets/task_evaluation.py", line 93, in evaluate_boxes
    dataset, all_boxes, output_dir, use_matlab=use_matlab
  File "/home/user/lichu/detectron/detectron/datasets/voc_dataset_evaluator.py", line 47, in evaluate_boxes
    filenames = _write_voc_results_files(json_dataset, all_boxes, salt)
  File "/home/user/lichu/detectron/detectron/datasets/voc_dataset_evaluator.py", line 70, in _write_voc_results_files
    assert index == image_index[i]
AssertionError

my own datasets is:
VOC2007
|_ JPEGImages
|  |_ <im-1-name>.jpg
|  |_ ...
|  |_ <im-N-name>.jpg
|_ annotations
|  |_ voc_2007_trainval.json
|  |_ voc_2007_test.json
|  
|_ VOCdevkit2007
|  |_ ImageSets
|  |   |_main
|  |   |   |_trainval.txt
|  |   |   |_test.txt

**Comment by zkself** [comment]
hello i meet this issue too,do u handle it?

**Comment by lilichu** [comment]
well, I use coco dataset format later @zkself.

**Comment by HELOBILLY** [comment]
@lilichu The order of images in val file is not consistent with that in json, for example, in val file, the name of the first image is 000001, but in json file, the first image might be 000008.

**Comment by pprp** [comment]
@lilichu I'm sure I check the order about json file and image, which is right. Besides, our datasets is coco.  But the error still happened, so what' s the problem?

**Comment by pprp** [comment]
Now, I have solved this problem. @HELOBILLY , Thank you very much. You are right.

**Comment by y-nissi** [comment]
@pprp  How to solve this problem? Change the name one by one?

**Comment by Sakurawy** [comment]
The order of the images in val file should be the same with that in json. 
I just fix this problem by changing the code as follows:
with open(image_set_path, 'r') as f:    
    image_index = [int(x.strip()) for x in f.readlines()]
    image_index = np.sort(image_index)

and here
assert int(index) == image_index[i], 'index not equal to image_index'

Hope it could help.

**Comment by garyfanhku** [comment]
Got another assertion error just a few lines below, 
`assert len(all_boxes[cls_ind]) == len(image_index)`
from my understanding, the latter returns total number of images and the former return total number of boxes for one class corresponding to "cls_ind", how could these two be equal?

**Comment by chenliqiong** [comment]
@Sakurawy  It worked in my code. Thank you very much!
