### ISSUE TITLE
How to modify the bounding boxes regression part to regress oriented bounding boxes

### ISSUE THREAD

**Issue by vsd550** [facebookresearch/Detectron#486]
I have a dataset where the **bounding boxes are oriented** i.e. all 4 coordinates (x1,y1,x2,y2,x3,y3,x4,y4) are given and need to be used for training. Since the objects in images are very dense, any approximation to get horizontal bounding boxes leads to **overlap** between 2 or more b_boxes.
Please suggest how to approach this problem.
Like how can we t**rain a model with such a dataset** or convert it to the coco format for training?
Thanks

**Comment by gadcam** [comment]
Looks like this issue is a duplicate of #241, should be closed.

**Comment by ir413** [comment]
Duplicate of #241.

**Comment by vsd550** [comment]
@ir413 @gadcam But there is no answer to that issue too!!

**Comment by gadcam** [comment]
@vsd550 There is no point to have duplicates as it can only dilute information.
