### ISSUE TITLE
Custom Face Recognition

### ISSUE THREAD

**Issue by andymancodes** [facebookresearch/Detectron#488]
Hi,

I am new to machine learning but I want to include a custom face recognizer for my project.

The project is: We have a set of employees with their photos. We want to build an application so that they can enter if their face is recognized.

The custom models of Microsoft or Google are about just recognizing a face, not about who is the person behind that face.

The Facebook website has an impressive photo tagging system so it must be recognizing faces somehow.

Please let us know, what Problem is this called (so that I can see if we can build a model) and whether detectron or other facebook libraries have support for training custom face recignition model.

Cheers!!

**Comment by gadcam** [comment]
Hi @andymancodes,
I think there could be a way to use the Detectron for this purpose, but, as far as I know, it is not the best way to proceed.
I think this paper can be a good starting point https://arxiv.org/abs/1804.06655

**Comment by ir413** [comment]
As @gadcam said, this functionality can likely be built on top of Detectron but is not readily available. You may also want to check out [this](https://www.cs.toronto.edu/~ranzato/publications/taigman_cvpr14.pdf) related paper.
