### ISSUE TITLE
how to change the  name of category?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#489]
hi!
I use my own datasets, and change NUM_CLASSES: 7 in yaml.  how to change the name of class?
for example, I run infer_simple.py using faster rcnn, the output is like person, car, but my datasets don't include these classes. how should I do?

**Comment by ir413** [comment]
Hi @lilichu, see discussion in #471.

**Comment by lilichu** [comment]
@ir413 Thanks very much! It's cool
