### ISSUE TITLE
how I can creat a fully connect shared operator

### ISSUE THREAD

**Issue by LeonJWH** [facebookresearch/Detectron#492]
I want to creat a shared FC operator in Detectron, like ConvShared operator. I build the FCShared operator like this in $Detectron/detectron/modeling/detrector.py:
```
    def FCShared(
        self,
        blob_in,
        blob_out,
        dim_in,
        dim_hidden,
        weight=None,
        bias=None,
        **kwargs
    ):
        use_bias = (
            False if ('no_bias' in kwargs and kwargs['no_bias']) else True
        )
        use_bias = True

        if self.use_cudnn:
            kwargs['engine'] = 'CUDNN'
            kwargs['exhaustive_search'] = self.cudnn_exhaustive_search
            if self.ws_nbytes_limit:
                kwargs['ws_nbytes_limit'] = self.ws_nbytes_limit

        if use_bias:
            blobs_in = [blob_in, weight, bias]
        else:
            blobs_in = [blob_in, weight]

        if 'no_bias' in kwargs:
            del kwargs['no_bias']

        return self.net.FC(
            blobs_in, blob_out, dim_in, dim_hidden, **kwargs
        )
```
And I use it as below:

```
model.FCShared(
                blobs_in[1],
                'cls_score_1st_2nd',
                dim,
                model.num_classes,
                weight='cls_score_1st_w',
                bias='cls_score_1st_b'
            )
```

But some error occured:

> Traceback (most recent call last):
>   File "/home/user/workspace/Detectron/tools/test_net.py", line 116, in <module>
>     check_expected_results=True,
>   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 128, in run_inference
>     all_results = result_getter()
>   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 125, in result_getter
>     gpu_id=gpu_id
>   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 235, in test_net
>     model = initialize_model_from_cfg(weights_file, gpu_id=gpu_id)
>   File "/home/user/workspace/Detectron/detectron_cascade/core/test_engine.py", line 328, in initialize_model_from_cfg
>     model = model_builder.create(cfg.MODEL.TYPE, train=False, gpu_id=gpu_id)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 124, in create
>     return get_func(model_type_func)(model)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 89, in generalized_rcnn
>     freeze_conv_body=cfg.TRAIN.FREEZE_CONV_BODY
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 230, in build_generic_detection_model
>     optim.build_data_parallel_model(model, _single_gpu_build_func)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/optimizer.py", line 54, in build_data_parallel_model
>     single_gpu_build_func(model)
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 204, in _single_gpu_build_func
>     spatial_scale_conv, cfg.MODEL.NUM_RCNN_STAGE
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/model_builder.py", line 270, in _add_cascade_fast_rcnn_head
>     model, blob_in, dim_in, spatial_scale_in, i + 2
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/fast_rcnn_heads.py", line 300, in add_roi_cascade_2mlp_head
>     model.FCShared(roi_feat, 'fc1' + '_1st' + '_2nd', dim_in * roi_size * roi_size, hidden_dim, weight='fc1_1st_w', bias='fc1_1st_b')
>   File "/home/user/workspace/Detectron/detectron_cascade/modeling/detector.py", line 453, in FCShared
>     blobs_in, blob_out, dim_in, dim_hidden, **kwargs
>   File "/usr/local/lib/python2.7/dist-packages/caffe2/python/core.py", line 2070, in <lambda>
>     op_type, *args, **kwargs)
> TypeError: _CreateAndAddToSelf() takes at most 4 arguments (8 given)

I am not quiet good at creat operators in Detectron, can you give some ideas?

**Comment by gadcam** [comment]
@LeonJWH Looks like you have a problem with how you call the FC operator.

I do not know much about it but Caffe2 does not seem to understand where it should put all the arguments.
For what it is worth, I would try to replace
```py
        return self.net.FC(
            blobs_in, blob_out, dim_in, dim_hidden, **kwargs
        )
```
by
```py
        return self.net.FC(
            blobs_in,
            blob_out,
            dim_in=dim_in, 
            dim_out=dim_hidden,
            **kwargs
        )
```

**Comment by LeonJWH** [comment]
OK, I tried your method and it worked, thanks a lot!
