### ISSUE TITLE
How to use roi_data/loader.py?

### ISSUE THREAD

**Issue by yw155** [facebookresearch/Detectron#496]
Hi, I use the mask-rcnn to perform keypoint estimation. I see the data input is concerned with three files, which are datasets/roidb.py, roi_data/loader.py, and roi_data/keypoint_rcnn.py. I am not very clear the relations between these three files. Is it possible to give me some detailed explanations? Thanks.

**Comment by ir413** [comment]
Hi @yw155, `roidb` is the data structure used for storing the required information about the images in a dataset (e.g. image paths, ground truth boxes, proposals, etc.). Study [this function](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/json_dataset.py#L82) to se how `roidb` for a dataset is constructed. [roi_data/loader.py](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/loader.py) contains the implementation of the Detectron's data loader  that handles loading of minibatch blobs (detailed description of its design is given at the top of the file). [roi_data/minibatch.py](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/minibatch.py) constructs minibatch blobs. [roi_data/keypoint_rcnn.py](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/keypoint_rcnn.py) contains logic for constructing blobs specific to Keypoint R-CNN.

**Comment by yw155** [comment]
Hi @ir413, thanks for your detailed explanations. Thank you.
