### ISSUE TITLE
Training in Python, Inference in C++ on a GPU/CPU

### ISSUE THREAD

**Issue by bayesianio** [facebookresearch/Detectron#501]
Dear All, 
I am looking for a simple example in which:
1 )Training is done in Python
2) Model is persisted to disk
3) Model is loaded elsewhere, possible on a machine with multiple GPU's
4) C++ is used to load the model and run inference, either on a CPU, a single GPU or multiple GPU's 

Many thanks,

**Comment by bayesianio** [comment]
Any one ...?

**Comment by gadcam** [comment]
@bayesianio 
Do not forget that there is a search function to find relevant issues before posting ;)
- 1\) / 2\) Cf README https://github.com/facebookresearch/Detectron#quick-start-using-detectron
- 4\) Cf #24  & #432 
- 3\) Maybe this comment can help you https://github.com/facebookresearch/Detectron/issues/432#issuecomment-391419145
