### ISSUE TITLE
evaluation of kps

### ISSUE THREAD

**Issue by jinxuan777** [facebookresearch/Detectron#504]
I trained a model of keypoints detection with own datasets. reval.py is used to evaluate the mAP of results. I found compute_oks set
sigmas = np.array([.26, .25, .25, .35, .35, .79, .79, .72, .72, .62,.62, 1.07, 1.07, .87, .87, .89, .89])/10.0
How could I recompute the sigmas ? @rbgirshick

**Comment by gadcam** [comment]
@jinxuan777 
keypoints.py reads
https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/utils/keypoints.py#L16
so the OKS(Object Keypoint Similarity) is defined here http://cocodataset.org/#keypoints-eval

The sigmas used to compute it are defined in the page
>As discussed, we set κ<sub>i</sub>=2σ<sub>i</sub> for each keypoint type i. For people, the σ's are .026, .025, .035, .079, .072, .062, .107, .087, &amp; .089 for the nose, eyes, ears, shoulders, elbows, wrists, hips, knees, &amp; ankles, respectively.

and the procedure used to obtain them is detailed in <code>1.3. Tuning OKS</code>.

**Comment by tucachmo2202** [comment]
Hi everyone,
I see that in Tuning OKS "First, using 5000 redundantly annotated images in val, for each keypoint type i we measured the per-keypoint standard deviation σi with respect to object scale s. That is we compute σi2=E[di^2/s^2]". When we don't evaluation, where can we get di from?
