### ISSUE TITLE
Jetson TX1 Inference process killed

### ISSUE THREAD

**Issue by johannathiemich** [facebookresearch/Detectron#507]
Hello,
I am trying to run the Mask RCNN.
I installed all the stuff needed for Detectron according to the install file. I am using an NVIDIA Jetson TX1.
All tests (command line for Caffe2, test_spatial_narrow_as_op.py) passed.
But when running the inference example (tools/infer_simple.py) the process gets killed. 
I already tried using a smaller model. So far I tried the ResNet101 FPN, ResNet50 FPN, ResNet 50 C4. 
My setup:
JetPack 3.2
Python 2.7
L4T R28.2 Ubuntu 16.04
Opencv 3.4 (built from source for Jetson)
CUDA 9.0
cudNN 7
The TX1 has 4 GB of GPU + CPU RAM (GPU and CPU space are shared). Is that simply not enough space to run inference?
Does anybody have a reference about how much space is taken in total while running inference?
After running the following command:
`python2 tools/infer_simple.py --cfg configs/12_2017_baselines/e2e_mask_rcnnR-50-C4_2x.yaml --output-dir /media/nvidia/swap/temp --image-ext jpg --wts models/mask_rcnn_r-50-c4_2x.pkl demo`

I got the following output:
```
Found Detectron ops lib: /media/nvidia/swap/pytorch/build/lib/libcaffe2_detectron_ops_gpu.so
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  59: Loading weights from: models/mask_rcnn_r-50-c4_2x.pkl
I0620 09:13:14.841773  9401 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000208955 secs
I0620 09:13:14.899009  9401 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000171196 secs
I0620 09:13:14.916280  9401 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 9.1197e-05 secs
INFO infer_simple.py: 125: Processing /media/nvidia/swap/detectron/demo/small_image.jpg -> /media/nvidia/swap/temp/small_image.jpg.pdf
I0620 09:13:14.977749  9401 net_async_base.cc:421] Using specified CPU pool size: 4; NUMA node id: -1
I0620 09:13:14.977933  9401 net_async_base.cc:426] Created new CPU pool, size: 4; NUMA node id: -1
Killed

```

I did adapt the infer_simple.py file a bit to use a picture I chose. That picture has a smaller resolution than the ones provided in demo, but it did not help.
When running tegrastats while executing the above command, the highest amount of memory used is supposed to be about 3800 MB out ot 3976 MB. So it is well possible that this is a pure memory problem.
How can I reduce the space taken during inference? 
Has anybody successfully executed this script on a Jetson TX1? 

Thanks in advance!

**Comment by gadcam** [comment]
@johannathiemich Not enough RAM is a common problem with the Detectron cf #21.
For the Jetson TX1 support there is the issue #88 but it seems to work well now.

**Comment by ir413** [comment]
Let's use #88 to consolidate Jetson TX1 reports.
