### ISSUE TITLE
How to print the metrics after evaluating on coco dataset 

### ISSUE THREAD

**Issue by vsd550** [facebookresearch/Detectron#513]
I ran the following  command 
 `CUDA_VISIBLE_DEVICES=0 python3 tools/test_net.py --dataset coco2017 --cfg configs/baselines/e2e_mask_rcnn_R-50-C4_1x.yaml --load_detectron /mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/detectron_pretrained_wts/model_final_R-50-C4-1x.pkl --output_dir output_dir  --range 1 101`

This runs the detection on 100 images. I am getting the following output:

> INFO test_engine.py: 314: Wrote detections to: /mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/output_dir/detection_range_1_101.pkl

Now how can I get the **final metrics, like AP, AR from the .pkl file**.

Also when I evaluated on the entire validation set, I got the following error : 

> INFO test_engine.py: 314: **Wrote detections** to: /mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/output_dir/detection_range_0_2500.pkl
> INFO test_engine.py: 211: **Wrote detections** to: /mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/output_dir/detections.pkl
> INFO test_engine.py: 161: Total inference time: 678.335s
> INFO task_evaluation.py:  75: **Evaluating detections**
> Traceback (most recent call last):
>   File "tools/test_net.py", line 112, in <module>
>     check_expected_results=False)  ##changed to False here
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/core/test_engine.py", line 128, in run_inference
>     all_results = result_getter()
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/core/test_engine.py", line 108, in result_getter
>     multi_gpu=multi_gpu_testing
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/core/test_engine.py", line 163, in test_net_on_dataset
>     dataset, all_boxes, all_segms, all_keyps, output_dir
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/datasets/task_evaluation.py", line 59, in evaluate_all
>     dataset, all_boxes, output_dir, use_matlab=use_matlab
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/datasets/task_evaluation.py", line 79, in evaluate_boxes
>     dataset, all_boxes, output_dir, use_salt=not_comp, cleanup=not_comp
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/datasets/json_dataset_evaluator.py", line 135, in evaluate_boxes
>     _write_coco_bbox_results_file(json_dataset, all_boxes, res_file)
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/datasets/json_dataset_evaluator.py", line 160, in _write_coco_bbox_results_file
>     json_dataset, all_boxes[cls_ind], cat_id))
>   File "/mnt/nfshome1/FRACTAL/vijay.dubey/Detectron.pytorch/lib/datasets/json_dataset_evaluator.py", line 171, in _coco_bbox_results_one_category
>     **assert len(boxes) == len(image_ids)**
> **AssertionError**

This error also saves the **detections.pkl** file but can't print the metric
Please help on this
Thanks

**Comment by lssily** [comment]
@vsd550 Hi! Do you know how to get the final  AP frpm the .pkl file?
