### ISSUE TITLE
How is the segmentation metric calculated in mask rcnn?

### ISSUE THREAD

**Issue by vsd550** [facebookresearch/Detectron#514]
Can anyone tell as to what metric is used for **evaluating the Segmentation masks in Mask-RCNN** and how is it implemented, because in the code, I can see that its using the same metric as the bounding box detection. How can the Dice Coefficient, used in [this](https://www.kaggle.com/c/carvana-image-masking-challenge#evaluation) kaggle challenge be used here?

**Comment by gadcam** [comment]
@vsd550
I think the segmentation evaluation is coded here https://github.com/facebookresearch/Detectron/blob/cd447c77c96f5752d6b37761d30bbdacc86989a2/detectron/utils/segms.py#L198-L227

It can also be worth reading how a result is evaluated in the COCO challenge http://cocodataset.org/#stuff-eval as it will provide the context.

**Comment by ir413** [comment]
See [this page](http://cocodataset.org/#detection-eval) and [this paper](https://arxiv.org/abs/1405.0312) for more info on COCO instance segmentation evaluation.
