### ISSUE TITLE
How to get test result（detection.pkl）of test data set

### ISSUE THREAD

**Issue by wytcsuch** [facebookresearch/Detectron#516]
I've trained my model by running train_net.py,and now I want to test on my own test data.but I don't have the annotations of test data,I just want to get the detection result(detection.pkl) ,I don't need to know the mAP. I run the infer_simple.py,it don't output the detection.pkl.what should I do?

**Comment by karlind** [comment]
You shold first convert your test dataset to coco format, and then add it to `dataset_catalog.py`. 
Note that if your data has no annotations, your dataset name should contains `test` characters.

After that, modify your yaml file, then just run `tools\test_net.py`. After that, you will properly get what you want.

**Comment by StalonWilson** [comment]
@karlind @wytcsuch Sorry, I still don't get it.
If I add an additional dataset to dataset_catalog.py, I still need to have an annotation file.
So how does the annotation format look like if I don't have any labeling?
Thanks for your patient help.
