### ISSUE TITLE
questions about Protobuf Errors

### ISSUE THREAD

**Issue by zhiAung** [facebookresearch/Detectron#519]
when i have the problem about
`-- Caffe2: Protobuf version
CMake Error at /data/xiaobing.wang/zhiang.hao/caffe2/build/Caffe2Config.cmake:55 (message):
  Your installed Caffe2 is built with protobuf , while your current cmake
  setting discovers protobuf version .  Please specify a protobuf version
  that is the same as the built version.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)`

then i follow this 
`cmake .. \
  # insert your Caffe2 CMake flags here
  -DPROTOBUF_PROTOC_EXECUTABLE=$HOME/c2_tp_protobuf/bin/protoc \
  -DPROTOBUF_INCLUDE_DIR=$HOME/c2_tp_protobuf/include \
  -DPROTOBUF_LIBRARY=$HOME/c2_tp_protobuf/lib64/libprotobuf.a`
 i donot know that what is the meaning  # insert your Caffe2 CMake flags here  so i find  a flag from caffe2 cmake file  then i run the commands from above but New problems arise

like this 
`cmake .. \
>   -Wno-deprecated-declarations
-- Configuring done
-- Generating done
-- Build files have been written to: /data/xiaobing.wang/peixuan.liang/caffe2/third_party/protobuf/cmake/build
xiaobing.wang@ubuntu:~/peixuan.liang/caffe2/third_party/protobuf/cmake/build$   -DPROTOBUF_PROTOC_EXECUTABLE=$HOME/c2_tp_protobuf/bin/protoc \
>   -DPROTOBUF_INCLUDE_DIR=$HOME/c2_tp_protobuf/include \
>   -DPROTOBUF_LIBRARY=$HOME/c2_tp_protobuf/lib64/libprotobuf.a
-bash: -DPROTOBUF_PROTOC_EXECUTABLE=/data/xiaobing.wang/c2_tp_protobuf/bin/protoc: No such file or directory
`
Do anyone know what's going on

**Comment by ir413** [comment]
Hi @zhiAung - yes, you should be able to use the [protobuf troubleshooting instructions](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#protobuf-errors) to first build protobuf and then point Caffe2 to your custom protobuf.

"`# insert your Caffe2 CMake flags here`" means that you should specify any additional Caffe2 CMake flags you would normally use (if you do not normally specify any of the other Caffe2 CMake options you can ignore this).

The errors you posted may suggest that you do not have custom protobuf compiler installed at the location you specified in the CMake command (`/data/xiaobing.wang/c2_tp_protobuf/bin/protoc`).

**Comment by zhiAung** [comment]
Thank you for your enthusiastic answer @ir413  
First of all I have found a Caffe2 CMake flags and have inserted him into the command line, but I don't know right, so where do you think should go to Caffe2 CMake flags?
Then about that wrong question,I ran these instructions
`# CAFFE2=/path/to/caffe2
cd $CAFFE2/third_party/protobuf/cmake
mkdir -p build && cd build
cmake .. \
  -DCMAKE_INSTALL_PREFIX=$HOME/c2_tp_protobuf \
  -Dprotobuf_BUILD_TESTS=OFF \
  -DCMAKE_CXX_FLAGS="-fPIC"
make install`

`/data/xiaobing.wang/c2_tp_protobuf` `is this` $HOME/c2_tp_protobuf
Do you mean it should not be this path?
Because these environments were previously configured by others,so ,the location he specified in the CMake command,I do not know where it is
Can you give me some further instructions and by the way mention that I am ready to replicate the results of DensePose?
