### ISSUE TITLE
what is the difference of ROI_MAX_LEVEL and RPN_MAX_LEVEL

### ISSUE THREAD

**Issue by coldgemini** [facebookresearch/Detectron#52]
the comment in code for these two parameters are the same.

**Comment by rbgirshick** [comment]
From the context (shown below), notice that `FPN.ROI_MAX_LEVEL` pertains to the use of RoI transforms (like `RoIAlign`) with `FPN` (Feature Pyramid Network), while `FPN.RPN_MAX_LEVEL` pertains to using `RPN` (Region Proposal Network) with `FPN`.

It's possible to have `RPN` use one interval of `FPN` levels and have `RoIAlign` use a different interval of `FPN` levels.

```
# Use FPN for RoI transform for object detection if True
__C.FPN.MULTILEVEL_ROIS = False
# Hyperparameters for the RoI-to-FPN level mapping heuristic
__C.FPN.ROI_CANONICAL_SCALE = 224  # s0
__C.FPN.ROI_CANONICAL_LEVEL = 4  # k0: where s0 maps to
# Coarsest level of the FPN pyramid
__C.FPN.ROI_MAX_LEVEL = 5
# Finest level of the FPN pyramid
__C.FPN.ROI_MIN_LEVEL = 2

# Use FPN for RPN if True
__C.FPN.MULTILEVEL_RPN = False
# Coarsest level of the FPN pyramid
__C.FPN.RPN_MAX_LEVEL = 6
# Finest level of the FPN pyramid
__C.FPN.RPN_MIN_LEVEL = 2
# FPN RPN anchor aspect ratios
__C.FPN.RPN_ASPECT_RATIOS = (0.5, 1, 2)
# RPN anchors start at this size on RPN_MIN_LEVEL
# The anchor size doubled each level after that
# With a default of 32 and levels 2 to 6, we get anchor sizes of 32 to 512
__C.FPN.RPN_ANCHOR_START_SIZE = 32
# Use extra FPN levels, as done in the RetinaNet paper
__C.FPN.EXTRA_CONV_LEVELS = False
```

**Comment by coldgemini** [comment]
ROI_MAX_LEVEL is for the two stage detector ans RPN_MAX_LEVEL is for the own stage retinanet detector?
I think using the word 'RPN' in retinanet is a bit misleading.

**Comment by rbgirshick** [comment]
FPN.RPN_* is for RPN and since RetinaNet uses the same modeling primitives as RPN it reuses it.
