### ISSUE TITLE
when I  test Retinanet,it only detect one class

### ISSUE THREAD

**Issue by wytcsuch** [facebookresearch/Detectron#521]
I used retianet to train my data，it should detect three classes，airport、bridge and  harbour.But when testing,it detect all the objects in the picture as airport.There should be no problem with training data, because FPN was trained earlier.what's wrong?

**Comment by ir413** [comment]
Hi @wytcsuch, it is very hard to tell what is wrong without having more information about the exact changes you made to the code and the commands you're running.
