### ISSUE TITLE
How to change classification loss function

### ISSUE THREAD

**Issue by PacteraOliver** [facebookresearch/Detectron#523]
I found #438 and #257 asked about the loss function issues.

I want to know how to change the loss function for a certain network.

I found that the loss function is now written in caffe2 [select_smooth_l1_loss_op.h](https://github.com/caffe2/caffe2/blob/master/modules/detectron/select_smooth_l1_loss_op.h)

Is there a way to change it or define by our self?

Thank you.

**Comment by ir413** [comment]
Hi @PacteraOliver, you can change the classification loss function [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/fast_rcnn_heads.py#L77-L80). You may also find it useful to look at the following functions that are used to define the losses for different tasks: [fast_rcnn_losses](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/fast_rcnn_heads.py#L75), [mask_rcnn_losses](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/mask_rcnn_heads.py#L95) and [keypoint_rcnn_losses](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/keypoint_rcnn_heads.py#L110).
