### ISSUE TITLE
Are the COCO dataset training images randomly shuffled when running train_net_step.py?

### ISSUE THREAD

**Issue by vsd550** [facebookresearch/Detectron#525]
Because we are using the **same json file** for training every time(if we **freshly train from scratch**), I was wondering how does this code ensure that the training samples are **randomly shuffled** every time we start fresh training, **OR** the images are not passed in the same order everytime.

Thanks

**Comment by rbgirshick** [comment]
The image order is [shuffled](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/loader.py) after each epoch.
