### ISSUE TITLE
training get slower and slower

### ISSUE THREAD

**Issue by LeonJWH** [facebookresearch/Detectron#526]
I add two new operators to implement some other functions, the models were trained successfully, but the training time for one each iteration became longer and longer, what possible reasons can results in this?

**Comment by rbgirshick** [comment]
Not enough information in the issue. Feel free to re-open if you provide more information (e.g., code for your new ops).

**Comment by LeonJWH** [comment]
I tried to implement Cascade RCNN under Detectron. To do this, I added to extra operators: DecodeBBoxOp and DistributeFpnRpnProposalsOP. The former one add deltas of bbox_pred to rois to generate detections results of current stage of rcnn, then the detection results are distributed to multi-level fpn, then fed into the next rcnn stage. 
Codes of operators are as below, some other dependent files, are written in Detectron coding style.
DecodeBBoxOp:
```
class DecodeBBoxOp(object):
    def __init__(self, train, stage_num):
        self._train = train
        self._stage_num = stage_num

    def forward(self, inputs, outputs):
        # The inputs contains [bbox_pred, cls_prob, rois]
        # rois --> np.array((num,5)), (batch_idx, x1, y2, x2, y2)
        # print('++++++++++++++++++++++ Decode BBox of rcnn stage {} +++++++++++++++++++++++'.format(self._stage_num))
        cls_prob = inputs[0].data[...]
        bbox_pred = inputs[1].data[...]
        rois = inputs[2].data[...]
        if self._train:
            overlaps = inputs[3].data[...]        
            im_info = inputs[4].data
        else:
            im_info = inputs[3].data

        proposals_next = rois[:, 1:5]

        # Use delta with max cls_score as deltas adding to rois
        cls_idx = cls_prob.argmax(axis=1)
        delta = np.zeros((bbox_pred.shape[0], 4), dtype=bbox_pred.dtype)
        for i in xrange(cls_idx.shape[0]):
            delta[i, :] = bbox_pred[i, cls_idx[i] * 4:cls_idx[i] * 4 + 4]

        # Add bbox deltas onto rois to generate new rois
        new_rois = box_utils.bbox_transform(proposals_next, delta, cfg.MODEL.BBOX_REG_WEIGHTS)
        batch_idxs = rois[:, 0].reshape(rois.shape[0], 1)
        new_rois = np.hstack((batch_idxs, new_rois))
        
        # remove invalid boxes
        output_rois_pre = remove_invalid_boxes(new_rois)

        if self._train:
            # screen out high IOU boxes, to remove redundant gt boxes
            output_rois = remove_high_iou_boxes(output_rois_pre, overlaps)
        else:
            output_rois = output_rois_pre
        
        # clip tiled boxes into image
        output_rois = clip_tiled_bboxes(output_rois, im_info[0, :2])
        blob_utils.py_op_copy_blob(output_rois, outputs[0])

def remove_invalid_boxes(boxes):

    ws = boxes[:, 3] - boxes[:, 1] + 1
    hs = boxes[:, 4] - boxes[:, 2] + 1
    invalid_idx_w = np.where(ws < 0)[0]
    invalid_idx_h = np.where(hs < 0)[0]
    _invalid_idx = np.append(invalid_idx_w, invalid_idx_h)
    invalid_idx = np.unique(_invalid_idx)

    if invalid_idx.shape[0] != 0:
        print('RCNN stage {} --- Distrubute And Fpn Rpn Proposals Op: input rois contain {} invalid boxes, they are:'.format(
               self._stage_num, invalid_idx.shape[0])
        )
        print(boxes[invalid_idx, :])

    new_boxes = np.delete(boxes, invalid_idx, axis=0)
    return new_boxes

def remove_high_iou_boxes(boxes, overlaps):
    assert boxes.shape[0] == overlaps.shape[0], 'number rois do not match number overlaps'

    # print('gt iou thr: {}'.format(cfg.TRAIN.GT_IOU_THR))
    valid_idx = np.where(overlaps < cfg.TRAIN.GT_IOU_THR)[0]
    # print('high iou boxes: {}'.format(boxes.shape[0] - valid_idx.shape[0]))

    new_boxes = boxes[valid_idx, :]
    return new_boxes

def clip_tiled_bboxes(boxes, im_shape):
    """Clip boxes to image boundaries. im_shape is [height, width] and boxes has shape (N, 4 * num_tiled_boxes)."""
    assert boxes.shape[1] % 4 == 1, 'boxes.shape[1] is {:d}, but must be divisible by 5.'.format(boxes.shape[1])
    # x1 >= 0
    boxes[:, 1::5] = np.maximum(np.minimum(boxes[:, 1::5], im_shape[1] - 1), 0)
    # y1 >= 0
    boxes[:, 2::5] = np.maximum(np.minimum(boxes[:, 2::5], im_shape[0] - 1), 0)
    # x2 < im_shape[1]
    boxes[:, 3::5] = np.maximum(np.minimum(boxes[:, 3::5], im_shape[1] - 1), 0)
    # y2 < im_shape[0]
    boxes[:, 4::5] = np.maximum(np.minimum(boxes[:, 4::5], im_shape[0] - 1), 0)
    return boxes 
```
DietributeFpnRpnProposalsOp:
```
class DistributeFpnRpnProposalsOp(object):
    def __init__(self, train, stage_num):
        self._train = train
        self._stage_num = stage_num

    def forward(self, inputs, outputs):
        """See modeling.detector.DistributeFpnRpnProposals for
        inputs/outputs documentation.
        """
        # inputs is [rois] out from decode_bbox operator
        # If training with Faster R-CNN, then inputs will additionally include
        #  + [roidb, im_info]
        _rois = inputs[0].data
        rois = remove_invalid_boxes(_rois, self._stage_num)
        if self._train:
            # During training we reuse the data loader code. We populate roidb
            # entries on the fly using the rois generated by RPN.
            # im_info: [[im_height, im_width, im_scale], ...]
            im_info = inputs[2].data
            im_scales = im_info[:, 2]
            roidb = blob_utils.deserialize(inputs[1].data)
            json_dataset.add_proposals(roidb, rois, im_scales, crowd_thresh=0)
            roidb_utils.add_bbox_regression_targets(roidb)

            # Compute training labels for the RPN proposals; also handles
            # distributing the proposals over FPN levels
            output_blob_names = fast_rcnn_roi_data.get_cascade_fast_rcnn_blob_names(is_training=True, stage_num=self._stage_num)
            blobs = {k: [] for k in output_blob_names}
            fast_rcnn_roi_data.add_fast_rcnn_blobs(blobs, im_scales, roidb, self._stage_num)
            for i, k in enumerate(output_blob_names):
                blob_utils.py_op_copy_blob(blobs[k], outputs[i])
        else:
            # For inference we have a special code path that avoids some data
            # loader overhead
            distribute(rois, None, outputs, self._train, self._stage_num)


def distribute(rois, label_blobs, outputs, train, stage_num):
    """To understand the output blob order see return value of
    detectron.roi_data.fast_rcnn.get_fast_rcnn_blob_names(is_training=False)
    """
    lvl_min = cfg.FPN.ROI_MIN_LEVEL
    lvl_max = cfg.FPN.ROI_MAX_LEVEL
    lvls = fpn.map_rois_to_fpn_levels(rois[:, 1:5], lvl_min, lvl_max)

    outputs[0].reshape(rois.shape)
    outputs[0].data[...] = rois
    # Create new roi blobs for each FPN level
    # (See: modeling.FPN.add_multilevel_roi_blobs which is similar but annoying
    # to generalize to support this particular case.)
    rois_idx_order = np.empty((0, ))
    for output_idx, lvl in enumerate(range(lvl_min, lvl_max + 1)):
        idx_lvl = np.where(lvls == lvl)[0]
        blob_roi_level = rois[idx_lvl, :]
        outputs[output_idx + 1].reshape(blob_roi_level.shape)
        outputs[output_idx + 1].data[...] = blob_roi_level
        rois_idx_order = np.concatenate((rois_idx_order, idx_lvl))
    rois_idx_restore = np.argsort(rois_idx_order)
    blob_utils.py_op_copy_blob(rois_idx_restore.astype(np.int32), outputs[-1])


def remove_invalid_boxes(rois, stage_num):
    # rois with shape (N, 5), contain (batch_idx, x1, y1, x2, y2)
    ws = rois[:, 3] - rois[:, 1] + 1
    hs = rois[:, 4] - rois[:, 2] + 1
    invalid_idx_w = np.where(ws < 0)[0]
    invalid_idx_h = np.where(hs < 0)[0]
    _invalid_idx = np.append(invalid_idx_w, invalid_idx_h)
    invalid_idx = np.unique(_invalid_idx)

    if invalid_idx.shape[0] != 0:
        print('RCNN stage {} --- Distrubute And Fpn Rpn Proposals Op: input rois contain {} invalid boxes, they are:'.format(
            stage_num, invalid_idx.shape[0])
        )
        print(rois[invalid_idx, :])

    new_rois = np.delete(rois, invalid_idx, axis=0)

    return new_rois
```

The training progress ran with no error until I resume training for one time, when I tried to resume training the Cascade RCNN with mask branch. The training progress went well at the begining, but alone with the training continues, the training time for each iter grows progressly, after hundreds or thousands of iterations, the training broke down with the cuda error below:

> *** Check failure stack trace: ***
> F0628 15:21:28.669647 1910 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669657 1911 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1904 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1909 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669703 1914 context_gpu.h:107] C06ck failed: error == cudaSuccess unspecified launch failure
> 28 15:21:28.669694 1906 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669710 1900 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670411 1912 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670415 1903 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> F0628 15:21:28.669647 1910 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669657 1911 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1904 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1909 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669703 1914 context_gpu.h:107] C06ck failed: error == cudaSuccess unspecified launch failure
> 28 15:21:28.669694 1906 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669710 1900 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670411 1912 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670415 1903 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670450 1902 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> F0628 15:21:28.669647 1910 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669657 1911 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1904 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1909 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669703 1914 context_gpu.h:107] C06ck failed: error == cudaSuccess unspecified launch failure
> 28 15:21:28.669694 1906 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669710 1900 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670411 1912 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670415 1903 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670450 1902 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670488 1913 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> E0628 15:21:28.669669 1907 net_dag.cc:195] Secondary exception from operator chain starting at '' (type 'Add'): caffe2::EnforceNotMet: [enforce fail at context_gpu.h:156] . Encountered CUDA error: unspecified launch failure Error from operator:
> input: "gpu_0/mask_fcn_logits_w_grad" input: "gpu_1/mask_fcn_logits_w_grad" output: "gpu_0/mask_fcn_logits_w_grad" name: "" type: "Add" device_option { device_type: 1 cuda_gpu_id: 0 }
> F0628 15:21:28.669647 1910 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669657 1911 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1904 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1909 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669703 1914 context_gpu.h:107] C06ck failed: error == cudaSuccess unspecified launch failure
> 28 15:21:28.669694 1906 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669710 1900 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670411 1912 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670415 1903 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670450 1902 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670488 1913 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> F0628 15:21:28.669647 1910 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669657 1911 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1904 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1909 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669703 1914 context_gpu.h:107] C06ck failed: error == cudaSuccess unspecified launch failure
> 28 15:21:28.669694 1906 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669710 1900 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670411 1912 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670415 1903 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670450 1902 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670488 1913 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureFF0628 15:21:28.669647 1910 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669657 1911 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1904 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669684 1909 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669703 1914 context_gpu.h:107] C06ck failed: error == cudaSuccess unspecified launch failure
> 28 15:21:28.669694 1906 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.669710 1900 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670411 1912 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670415 1903 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670450 1902 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670488 1913 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failureF0628 15:21:28.670533 1907 context_gpu.h:107] Check failed: error == cudaSuccess unspecified launch failure
> *** Check failure stack trace: ***
> *** Check failure stack trace: ***.
I also tried to train original Mask RCNN, but run into the same error, could you give me some advices?
