### ISSUE TITLE
Enquiry about data loader parameters

### ISSUE THREAD

**Issue by yw155** [facebookresearch/Detectron#531]
### Expected results
Hi @ir413, I would like to ask you some questions about the data loading parameters. 
First, I see the 'DATA_LOADER.NUM_THREADS = 4' is the sweet spot in the config.py. Is it indicates for one GPU or eight GPUs? 
Second, I see each thread will read two images. Is there a design principle to choose the thread number and the image number processed in each thread? 
Third, is the parameter of 'minibatch_queue_size' indicates the number of 'roi' or the number of images? 
Fourth, in my project, each image has just one 'roi' and the minibatch number equals the number of images. How do I choose these parameters? Do I need to increase the parameter of 'NUM_THREADS' or just increasing the number of images being processed in each thread? Your answer would be very helpful. Thank you in advance!

**Comment by ir413** [comment]
Hi @yw155, please find the answers below:

> First, I see the 'DATA_LOADER.NUM_THREADS = 4' is the sweet spot in the config.py. Is it indicates for one GPU or eight GPUs?

This was determined empirically for the baseline 8 GPU configs (also see below).

> Third, is the parameter of 'minibatch_queue_size' indicates the number of 'roi' or the number of images?

It indicates the number of images (`roidb` entries).

> Second, I see each thread will read two images. Is there a design principle to choose the thread number and the image number processed in each thread?

> Fourth, in my project, each image has just one 'roi' and the minibatch number equals the number of images. How do I choose these parameters? Do I need to increase the parameter of 'NUM_THREADS' or just increasing the number of images being processed in each thread?

I think the best way to choose the data loader parameters is to choose them empirically for the setting you care about. You may find the [`data_loader_benchmark.py`](https://github.com/facebookresearch/Detectron/blob/master/detectron/tests/data_loader_benchmark.py) useful for quickly experimenting with data loader parameters.

**Comment by yw155** [comment]
Hi @ir413, thanks for your explanations.
