### ISSUE TITLE
Can I feed features to Detect Network? Not use backbone.

### ISSUE THREAD

**Issue by tzjtatata** [facebookresearch/Detectron#534]
I want to use some features extracting by other programs. So can I use the pre-trained Faster RCNN without the backbone Network?
I found that I can feed blobs to the workspace. But it seems I can't just run the network without backbone. Can I?
Thanks for helping. :)

**Comment by ir413** [comment]
Hi @tzjtatata, it should be possible to do what you describe. The easiest way may be to extract the part of the network you care about into a separate net and run only the newly created net (in the workspace containing the required feature blobs). It may be helpful to look at how the mask prediction net is extracted [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/model_builder.py#L280-L286) and to check out [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/c2.py#L53) helper function.
