### ISSUE TITLE
Problem with proposal files at test time for R-FCN model

### ISSUE THREAD

**Issue by alashkari** [facebookresearch/Detectron#535]
Hi,

I tried training R-FCN with ResNet-50 backbone on COCO 2014 dataset but got an error at test time, after the training has finished. It has something to do with proposal files. Please see the details below.

Thank you very much in advance for any help!

**Expected results**
The accuracy on the test set.

**Actual results**
This is the end of my terminal output, with an error:

INFO net.py: 142: Saving parameters and momentum to /detectron/Models/detectron-RFCN/train/coco_2014_train/ResNet50_rfcn/model_iter119999.pkl
INFO net.py: 142: Saving parameters and momentum to /detectron/Models/detectron-RFCN/train/coco_2014_train/ResNet50_rfcn/model_final.pkl
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 126: Stopping enqueue thread
INFO loader.py: 113: Stopping mini-batch loading thread
INFO loader.py: 113: Stopping mini-batch loading thread
INFO loader.py: 113: Stopping mini-batch loading thread
INFO loader.py: 113: Stopping mini-batch loading thread
Traceback (most recent call last):
  File "tools/train_net_rfcn.py", line 129, in <module>
    main()
  File "tools/train_net_rfcn.py", line 114, in main
    test_model(checkpoints['final'], args.multi_gpu_testing, args.opts)
  File "tools/train_net_rfcn.py", line 124, in test_model
    check_expected_results=True,
  File "/detectron/detectron/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/detectron/detectron/core/test_engine.py", line 101, in result_getter
    dataset_name, proposal_file = get_inference_dataset(i)
  File "/detectron/detectron/core/test_engine.py", line 76, in get_inference_dataset
    'If proposals are used, one proposal file must be specified for ' \
AssertionError: If proposals are used, one proposal file must be specified for each dataset

**Detailed steps to reproduce**

I'm training the model on COCO 2014 dataset, which I successfully trained Faster R-CNN on.
This is the model config:

MODEL:
  
  TYPE: ResNet50_rfcn
  CONV_BODY: FPN.add_fpn_ResNet50_conv5_body
  NUM_CLASSES: 81
  #FASTER_RCNN: True

NUM_GPUS: 2

SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.0025
  GAMMA: 0.1
  MAX_ITER: 120000
  STEPS: [0, 90000, 100000]

FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True

RESNETS:
  RES5_DILATION: 2

RFCN:
  #RFCN_ON: True
  PS_GRID_SIZE: 7

TRAIN:
  WEIGHTS: https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl
  DATASETS: ('coco_2014_train',)
  SCALES: (500,)
  MAX_SIZE: 833
  IMS_PER_BATCH: 2
  BATCH_SIZE_PER_IM: 256
  RPN_PRE_NMS_TOP_N: 2000
  SNAPSHOT_ITERS: 10000

TEST:
  DATASETS: ('coco_2014_minival',)
  SCALE: 500
  MAX_SIZE: 833
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000
  RPN_POST_NMS_TOP_N: 300

OUTPUT_DIR: /detectron/Models/detectron-RFCN

**System information**

Operating system: Ubuntu 16.04
Compiler version: gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CUDA version: Cuda compilation tools, release 8.0, V8.0.61
cuDNN version: 
NVIDIA driver version: Driver Version: 396.26
GPU models (for all devices if they are not all the same): TITAN X
`PYTHONPATH` environment variable: NONE
`python --version` output: Python 2.7.15 :: Anaconda, Inc.
Anything else that seems relevant: None

**Comment by ir413** [comment]
Hi @alashkari, the error suggests that the config you're using requires proposals to be provided for the test dataset (RPN subnetwork is not enabled in your config; see [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L461-L471) config option).
