### ISSUE TITLE
Not seeing masks in output images

### ISSUE THREAD

**Issue by samhodge** [facebookresearch/Detectron#54]
[33823288584_1d21cf0a26_k.jpg.pdf](https://github.com/facebookresearch/Detectron/files/1670601/33823288584_1d21cf0a26_k.jpg.pdf)
See image attached am I doing something wrong?

This is using ResNet50.

It is a fresh caffe2 install on Ubuntu 16.04 with cuda 8.0 and cudnn 6.0

this is the command I ran

`python2 tools/infer_simple.py   --cfg configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml   --output-dir /tmp/detectron-visualizations --image-ext jpg --wts https://s3-us-west-2.amazonaws.com/detectron/35857389/12_2017_baselines/e2e_faster_rcnn_R-50-FPN_2x.yaml.01_37_22.KSeq0b5q/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl demo
`

**Comment by samhodge** [comment]
Derp, I see I have used faster rcnn, where can I find the resnet 50 mask rcnn?

**Comment by samhodge** [comment]
I think my answer is somewhere here: https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md

**Comment by samhodge** [comment]
My GPU is only 4Gb is there a way I can do inference CPU only, I have 32 Gb of RAM.

**Comment by rbgirshick** [comment]
Marking this as a duplicate of #21 + #24.

**Comment by manyaafonso** [comment]
Hi @samhodge , how exactly did you solve this problem? I am also facing it. Which model did you use?

**Comment by manyaafonso** [comment]
I solved it, the config .yaml file must contain the line
MASK_ON: True
under Model:
Hope this saves someone else time.
