### ISSUE TITLE
After testing my own e2e_mask model, I can only get boxes,but no masks

### ISSUE THREAD

**Issue by zhangjinjing3** [facebookresearch/Detectron#540]
![qq 20180705151036](https://user-images.githubusercontent.com/22672283/42307643-b8ec8802-8065-11e8-95ab-763354caa6c0.png)
I trained the model with my own dataset, then I tried to test my model. But I can only get boxes,no mask was saved.In addition, some images cannot be saved normally.

**Comment by ir413** [comment]
Hi @zhangjinjing3, it is hard to tell what the issue is from the provided information. Please reopen the issue with a detailed description (modifications to the code made, commands and configs run, etc.).
