### ISSUE TITLE
Out of memory while test on custom dataset

### ISSUE THREAD

**Issue by soumenms2015** [facebookresearch/Detectron#543]
I am using 4 GPUs  GeForce GTX 1080Ti and model is ResNext-101-32x8d. The training is successfully completed. But out of memory issue is triggered while testing. 
Here is the error message:
INFO test_engine.py: 287: im_detect: range [1, 148] of 148: 1/148 15.559s + 1.122s (eta: 0:40:52)
terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /netscratch/pramanik/caffe2/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/res4_19_branch2c" input: "gpu_0/res4_19_branch2c_bn_s" input: "gpu_0/res4_19_branch2c_bn_b" output: "gpu_0/res4_19_branch2c_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 }
*** Aborted at 1530793624 (unix time) try "date -d @1530793624" if you are using GNU date ***
PC: @     0x7f77b4364f67 __GI_raise
*** SIGABRT (@0xbf600009960) received by PID 39264 (TID 0x7f75a1ffb700) from PID 39264; stack trace: ***
    @     0x7f77b4de9c10 (unknown)
    @     0x7f77b4364f67 __GI_raise
    @     0x7f77b436633a __GI_abort
    @     0x7f77acf17b39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f77acf161fb __cxxabiv1::__terminate()
    @     0x7f77acf16234 std::terminate()
    @     0x7f77acf31c8a execute_native_thread_routine_compat
    @     0x7f77b4de1724 start_thread
    @     0x7f77b441ce8d __clone
Aborted (core dumped)

I have also tried with 6 GPUS(0,1,2,3,4,5). But I am getting the same error.
I am using the multi-scale. 
what is the minimum memory required for it?

The same config file with single scale works for both train and test.

Thank you!

**Comment by ningxiangyun** [comment]
＠soumenms2015 Excuse me, how much time did it take to train the coco dataset under the conditions of 4 GPUs　GeForce GTX 1080Ti and model is ResNext-101-32x8d ?
Thank you！

**Comment by soumenms2015** [comment]
@ningxiangyun  I didn't try on coco dataset. I tried on my own custom datasets which usually takes more than 48 hours.

**Comment by ir413** [comment]
The minimum memory required at test time depends on the model and the scales you're using (note that this is not affected by the number of GPUs used; see #451 for discussion). It seems likely that the scales specified for your multi-scale testing are too large for your setting.

**Comment by soumenms2015** [comment]
Okay. Thank you for your response. Yes there was a mistake on my part. Although I mentioned 6 GPUs, but I run single gpu test_net, so it was using only single GPU so it triggers the out of memory. Unfortunately the multi-gpu testing also doesnt work. I am using GPU(0,1,2,3,4,5).
Here is the error message 

terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /netscratch/pramanik/caffe2/caffe2/core/context_gpu.cu:343: out of memory Error from operator:
input: "gpu_0/fpn_res2_2_sum" input: "gpu_0/conv_rpn_fpn2_w" input: "gpu_0/conv_rpn_fpn2_b" output: "gpu_0/conv_rpn_fpn2" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1531582711 (unix time) try "date -d @1531582711" if you are using GNU date ***
PC: @     0x7f5b50168f67 __GI_raise
*** SIGABRT (@0xbf6000088aa) received by PID 34986 (TID 0x7f5a7d7a4700) from PID 34986; stack trace: ***
    @     0x7f5b50bedc10 (unknown)
    @     0x7f5b50168f67 __GI_raise
    @     0x7f5b5016a33a __GI_abort
    @     0x7f5b48d1bb39 __gnu_cxx::__verbose_terminate_handler()
    @     0x7f5b48d1a1fb __cxxabiv1::__terminate()
    @     0x7f5b48d1a234 std::terminate()
    @     0x7f5b48d35c8a execute_native_thread_routine_compat
    @     0x7f5b50be5724 start_thread
    @     0x7f5b50220e8d __clone
Traceback (most recent call last):
  File "tools/test_net.py", line 115, in <module>
    check_expected_results=True,
  File "....../Detectron/lib/core/test_engine.py", line 128, in run_inference
    all_results = result_getter()
  File "/......./Detectron/lib/core/test_engine.py", line 108, in result_getter
    multi_gpu=multi_gpu_testing
  File "/......./Detectron/lib/core/test_engine.py", line 155, in test_net_on_dataset
    weights_file, dataset_name, proposal_file, num_images, output_dir
  File "/......../Detectron/lib/core/test_engine.py", line 188, in multi_gpu_test_net_on_dataset
    'detection', num_images, binary, output_dir, opts
  File "/....../Detectron/lib/utils/subprocess.py", line 95, in process_in_parallel
    log_subprocess_output(i, p, output_dir, tag, start, end)
  File "/......./Detectron/lib/utils/subprocess.py", line 133, in log_subprocess_output
    assert ret == 0, 'Range subprocess failed (exit code: {})'.format(ret)
AssertionError: Range subprocess failed (exit code: -6)
