### ISSUE TITLE
it get aborted when running test_spatial_narrow_as_op.py 

### ISSUE THREAD

**Issue by universewill** [facebookresearch/Detectron#544]
i run 'python3 detectron/tests/test_spatial_narrow_as_op.py' command after install densePose.
And it get aborted.
The same error happens with test_zero_even_op.py.
Notice that i use python3 to install detectron.

The log:
```
net_drawer will not run correctly. Please install the correct dependencies.
E0706 19:22:05.272351  7774 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0706 19:22:05.272370  7774 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0706 19:22:05.272377  7774 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
Found Detectron ops lib: /usr/local/lib/libcaffe2_detectron_ops_gpu.so
*** Aborted at 1530876125 (unix time) try "date -d @1530876125" if you are using GNU date ***
PC: @     0x7f2ff6f2ae10 (unknown)
```

**Comment by gadcam** [comment]
> net_drawer will not run correctly. Please install the correct dependencies.

Looks like you did not install all the dependencies of Caffe2/PyTorch. So you could double-check something like this https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile#install-dependencies

> Notice that i use python3 to install detectron.

See also #85 & #110
