### ISSUE TITLE
How to train only one class

### ISSUE THREAD

**Issue by wytcsuch** [facebookresearch/Detectron#547]
My dataset contains 10 categories,  I just want to train one category of them, eg ship. but it is difficult for me to separate ship samples  from dataset. What should I do?

**Comment by ir413** [comment]
Hi @wytcsuch, you could modify the [`roidb construction`](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/json_dataset.py#L82) to perform the desired filtering of ground truth annotations. However, it may be easier and less error-prone to preprocess your json annotations.

**Comment by gittigxuy** [comment]
@wytcsuch @ir413 ,could you please illustrate detailly?how to preprocess  json annotations?

**Comment by ir413** [comment]
Hi @gittigxuy, here is a draft of a function that you may find useful for filtering the json annotations:
```
def filter_json_anns(json_file, out_file, cat_id):
    """Filters out the anns that are not of cat_id class."""

    # Load the data from the json file
    with open(json_file, 'r') as f:
        dataset_obj = json.load(f)

    # Filter out the annotations
    filtered_anns = []
    img_ids_to_keep = set()
    for ann in dataset_obj['annotations']:
        if ann['category_id'] == cat_id:
            filtered_anns.append(ann)
            img_ids_to_keep.add(ann['image_id'])

    # Filter out the images
    filtered_imgs = []
    for img in dataset_obj['images']:
        if img['id'] in img_ids_to_keep:
            filtered_imgs.add(img)

    # Filter out the categories
    filtered_cats = []
    for cat in dataset_obj['categories']:
        if cat['id'] == cat_id:
            filtered_cats.append(cat)

    # Construct a coco-style dataset object
    filtered_dataset_obj = {
        'annotations': filtered_anns,
        'images': filtered_imgs,
        'categories': filtered_cats
    }

    # Save the filtered data
    with open(out_file, 'w') as f:
        json.dump(filtered_dataset_obj, f)
```
Please note that I have not tested the function so may need to modify it slightly to get it to run.
