### ISSUE TITLE
run python2 $DETECTRON/tests/test_spatial_narrow_as_op.py error: #346

### ISSUE THREAD

**Issue by BanuSelinTosun** [facebookresearch/Detectron#549]
I had the same exact issue as in this post. 
https://github.com/facebookresearch/Detectron/issues/346

I changed the PYTHON PATH and then I started getting the TypeError as unexpected keywork argument "file" and my caffe2 test is not printing out 1 anymore either. Prior to the path change it was printing 1 for this code: 
python -c 'from caffe2.python import workspace; print(workspace.NumCudaDevices())'

After going back and forth with python path and checking the caffe2 installation. Now the above installation is printing 1 (as it should) and my path is fine. And the new error when I run the test_spatial_narrow_as_op.py, I am getting this error. 

![image](https://user-images.githubusercontent.com/27472189/42402578-8c5e8b66-8130-11e8-899d-d840c53a720b.png)

system: ubuntu16.04
gcc: 5.4.0
cudnn version: 9.0.176

Thank you,
Selin

**Comment by gadcam** [comment]
Seems to be the same as https://github.com/facebookresearch/DensePose/issues/57.

I read there
> this error might happen when you've got several versions of Caffe2 installed on your system

is it your case ?

**Comment by gadcam** [comment]
> Now different problems are happening.

Then this issue can be closed.

**Comment by BanuSelinTosun** [comment]
@gadcam I think you have seen my other post. Thank you for your reply.

**Comment by ir413** [comment]
Closing as the original issue seems resolved, please reopen if that is not the case.

**Comment by BanuSelinTosun** [comment]
@gadcam @ir413 

The issue is not resolved. The problem just shifted to another issue which is not resolved and still pending.
