### ISSUE TITLE
What does mask r-cnn's AP, AP50, AP70 mean?

### ISSUE THREAD

**Issue by bughunter99** [facebookresearch/Detectron#55]
Hi.

I'm novice on r-cnn.There are term AP, AP50, AP75 on mask r-cnn paper. 50, 75 is small postfix, but I can't make it small, sorry. Anyway the paper says it is averaged over IOU thresholds. For AP50, only candidates over 50% region comparing ground truth are counted, and for AP75 only candidate over 75% are counted. Then what is empty AP? I knew AP use 70% IoU threshold, but it wouldn't. Because just AP is lower then AP75.

And additionally, there are another terms I don't understand well. They are APs, m, L. I know they mean small, medium, large. Then is there any criteria how big they are. Just saying small, medium, large makes me little bit confused.

Thanks in advance!

**Comment by ppwwyyxx** [comment]
See coco home page: http://cocodataset.org/#detections-eval

**Comment by xQsM3** [comment]
which confidence score is used for AP computation? I cannot find it at the coco home page you posted here. thanks for help
