### ISSUE TITLE
what does the yaml name mean? 

### ISSUE THREAD

**Issue by JaosonMa** [facebookresearch/Detectron#550]
e.g:
e2e_mask_rcnn_R-101-FPN_2x_gn.yaml
mask_rcnn_R-101-FPN_2x_gn.yaml
sctatch_e2e_mask_rcnn_R-101-FPN_2x_gn.yaml
what does it mean?
就是名称怎么解析？
组合规则，关键字的意思怎么理解？

**Comment by JaosonMa** [comment]
alse   what does  gn  mean?

**Comment by gadcam** [comment]
@JaosonMa Please see the [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) to understand the 
GN means Group Normalization see https://github.com/facebookresearch/Detectron/tree/master/projects/GN

**Comment by JaosonMa** [comment]
@gadcam 
![image](https://user-images.githubusercontent.com/23551774/42445898-19d92474-83a7-11e8-811e-66a86d3a74cd.png)
here is the config
e2e_mask_rcnn_R-101-FPN_2x_gn.yaml
______________________________________________________
MODEL:
  TYPE: generalized_rcnn
  CONV_BODY: FPN.add_fpn_ResNet101_conv5_body
  NUM_CLASSES: 2
  FASTER_RCNN: True
  MASK_ON: True
NUM_GPUS: 4
SOLVER:
  WEIGHT_DECAY: 0.0001
  LR_POLICY: steps_with_decay
  BASE_LR: 0.01
  GAMMA: 0.1
  MAX_ITER: 180000
  STEPS: [0, 120000, 160000]
FPN:
  FPN_ON: True
  MULTILEVEL_ROIS: True
  MULTILEVEL_RPN: True
  USE_GN: True  # Note: use GN on the FPN-specific layers
RESNETS:
  STRIDE_1X1: False  # default True for MSRA; False for C2 or Torch models
  TRANS_FUNC: bottleneck_gn_transformation  # Note: this is a GN bottleneck transform
  STEM_FUNC: basic_gn_stem  # Note: this is a GN stem
  SHORTCUT_FUNC: basic_gn_shortcut  # Note: this is a GN shortcut
FAST_RCNN:
  ROI_BOX_HEAD: fast_rcnn_heads.add_roi_Xconv1fc_gn_head  # Note: this is a Conv GN head
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 7
  ROI_XFORM_SAMPLING_RATIO: 2
MRCNN:
  ROI_MASK_HEAD: mask_rcnn_heads.mask_rcnn_fcn_head_v1up4convs_gn  # Note: this is a GN mask head
  RESOLUTION: 28  # (output mask resolution) default 14
  ROI_XFORM_METHOD: RoIAlign
  ROI_XFORM_RESOLUTION: 14  # default 7
  ROI_XFORM_SAMPLING_RATIO: 2  # default 0
  DILATION: 1  # default 2
  CONV_INIT: MSRAFill  # default GaussianFill
TRAIN:
  WEIGHTS: pre_weights/R-101-GN.pkl  # Note: a GN pre-trained model
  DATASETS: ('lkk_20180709_train',)
  SCALES: (800,)
  MAX_SIZE: 1333
  BATCH_SIZE_PER_IM: 512
  RPN_PRE_NMS_TOP_N: 2000  # Per FPN level
TEST:
  DATASETS: ('lkk_20180709_val',)
  SCALE: 800
  MAX_SIZE: 1333
  NMS: 0.5
  RPN_PRE_NMS_TOP_N: 1000  # Per FPN level
  RPN_POST_NMS_TOP_N: 1000
OUTPUT_DIR: output_pkl
_____________________________________________________
RuntimeError: [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /home/jansonm/caffe2/pytorch/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/fpn_inner_res2_2_sum" input: "gpu_0/fpn_res2_2_sum_w" output: "gpu_0/fpn_res2_2_sum" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "stride" i: 1 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "dilation" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"

##########################################
how can i fix this?
which param shoul i to low?

**Comment by JaosonMa** [comment]
@gadcam i can not find the batch_size? where can i change the batch_size? 
help me @gadcam  best wishes to you

**Comment by gadcam** [comment]
@JaosonMa The batch size is defined here
https://github.com/facebookresearch/Detectron/blob/b2d24147a9c614e04389b0b7dcbbf00fedc45e8d/detectron/core/config.py#L91-L93
so you can change it with the config file.

<code>out of memory</code> I do not know more and I think we do not have enough information to answer.
I would suggest you open a new issue (after closing this one) following the template and describing a bit more what you are trying to achieve.

**Comment by ir413** [comment]
Closing since the original question seems answered.

**Comment by rudy-letote** [comment]
> @JaosonMa Please see the [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) to understand the names.
> GN means Group Normalization see https://github.com/facebookresearch/Detectron/tree/master/projects/GN

thanks very much ,it is very useful for me . i am worrying about these yaml .

**Comment by rudy-letote** [comment]
@gadcam 
thanks very much ,it is very useful for me . i am worrying about these yaml .

**Comment by rudy-letote** [comment]
> @JaosonMa Please see the [Model Zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) to understand the names.
> GN means Group Normalization see https://github.com/facebookresearch/Detectron/tree/master/projects/GN

@gadcam 
thanks very much ,it is very useful for me . i am worrying about these yaml .
