### ISSUE TITLE
How to use the specified GPUS?

### ISSUE THREAD

**Issue by JaosonMa** [facebookresearch/Detectron#551]
How to use the specified GPUS?
there are 8 gpus in our computer,but i can only use the last 4 gpus, id : 4,5,6,7 
how can i limit them?

公司电脑有八块GPU，但是只有四块是属于我的，我该怎么限定使用后四个GPU？

**Comment by lilichu** [comment]
if you use 1 GPU , you can choose gpu such as:  
CUDA_VISIBLE_DEVICES=4
if you use more gpus, you can choose gpus such as:
CUDA_VISIBLE_DEVICES=4,5,6,7

**Comment by JaosonMa** [comment]
@lilichu I see the cmd, and more, where should i add this cmd? 

put in here?
我应该把这句命令ti添加在哪里？ yaml的配置中，还是训练时候？

**Comment by lilichu** [comment]
添加在Python命令之前。
如果你同时使用4块gpu，如`CUDA_VISIBLE_DEVICES=4,5,6,7`， 那么yaml文件中对应修改`NUM_GPUS: 4`
如果使用1块gpu， 如`CUDA_VISIBLE_DEVICES=4`， 那么yaml文件中对应修改`NUM_GPUS: 1`

**Comment by JaosonMa** [comment]
@lilichu i tried,but the result is not good,
![image](https://user-images.githubusercontent.com/23551774/42436719-896e21b4-838d-11e8-9d88-37f5b23e07b6.png)
我在python2 训练 命令前添加了，但是好像不起作用，
而且 八块显卡都有占用情况，虽然第一块使用量最大？
这是什么原因

**Comment by lilichu** [comment]
`CUDA_VISIBLE_DEVICES=4`与python语句是同一行的。
你这样应该还是没选择gpu，默认还是使用的0号gpu。

**Comment by JaosonMa** [comment]
@lilichu 
![image](https://user-images.githubusercontent.com/23551774/42437396-97ad91ea-838f-11e8-89c5-4654e66ec139.png)

![image](https://user-images.githubusercontent.com/23551774/42437377-899ef6a2-838f-11e8-8503-b7a5b277a482.png)
it works!
thank  you very much!!!
