### ISSUE TITLE
Using plt show to show the results after the inferences are made

### ISSUE THREAD

**Issue by stanleycelestin1** [facebookresearch/Detectron#553]
I tried to edit the vis_image function that is used in tools/infer_simple by doing changing:

this
```
    output_name = os.path.basename(im_name) + '.' + ext
    fig.savefig(os.path.join(output_dir, '{}'.format(output_name)), dpi=dpi)
    plt.close('all')
```
to this:
```
    plt.pause(0.2)
    plt.draw()
    plt.close('all')
```
It doesn't seem to be showing the figure. Anyone know what can be causing this issue?

**Comment by ir413** [comment]
Hi @stanleycelestin1, this doesn't seem like a detectron issue but I think you may need to call [`plt.show`](https://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.show) to display the figure.
