### ISSUE TITLE
runtime error RuntimeError: [enforce fail at context_gpu.cu:343] error == cudaSuccess. # Making Inference using pretrained model in Detectron

### ISSUE THREAD

**Issue by Rahul-Venugopal** [facebookresearch/Detectron#554]
I followed all the steps for **Installing detectron** following this link : **https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md**

Running the following command is giving result as mentioned in page
`python2 $DETECTRON/detectron/tests/test_spatial_narrow_as_op.py` 
Thus I conclude all dependencies were installed correctly

But when I try to run the following command to run object masking on the demo images:

```
python tools/infer_simple.py \
--cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
--output-dir demo/output \
--image-ext jpg \
--wts \
https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
demo


```
Following Error is showing after completion of 100%

**ERROR :** 

WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  59: Loading weights from: /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000128834 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000113216 secs
[I net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.7989e-05 secs
INFO infer_simple.py: 133: Processing demo/15673749081_767a7fa63a_k.jpg -> /tmp/detectron-visualizations/15673749081_767a7fa63a_k.jpg.pdf
[I net_async_base.cc:435] Using specified CPU pool size: 4; NUMA node id: -1
[I net_async_base.cc:440] Created new CPU pool, size: 4; NUMA node id: -1
[E net_async_base.cc:368] [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /home/rahul/pytorch/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/res3_0_branch1" input: "gpu_0/res3_0_branch1_bn_s" input: "gpu_0/res3_0_branch1_bn_b" output: "gpu_0/res3_0_branch1_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 },  op AffineChannel
[E net_async_base.cc:368] [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /home/rahul/pytorch/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/res3_0_branch2c" input: "gpu_0/res3_0_branch2c_bn_s" input: "gpu_0/res3_0_branch2c_bn_b" output: "gpu_0/res3_0_branch2c_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 },  op AffineChannel
WARNING workspace.py: 185: Original python traceback for operator `44` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 171, in <module>
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 121, in main
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/core/test_engine.py", line 328, in initialize_model_from_cfg
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/model_builder.py", line 229, in build_generic_detection_model
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/optimizer.py", line 54, in build_data_parallel_model
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/model_builder.py", line 169, in _single_gpu_build_func
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/FPN.py", line 63, in add_fpn_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/FPN.py", line 104, in add_fpn_onto_conv_body
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/ResNet.py", line 48, in add_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/ResNet.py", line 107, in add_ResNet_convX_body
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/ResNet.py", line 85, in add_stage
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/ResNet.py", line 183, in add_residual_block
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/ResNet.py", line 331, in bottleneck_transformation
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/detector.py", line 410, in ConvAffine
WARNING workspace.py: 190:   File "/home/rahul/detectron_util/detectron/detectron/modeling/detector.py", line 105, in AffineChannel
Traceback (most recent call last):
  File "tools/infer_simple.py", line 171, in <module>
    main(args)
  File "tools/infer_simple.py", line 139, in main
    model, im, None, timers=timers
  File "/home/rahul/detectron_util/detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/rahul/detectron_util/detectron/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/usr/local/lib/python2.7/dist-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.cu:343] error == cudaSuccess. 2 vs 0. Error at: /home/rahul/pytorch/caffe2/core/context_gpu.cu:343: out of memory Error from operator: 
input: "gpu_0/res3_0_branch1" input: "gpu_0/res3_0_branch1_bn_s" input: "gpu_0/res3_0_branch1_bn_b" output: "gpu_0/res3_0_branch1_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 }

**The command that you ran**
```
python tools/infer_simple.py \
--cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
--output-dir demo/output \
--image-ext jpg \
--wts \
https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
demo

### System information

* Operating system: Ubuntu 16.04 LTS
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by gadcam** [comment]
> * GPU models (for all devices if they are not all the same):

Can you provide this information ?

> out of memory 

One track to explore is if there is enough memory on your GPU.

**Comment by Rahul-Venugopal** [comment]
@gadcam  Thanks for replying.
I am sorry , that I did not understand exactly what you asked.

1)
rahul@rahul-ThinkPad-E470:~$ `nvcc --version`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85

2)`nvidia-smi`
Wed Jul 11 18:03:15 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.26                 Driver Version: 396.26                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce 940MX       Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P5    N/A /  N/A |    505MiB /  2004MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1061      G   /usr/lib/xorg/Xorg                           223MiB |
|    0      3403      G   compiz                                       183MiB |
|    0      3780      G   ...-token=20735AA88F73807AB58742E3D2371FE0    29MiB |
|    0     29321      G   ...-token=98FFD7A502BEFD955214BD03DDFA2B04    66MiB |
+-----------------------------------------------------------------------------+


Please let me know if I can provide any specific information

Thanks

**Comment by gadcam** [comment]
>| 0 GeForce 940MX Off | 00000000:01:00.0 Off | N/A |
>| N/A 38C P5 N/A / N/A | 505MiB / 2004MiB | 0% Default |

You do not have enough RAM on your card to run inference.
See #21

**Comment by Rahul-Venugopal** [comment]
Thanks  @gadcam  for  replying.  
I have an 8 GB RAM on my machine and is there any way to run inference ?

**Comment by ir413** [comment]
Increasing the number of GPUs will not reduce the test time memory requirements (see also #451 for discussion on how multi-gpu inference is performed in detectron).

**Comment by khorshidisamira** [comment]
Running this command :python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo  
I'm getting the same error:
Found Detectron ops lib: /home/samira/anaconda2/lib/libcaffe2_detectron_ops_gpu.soE0718 00:54:42.856298 15289 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.E0718 00:54:42.856317 15289 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.E0718 00:54:42.856320 15289 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  59: Loading weights from: /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl
I0718 00:54:46.429167 15289 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000182457 secs
I0718 00:54:46.429527 15289 net_dag.cc:46] Number of parallel execution chains 63 Number of operators = 402
I0718 00:54:46.442142 15289 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 0.000185008 secs
I0718 00:54:46.442507 15289 net_dag.cc:46] Number of parallel execution chains 30 Number of operators = 358
I0718 00:54:46.443876 15289 net_dag_utils.cc:102] Operator graph pruning prior to chain compute took: 1.1465e-05 secs
I0718 00:54:46.443929 15289 net_dag.cc:46] Number of parallel execution chains 5 Number of operators = 18
INFO infer_simple.py: 133: Processing demo/19064748793_bb942deea1_k.jpg -> /tmp/detectron-visualizations/19064748793_bb942deea1_k.jpg.pdf
E0718 00:54:47.287029 15300 net_dag.cc:195] Exception from operator chain starting at '' (type 'Sum'): caffe2::EnforceNotMet: [enforce fail at context_gpu.cu:336] error == cudaSuccess. 2 vs 0. Error at: /var/lib/jenkins/conda-bld/caffe2-cuda9.0-cudnn7_1526317478991/work/caffe2/core/context_gpu.cu:336: out of memory Error from operator: 
input: "gpu_0/res4_4_branch2c" input: "gpu_0/res4_4_branch2c_bn_s" input: "gpu_0/res4_4_branch2c_bn_b" output: "gpu_0/res4_4_branch2c_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 }
WARNING workspace.py: 185: Original python traceback for operator `128` in network `generalized_rcnn` in exception above (most recent call last):
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 171, in <module>
WARNING workspace.py: 190:   File "tools/infer_simple.py", line 121, in main
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/core/test_engine.py", line 328, in initialize_model_from_cfg
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/model_builder.py", line 124, in create
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/model_builder.py", line 89, in generalized_rcnn
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/model_builder.py", line 229, in build_generic_detection_model
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/optimizer.py", line 54, in build_data_parallel_model
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/model_builder.py", line 169, in _single_gpu_build_func
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/FPN.py", line 63, in add_fpn_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/FPN.py", line 104, in add_fpn_onto_conv_body
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/ResNet.py", line 48, in add_ResNet101_conv5_body
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/ResNet.py", line 112, in add_ResNet_convX_body
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/ResNet.py", line 85, in add_stage
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/ResNet.py", line 183, in add_residual_block
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/ResNet.py", line 331, in bottleneck_transformation
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/detector.py", line 410, in ConvAffine
WARNING workspace.py: 190:   File "/home/samira/detectron/detectron/modeling/detector.py", line 105, in AffineChannel
Traceback (most recent call last):
  File "tools/infer_simple.py", line 171, in <module>
    main(args)
  File "tools/infer_simple.py", line 139, in main
    model, im, None, timers=timers
  File "/home/samira/detectron/detectron/core/test.py", line 66, in im_detect_all
    model, im, cfg.TEST.SCALE, cfg.TEST.MAX_SIZE, boxes=box_proposals
  File "/home/samira/detectron/detectron/core/test.py", line 158, in im_detect_bbox
    workspace.RunNet(model.net.Proto().name)
  File "/home/samira/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 217, in RunNet
    StringifyNetName(name), num_iter, allow_fail,
  File "/home/samira/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 178, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at context_gpu.cu:336] error == cudaSuccess. 2 vs 0. Error at: /var/lib/jenkins/conda-bld/caffe2-cuda9.0-cudnn7_1526317478991/work/caffe2/core/context_gpu.cu:336: out of memory Error from operator: 
input: "gpu_0/res4_4_branch2c" input: "gpu_0/res4_4_branch2c_bn_s" input: "gpu_0/res4_4_branch2c_bn_b" output: "gpu_0/res4_4_branch2c_bn" name: "" type: "AffineChannel" device_option { device_type: 1 cuda_gpu_id: 0 }

My OS is Ubuntu 16.04
Cuda 9.0

~/detectron$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
~/detectron$ nvidia-smi 
Wed Jul 18 00:56:48 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 384.81                 Driver Version: 384.81                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M520         Off  | 00000000:02:00.0 Off |                  N/A |
| N/A   41C    P0    N/A /  N/A |      0MiB /  2002MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
Please help!

**Comment by gadcam** [comment]
@khorshidisamira 
> | 0 Quadro M520 Off | 00000000:02:00.0 Off | N/A |
> | N/A 41C P0 N/A / N/A | 0MiB / 2002MiB | 0% Default |

Same problem, same answer : see https://github.com/facebookresearch/Detectron/issues/554#issuecomment-404325917

**Comment by Rahul-Venugopal** [comment]
@gadcam  

I had used another machine with following configuration : 


Tue Jul 24 18:54:33 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.37                 Driver Version: 396.37                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro M2000M       Off  | 00000000:01:00.0  On |                  N/A |
| N/A   43C    P8    N/A /  N/A |    526MiB /  4043MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1184      G   /usr/lib/xorg/Xorg                           273MiB |
|    0      3116      G   compiz                                       209MiB |
|    0     10277      G   ...-token=6EF19F8877D2BB96CD1766BF0F9F51F5    39MiB |
+-----------------------------------------------------------------------------+


**In this machine the inference runs sometime and sometimes it does not.**

Can you please help me to know , **how much minimum RAM on the card is recommended to run the inference ?**

Also the RAM we are talking about is the with the graphics card right ? Or are you mentioning the system RAM .

Sometimes I get 
### error 

Found Detectron ops lib: /home/samira/anaconda2/lib/libcaffe2_detectron_ops_gpu.soE0718 00:54:42.856298 15289 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.E0718 00:54:42.856317 15289 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.E0718 00:54:42.856320 15289 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py: 25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py: 59: Loading weights from: /tmp/detectron-download-cache/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl


### Is there anything I have to do in relation with cuda to run inference without any issues ?


Thanks in advance.

**Comment by gadcam** [comment]
@Rahul-Venugopal As noted in #21 4GB is not enough (most of the time at least).
The RAM you need depend on what model you want to run and of your input.
Sorry for not being that accurate but I do not know more.
