### ISSUE TITLE
docker build problem

### ISSUE THREAD

**Issue by hxtkyne** [facebookresearch/Detectron#569]
Hi all,
So when docker build -t detectron:c2-cuda9-cudnn7 is executed, step 1 is run without a problem, but in step 2/13, there is problem which is 
"mv: cannot move '/usr/local/caffe2' to a subdirectory of itself, '/usr/local/caffe2_build'
The command '/bin/sh -c mv /usr/local/caffe2 /usr/local/caffe2_build' returned a non-zero code: 1"

Thanks in advance for any assistance or comments anyone might be able to offer!

**Comment by ir413** [comment]
Hi @hxtkyne, please provide the full output of building the original docker file as well as other info requested in the issue template. Also, when building the docker image please use the `--no-cache` flag as from #570 it seems that you have been building different variations of the docker file using the same name (build command: `docker build --no-cache -t detectron:c2-cuda9-cudnn7 .`).

**Comment by hxtkyne** [comment]
Hi @ir413 , I have solved the problem by using cp command instead of mv command when build, that means, "cp /usr/local/caffe2 /usr/local/caffe2_build", however, I still don't know why. Thank you for your reply.

**Comment by ir413** [comment]
Thanks for the update @hxtkyne.
