### ISSUE TITLE
Improve inference time

### ISSUE THREAD

**Issue by antocapp** [facebookresearch/Detectron#576]
Hello,
is there a way to improve inference time? 
I noticed this is done in training but not in inference. 

If you have news about this please let me know.
Thanks

**Comment by ir413** [comment]
Hi @antocapp, could you please clarify what do you mean by "this is done in training but not in inference"?

**Comment by antocapp** [comment]
I refer to [this comment](https://github.com/facebookresearch/Detectron/issues/21#issuecomment-360169723) made by **rbgirshick**

**Comment by ir413** [comment]
Thanks for clarifying @antocapp. Closing to consolidate the discussion about this in #21.
