### ISSUE TITLE
Calculate AP only on specific classes

### ISSUE THREAD

**Issue by johannathiemich** [facebookresearch/Detectron#577]
Hello, 
I would like to know if there is a way to calculate the APs and ARs specifically for some classes of MS COCO. I already found the get_coco_dataset() function in the dummy_datasets.py script.
I would just change that array of strings to one that only contains the classes that I am interested in.
Afterwards I would count the remaining classes and put them into the configuration file.
Does that seem like a valid approach? Will the calculated AP and AR be correct?

Thanks in advance!

**Comment by ir413** [comment]
Hi @johannathiemich, per-category AP @ IoU=[0.50,0.95] is already computed and logged during evaluation (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/json_dataset_evaluator.py#L224-L231)). Computation of per-category AP and AR at different IoU thresholds can be implemented analogously.
