### ISSUE TITLE
I want to detect small objects by faster rcnn,  what parameters can I modify?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#579]
hi!
I want to detect traffic lights, which are very small objects.  The side lengths are about 5-40 pixels, and most is under 20 pixels. 
I try to change anchor size from:
`RPN_ANCHOR_START_SIZE: 32`
to:
`RPN_ANCHOR_START_SIZE: 8`
However, the result doesn't improve. I am so confuse, as I understand, the default anchor size 32-512(RPN2-6) is large, so when I change it to 8~128(RPN2-6), the result should be improve.  whether other parameters should be modify when I change the `RPN_ANCHOR_START_SIZE `?
Besides, whether other methods(based on faster_rcnn-FPN) can I use to detect the small objects? 
thanks!

**Comment by sidnav** [comment]
Hi @lilichu did you find the answer for this? Could you post it here?
