### ISSUE TITLE
License Incomplete

### ISSUE THREAD

**Issue by rkpasia** [facebookresearch/Detectron#58]
I think that the Apache license need to be completed with your copyright information.

https://github.com/facebookresearch/Detectron/blob/829a394188a8991ae04f73fdb2d5830b957f000b/LICENSE#L178-L189

**Comment by rbgirshick** [comment]
@rkpasia: this part of the license provides instructions for how to place the individual files in the project under the license (i.e., put the copyright and license notice header at the top of each file).

For reference, here's what the corresponding file looks like in two projects under the Apache foundation (so we'll assume they are implementing the license file correctly):

https://svn.apache.org/viewvc/httpd/httpd/trunk/LICENSE?view=markup#l189
https://github.com/apache/spark/blob/master/LICENSE#L189
