### ISSUE TITLE
Is there data augmentation?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#580]
hi!
I want to rotate the images to augment the dataset when I use faster_rcnn-FPN to detect traffic lights.
is there such data augmentation? I only find horizontally-flipped in `config.py`:
```
# Use horizontally-flipped images during training?
__C.TRAIN.USE_FLIPPED = True
```

**Comment by ir413** [comment]
Hi @lilichu, detectron currently supports only scaling and horizontal flipping data augmentations for training. You can look into [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/minibatch.py#L89) function to add support for rotations.

**Comment by gru35** [comment]
Hi, I'm trying to implement 3 geometric transformations (rotation, shear and zoom) to augment my data during the training. I add the transformations [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/minibatch.py#L89) and more specifically [here](https://github.com/facebookresearch/Detectron/blob/8a4723835cb163c3c02d90593f2f4f4ef1f45f4b/detectron/utils/blob.py#L117) as you suggested but I am not sure where I need to add the transformation for the new ground truth box. 
I made some changes [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/rpn.py#L91) to transform the box to the new location but I am not sure if it's working correctly. 
Can you point me to the correct direction as to where I need to make the final changes?

P.S. Sorry to bump this old issue but I do not find it optimal to open a new one about the same question.
Thanks in advanced.
