### ISSUE TITLE
About SCALE and MAX_SIZE

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#584]
All images of my dataset is 720 * 1280 and 1280 * 720(height*weight), in yaml: 
```
  SCALES: (800,)
  MAX_SIZE: 1333
```
Does it mean the image will be resize as 800 * 1280 and 1280 * 800?

**Comment by ppwwyyxx** [comment]
No it will be resized to 750x1333. See https://github.com/facebookresearch/Detectron/blob/b5dcc0fe1d091cb70f9243939258215dd63e3dfa/detectron/utils/blob.py#L100-L125 for the implementation.

**Comment by chelixuan** [comment]
Hi!  The ratio of length to width of the picture in Ms COCO is different, if we re-scale the images that their shorter side is 800, we get the different ratio. In the end, the longer side of images is different. The size of the training images is different . But the input_image should be at the same size. How can I solve this problem? Thx~ @ppwwyyxx @
