### ISSUE TITLE
[Demo] Running error: utils/cython_nms.so: undefined symbol: PyFPE_jbuf

### ISSUE THREAD

**Issue by forestriveral** [facebookresearch/Detectron#589]
### Detailed steps to reproduce

to run detectron demo with Pretrained Models by following the instruction of `GETTING_STARTED.md`
https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md
The command that I ran:
```
python tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
```
### Actual results
Then I got the following error:
```
Traceback (most recent call last):
  File "tools/infer_simple.py", line 44, in <module>
    import detectron.core.test_engine as infer_engine
  File "/home/forestriveral/DeepLearning/Detectron/detectron/detectron/core/test_engine.py", line 35, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "/home/forestriveral/DeepLearning/Detectron/detectron/detectron/core/rpn_generator.py", line 42, in <module>
    from detectron.datasets import task_evaluation
  File "/home/forestriveral/DeepLearning/Detectron/detectron/detectron/datasets/task_evaluation.py", line 47, in <module>
    import detectron.datasets.json_dataset_evaluator as json_dataset_evaluator
  File "/home/forestriveral/DeepLearning/Detectron/detectron/detectron/datasets/json_dataset_evaluator.py", line 33, in <module>
    import detectron.utils.boxes as box_utils
  File "/home/forestriveral/DeepLearning/Detectron/detectron/detectron/utils/boxes.py", line 52, in <module>
    import detectron.utils.cython_nms as cython_nms
ImportError: /home/forestriveral/DeepLearning/Detectron/detectron/detectron/utils/cython_nms.so: undefined symbol: PyFPE_jbuf
```
Is there any solution ? 
If you know something about this, any suggestion will be helpful! Thanks!

### System information

* Operating system: Ubuntu 16.04
* Compiler version: GCC/G++ 5.4.0 cmake 3.11.4
* CUDA version: 9.0
* cuDNN version: 7.0.5
* NVIDIA driver version: 390.67
* GPU models (for all devices if they are not all the same): GTX1050
* `PYTHONPATH` environment variable: `/home/forestriveral/anaconda3/envs/detectron/bin/`
* `python --version` output: `Python 2.7.15 :: Anaconda, Inc.`
* Anything else that seems relevant:

**Comment by gadcam** [comment]
@forestriveral Try to (re)install cython in your Anaconda environment.

**Comment by forestriveral** [comment]
It seems to have nothing to do with the COCO API. I rebuild caffe2 and detectron in a new environment but still got the error. I think there may be some compatible problem but I don't know where exactly is it. Has nobody ever encountered some errors like this ?

**Comment by ir413** [comment]
Hi @forestriveral, I understand that this is unrelated to the COCO API but the issue with mixing of python version described above (in the context of the COCO API) may apply here and I think is worth checking.

**Comment by forestriveral** [comment]
@ir413 It is the conflicting python packages between system and anaconda env that cause this error. I removed `cython` and `numpy` packages that installed in system, and re-make `detectron` in anaconda env. Then the error is gone. Thanks for your help !

**Comment by mouad47** [comment]
Hi @forestriveral 
I'm having the same issue, but I'm using colab environment, would you explain a little bit how did you solved the problem ?
