### ISSUE TITLE
Image Resizing Question during Testing and Training

### ISSUE THREAD

**Issue by karanchahal** [facebookresearch/Detectron#591]
Hello,

This is not an implementation issue, and more of a theoretical question. I am confused as to how images are modified in training and testing.

The readme states 

> Training uses multi-scale jitter over scales {640, 672, 704, 736, 768, 800}
Row 1: test-time augmentations are multi-scale testing over {400, 500, 600, 700, 900, 1000, 1100, 1200} and horizontal flipping (on each scale

I don't understand what you mean by "multi scale jitter" and can you also tell me how the images are modified when they are inputted during inference time ?

Like for example if one has a small image, say a size of 80 by 80, resizing it to a 600 size scale would not be great.

I would be very grateful if these queries are resolved.

Thanks,
 Karanbir Chahal

**Comment by ir413** [comment]
Hi @karanchahal, during training each image in a minibatch is scaled using a randomly sampled scale from `TRAIN.SCALES` (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/minibatch.py#L89-L116)). At test time, for each image the predictions are computed at all scales specified by `TEST.SCALES` + `TEST.{task}_AUG.SCALES` (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/test.py#L232-L238)) and combined using one of the available heuristics.

**Comment by karanchahal** [comment]
Thank you so much !

**Comment by ash1995** [comment]
@ir413  Do a set of scales (1200,800,600,200) imply that the image (say 400 x 400) is scaled to 1200 x 1200, 800 x 800, 600 x 600, and 200 x 200 respectively?

**Comment by karanchahal** [comment]
You can think of scales as the surface area of a single anchor. So a 32
scale means an anchor of 32 by 32 shape. Multiplied by the aspect ratio
chosen.
