### ISSUE TITLE
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed

### ISSUE THREAD

**Issue by jaskarannagi19** [facebookresearch/Detectron#595]
Somebody help me in solving detectron I have search entire universe for this. Note caffe 2 is working fine and I am using anaconda environment thanks in advance
make ops
mkdir -p build && cd build && cmake .. && make -j8
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /home/jaskaran/.conda/envs/Pose/include, library: /home/jaskaran/.conda/envs/Pose/lib/libglog.so)
-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Caffe2: CUDA detected: 8.0
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 8.0
-- Found cuDNN: v6.0.21  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1 
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.5.1
--   CMake command        : /usr/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 5.4.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.2
--   Caffe2 include path  : /home/jaskaran/.conda/envs/Pose/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 8.0
--     CuDNN version      : 6.0.21
-- Configuring done
-- Generating done
-- Build files have been written to: /home/jaskaran/densepose/build
make[1]: Entering directory '/home/jaskaran/densepose/build'
make[2]: Entering directory '/home/jaskaran/densepose/build'
make[3]: Entering directory '/home/jaskaran/densepose/build'
make[3]: Entering directory '/home/jaskaran/densepose/build'
make[3]: Leaving directory '/home/jaskaran/densepose/build'
[ 12%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o
[ 25%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o
make[3]: Entering directory '/home/jaskaran/densepose/build'
[ 37%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o
[ 50%] Building CXX object CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o
In file included from /home/jaskaran/densepose/detectron/ops/pool_points_interp.h:13:0,
                 from /home/jaskaran/densepose/detectron/ops/pool_points_interp.cc:10:
/home/jaskaran/.conda/envs/Pose/include/caffe2/core/context.h:16:36: fatal error: ATen/core/ATenCoreTest.h: No such file or directory
compilation terminated.
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:86: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/pool_points_interp.cc.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/jaskaran/densepose/detectron/ops/zero_even_op.h:12:0,
                 from /home/jaskaran/densepose/detectron/ops/zero_even_op.cc:9:
/home/jaskaran/.conda/envs/Pose/include/caffe2/core/context.h:16:36: fatal error: ATen/core/ATenCoreTest.h: No such file or directory
compilation terminated.
CMakeFiles/caffe2_detectron_custom_ops.dir/build.make:62: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/detectron/ops/zero_even_op.cc.o] Error 1
make[3]: Leaving directory '/home/jaskaran/densepose/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
In file included from /home/jaskaran/.conda/envs/Pose/include/caffe2/core/context_gpu.h:9:0,
                 from /home/jaskaran/densepose/detectron/ops/pool_points_interp.cu:11:
/home/jaskaran/.conda/envs/Pose/include/caffe2/core/context.h:16:36: fatal error: ATen/core/ATenCoreTest.h: No such file or directory
compilation terminated.
CMake Error at caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o.cmake:219 (message):
  Error generating
  /home/jaskaran/densepose/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:63: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_pool_points_interp.cu.o] Error 1
make[3]: *** Waiting for unfinished jobs....
In file included from /home/jaskaran/.conda/envs/Pose/include/caffe2/core/context_gpu.h:9:0,
                 from /home/jaskaran/densepose/detectron/ops/zero_even_op.cu:9:
/home/jaskaran/.conda/envs/Pose/include/caffe2/core/context.h:16:36: fatal error: ATen/core/ATenCoreTest.h: No such file or directory
compilation terminated.
CMake Error at caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o.cmake:219 (message):
  Error generating
  /home/jaskaran/densepose/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:70: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o' failed
make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o] Error 1
make[3]: Leaving directory '/home/jaskaran/densepose/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/jaskaran/densepose/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/jaskaran/densepose/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2

**Comment by jaskarannagi19** [comment]
I was able to solve it by building atgen in pytorch and copying the build files to conda caafe2 environment 
Just in case anyone needs this
Thanks

**Comment by bmabir17** [comment]
@jaskarannagi19 can you please give some instruction on how to rebuild atgen in pytorch and what other steps you took to solve this error? i am facing the same problems

**Comment by jaskarannagi19** [comment]
@bmabir17 if your are using ubuntu. Then activate your environment if in anaconda go to pytorch directory and navigate to atgen use make command to build. You will find a build folder in your atgen folder copy that folder to your location where it is trying to find.

**Comment by bmabir17** [comment]
there is seems to be no atgen directory in pytorch , but there is aten directory present. Should i execute build command there? are both the same library?

**Comment by jaskarannagi19** [comment]
@bmabir17 make search for it. Its somewhere there let me check where it found it

**Comment by jaskarannagi19** [comment]
@bmabir17 its inside aten and inside caffe2

**Comment by Computational-Camera** [comment]
I came across same problem. If you are using Anaconda2, you can fix it by move all the files from Anaconda2/include/ATen/core/core to Anaconda2/include/ATen/core/
