### ISSUE TITLE
how to see the segmentation data in the segmentations_val_results.json?

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#597]
hi!
I use mask rcnn to detect object. the val results is saved in `bbox_sign_val_results.json` and `segmentations_sign_val_results.json`. 
however, I find the segmentations data in `segmentations_sign_val_results.json` is such:
```
    {
        "image_id": 1, 
        "segmentation": {
            "counts": "R[W<=Sf0001O000000000000000000000000000000000000000^_\\?", 
            "size": [
                720, 
                1280
            ]
        }, 
        "category_id": 1, 
        "score": 0.992115
    }, 
```
what is `"counts": "R[W<=Sf0001O000000000000000000000000000000000000000^_\\?"`? How to see the segmentations data?
I want to get the data such as:
```
            "segmentation": [
                [
                    662.1764705882352, 
                    387, 
                    686, 
                    386.5882352941176, 
                    686, 
                    398, 
                    662.7647058823529, 
                    399
                ]
```

thanks!

**Comment by ppwwyyxx** [comment]
You can refer to coco documentation to understand its result format: http://cocodataset.org/#format-results

**Comment by lilichu** [comment]
@ppwwyyxx    thanks! but I don't find the detailed explanation. for example, how should I understand the results such as:
`"counts": "R[W<=Sf0001O000000000000000000000000000000000000000^_\\?"`
`"counts": "Qd]><Tf01O00000000000000000000000000000_]Z="`
thanks!
