### ISSUE TITLE
 Dose this system can support pascal voc format in faster rcnn?

### ISSUE THREAD

**Issue by JohnnyGambler** [facebookresearch/Detectron#6]
I have try pascal voc data in lib/datasets/data/ , it can't work

**Comment by zhangxiaoqiang7** [comment]
@JohnnyGambler Maybe you can convert the pascal voc format to the COCO API json format according to FAQ.md. I have tried doing it with cocoapi and it works.

**Comment by rbgirshick** [comment]
@JohnnyGambler: please use the PASCAL VOC annotations that have been converted to the COCO API json format. They are available for download https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip via http://cocodataset.org/#external. We'll update the dataset installation instructions with this information.

**Comment by ir413** [comment]
Hi @JohnnyGambler, Detectron supports the PASCAL VOC dataset. However, as @zhangxiaoqiang7 suggests, we expect PASCAL VOC annotations in COCO json format (which are available at http://cocodataset.org/#external). We will update the `data/README.md`, to clarify the expected `lib/datasets/data` directory structure and content for PASCAL VOC. Thanks @zhangxiaoqiang7 for helping out!

**Comment by soumenms2015** [comment]
@rbgirshick @ir413 : How can the my own dataset which are in VOC format be used?

**Comment by jwnsu** [comment]
It's very small effort to produce a python conversion script (~100 lines of codes).

**Comment by ir413** [comment]
Please see 286b9f4 for the updated dataset installation instructions.

**Comment by truetqy** [comment]
You can use cocoapi/MatlabAPI(https://github.com/cocodataset/cocoapi/), CocoUtils.convertPascalGt( dataDir, year, split, annFile ) to convert any Pascal VOC annotations to COCO json format.

**Comment by panovr** [comment]
@jwnsu May you share the conversion script?
Thanks!

**Comment by zhangtao22** [comment]
@zhangxiaoqiang7 我的cocountils不工作啊，你的PASreadrecord用的哪个，我在github上找的一个人的VOCxml2struct解析有问题，能把你工作的代码给我一份嘛？我邮箱5927484@qq.com，谢谢

**Comment by TWDH** [comment]
> @JohnnyGambler: please use the PASCAL VOC annotations that have been converted to the COCO API json format. They are available for download https://storage.googleapis.com/coco-dataset/external/PASCAL_VOC.zip via http://cocodataset.org/#external. We'll update the dataset installation instructions with this information.

Hi, the link to have pascal voc dataset in COCO format is not available right now, is there any alternative website we can use? (Access denied)
