### ISSUE TITLE
How to get the bounding box of the head

### ISSUE THREAD

**Issue by costef** [facebookresearch/Detectron#601]
Hi everybody
first of all, thanks for your awesome project.
I'm currently using infer_simple.py and getting the expected results.
How can I get the bounding box of the heads ?
Could you please answer ? hopefully with a piece of python code.
Thanks a lot

**Comment by ir413** [comment]
Hi @costef, detectron does not provide models that predict head bounding boxes at this time.  If you have an appropriately labeled dataset, you should be able to use detectron to train a detector for that task. You might also be able to get a rough approximation of person head bounding boxes by using the available keypoint models and some heuristics.
