### ISSUE TITLE
an unexpected keyword argument 'out_when_no_box'

### ISSUE THREAD

**Issue by zhangjinjing3** [facebookresearch/Detectron#602]
I trained MaskRCNN model with my own dataset successfully. I have not changed any  parameters, but when I test my model ,I got this error, no result was saved.
![11](https://user-images.githubusercontent.com/22672283/43704014-0a27e4e8-9991-11e8-8fa2-30b45c7ca812.png)

**Comment by gadcam** [comment]
This argument was added in #400.
Could you check that your function <code>vis_one_image</code> in [/detectron/utils/vis.py](https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/vis.py) was updated accordingly ?

**Comment by zhangjinjing3** [comment]
Thanks, I checked my function vis_one_image, then I can run infer_sample successfully. However, I want to save my pictures in tmp/result_0806, but no picture was saved.
![1](https://user-images.githubusercontent.com/22672283/43873547-8a7c3732-9bb9-11e8-88aa-19a06ba85a90.png)
![222](https://user-images.githubusercontent.com/22672283/43873554-906db116-9bb9-11e8-980f-2e9a23be5752.png)

**Comment by zhangjinjing3** [comment]
@gadcam  Wish to get your help.

**Comment by ir413** [comment]
Hi @zhangjinjing3, closing since the original issue seems resolved (advice for debugging the new issue is given as well). Thanks @gadcam.
