### ISSUE TITLE
What is the difference between TEST.RPN_PRE_NMS_TOP_N and TEST.RPN_POST_NMS_TOP_N?

### ISSUE THREAD

**Issue by sidnav** [facebookresearch/Detectron#604]

**Comment by gadcam** [comment]
@sidnav You have a short explanation here https://github.com/facebookresearch/Detectron/blob/2362ea3b22af8264b4e9ffdef90c161bfab8246e/detectron/core/config.py#L160-L167

**Comment by sidnav** [comment]
How are the RPN scores for the proposals calculated during Inference time? the IoU method is not possible as we do not have GT during Inference. thank you @gadcam

**Comment by gadcam** [comment]
@sidnav Looks like you should find what you look for here 
https://github.com/facebookresearch/Detectron/blob/6a2b761c2f19fd3e66363fa1e31a090cca7ae177/detectron/ops/generate_proposals.py#L41-L57
