### ISSUE TITLE
how to build the docker image with cuda8/cudnn6

### ISSUE THREAD

**Issue by ddeeppnneett** [facebookresearch/Detectron#605]
I've built a detectron docker image using the Dockerfile(cuda9/cudnn7). But it doesnt work. The systems administrator told me I should build detectron with cuda8 and cudnn6. 

I couldnt find out any caffe2 docker image with cuda8/cudnn6. So I tried to build the caff2-cuda8-cudnn6 by this dockerfile https://github.com/pytorch/pytorch/tree/master/docker/caffe2/ubuntu-16.04-cuda8-cudnn6-all-options . But the "third_party" eigen could not be downloaded. 

Then I modified the dockerfile https://github.com/pytorch/pytorch/tree/master/docker/caffe2/ubuntu-16.04-cuda8-cudnn7-all-options from **cudnn7** to **cudnn6**. This time, I have built the caffe2 images without any error. 

But when I went to next step to build detectron image, I found there is no such folder /usr/local/caffe2, and I could not find the correct path. The command "RUN mv /usr/local/caffe2 /usr/local/caffe2_build" ended with an error.

**Comment by ddeeppnneett** [comment]
@ir413

**Comment by ddeeppnneett** [comment]
I found a caffe2_cuda8/cudnn6,  
` FROM caffe2ai/caffe2:c2v0.8.0.cuda8.cudnn6.ubuntu16.04`

However, I got this error message

> 
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> CMake Error at CMakeLists.txt:8 (find_package):
>   By not providing "FindCaffe2.cmake" in CMAKE_MODULE_PATH this project has asked CMake to find a package configuration file provided by "Caffe2", but CMake did not find one.
>   Could not find a package configuration file provided by "Caffe2" with any of the following names:
> 
>     Caffe2Config.cmake
>     caffe2-config.cmake
> 
>   Add the installation prefix of "Caffe2" to CMAKE_PREFIX_PATH or set
>   "Caffe2_DIR" to a directory containing one of the above files.  If "Caffe2"  provides a separate development package or SDK, be sure it has been installed.
> 
> -- Configuring incomplete, errors occurred!
> See also "/detectron/build/CMakeFiles/CMakeOutput.log".
> make: *** [ops] Error 1
> Makefile:13: recipe for target 'ops' failed
> The command '/bin/sh -c make ops' returned a non-zero code: 2
> 

I guess this docker image is too old.

**Comment by ir413** [comment]
Hi @ddeeppnneett - see facebookresearch/video-nonlocal-net#39 for discussion about the eigen third party error. The modified Caffe2 image you're trying to use likely has Caffe2 installed at a different location than the Caffe2 image detectron docker file expects. Please let me know if this is not resolved yet and I will look into the image you're trying to use and adapt the detectron docker file accordingly.

**Comment by ddeeppnneett** [comment]
@ir413 

Sorry for the late reply. I have been busy these days.

Thanks for your link, I have solved the third_party/eigen problem, when building caffe2 from the  dockerfile [https://github.com/pytorch/pytorch/tree/master/docker/caffe2/ubuntu-16.04-cuda8-cudnn6-all-options](https://github.com/pytorch/pytorch/tree/master/docker/caffe2/ubuntu-16.04-cuda8-cudnn6-all-options)  . The new error is about ATen

> Unable to checkout 'f3c627d517968c20e8269ead1d90cd3a6c199356' in submodule path 'third_party/aten'

According to [https://github.com/caffe2/caffe2/issues/2510](https://github.com/caffe2/caffe2/issues/2510)  and [https://github.com/facebookresearch/TensorComprehensions/issues/328](https://github.com/facebookresearch/TensorComprehensions/issues/328) , 

> "Temporary disabling ATen looks like the easiest solution"

I delete those three lines about aten in the gitmodules file. There is still a error about aten.  I couldnt figure out how to disable it.

Then, in the Dockerfile,  I replaced  
`RUN git clone --branch master --recursive https://github.com/caffe2/caffe2.git`
with 
`RUN git clone --branch master --recursive https://github.com/pytorch/pytorch.git `

This time I got no error about caffe2, but the error like last time, 

> Caffe2 installed at a different location than the Caffe2 image detectron docker file expects


So, right now, it is not possible to use old version of caffe2.git becasue of the aten problem. And it is not possible to use new version of  pytorch.git because of the different location of caffe2 folder. 

I hope you could help me  with the ATen in caffe2.git, or the caffe2 folder in pytorch.git.  If, by any chance, you know how to directly pull  caffe2:cuda8.0-cudnn6-ubuntu16.04  or detectron:cuda8.0-cudnn6-ubuntu16.04, that would be great.

**Comment by ddeeppnneett** [comment]
Replacing

RUN mv /usr/local/caffe2 /usr/local/caffe2_build
ENV Caffe2_DIR /usr/local/caffe2_build
ENV PYTHONPATH /usr/local/caffe2_build:${PYTHONPATH}
ENV LD_LIBRARY_PATH /usr/local/caffe2_build/lib:${LD_LIBRARY_PATH} 

with

ENV LD_LIBRARY_PATH /usr/local/lib:${LD_LIBRARY_PATH}
 
I could build the detectron without error.

**Comment by my-hello-world** [comment]
@ddeeppnneett @ir413 hello,maybe it can't install detectron with Caffe2 GPU build?
os:ubuntu 14.04
cuda 8.0 cudnn 7
python :2.7
conda env

please
