### ISSUE TITLE
Model Performance Terminology

### ISSUE THREAD

**Issue by SiDinhThoi** [facebookresearch/Detectron#610]
Hi, 

My question is what are accuracy_cls, eta, loss, ..., mem, and time ? I only understand what is iter. 

Anyone can explain these terms for me. Thank you very much

json_stats: {"accuracy_cls": 1.000000, "eta": "0:21:51", "iter": 55080, "loss": 0.024404, "loss_bbox": 0.000645, "loss_cls": 0.001896, "loss_mask": 0.020639, "loss_rpn_bbox_fpn2": 0.000000, "loss_rpn_bbox_fpn3": 0.000000, "loss_rpn_bbox_fpn4": 0.000000, "loss_rpn_bbox_fpn5": 0.000142, "loss_rpn_bbox_fpn6": 0.000000, "loss_rpn_cls_fpn2": 0.000000, "loss_rpn_cls_fpn3": 0.000000, "loss_rpn_cls_fpn4": 0.000002, "loss_rpn_cls_fpn5": 0.000019, "loss_rpn_cls_fpn6": 0.000000, "lr": 0.000025, "mb_qsize": 64, "mem": 3084, "time": 0.266505}

**Comment by ir413** [comment]
Hi @SiDinhThoi - `accuracy_cls` is the box classsification accuracy (e.g. see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/fast_rcnn_heads.py#L48)), `eta` is the estimated time until the end of training (i.e. `num_iters_left * avg_iter_time`), `loss_*` are values of different losses, `mem` is the GPU memory usage (MB) and `time` is the average iteration time (s).
