### ISSUE TITLE
Keypoints without bbox?

### ISSUE THREAD

**Issue by fire17** [facebookresearch/Detectron#611]
Hey there, quick question...
Is it possible to get just keypoints without bbox? or bbox is always necessary before keypoints?

INFO infer_simple.py: 330: Inference time: 0.249s
INFO infer_simple.py: 332:  | im_detect_bbox: 0.234s **********************
INFO infer_simple.py: 332:  | im_detect_keypoints: 0.005s
INFO infer_simple.py: 332:  | misc_keypoints: 0.010s
INFO infer_simple.py: 332:  | misc_bbox: 0.000s

can I scape 0.234s from my Inference time?
Thank you very much!!
Tami

**Comment by gadcam** [comment]
@fire17 That is not possible the boxes and the process used to generate them is necessary for keypoints detection.
You can check the paper to have a better understanding of how it works conceptually https://arxiv.org/abs/1703.06870

You have the function to detect the keypoints here https://github.com/facebookresearch/Detectron/blob/e5bb3a8ff0b9caf59c76037726f49465d6b9678b/detectron/core/test.py#L540-L578

**Comment by fire17** [comment]
Thank you for the quick reply :)
you can close this issue
