### ISSUE TITLE
Is there a link for downloading the vgg19 pkl model?

### ISSUE THREAD

**Issue by yw155** [facebookresearch/Detectron#613]
What did you expect to see?

I would like to download a vgg19 pkl model for detectron.

**Comment by yw155** [comment]
I transferred the vgg19 model into pkl model by myself.

**Comment by hashiting** [comment]
Hi, can you please send the vgg19.pkl to me?

**Comment by yw155** [comment]
Sure, the download link is here: https://drive.google.com/open?id=1V_SkMDvfrof-n3YsitsCJ_XZmg6A6kWz

**Comment by hashiting** [comment]
thank you so much

**Comment by hashiting** [comment]
Hi, Can I know how to use the file? (What is the order for all the keys/layers).The key of the dict is not in order and I want to know how to use it in order (same as the vgg19 structure).
