### ISSUE TITLE
100% CPU Inference

### ISSUE THREAD

**Issue by fire17** [facebookresearch/Detectron#617]
Hello there,
I'm running Detectron nicely but my inference times can much faster.
I got 8 CPUs and none of them clock over 20% usage while running, even when I give the python process the nicest highest priority...
I'd like to run the program at 100% of all CPUs
So how can I do this?
Thank you very much!
Tami

* Operating system: Ubuntu 16.04
PS - Im leaving out most of the information as I hope to get a general solution that will help others as well.
If you believe this is should be specific to my environment I'll update the info... :)

**Comment by ir413** [comment]
Hi @fire17, I'm not sure if 100% CPU utilization is achievable or if it would make a significant difference in the case of detectron. Namely, inference is done mostly on the GPU with a small amount of computation done on the CPU. The current CPU code is not optimized and can likely be improved substantially. However, optimizing the CPU code may not affect the overall inference time substantially (dominated by the GPU). See [model zoo](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) for current inference times (given as X + Y, where X and Y are time spent on GPU and CPU, respectively).
