### ISSUE TITLE
Can I train the model without validation set?

### ISSUE THREAD

**Issue by nonstop1962** [facebookresearch/Detectron#62]
Hi, I try to train the retinaNet model with my own dataset. In your tutorial, all examples have a validation set. 
I would like to ask if the model can be learned without a validation set. To train without validation set, it is okay to modify *.yaml file's TRAIN.DATASETS section as below?

TRAIN:
  DATASETS: ('coco_2014_train',)

Thank you!

**Comment by ir413** [comment]
Hi @nonstop1962, yes that is fine. You can train with any collection of images with the appropriate annotations. Note that as far as the code is concerned there is no notion of the validation set. The union of all the datasets passed to `TRAIN.DATASETS` will be used for training while the model will be tested on each of the datasets passed to `TEST.DATASETS`. Some of the dataset names used in our configs contain the string `val`, but that is just a name for a collection of images and does not mean that the dataset will be used as a validation set.
