### ISSUE TITLE
i need to load two modules in my project? how to Realization?

### ISSUE THREAD

**Issue by JaosonMa** [facebookresearch/Detectron#622]
in my python project, i need load first module to detect one big class, and another module to detect the second big class, so how to reslization this?

怎么实现在一个工程中加载两个模型，两个模型识别统一张图像

AttributeError: Attempted to set "NUM_GPUS" to "1", but AttrDict is immutable

when first module works , the sencond module can not init succ!

**Comment by JaosonMa** [comment]
@ynd @zpao @pietern @ashwinb @ericnakagawa

**Comment by ir413** [comment]
Hi @JaosonMa, you are likely seeing this error since you're trying to modify the config after it has been made immutable (see [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L1069-L1084) function). You can avoid this error by not making the config immutable (`make_immutable=False`). However, we do not recommend this as it can make the code harder to understand and lead to hard to debug errors.

**Comment by JaosonMa** [comment]
@ir413 i had read the code of config.py, and i also understand . i don't want to do things that may be come lead to any debug errors, but my porblem is that  i have two models traind by detectron, i must run the two models one by one ,so that i can get the info from the image , i want to know how can i Realization by without change the code? 
Forgive me for my broken English.!!!

**Comment by JaosonMa** [comment]
@ir413 thank you so much!  i think this may solve my problem, i will go to learn this code . 
i alse see this #427 , it looks like he does not install detectron on his server , he used the caffe2 to realization the perform, if this way works well, it may be better . because i don't need install deterctron on my server machine. anyway thank you so much , i will try this way after try the way you telled me, and i will write the result someday, 
--------------------------

**Comment by pkhigh** [comment]
> Hi @JaosonMa, I think the easiest way to do this may be to study and potentially adapt the [`infer.py`](https://github.com/facebookresearch/Detectron/blob/master/tools/infer.py) tool which allows for using a combination of multiple models to perform inference.

@ir413 I tried using the idea of mergin config files to use multiple models. But the problem is that I want to let the model be loaded even though I have merged into a different config file and loaded again. However, in the code in infer.py relpaces the net in workspace with latest net.
