### ISSUE TITLE
Some images are not processing with Facebook Detectron-Mask RCNN

### ISSUE THREAD

**Issue by SiDinhThoi** [facebookresearch/Detectron#629]
Hi,

Have you ever meet above problem ?

I am looking forward to hearing back from you guys

**Comment by ir413** [comment]
Hi @SiDinhThoi, it is hard to tell what the problem is from the provided description. Please follow the instructions from the [issue template](https://github.com/facebookresearch/Detectron/blob/master/.github/issue_template.md) and reopen the issue.
