### ISSUE TITLE
Bbox Mean/STD normalization 

### ISSUE THREAD

**Issue by gaklein2007** [facebookresearch/Detectron#632]
In the previous iteration of this model, the Faster RCNN model, the bounding boxes are normalized based on their mean and standard deviation. In this iteration there does not seem to be any mention of normalizing the bounding box regression now, and the only reference I found was in utils/net.py in the configure_bbox_reg_weights which talks about using fixed weights. Are the regression outputs no longer normalized, and if not, what is done instead?

**Comment by ppwwyyxx** [comment]
They are still normalized during bounding box regression as you can see here:
https://github.com/facebookresearch/Detectron/blob/8170b25b425967f8f1c7d715bea3c5b8d9536cd8/detectron/datasets/roidb.py#L174-L175

**Comment by ppwwyyxx** [comment]
> So are they no longer normalized by the mean and standard deviation? 

The mean is considered zero. So you can either call it "normalization", or "multiply by a weight".

> And are these weights applied to both the RPN and Fast RCNN sides of the network? 

Only Fast RCNN side.

> They look to be the same as the Faster RCNN normalization parameters just inverted, is that correct?

dividing by x is equivalent to multiplying by the inverse of x.
