### ISSUE TITLE
Hi, I install Detectron, But for Build the custom operators library, I get this error:

### ISSUE THREAD

**Issue by faezehamjadi** [facebookresearch/Detectron#636]
mkdir -p build && cd build && cmake .. && make -j8
-- Caffe2: Found gflags with new-style gflags target.
-- Caffe2: Cannot find glog automatically. Using legacy find.
-- Caffe2: Found glog (include: /home/faezehh/anaconda2/envs/newenv/include, library: /home/faezehh/anaconda2/envs/newenv/lib/libglog.so)
-- Caffe2: Found protobuf with old-style protobuf targets.
-- Caffe2: Protobuf version 
-- Caffe2: CUDA detected: 9.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.2
-- Found cuDNN: v7.2.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
-- Autodetected CUDA architecture(s): 6.1 
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Summary:
--   CMake version        : 3.5.1
--   CMake command        : /usr/bin/cmake
--   System name          : Linux
--   C++ compiler         : /usr/bin/c++
--   C++ compiler version : 5.4.0
--   CXX flags            :  -std=c++11 -O2 -fPIC -Wno-narrowing
--   Caffe2 version       : 0.8.2
--   Caffe2 include path  : /home/faezehh/anaconda2/pkgs/caffe2-cuda8.0-cudnn7-0.8.dev-py36_2018.08.24/include
--   Caffe2 found CUDA    : True
--     CUDA version       : 9.2
--     CuDNN version      : 7.2.1
-- Configuring done
-- Generating done
-- Build files have been written to: /home/faezehh/newdir/build
make[1]: Entering directory '/home/faezehh/newdir/build'
make[2]: Entering directory '/home/faezehh/newdir/build'
make[3]: Entering directory '/home/faezehh/newdir/build'
make[3]: Leaving directory '/home/faezehh/newdir/build'
make[3]: Entering directory '/home/faezehh/newdir/build'
make[3]: Entering directory '/home/faezehh/newdir/build'
make[3]: *** No rule to make target '/opt/anaconda1anaconda2anaconda3/lib/libmkl_intel_lp64.so', needed by 'libcaffe2_detectron_custom_ops.so'.  Stop.
make[3]: Leaving directory '/home/faezehh/newdir/build'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/home/faezehh/newdir/build'
make[3]: Entering directory '/home/faezehh/newdir/build'
make[3]: *** No rule to make target '/opt/anaconda1anaconda2anaconda3/lib/libmkl_intel_lp64.so', needed by 'libcaffe2_detectron_custom_ops_gpu.so'.  Stop.
make[3]: Leaving directory '/home/faezehh/newdir/build'
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed
make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2
make[2]: Leaving directory '/home/faezehh/newdir/build'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/faezehh/newdir/build'
Makefile:13: recipe for target 'ops' failed
make: *** [ops] Error 2
  please let me know what is the problem.

**Comment by gadcam** [comment]
@faezehamjadi 
>make[3]: *** No rule to make target '/opt/anaconda1anaconda2anaconda3/lib/libmkl_intel_lp64.so', needed by 'libcaffe2_detectron_custom_ops.so'. Stop.

Looks like sometimes it is solved by [adding the path to this lib](
https://stackoverflow.com/questions/35046753/using-mkl-error-while-loading-shared-libraries-libmkl-intel-lp64-so) in <code>LD_LIBRARY_PATH</code> but it should not be needed: here it is only a symptom of a deeper problem.

>-- Caffe2: CUDA detected: 9.2

>-- Caffe2 include path : /home/faezehh/anaconda2/pkgs/caffe2-cuda8.0-cudnn7-0.8.dev-py36_2018.08.24/include

Looks like you have two conflicting CUDA versions.
I would try to switch to use only CUDA 9.

**Comment by faezehamjadi** [comment]
Thank you so much for reply. but after I get this error for test.

faezeh@lambdablade2:~/densepose$ python2 tools/infer_simple.py \
>     --cfg configs/DensePose_ResNet101_FPN_s1x-e2e.yaml \
>     --output-dir DensePoseData/infer_out/ \
>     --image-ext jpg \
>     --wts https://s3.amazonaws.com/densepose/DensePose_ResNet101_FPN_s1x-e2e.pkl \
>     DensePoseData/demo_data/demo_im.jpg
Found Detectron ops lib: /home/faezeh/anaconda2/lib/libcaffe2_detectron_ops_gpu.so
E0901 10:47:09.822866 26744 init_intrinsics_check.cc:43] CPU feature avx is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0901 10:47:09.822891 26744 init_intrinsics_check.cc:43] CPU feature avx2 is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
E0901 10:47:09.822899 26744 init_intrinsics_check.cc:43] CPU feature fma is present on your machine, but the Caffe2 binary is not compiled with it. It means you may not get the full speed of your CPU.
WARNING cnn.py:  25: [====DEPRECATE WARNING====]: you are creating an object from CNNModelHelper class which will be deprecated soon. Please use ModelHelper object with brew module. For more information, please refer to caffe2.ai and python/brew.py, python/brew_test.py for more information.
INFO net.py:  51: Loading weights from: /tmp/detectron-download-cache/DensePose_ResNet101_FPN_s1x-e2e.pkl
Traceback (most recent call last):
  File "tools/infer_simple.py", line 140, in <module>
    main(args)
  File "tools/infer_simple.py", line 91, in main
    model = infer_engine.initialize_model_from_cfg(args.weights)
  File "/home/faezeh/densepose/detectron/core/test_engine.py", line 336, in initialize_model_from_cfg
    model, weights_file, gpu_id=gpu_id,
  File "/home/faezeh/densepose/detectron/utils/net.py", line 103, in initialize_gpu_from_weights_file
    src_blobs[src_name].astype(np.float32, copy=False))
  File "/home/faezeh/anaconda2/lib/python2.7/site-packages/caffe2/python/workspace.py", line 336, in FeedBlob
    return C.feed_blob(name, arr, StringifyProto(device_option))
RuntimeError: [enforce fail at common_cudnn.h:112] version_match || backwards_compatible_7 || patch_compatible. cuDNN compiled (7201) and runtime (7005) versions mismatch

###################some info############################################

faezeh@lambdablade2:~/densepose$ env | grep '^LD_LIBRARY_PATH'
LD_LIBRARY_PATH=/home/ubuntu/torch/install/lib:/usr/local/lib
faezeh@lambdablade2:~/densepose$ which python
/home/faezeh/anaconda2/bin/python
faezeh@lambdablade2:~/densepose$  cat /usr/include/x86_64-linux-gnu/cudnn_v*.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 7
#define CUDNN_MINOR 0
#define CUDNN_PATCHLEVEL 5
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
faezeh@lambdablade2:~/densepose$

**Comment by gadcam** [comment]
@faezehamjadi Looks like you either need to update the system cuDNN or remove the path in <code>LD_LIBRARY_PATH</code>

**Comment by ir413** [comment]
Closing as the original issue seems resolved.
