### ISSUE TITLE
training log

### ISSUE THREAD

**Issue by coldgemini** [facebookresearch/Detectron#64]
can you release some of your training logs so as to make clearer what is the proper loss values expected.

**Comment by rbgirshick** [comment]
We plan to release training logs for all models in the model zoo. Not sure of the eta yet.

**Comment by rbgirshick** [comment]
Training logs for (most) model zoo models are [now available](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#log-files).
