### ISSUE TITLE
Whether Shuffle of images happens inside faster RCNN training?

### ISSUE THREAD

**Issue by subhamvs** [facebookresearch/Detectron#641]
Hello all,
I was working with Faster RCNN Resnet 50 with the custom dataset. While generating data in coco format, I didn't introduce any shuffle. Whether it happens automatically via code during training or is there any parameter for the shuffling images during training?

**Comment by ppwwyyxx** [comment]
#525

**Comment by subhamvs** [comment]
Thanks for a help.
