### ISSUE TITLE
In Faster RCNN training, batch of images for every iteration == 1 or 2 ? Is that valid? 

### ISSUE THREAD

**Issue by subhamvs** [facebookresearch/Detectron#642]
Hello all,
I was working with Faster RCNN Resnet 50 with the custom dataset. I am using one GPU for training.
As per my knowledge, weights will be updated based on every iteration loss value.  I could feel that 1 or 2 images per batch won't converge fastly.
Please correct me if I am wrong.
If my above statement is correct, is there any way to update cumulative weights after the fixed number of iterations?

**Comment by ppwwyyxx** [comment]
(1): #211 
(2): #562

**Comment by ir413** [comment]
Hi @subhamvs, please see the issues referenced by @ppwwyyxx.
