### ISSUE TITLE
How to see layers' information

### ISSUE THREAD

**Issue by leek018** [facebookresearch/Detectron#647]
Hi, Are there any tips for seeing layer's input dimension or output dimension in inferencing

I tried 'print(model.net.Proto())' from caffe2.ai 

but it's output shows ' op{ ... }  ' except layers' input dimension or output dimension

Is there any solution for knowing layers' information?

**Comment by zeenolife** [comment]
There is a `print_net()` function in utils/net.py that might do the job

**Comment by leek018** [comment]
Thank you~!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! thank you 
thank you ~~~~~
