### ISSUE TITLE
infer_simple.py use none default GPU_ID(0)

### ISSUE THREAD

**Issue by peyer** [facebookresearch/Detectron#65]
@rbgirshick , Hi, I have successfully installed caffe2 and Detectron project  on NVIDIA DRIVE  PX2, but the time used for a 600x900x3 input of Mask RCNN (ResNet50-FPN) almost took 0.5-0.8s(run infer_simple.py). However,  when I tested on other device equipped with GTX 1070 and I5-7500T, it only spent 0.13-0.3s .
I just tried to change the code c2_utils.NamedCudaScope(0) to c2_utils.NamedCudaScope(1) to use other gpu with an error as results,  could you show me that how can I use gpu_id(1) in infer_simple.py script?

**Comment by hariag** [comment]
```sh
export CUDA_VISIBLE_DEVICES=1
```
or
```python
import os
os.environ['export CUDA_VISIBLE_DEVICES']='1'
```
should work!

**Comment by rbgirshick** [comment]
@peyer: as documented and pointed out by @hariag, please use `CUDA_VISIBLE_DEVICES`.
