### ISSUE TITLE
Selective search codes are not included in the code?

### ISSUE THREAD

**Issue by tengerye** [facebookresearch/Detectron#653]
I am wondering if I want to repeat the fast rcnn paper which uses selective search, do I need to use external selective search codes? I could not find corresponding codes in this project.

Thanks.

**Comment by ir413** [comment]
Hi @tengery - that's right, selective search is not implemented in Detectron at this time. Sorry for the inconvenience.

**Comment by ir413** [comment]
Hi @tengerye, you can use the [`convert_selective_search`](https://github.com/facebookresearch/Detectron/blob/master/tools/convert_selective_search.py) tool to convert selective search boxes into detectron proposal file format (see also #164 for related discussion).

**Comment by tengerye** [comment]
Thank you so much for your kind reply. I think it is better for me to ask within this [issue](https://github.com/facebookresearch/Detectron/issues/710) now.
