### ISSUE TITLE
Is this possible?

### ISSUE THREAD

**Issue by rohit-shah** [facebookresearch/Detectron#654]
Hey, 

This is more of a question than an issue. Feel free to delete this if it's not the right place. I want to know, how can I actually detect and track a specific part of the body, say a tshirt and be able to add something on top of it. 

So for example, adding a logo (image) on actor's tshirt in such a way where it looks like the actor is actually wearing a shirt with the logo on it (so the logo image actually moves as the actor moves in the video frames).

Is this possible? If not, please point me in the right direction. 

Thanks in advance!

**Comment by ir413** [comment]
Hi @rohit-shah, please see the related discussion in #284.
