### ISSUE TITLE
Training stats?

### ISSUE THREAD

**Issue by ysfalo** [facebookresearch/Detectron#66]
I wonder why the training stats are formatted as json strings by default, are there any supported tools like tensorboard that can give a better look for training stats/net graph, etc.? Thanks for all your works!

**Comment by mattifrind** [comment]
Hey, @ysfalo I wrote a simple [visualization software](https://github.com/mattifrind/detectron-trainings-visualization) in JavaFX. Maybe this can help you.
Regards, Matti

**Comment by ambigus9** [comment]
@mattifrind Thanks! Wich is the process to install your tool? and Where we can find the training stats log? Thanks.

**Comment by mattifrind** [comment]
@ambigus9 I just used this software in my IDE (for example NetBeans). At top of the main class, you can edit the settings so you can change the name of your log file there. After you compiled the program you can start it and a window with the chart will open. You can save the content by clicking the "save image"-Button. If I have some time left I will develop a way without using a IDE and a GUI. 

Unfortunately, Detectron doesn't save any logs by itself, but it writes them to stdout. I saved them with the tee command of Ubuntu.
```
python2 tools/train_net.py <CONFIGURATIONS> | tee /path/to/log/file.txt
```

**Comment by ambigus9** [comment]
@mattifrind Thanks!
