### ISSUE TITLE
When I use "python2 detectron/tests/test_zero_even_op.py ",I get the following error

### ISSUE THREAD

**Issue by gittigxuy** [facebookresearch/Detectron#660]
![default](https://user-images.githubusercontent.com/15090557/45546976-bdbde280-b851-11e8-9e38-12fbe6345613.png)

what should I do?

**Comment by amin07** [comment]
Hello I am having the exact same problem. let me know if you have any solution. please help us.
![image](https://user-images.githubusercontent.com/15855504/45592798-61d48600-b945-11e8-894d-6e467199ca51.png)

**Comment by kinsou** [comment]
I also encountered the same problem. How to solve it?

**Comment by gittigxuy** [comment]
it is a test code,I think you could ignore it,and I don't know how to solve it

**Comment by ir413** [comment]
Closing as this seems like a duplicate of #502.
