### ISSUE TITLE
What kind of score strategy used in Detectron's pose estimation?

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/Detectron#661]
According to Detectron's code, there are three strategies in keypoints confident scores: logit, prob, bbox.
I'm curious if 'bbox' strategy is using bbox score directly as the keypoints score of a pose?

**Comment by ir413** [comment]
Hi @ArchNew - when `bbox` strategy is used, `bbox` detection scores are used as scores for keypoint predictions (by keypoint predictions I mean a set of 17 keypoints predicted for an instance; see [here](https://github.com/facebookresearch/Detectron/blob/6e95bea8c74551c027b955ef918a7a6e2d4e8383/detectron/datasets/json_dataset_evaluator.py#L417-L418)).
