### ISSUE TITLE
Can you provide a config for faster-rcnn(train from scratch) like e2e_faster_rcnn_R-50-C4_1x.yaml

### ISSUE THREAD

**Issue by mytxgmy** [facebookresearch/Detectron#665]
Can you provide a config for faster-rcnn(train from scratch) like e2e_faster_rcnn_R-50-C4_1x.yaml.I tried to train from scratch but mAP is low.

**Comment by ppwwyyxx** [comment]
You can take an existing scratch config file such as https://github.com/facebookresearch/Detectron/blob/master/configs/04_2018_gn_baselines/scratch_e2e_mask_rcnn_R-101-FPN_3x_gn.yaml, and remove all the mask rcnn related configs.

**Comment by mytxgmy** [comment]
@ppwwyyxx Thank you! But my caffe2 doesn't support GN. Can you provide another config without GN?
When I train e2e_faster_rcnn_R-50-C4_1x from scratch,I always get nan loss unless I use very low lr.

**Comment by ppwwyyxx** [comment]
Training from scratch without GN will give you low mAP as expected.
