### ISSUE TITLE
SpatialBN:error occurs when testing

### ISSUE THREAD

**Issue by mytxgmy** [facebookresearch/Detectron#667]
my code:
`blob_out = model.SpatialBN(conv_blob, prefix + suffix, dim_in=dim_out, is_test=is_test)`

error
`terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at blob.h:94] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/conv1_1_bn_rm.
Error from operator:
input: "gpu_0/conv1_1" input: "gpu_0/conv1_1_bn_s" input: "gpu_0/conv1_1_bn_b" input: "gpu_0/conv1_1_bn_rm" input: "gpu_0/conv1_1_bn_riv" output: "gpu_0/conv1_1_bn" name: "" type: "Spati$
lBN" arg { name: "is_test" i: 1 } arg { name: "use_cudnn" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "order" s: "NCHW" } device_option { device_type: 1 cuda_gpu_id: 0
 }
`

**Comment by ir413** [comment]
Hi @mytxgmy, it seems that the blob you are trying to use is not initialized. Please ensure that all the blobs your operator requires are present in the workspace when the operator is run.
