### ISSUE TITLE
Out of memory for Inference of Mask R-CNN with Bells & Whistles ,1080 Ti

### ISSUE THREAD

**Issue by HuangOwen** [facebookresearch/Detectron#674]
@rbgirshick 

Hi,I'm using the Mask R-CNN with Bells & Whistles(X-152-32x8d-FPN-IN5k). My GPU is 1080 Ti and it stills run out of memory. I search it and I found that it actually needs more than 12GB. What's more, I also notice that you mention you are working on optimization of the GPU memory of  Inference. Is that uploaded somewhere?

Since I only want to use the box information, Is there anything I can do to decrease the GPU memory it takes if I freeze or delete part of the model related to mask? If any, Plz tell me! Thanks!

**Comment by ir413** [comment]
Hi @HuangOwen, inference memory optimization are not available at this time (see #21 for discussion). Sorry for the inconvenience. If you don't want to compute the masks, you can disable the mask head by setting the [`MASK_ON`](https://github.com/facebookresearch/Detectron/blob/master/configs/12_2017_baselines/e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x.yaml#L6) option to `False`.
