### ISSUE TITLE
RuntimeError: [enforce fail at sigmoid_cross_entropy_loss_op.cu:81] X.size() == T.size(). 

### ISSUE THREAD

**Issue by CPFelix** [facebookresearch/Detectron#675]
When I train MaskRCNN on my own data,I modified the mask branch to reset structure,and get the following issues:

RuntimeError: [enforce fail at sigmoid_cross_entropy_loss_op.cu:81] X.size() == T.size(). Logit and target must have the same size(3920 vs. 15680)Error from operator: 
input: "gpu_0/mask_fcn_logits" input: "gpu_0/masks_int32" output: "gpu_0/loss_mask" name: "" type: "SigmoidCrossEntropyLoss" arg { name: "scale" f: 1 } device_option { device_type: 1 cuda_gpu_id: 0 }

Does this caused by reset structure or mask_loss?
I'm confused,please help!

**Comment by ir413** [comment]
Hi @CPFelix, I'm not quite sure what  do you mean by resetting the mask branch structure? It seems that there is a blob size missmatch in the [`SigmoidCrossEntropyLoss`](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/mask_rcnn_heads.py#L98) op. Please ensure that the blobs passed to the op are of the same size.

**Comment by CPFelix** [comment]
I use the resnet50+FPN,and I let the ROI_MASK_HEAD:mask_rcnn_heads.mask_rcnn_fcn_head_v0up,and it cause the problem above.
