### ISSUE TITLE
Lack of useful imagenet pre-trained models (even with claimed support)

### ISSUE THREAD

**Issue by calledbymountains** [facebookresearch/Detectron#677]
There is no imagenet pre-trained network for ResNet152 in Detectron. 

The `caffemodel` files elsewhere do not work as the layer names are quite different. 
The conversion is therefore not straightforward.  This is surprising because in the [source code](https://github.com/facebookresearch/Detectron/blob/master/detectron/modeling/ResNet.py) there is a mention of ResNet152 (as well as in `README.md`). 

Changing the source code directly for ResNet152 is very hard considering that the code for different variations of ResNet are very tightly coupled (same set of functions support R50 and 101 as well). 

All of this makes it hard to do benchmarking with Detectron even with all the backbones it claims to support. 

Are there any plans to work on it ? Maybe the converted imagenet pre-trained models at the least can be provided for all the backbones which are claimed to be supported. That can assist in a consistent usage of the framework.

**Comment by rbgirshick** [comment]
See: https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#imagenet-pretrained-models
