### ISSUE TITLE
how can I use color transform in the data augment

### ISSUE THREAD

**Issue by gittigxuy** [facebookresearch/Detectron#678]
as you know ,currently,the detectron only implement the flip method in the roidb.py,so how could  I implement the color transform in the data augment?

**Comment by ir413** [comment]
Hi @gittigxuy , detectron currently supports only scaling and horizontal flipping data augmentations for training. You can look into [this](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/minibatch.py#L89) function to add support for color augmentations.
