### ISSUE TITLE
Invalid bbox in coco style annotations (instances_minival2014.json, pascal_train2007.json file)

### ISSUE THREAD

**Issue by nonstop1962** [facebookresearch/Detectron#68]
Hi, I'm analyzing dataset and find that there many invalid bbox annotation in coco_minival.json and pascal_train2007.json file. 

According to the coco homepage, annotation for bbox is in order as "bbox" : [x,y,width,height].
However, many bbox annotations in .json file looks like "bbox":[8,229,237,271] or "bbox":[224,0,110,486]. These boxes have upper left point of minus values. 

Is this an original dataset looks like? Isn't there any problem during training because of this issue?

**Comment by rbgirshick** [comment]
The `(x,y)` specify the *top-left corner* of the box, so for the examples you provided the top-left corners are `(8, 229)` and `(224, 0)`, which seems fine.
