### ISSUE TITLE
hard negative mining

### ISSUE THREAD

**Issue by EgorAntonovich** [facebookresearch/Detectron#680]
I train Detectron on my custom dataset with caffe 2 and on MAsk RCNN without masks, i use only bbox. and after training false alarm on some classes was hight.
I want to implement hard negative mining on detectron. may be anybody implemented this method or know how to implement?

**Comment by ir413** [comment]
Hi @EgorAntonovich, please see #129 for a related discussion.

**Comment by EgorAntonovich** [comment]
@ir413 thanks a lot .
