### ISSUE TITLE
how to draw the loss curve and P-R curve in detectron？

### ISSUE THREAD

**Issue by shenghsiaowong** [facebookresearch/Detectron#682]
how to draw the loss curve and P-R curve in detectron？

**Comment by ir413** [comment]
Hi @shenghsiaowong, see #66, #308 and #538 for discussion about plotting the training stats. COCO eval object should contain all the information required for plotting the PR curve. You may also find the COCO analysis code useful (see [here](http://cocodataset.org/#detection-eval) for more info).
