### ISSUE TITLE
Question About Protobuf 

### ISSUE THREAD

**Issue by SavannahZhang** [facebookresearch/Detectron#688]
In ' INSTALL.md - Protobuf Errors ':

" To point Caffe2 CMake to the newly built protobuf:

cmake .. \
  ### insert your Caffe2 CMake flags here
  -DPROTOBUF_PROTOC_EXECUTABLE=$HOME/c2_tp_protobuf/bin/protoc \
  -DPROTOBUF_INCLUDE_DIR=$HOME/c2_tp_protobuf/include \
  -DPROTOBUF_LIBRARY=$HOME/c2_tp_protobuf/lib64/libprotobuf.a "

Should it be run in /path/to/pytorch/build or /path/to/caffe2 or $CAFFE2/third_party/protobuf/cmake/build?
Also, after point Caffe2 Cmake to the newly built protobuf, should I rebuild caffe2?

**Comment by ir413** [comment]
Hi @SavannahZhang, please find the answers below.

> Should it be run in /path/to/pytorch/build or /path/to/caffe2 or $CAFFE2/third_party/protobuf/cmake/build?

That CMake command should be run from the Caffe2 build dir (`/path/to/pytorch/build`).

> Also, after point Caffe2 Cmake to the newly built protobuf, should I rebuild caffe2?

Yes, after running cmake you should re-build your Caffe2.
