### ISSUE TITLE
Mask R-CNN ResNeXt X-101-32x8d-FPN model and weights inconsistent?

### ISSUE THREAD

**Issue by smoosbau** [facebookresearch/Detectron#689]
I tried to start inference by using the following command:
`python2 tools/infer_simple.py     --cfg /input/configs/ResNet_101/DGX/Onshore/Aspect_Ratio_Default/e2e_mask_rcnn_RPN-101-FPN_2x_ASS_32.yaml --output-dir /tmp/detectron-visualizations     --image-ext jpg     --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl demo`

I get the following error:
`terminate called after throwing an instance of 'caffe2::EnforceNotMet'
  what():  [enforce fail at blob.h:94] IsType<T>(). wrong type for the Blob instance. Blob contains nullptr (uninitialized) while caller expects caffe2::Tensor<caffe2::CUDAContext> .
Offending Blob name: gpu_0/conv_rpn_fpn2_w.
Error from operator: 
input: "gpu_0/fpn_res5_2_sum" input: "gpu_0/conv_rpn_fpn2_w" input: "gpu_0/conv_rpn_fpn2_b" output: "gpu_0/conv_rpn_fpn5" name: "" type: "Conv" arg { name: "kernel" i: 3 } arg { name: "exhaustive_search" i: 0 } arg { name: "pad" i: 1 } arg { name: "order" s: "NCHW" } arg { name: "stride" i: 1 } device_option { device_type: 1 cuda_gpu_id: 0 } engine: "CUDNN"
*** Aborted at 1538127804 (unix time) try "date -d @1538127804" if you are using GNU date ***
PC: @     0x7fe1ad23e428 gsignal
*** SIGABRT (@0xad0) received by PID 2768 (TID 0x7fdf5bfff700) from PID 2768; stack trace: ***
    @     0x7fe1ad5e4390 (unknown)
    @     0x7fe1ad23e428 gsignal
terminate called recursively
    @     0x7fe1ad24002a abort
    @     0x7fe1a72ec84d __gnu_cxx::__verbose_terminate_handler()
terminate called recursively
    @     0x7fe1a72ea6b6 (unknown)
    @     0x7fe1a72ea701 std::terminate()
    @     0x7fe1a7315d38 (unknown)
    @     0x7fe1ad5da6ba start_thread
terminate called recursively
    @     0x7fe1ad31041d clone
    @                0x0 (unknown)
Aborted (core dumped)`

By reading other issues I recognized that there are some models that may be inconsistent with their depending weight files.
Could this be the case here as well?
If it is, is there a way I can fix this?

Thanks in advance for any help :)

**Comment by smoosbau** [comment]
close
weights files link was wrong (weigths with precomputed RPN proposals used)

**Comment by manyaafonso** [comment]
So can you please post the correct command that worked for you?
