### ISSUE TITLE
how to convert my own dataset to coco style dataset?

### ISSUE THREAD

**Issue by iFighting** [facebookresearch/Detectron#69]
i want to train my own dataset
how to convert my own dataset to coco style dataset?

**Comment by rbgirshick** [comment]
This question is a bit beyond the scope of what we can answer in detail here. I recommend looking at some existing conversion code in the COCO API github repo, e.g., here https://github.com/cocodataset/cocoapi/blob/master/MatlabAPI/CocoUtils.m#L29. The format is pretty straightforward and it should not be difficult to write a conversion script.
