### ISSUE TITLE
Python3 Attribute error after running train.py

### ISSUE THREAD

**Issue by canerozer** [facebookresearch/Detectron#694]
### Expected results

In def download_url located in $DETECTRON/detectron/utils/io.py, line 140 must be changed from 
`    total_size = response.info().getheader('Content-Length').strip()` to 
`    total_size = response.info().get('Content-Length').strip()`. 
HTTPMessage objects do not have `getheader` attributes in python3. I would appreciate if anyone can write both Python2/3 adapted code.

### Actual results

> INFO io.py:  91: Downloading remote file https://s3-us-west-2.amazonaws.com/detectron/ImageNetPretrained/MSRA/R-50.pkl to /tmp/detectron-download-cache/ImageNetPretrained/MSRA/R-50.pkl
/tmp/detectron-download-cache/ImageNetPretrained/MSRA/R-50.pkl
AttributeError: 'HTTPMessage' object has no attribute 'getheader'

### Detailed steps to reproduce

Installed caffe2 for python3 and then cloned Detectron and also installed it successfully. Afterthat, I tried to run the following code to see if I can start training on a single GPU.

`python3 $DETECTRON/tools/train_net.py --cfg=configs/getting_started/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml 
`

### System information

* Operating system: Ubuntu 16.04.1
* Compiler version: 5.4.0
* CUDA version: 9.0
* cuDNN version: 7.0.5
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): 1080 GTX x 1
* `python --version` output: Python 3.5.2

**Comment by ir413** [comment]
Thanks for reporting @canerozer. We are looking into it.
