### ISSUE TITLE
how to use soft-NMS?

### ISSUE THREAD

**Issue by gittigxuy** [facebookresearch/Detectron#695]
just change the NMS ->SOFT_NMS in the test part in yaml file?or any other modify?
Thanks

**Comment by ir413** [comment]
Hi @gittigxuy, please see the description of Soft NMS options [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L401-L411).

**Comment by gittigxuy** [comment]
@ir413 ,Thanks,I just set soft_nms.enabled=True,it will be ok,but if I train the model use soft_nms.enabled=False,but when I want to test the model,I modify the config to True,will it be error?if thus,must I retrain the model?

**Comment by ir413** [comment]
@gittigxuy: Soft NMS is used only at test time so there is no need to retrain the model when changing Soft NMS config options.
