### ISSUE TITLE
How to train  model on the negative sample ?

### ISSUE THREAD

**Issue by JiYuanFeng** [facebookresearch/Detectron#697]
Hello!, recently I try to train a model on my own datasets, which only contain one category + background.
And there are some image without any category instance(which are all background),
I try to change the code in the project, however, it's too difficult. Is there any easy method to train on the negative data?

**Comment by ir413** [comment]
Hi @JiYuanFeng - Detectron requires that each training image has at least one positive or at least one negative RoI (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/roidb.py#L114)). You should be able to use images with no positives  for training 2-stage models (w/ pre-computed proposals) without modifications to the code. Using images with no positives for training end-to-end models will require some modifications to the code.

**Comment by pkhigh** [comment]
@ir413 
I tried using the code changes made by @ gcheron in his repository : https://github.com/gcheron/Detectron.git with branch : pr_negative_samples. However, he has only made changes for RPN. 
Can you suggest the changes to be made in roi_data/retinanet.py so that I can train it with background images for RETINANET?

**Comment by TemitopeOladokun** [comment]
Do you know how to train the model with the misclassified(negative) labelled data?
@JiYuanFeng @ir413 @zpao @pkhigh @ashwinb

**Comment by pkhigh** [comment]
@TemitopeOladokun this repository is not in development. You should use https://github.com/facebookresearch/detectron2 for your work. In the config files, you can set FILTER_EMPTY_ANNOTATIONS to False to train on negative images in detectron2.
