### ISSUE TITLE
ImportError: cannot import name task_evaluation

### ISSUE THREAD

**Issue by panovr** [facebookresearch/Detectron#7]
When invoke this command:
```
python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
```
got this error:
```
Traceback (most recent call last):
  File "tools/infer_simple.py", line 42, in <module>
    import core.test_engine as infer_engine
  File "/home/ylzhao/develop/detectron/lib/core/test_engine.py", line 36, in <module>
    from datasets import task_evaluation
ImportError: cannot import name task_evaluation
```

**Comment by jwnsu** [comment]
Encountered same issue, solved by adding lib to python path. For example, you can add following lines to tools/_init_path.py, then import it in train_net.py:

[import os.path as osp
import sys

def add_path(path):
    if path not in sys.path:
        sys.path.insert(0, path)

this_dir = osp.dirname(__file__)

# Add lib to PYTHONPATH
lib_path = osp.join(this_dir, '..', 'lib')
add_path(lib_path) ](url)

**Comment by panovr** [comment]
@jwnsu Thanks!
The problem can be fixed by adding `lib` to the `PYTHONPATH` environment variable alternative.

**Comment by jungalwala** [comment]
@panovr Add which lib directory to the PYTHONPATH?

**Comment by panovr** [comment]
@jungalwala `detectron`->`lib`

**Comment by LousyLory** [comment]
Can't find lib in detectron anymore! i'm getting the following error while using Detectron as backend:
File "tools/test_net.py", line 41, in <module>
    from core.test_retinanet import test_retinanet
ImportError: cannot import name test_retinanet
