### ISSUE TITLE
why don't use pytorch to implement?

### ISSUE THREAD

**Issue by yingxingde** [facebookresearch/Detectron#70]
when I use pytorch to implement FPN, I have got in trouble. I can not achieve the good result.  My experiment dataset is VOC2007

**Comment by rbgirshick** [comment]
The Detectron project started before pytorch existed, so naturally it wasn't written in pytorch from the start. I think having a pytorch port of Detectron would be great for the community.

**Comment by ahkarami** [comment]
+1 for PyTorch

**Comment by u39kun** [comment]
+1 for PyTorch

**Comment by levants** [comment]
+1 for PyTorch

**Comment by rbgirshick** [comment]
From @ignacio-rocco:

> Hi,
> 
> I'm working on a PyTorch version of Detectron [here](https://github.com/ignacio-rocco/detectorch).

(I locked this thread because +1's are unhelpful. Obviously it will be great to have a pytorch version, but please make it happen by writing code, not +1's.)
