### ISSUE TITLE
Errors with Inference with Pretrained Models

### ISSUE THREAD

**Issue by aikivl3** [facebookresearch/Detectron#705]
### I tried to run the first command of Inferencing with Pretrained Models
<code>
python tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
</code>

_but I got this error:_

"
Traceback (most recent call last):
  File "tools/infer_simple.py", line 49, in <module>
    c2_utils.import_detectron_ops()
  File "/home/bapvn/work/detectron/detectron/utils/c2.py", line 43, in import_detectron_ops
    detectron_ops_lib = envu.get_detectron_ops_lib()
  File "/home/bapvn/work/detectron/detectron/utils/env.py", line 71, in get_detectron_ops_lib
    ('Detectron ops lib not found; make sure that your Caffe2 '

AssertionError: Detectron ops lib not found; make sure that your Caffe2 version includes Detectron module

"

**_I have installed all the necessary environment for Detectron (please see the attachments)_**

![detectrion_issue](https://user-images.githubusercontent.com/8035201/46947083-f3015e80-d0a3-11e8-8629-517e478d59c8.png)
![installation_results](https://user-images.githubusercontent.com/8035201/46947084-f3015e80-d0a3-11e8-8781-1e0f2fb83917.png)
![pytorch_question](https://user-images.githubusercontent.com/8035201/46947085-f3015e80-d0a3-11e8-9711-7c6bd8fdb6cb.png)

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 
* CUDA version: 9.0
* cuDNN version: 7.3.1
* NVIDIA driver version: nvidia396
* GPU models (for all devices if they are not all the same):  GTX 1070
* `PYTHONPATH` environment variable: Python 3.6
* `python --version` output: Python 3.6.3 :: Anaconda custom (64-bit)

I would like to ask if any one knows to fix this?

**Comment by ir413** [comment]
Hi @aikivl3, this may be the same as #711. Please retry with latest master and reopen the issue if the problem is still present.
