### ISSUE TITLE
How to use other networks such as GoogleNet (inception V1)?

### ISSUE THREAD

**Issue by freddiew509** [facebookresearch/Detectron#71]
I downloaded pre-trained GoogleNet from Caffe2 model zoo (init_net.pb and predict_net.pb), but somehow I can't load the pre-trained weights to training. Do I have to convert ".pb" to ".pkl" as for ResNet? Thank you!

**Comment by freddiew509** [comment]
Is there an existing script that converts models pre-trained on ImageNet to the format used by Detectron (e.g. R-50.pkl, R-101.pkl in "MODEL_ZOO.md")? If not, how should I write one for GoogleNet?

Thank you!

**Comment by rbgirshick** [comment]
We used this script to convert caffe(1) VGG and ResNet models to the format used by Detectron (which is a simple dict mapping from parameter blob name to numpy array): https://github.com/facebookresearch/Detectron/blob/master/tools/pickle_caffe_blobs.py. You should be able to build on it to convert the caffe GoogleNet model.
