### ISSUE TITLE
Fast R-CNN inference with pre-computed proposals

### ISSUE THREAD

**Issue by tengerye** [facebookresearch/Detectron#710]
I try to run inference on fast rcnn backbones with pre-computed proposals. There are a similar [topic](https://github.com/facebookresearch/Detectron/issues/164) except I want inference on my own dataset instead of given dataset like COCO.

How could I do that?

My study on the codes tells me I have to manage combine the proposals with image somehow. But it is impossible right?

**Comment by ir413** [comment]
Hi @tengerye, the easiest way to do this may be to adapt the existing [`infer.py`](https://github.com/facebookresearch/Detectron/blob/master/tools/infer.py) tool to take the precomputed proposals as input instead of computing the proposals on the fly using the provided RPN.

**Comment by tengerye** [comment]
Hi, thank you for your kind reply @ir413 . But how could I feed my pre-computed proposals please? 

`--rpn-cfg` is for pre-trained model file. As for the `--rpn-pkl`, the only potential function that uses it is in `initialize_gpu_from_weights_file(model, weights_file, gpu_id=0)`, but I could not find any codes that may use pre-computed proposals within.

**Comment by ir413** [comment]
Hi @tengerye, you would need to adapt `infer.py` slightly. For example, instead of [computing proposals](https://github.com/facebookresearch/Detectron/blob/master/tools/infer.py#L126) using the RPN (specified via `--rpn-cfg` and `--rpn-pkl`) you can add the code to load the precomputed proposals (e.g. something like `proposal_boxes = load_proposals("/path/to/proposals")`).

**Comment by tengerye** [comment]
Hi @ir413 , sorry to disturb again. According to your kind instructions, I replaced [`proposal_boxes=None`](https://github.com/facebookresearch/Detectron/blob/master/tools/infer.py#L129) to `proposal_boxes = np.asarray([[0, 0, 50, 50]])` to have a try.

Then I tried
`--output-dir ./ --im test.png /tmp/detectron-download-cache/36224013/12_2017_baselines/fast_rcnn_R-50-C4_1x.yaml.08_22_00.vHd5BeBP/output/train/coco_2014_train%3Acoco_2014_valminusminival/generalized_rcnn/model_final.pkl configs/12_2017_baselines/fast_rcnn_R-50-C4_1x.yaml`, but I still get more than one bounding box.

I found [`box_deltas = workspace.FetchBlob(core.ScopedName('bbox_pred')).squeeze()`](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/test.py#L173) somehow replaces my proposals. May I ask what am I supposed to do next?

**Comment by ir413** [comment]
Hi @tengerye, when using a single proposal like in your example above you can get at most one box per-class so there can be up to 80 boxes in `cls_boxes` results for the model you're using (note that the number of surviving boxes is affected by the value of `TEST.SCORE_THRESH`).
