### ISSUE TITLE
Detectron ops lib not found

### ISSUE THREAD

**Issue by Anko59** [facebookresearch/Detectron#711]
### Expected results

Successfull Test

### Actual results

Traceback (most recent call last):
`File "test_spatial_narrow_as_op.py", line 88, in <module>`
    `    c2_utils.import_detectron_ops()`
`File ".../detectron/detectron/utils/c2.py", line 43, in import_detectron_ops`
    `    detectron_ops_lib = envu.get_detectron_ops_lib()`
 `File ".../detectron/detectron/detectron/utils/env.py", line 71, in get_detectron_ops_lib`
   `     ('Detectron ops lib not found; make sure that your Caffe2 `
`AssertionError: Detectron ops lib not found; make sure that your Caffe2 version includes Detectron module`

### Detailed steps to reproduce
 `conda install pytorch-nightly -c pytorch`
 DETECTRON=/path/to/clone/detectron
`git clone https://github.com/facebookresearch/detectron $DETECTRON`
`pip install -r $DETECTRON/requirements.txt`
`cd $DETECTRON && make`
`python $DETECTRON/detectron/tests/test_spatial_narrow_as_op.py`

### System information

* Operating system: Ubuntu 16.04
* Compiler version: Cmake 3.12.0
* CUDA version: 9.2
* cuDNN version: 9.0
* NVIDIA driver version:  396.37
* GPU model: Nvidia K80
* `PYTHONPATH`: empty
* `python --version` output:  Python 2.7.15 :: Anaconda, Inc.
* Anything else that seems relevant: 
Caffe2 is working fine on it's own, i'd rather stay with my versions of cuda and cudnn as I am using other deep learning frameworks that work fine with those versions
I tried compiling the sources without using Anaconda, caffe2 was not working with the following error:
`CRITICAL:root:Cannot load caffe2.python. Error: No module named 'caffe2.python.caffe2_pybind11_state'`
I tried adding `/path/to/caffe2/build` to PYTHONPATH, but there is no build folder in `.../anaconda3/envs/caffenv/lib/python2.7/site-packages/caffe2`, only `contrib` `proto` and `python` folders

Thank you for your help !

**Comment by ir413** [comment]
Thanks for reporting @Anko59. We reproduced the issue and are looking into it.

**Comment by ir413** [comment]
Hi @Anko59, we addressed this issue in df0e497.
