### ISSUE TITLE
Suggested hyperparams for roi pooling

### ISSUE THREAD

**Issue by mingruimingrui** [facebookresearch/Detectron#712]
Hi, I want to train a mask rcnn model on a custom dataset.
Some objects in the dataset are very small (4 pixels across)
by scaling all images by a scale of 2 and by using the following RPN
settings,
RPN_MAX_LEVEL: 6
RPN_MIN_LEVEL: 2
RPN_ASPECT_RATIOS: (0.25, 0.5, 1.0, 2.0, 4.0)
RPN_ANCHOR_START_SIZE: 8

Hopefully the small objects can be detected
The question is, should I edit the params for ROI pooling?

I would be referring to
ROI_CANONICAL_SCALE
ROI_CANONICAL_LEVEL
ROI_MAX_LEVEL
ROI_MIN_LEVEL

Thanks for your advice!

**Comment by tdiekel** [comment]
@mingruimingrui did you have success detecting small objects with editing the listed params?
