### ISSUE TITLE
how can i get mAP for each snapshot over validation dataset?

### ISSUE THREAD

**Issue by rrkotik** [facebookresearch/Detectron#718]
Hello! i want to get mAP for each snapshot over validation dataset during training. How can i do this?
Currently I have results only for final model. Thanks.

**Comment by ir413** [comment]
Hi @rrkotik, please see [this section](https://github.com/facebookresearch/Detectron/blob/master/FAQ.md#q-how-do-i-compute-validation-ap-during-training) of the [FAQ](https://github.com/facebookresearch/Detectron/blob/master/FAQ.md) for more info on how to compute val AP during training.
