### ISSUE TITLE
Trained RetinaNet R-50-FPN-1x doesn't produce expected mAP

### ISSUE THREAD

**Issue by freddiew509** [facebookresearch/Detectron#72]
I trained a RetinaNet using "retinanet_R-50-FPN_1x.yaml". The only changes I made were setting NUM_GPUS to 1 and BASE_LR to 0.00125. 

The testing results are as follows:
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.233
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.395
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.240
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.115
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.267
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.312
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.241
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.398
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.422
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.220
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.467
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.579

Somehow the AP is much worse than the one reported in model zoo (35.7%). 

Also, when I ran the provided pre-trained RetinaNet (retinanet_R-50_FPN_1x.yaml.08_29_48) on the demos images, the result is not as good as expected. 
![15673749081_767a7fa63a_k](https://user-images.githubusercontent.com/16884221/35539742-b50744c2-0507-11e8-84c0-7b502903fb6a.jpg)

When I run networks other than RetinaNet, the results are pretty good and I can reproduce their mAPs reported in model zoo. 

Thanks.

**Comment by rbgirshick** [comment]
Did you make the training schedule 8x longer?

**Comment by freddiew509** [comment]
Hi @rbgirshick,

Thanks for the prompt reply. I will increase the MAX_ITER to 8x and change the STEPS accordingly.

**Comment by rbgirshick** [comment]
Sounds good! (Please study https://github.com/facebookresearch/Detectron/blob/master/GETTING_STARTED.md and the getting started configs carefully.)
