### ISSUE TITLE
How to extract feature map in the middle of the backbone?

### ISSUE THREAD

**Issue by ArchNew** [facebookresearch/Detectron#720]
### Expected results
I want to extract feature map from ResNeXt-152-FPN's output (every level of FPN). I tried to get something from the function ```add_roi_2mlp_head```, specifically, the ```blob_in``` parameter. I expected every level of FPN would be stored in the ```blob_in```

### Actual results
The reality is...I got nothing from ```blob_in```. The ```print(blob_in)``` reports that it is empty. Then it occurred to me that Caffe2 is a static graph AI framework.

Is there any way I can make Detectron output the heatmap I want?

### System information

* Operating system: Ubuntu 16.04
* Compiler version: 5.4.0
* CUDA version: 8.0
* cuDNN version: 7.2.1
* NVIDIA driver version: 381.22
* GPU models (for all devices if they are not all the same): Nvidia Titan XP
* `PYTHONPATH` environment variable: /home/zhouzhou/pytorch/build
* `python --version` output: 2.7.13

**Comment by ir413** [comment]
Hi @ArchNew, you can retrieve the features you care about by fetching the appropriate blob(s) from the Caffe2 workspace. Please see discussion in #123 for more info on how to do that.
