### ISSUE TITLE
How can I export init_net.pb and predict_net.pb files on my own?

### ISSUE THREAD

**Issue by arenchdlaam** [facebookresearch/Detectron#722]
I want to convert the retinanet in Detectron to an onnx model, but I need to prepare init_net.pb and predict_net.pb files first. Followed by the script bellow I got these two files, but when I tried to run the convert procedure an error occured and I don't know how to handle this. Can anybody help me with this problem?
####################
script to generate .pb files:

def SaveNet(INIT_NET, PREDICT_NET, workspace, model):
    init_net, predict_net = mobile_exporter.Export(
        workspace, model.net, model.params
    )
    with open(PREDICT_NET, 'wb') as f:
        f.write(model.net._net.SerializeToString())
    with open(INIT_NET, 'wb') as f:
        f.write(init_net.SerializeToString())
    print("== saved init_net and predict_net. ==")

#############################
script to convert files to onnx:
import os
os.environ['CUDA_VISIBLE_DEVICES']='0'
import onnx
import caffe2.python.onnx.frontend
from caffe2.proto import caffe2_pb2
data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 480, 640)
value_info = {
    'gpu_0/data': (data_type, data_shape)
}
predict_net = caffe2_pb2.NetDef()
with open('predict_net.pb', 'rb') as f:
    predict_net.ParseFromString(f.read())
init_net = caffe2_pb2.NetDef()
with open('init_net.pb', 'rb') as f:
    init_net.ParseFromString(f.read())
onnx_model = caffe2.python.onnx.frontend.caffe2_net_to_onnx_model(
    predict_net,
    init_net,
    value_info,
)
onnx.checker.check_model(onnx_model)

##############################
ERROR:
[E net_async_base.cc:422] [enforce fail at context_gpu.cu:343] error == cudaSuccess. 77 vs 0. Error at: /home/bjtu/Downloads/pytorch/caffe2/core/context_gpu.cu:343: an illegal memory access was encounteredError from operator: 
input: "gpu_0/conv1_3" output: "gpu_0/pool1_1" name: "" type: "MaxPool" arg { name: "kernel" i: 3 } arg { name: "order" s: "NCHW" } arg { name: "pad" i: 1 } arg { name: "cudnn_exhaustive_search" i: 0 } arg { name: "stride" i: 2 } device_option { device_type: 1 device_id: 0 } engine: "CUDNN",  op MaxPool
[F context_gpu.h:118] Check failed: error == cudaSuccess an illegal memory access was encountered

### System information

* Operating system: ubuntu16.04
* Compiler version: gcc 5.4.0
* CUDA version: 8.0
* cuDNN version: 7.1.4
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): quadro m5000
* `PYTHONPATH` environment variable: ?
* `python --version` output: 2.7
* Anything else that seems relevant: ?

**Comment by ir413** [comment]
Hi @arenchdlaam - I'm not familiar with the ONNX conversion process so don't have any useful suggestions. I think it would be better to post about this on the Caffe2 or ONNX page.
