### ISSUE TITLE
How to detect more than 100 objects in one image?

### ISSUE THREAD

**Issue by yohohohoho** [facebookresearch/Detectron#726]
I trained a model. But when I use the trained model to predict using infer_simple.py, I found that it can output up to one hundred results for one image.

Can I control the number of bbox?

**Comment by ir413** [comment]
Hi @yohohohoho, you can use [`TEST.DETECTIONS_PER_IM`](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L265-L267) config option to adjust the maximum number of detections to return per image (default value is 100).
