### ISSUE TITLE
What will happen if I miss annotate a foreground object ?

### ISSUE THREAD

**Issue by so-chin** [facebookresearch/Detectron#727]
What will happen if I miss annotate a foreground object ?
Will it be learned as background or just be ignored by default?

**Comment by ir413** [comment]
Hi @so-chin - yes, unannotated foreground objects (that are not covered by ignore regions) could be used as background examples. This is affected by the choice of the background RoI overlap thresholds (see [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py#L106-L109) for more info), proposals used for training, and the relative positions of annotated and unannotated objects.
