### ISSUE TITLE
/usr/local/caffe2_build/include/caffe2/utils/math.h:36:22: fatal error: Eigen/Core: No such file or directory

### ISSUE THREAD

**Issue by wangpichao** [facebookresearch/Detectron#729]
I tried to install DetectAndTrack from source, but failed, thus I turned to Dockerfile, and successfully installed caffe2 and DetectAndTrack. All the test passed until I the train module:python launch.py -c configs/video/2d_best/01_R101_best_hungarian.yaml -m train, and it saysAttributeError: Method AffineChannelNd is not a registered operator. Did you mean: [AffineChannel]. I investigated this problem and found that the lib/ops/affine_channel_nd_op.* need to be copied to caffe2/modules/detectron/. However, there is no detectron folder under the caffe2 installed by dockerfile, and then I git clone the detectron to the caffe2 folder. After I copy all the affine_channel_nd_op.* into the /detectron/ops/, and make, it occurred the error:/usr/local/caffe2_build/include/caffe2/utils/math.h:36:22: fatal error: Eigen/Core: No such file or directory. I found several solution for this error, but all of them need to revise the .cc files, for example, caffe2/core/context.cc file. But there is no such files in caffe2 using Dockerfile. How to deal with this problem?

**Comment by zhiweichen12** [comment]
you can try to  add Eigen directory when you cmake

**Comment by ir413** [comment]
Hi @wangpichao, it seems that you're using an old fork of detectron and are having issues with building custom ops for that fork. Could you please provide steps to reproduce the issue using the up to date detectron (this repo) and provide the info requested in the issue template? It is hard to debug otherwise.
