### ISSUE TITLE
error when testing the coco dataset with downloaded weights, while training is ok

### ISSUE THREAD

**Issue by iFighting** [facebookresearch/Detectron#73]
error when testing the coco dataset with downloaded weights, while training is ok
this is the error image
![image](https://user-images.githubusercontent.com/6366788/35545423-00b1049c-05aa-11e8-9050-a71faea1aa2e.png)
![image](https://user-images.githubusercontent.com/6366788/35545463-2d63a9c2-05aa-11e8-8648-3cfac035b4eb.png)

**Comment by rbgirshick** [comment]
`filter.dim32(1) == C / group_. 8 vs 4` implies that you have a mismatch between the yaml config and the pkl model. One must be for ResNeXt w/ 64x4d while the other is 32x8d. I cannot check if this is true because the you did not provide the command that you ran, but I expect it is true.

**Comment by iFighting** [comment]
thanks, you are right，i just mistake the pkl model

**Comment by iFighting** [comment]
another problem, it seems that the code does not support CUDA_VISIBLE_DEVICES

**Comment by rbgirshick** [comment]
`CUDA_VISIBLE_DEVICES` should work for multi-gpu inference. Please provide the exact steps you ran.

**Comment by rbgirshick** [comment]
Closing since the scope of the original issue has been addressed.
