### ISSUE TITLE
ImageNet-5k synset list

### ISSUE THREAD

**Issue by xternalz** [facebookresearch/Detectron#733]
Hi, can you provide the ImageNet-5k synset list used for training ResNeXt-152-32x8d `X-152-32x8d-IN5k.pkl?`? Thanks.

**Comment by ir413** [comment]
Hi @xternalz, you can find the list of IN-5k category ids used to pre-train the model you mention [here](https://gist.github.com/ir413/afc85faabc36f4884253840a61a12f3a).
