### ISSUE TITLE
ModuleNotFoundError: No module named 'detectron.utils.cython_bbox'

### ISSUE THREAD

**Issue by jiapei100** [facebookresearch/Detectron#736]
```
Detectron git:(master) ✗ python tools/infer_simple.py \                                                                     
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo
Traceback (most recent call last):
  File "tools/infer_simple.py", line 44, in <module>
    import detectron.core.test_engine as infer_engine
  File "....../Detectron/detectron/core/test_engine.py", line 34, in <module>
    from detectron.core.rpn_generator import generate_rpn_on_dataset
  File "....../Detectron/detectron/core/rpn_generator.py", line 41, in <module>
    from detectron.datasets import task_evaluation
  File "....../Detectron/detectron/datasets/task_evaluation.py", line 47, in <module>
    import detectron.datasets.json_dataset_evaluator as json_dataset_evaluator
  File "....../Detectron/detectron/datasets/json_dataset_evaluator.py", line 34, in <module>
    import detectron.utils.boxes as box_utils
  File "....../Detectron/detectron/utils/boxes.py", line 51, in <module>
    import detectron.utils.cython_bbox as cython_bbox
ModuleNotFoundError: No module named 'detectron.utils.cython_bbox'
```

**Comment by jesszgc** [comment]
@jiapei100  stucked by the same error. have you ever go through?

**Comment by ir413** [comment]
Hi @jiapei100, have you run `make` to set up python detectron modules? (as described [here](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#detectron)) If this doesn't solve the issue, please re-open with the instructions on how to reproduce together with your system / environment info (following the issue template).

**Comment by hoanganhtuanfsoft** [comment]
> Hi @jiapei100, have you run `make` to set up python detectron modules? (as described [here](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md#detectron)) If this doesn't solve the issue, please re-open with the instructions on how to reproduce together with your system / environment info (following the issue template).

I have met the same issue. I run python setup.py install and added PYTHONPATH too.

**Comment by taxuewuhenxiaoer** [comment]
I have the same question, how to solve it?

**Comment by jiapei100** [comment]
@taxuewuhenxiaoer 
Move to [Detectron2](https://github.com/facebookresearch/Detectron2)
