### ISSUE TITLE
How to calculate the IoU?

### ISSUE THREAD

**Issue by holyhond** [facebookresearch/Detectron#739]
I want to compare Deeplab v3 with Mask RCNN,but I con't calculate the IoU of Mask RCNN.

**Comment by ir413** [comment]
Hi @holyhond, I'm not quire sure what the question is. Could you please clarify and re-open the issue? FWIW, you can compute the IoU between masks (irrespective of the method used to compute the mask) by using the [COCO API](https://github.com/cocodataset/cocoapi/blob/master/PythonAPI/pycocotools/mask.py).
