### ISSUE TITLE
I can not use gpu 1 in infer.py.

### ISSUE THREAD

**Issue by thejn** [facebookresearch/Detectron#74]
I succeeded in installing caffe2 and testing infer.py of detectorn.
I want to use infer.py in parallel.
So I try to use infer.py in gpu 0 and gpu 1 as several processes as memory space becomes available.
However, I could not change the gpu number with c2_utils.NamedCudaScope (1) alone, but rather ended with an error.
How do I change it in my infer.py code?

**Comment by rbgirshick** [comment]
Please see https://github.com/facebookresearch/Detectron/blob/master/FAQ.md#q-how-do-i-restrict-detectron-to-use-only-a-subset-of-the-gpus-on-a-server.

**Comment by thejn** [comment]
Thank you for answer.
That comment had been confirmed before.
I would like to use it without CUDA_VISIBLE_DEVICES.
Is there any way not to use CUDA_VISIBLE_DEVICES?
