### ISSUE TITLE
Cannot create operator of type 'BatchPermutation' on the device 'CPU'

### ISSUE THREAD

**Issue by lilichu** [facebookresearch/Detectron#740]
hi! I use` convert_pkl_to_pb.py` to convert the detectron model to caffe2 model successfully. Then I want to use ONNX to convert the caffe2 model to ONNX model. But I encounter the issue such as:
`RuntimeError: [enforce fail at operator.cc:185] op. Cannot create operator of type 'BatchPermutation' on the device 'CPU'. Verify that implementation for the corresponding device exist. It might also happen if the binary is not linked with the operator implementation code. If Python frontend is used it might happen if dyndep.InitOpsLibrary call is missing. Operator def: input: "roi_feat_shuffled_1" input: "rois_idx_restore_int32_1" output: "roi_feat_1" name: "" type: "BatchPermutation" device_option { } engine: "" `
I can't understand the issue. Is it a caffe2 problem or ONNX problem?
thanks!

**Comment by lilichu** [comment]
It seems to be because `BatchPermutation` belongs to detectron, we should import detectron operator lib. for example, my detectron_ops_lib is in '/home/user/pytorch/build/lib/libcaffe2_detectron_ops_gpu.so', I add the code such as:
```
from caffe2.python import dyndep
detectron_ops_lib = '/home/user/pytorch/build/lib/libcaffe2_detectron_ops_gpu.so'
dyndep.InitOpsLibrary(detectron_ops_lib)
```
It is OK.

**Comment by ltm920716** [comment]
@lilichu  hello， I meet the same error！ And I meet the new error followed by your solution

WARNING:caffe2.python.workspace:Original python traceback for operator `192` in network `detectron` in exception above (most recent call last):
Traceback (most recent call last):
  File "tools/2onnx.py", line 87, in <module>
    value_info,
  File "/usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/onnx/frontend.py", line 351, in caffe2_net_to_onnx_model
    model = make_model(cls.caffe2_net_to_onnx_graph(*args, **kwargs),
  File "/usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/onnx/frontend.py", line 233, in caffe2_net_to_onnx_graph
    inputs)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/onnx/helper.py", line 62, in c2_native_run_net
    ws.RunNetOnce(predict_net)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/onnx/workspace.py", line 63, in f
    return getattr(workspace, attr)(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/workspace.py", line 201, in RunNetOnce
    StringifyProto(net),
  File "/usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/workspace.py", line 180, in CallWithExceptionIntercept
    return func(*args, **kwargs)
RuntimeError: [enforce fail at generate_proposals_op.cc:243] im_info_tensor.sizes() == (vector<int64_t>{num_images, 3}). [0] vs 1 3
Error from operator:
input: "rpn_cls_probs_fpn2" input: "rpn_bbox_pred_fpn2" input: "im_info" input: "anchor2" output: "rpn_rois_fpn2" output: "rpn_roi_probs_fpn2" name: "" type: "GenerateProposals" arg { name: "spatial_scale" f: 0.25 } arg { name: "pre_nms_topN" i: 1000 } arg { name: "post_nms_topN" i: 1000 } arg { name: "nms_thresh" f: 0.7 } arg { name: "min_size" f: 0 } arg { name: "correct_transform_coords" i: 1 } device_option { } engine: ""frame #0: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x59 (0x7fcf5f703c29 in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: <unknown function> + 0x16791b6 (0x7fcf8e8bb1b6 in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #2: <unknown function> + 0x1238865 (0x7fcf8e47a865 in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #3: caffe2::SimpleNet::Run() + 0x1b2 (0x7fcf8e577372 in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #4: caffe2::Workspace::RunNetOnce(caffe2::NetDef const&) + 0x2b (0x7fcf8e5b05ab in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/../../torch/lib/libcaffe2.so)
frame #5: <unknown function> + 0x55dc8 (0x7fcf8f9a5dc8 in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
frame #6: <unknown function> + 0x8b658 (0x7fcf8f9db658 in /usr/local/miniconda3/lib/python3.6/site-packages/caffe2/python/caffe2_pybind11_state_gpu.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #42: __libc_start_main + 0xf5 (0x7fcfe6f8b445 in /usr/lib64/libc.so.6)

if you have the solution for this problem，thank you！

**Comment by civilpat** [comment]
@lilichu Hello, lilichu! Could you please post the script for exporting caffe2 model to onnx? Thank you! I followed your suggestion and the code is attached as below. But I still encounter "OSError: /home/pat/Deep-Learning/pytorch/build/lib/libcaffe2_detectron_ops_gpu.so: undefined symbol: _ZNK6caffe214ArgumentHelper17GetSingleArgumentIiEET_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERKS2_". 


`import onnx
import caffe2.python.onnx.frontend
from caffe2.proto import caffe2_pb2

from caffe2.python import dyndep
detectron_ops_lib = '/home/pat/Deep-Learning/pytorch/build/lib/libcaffe2_detectron_ops_gpu.so'
dyndep.InitOpsLibrary(detectron_ops_lib)

# We need to provide type and shape of the model inputs,
# see above Note section for explanation
data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 224, 224)
value_info = {
    'data': (data_type, data_shape)
}

predict_net = caffe2_pb2.NetDef()
with open('./model.pb', 'rb') as f:
    predict_net.ParseFromString(f.read())

init_net = caffe2_pb2.NetDef()
with open('./model_init.pb', 'rb') as f:
    init_net.ParseFromString(f.read())

onnx_model = dyndep.onnx.frontend.caffe2_net_to_onnx_model(
    predict_net,
    init_net,
    value_info,
)

onnx.checker.check_model(onnx_model)`
