### ISSUE TITLE
official PyTorch port of Detectron

### ISSUE THREAD

**Issue by sophia-wright-blue** [facebookresearch/Detectron#744]
Is there a public official (supported by Facebook) PyTorch port/version of Detectron that we can contribute to, so this can be developed sooner?

I see this issue has been brought up before (https://github.com/facebookresearch/Detectron/issues/681; https://github.com/facebookresearch/Detectron/issues/70; https://github.com/facebookresearch/Detectron/issues/375), but it's not clear what the current official status of development is;

some git repos that have started work on this are: https://github.com/ignacio-rocco/detectorch; https://github.com/roytseng-tw/Detectron.pytorch; https://github.com/triangleCZH/RetinaNet-and-SSD-in-PyTorch-Detectron

hope to have this clarified by from someone from facebook, thanks.

**Comment by lilichu** [comment]
This is offical faster and mask rcnn of pytorch(supported by facebook):
https://github.com/facebookresearch/maskrcnn-benchmark
hope it can help you

**Comment by sophia-wright-blue** [comment]
thank you @lilichu , that's very helpful

**Comment by ctawong** [comment]
Update - Official project is now detectron2
https://github.com/facebookresearch/detectron2
