### ISSUE TITLE
Convert to pb issue with proto

### ISSUE THREAD

**Issue by Derongan** [facebookresearch/Detectron#745]
### Expected results
I expect the tool to finish and output usable pb files.

### Actual results

```
Fusing affine channel...
Traceback (most recent call last):
  File "tools/convert_pkl_to_pb.py", line 652, in <module>
    main()
  File "tools/convert_pkl_to_pb.py", line 640, in main
    [net, init_net] = convert_model_gpu(args, net, init_net)
  File "tools/convert_pkl_to_pb.py", line 347, in convert_model_gpu
    cdo_cuda = mutils.get_device_option_cuda()
  File "/detectron/detectron/utils/model_convert_utils.py", line 346, in get_device_option_cuda
    device_option.device_id = gpu_id
AttributeError: Assignment not allowed (no field "device_id" in protocol message object).
```

### Detailed steps to reproduce

Install caffe2
Install coco api
Install detectron
modify config file to include weights url for model found in model zoo under tests

Run
```
python tools/convert_pkl_to_pb.py --cfg /detectron/configs/12_2017_baselines/e2e_mask_rcnn_R-50-C4_1x.yaml --out_dir . --fuse_af 1 --device gpu
```

### System information

* Operating system: Ubuntu NVIDIA docker image (16.04.5 LTS (Xenial Xerus))
* Compiler version: 5.4.0
* CUDA version: 8
* cuDNN version: 7
* NVIDIA driver version: 410.66
* GPU models (for all devices if they are not all the same): 
* `PYTHONPATH` environment variable: /usr/local
* `python --version` output: 2.7.12

**Comment by goan15910** [comment]
I change the code in function of get_device_option_cuda in `detectron/utils/model_covert_utils.py`.
```
# comment this line
# device_option.device_id = gpu_id
device_option.cuda_gpu_id = gpu_id
```
and it works.

**Comment by Derongan** [comment]
That worked for me! Thanks!

**Comment by Walid-Ahmed** [comment]
@Derongan 
I am stuck at converting detection model for Caffe2, I am using the cpu flag for conversion as I knew no Caffe inference can be done on GPU
python convert_pkl_to_pb.py --cfg e2e_faster_rcnn_R-101-FPN_1x.yaml  --out_dir . --device cpu

The conversion starts and is stuck at first layer after loading weights.  
Can you please help ?

Thanks
Walid
