### ISSUE TITLE
TypeError: im_detect_all() got multiple values for keyword argument 'timers'

### ISSUE THREAD

**Issue by happyzhanglc** [facebookresearch/Detectron#746]
TypeError: im_detect_all() got multiple values for keyword argument 'timers'

**Comment by ir413** [comment]
Hi @happyzhanglc, please re-open the issue with steps to reproduce (commands you run), system / environment info (requested in the issue template), and any modifications made to the code (you should not be seeing this error when running detectron w/o any modifications).
