### ISSUE TITLE
AssertionError: Models that require precomputed proposals are not supported

### ISSUE THREAD

**Issue by rudy-letote** [facebookresearch/Detectron#759]
hello, boss.
when i run below order:
        "python ./tools/infer_simple.py     
        --cfg ./configs/12_2017_baselines/mask_rcnn_R-50-FPN_1x.yaml       
        --output-dir /tmp/mask-visualizations      
        --image-ext jpg     
        --wts /tmp/mask-     
        output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl     
        demo"

it met an error:"AssertionError: Models that require precomputed proposals are not supported"  where the code is "assert not cfg.TEST.PRECOMPUTED_PROPOSALS, 'Models that require precomputed proposals are not supported ' " in  infer_simple file.

i have finished the train code and the "model_final .pkl" had created in specified dir 。
i don't know how to supply precomputed proposals and i have seen the related code ,but i do not know how to deal with it . look forward to read boss's message and your instructions,thanks.

* Operating system: ubantu：16.04
* Compiler version: 4:5.3.1
* CUDA version: 8000
* cuDNN version: 7102
* NVIDIA driver version: 384.130
* GPU models : 4* nvidia 1080ti 
* `python --version` output: 2.7.15
* Anything else that seems relevant: conda3

**Comment by ir413** [comment]
Hi @rudy-letote, `infer_simple.py` does not support models that require precomputed proposals at this time. Sorry for the inconvenience. You can either use `infer_simple.py` with models that do not require precomputed proposals or add support for using models with precomputed proposals.

**Comment by rudy-letote** [comment]
it is very happy receive your message,thanks very much .
