### ISSUE TITLE
A tiny bug in vis.py when drawing mask

### ISSUE THREAD

**Issue by tumitx** [facebookresearch/Detectron#76]
https://github.com/facebookresearch/Detectron/blob/757d77c239fbef9d6a341cdfcea2f43219175709/lib/utils/vis.py#L332

When the mask has a hole, the polygon 'fill=True' will fill the hole. We'd better draw the mask first, then create the contours.

**Comment by rbgirshick** [comment]
This is a visualization style choice. Other options and opinions are valid as well.
