### ISSUE TITLE
ops file error

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [facebookresearch/Detectron#760]
Hi , Please help to resolve this problem .  i am trying to resolve it from many days. 
CUDA version 10.0, 
cudnn version 6
python 2.7

[ 60%] Building NVCC (Device) object CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

make[3]: Leaving directory '/home/asad/detectron/build'

[ 60%] Built target caffe2_detectron_custom_ops
/home/asad/detectron/detectron/ops/zero_even_op.cu:17:37: fatal error: caffe2/core/context_gpu.h: No such file or directory

compilation terminated.

CMake Error at caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o.cmake:219 (message):
 
 Error generating

  /home/asad/detectron/build/CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/./caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o

CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/build.make:63: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o' failed

make[3]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/detectron/ops/caffe2_detectron_custom_ops_gpu_generated_zero_even_op.cu.o] Error 1

make[3]: Leaving directory '/home/asad/detectron/build'
CMakeFiles/Makefile2:109: recipe for target 'CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all' failed

make[2]: *** [CMakeFiles/caffe2_detectron_custom_ops_gpu.dir/all] Error 2

make[2]: Leaving directory '/home/asad/detectron/build'

Makefile:129: recipe for target 'all' failed

make[1]: *** [all] Error 2

make[1]: Leaving directory '/home/asad/detectron/build'

Makefile:13: recipe for target 'ops' failed

make: *** [ops] Error 2

**Comment by noNameForMe1994** [comment]
same error here

**Comment by maikelronnau** [comment]
@MuhammadAsadJaved I had very similar issues and adding these lines to ```/path/detectron/CMakeLists.txt``` solved the problem:

```
set(Caffe2_DIR "/path/to/pytorch/torch/share/cmake/Caffe2")
include_directories("/path/to/pytorch/torch/lib/include/")
set(PROTOBUF_LIB "/path/to/pytorch/build/lib/libprotobuf.a")
```

Don't forget to run ```make clean``` before compiling again.

**Comment by ZHONGCHUYUN** [comment]
@MuhammadAsadJaved I met the same error. And I have run `make clean` but still failed. Have you solved it now?
