### ISSUE TITLE
Load pretrained ResNet-18 model with '*.pth'

### ISSUE THREAD

**Issue by TinaLiuCV** [facebookresearch/Detectron#764]
I want to use the pretrained model, such as ResNet-18 provided by pytorch group. The available versions are saved as '*.pth'. I wonder if this type of pretrained models could be used in Detectron. If not, what should I do? Thanks.

**Comment by liu09114** [comment]
Similar questions, did you solve it?

**Comment by ir413** [comment]
Hi @TinaLiuCV and @liu09114, Detectron uses Caffe2 and loading pre-trained PyTorch models is not supported at this time. Sorry for the inconvenience. As a workaround, you can write a simple tool to convert weights from PyTorch to Caffe2 format expected by Detectron.
