### ISSUE TITLE
faster_rcnn_R-50 used more memory than faster_rcnn_R-50-FPN

### ISSUE THREAD

**Issue by daoyijushi** [facebookresearch/Detectron#769]
when I use detectron train my dataset, I find that the model of faster_rcnn_R-50 has used 8235M and the model of faster_rcnn_R-50-FPN has used 2000M, could someone tell me the reason? All configuration files are officially available except for data sets . thank you.

**Comment by ir413** [comment]
Hi @daoyijushi, the overall FPN-based Faster R-CNN system has faster running time and lower memory usage. The main difference comes from a lighter weight head (2-fc MLP head instead of the standard conv5 head; see section 4.2 of the FPN paper for more info).
