### ISSUE TITLE
Detectron-->caffe2-->onnx

### ISSUE THREAD

**Issue by shuxp** [facebookresearch/Detectron#771]
I convert my model(rcnn-resnet-50-FPN) to caffe2(pb file) with error "TypeError: write() argument must be str, not bytes+". I modify write mode from 'w' to 'wb' this problem solved.

https://github.com/facebookresearch/Detectron/blob/8181a324796202e4afe7660b7458b7bf1e08cf8b/tools/convert_pkl_to_pb.py#L407

After I got pb file, I have 3 file(model.pb, model_init.pb, model.pbtxt), now I want to export pb file to onnx. The demo used in onnx not work with this network. So how to change caffe2 model to onnx model

Can anyone help me with this? Thanks.

**Comment by mosjoker** [comment]
Have you figured out it? @shuxp

**Comment by fuzzyBatman** [comment]
Maybe this will provide some info https://github.com/facebookresearch/maskrcnn-benchmark/issues/116

**Comment by civilpat** [comment]
@shuxp Hi, have you figured out to convert caffe2 (odel.pb, model_init.pb, model.pbtxt) into onnx? I have faced the same issue and did't find a way out. Thank you very much!

**Comment by fuzzyBatman** [comment]
[This](https://github.com/onnx/onnx/issues/1552#issuecomment-496620584)

> Object detection models like YOLO , SSD, and FasterRCNN are now supported as of ONNX 1.5. Support for image segmentation models like MaskRCNN are planned for ONNX 1.6.

**Comment by fuzzyBatman** [comment]
[This](https://github.com/onnx/tutorials/blob/master/tutorials/Caffe2OnnxExport.ipynb) is supposed to be the procedure. I'm trying to convert a Faster R-CNN model right now. Errors till now.

**Comment by fuzzyBatman** [comment]
@shuxp My Faster R-CNN model, which I obtained by setting `MASK_ON=False` for a Mask R-CNN model, contains **GenerateProposals** and **ResizeNearest** ops which are currently not in the [Operator list](https://github.com/onnx/onnx/blob/master/docs/Operators.md) of ONNX.
