### ISSUE TITLE
how to infer multiple images simultaneously

### ISSUE THREAD

**Issue by lssily** [facebookresearch/Detectron#774]
When I run the infer_simple.py, I found that both GPU and CPU have a low utilization rate. I have 2 questions:
1) How to infer multiple images on one gpu simultaneously?
2) How to infer multiple images on multiple gpus simultaneously?
Look forward to your suggestions!

**Comment by 13070151771** [comment]
hello Issily .I have the same question，have you got answer now？

**Comment by ir413** [comment]
Hi @lssily, batched inference is not supported at this time. Please see #451 for a related discussion.
