### ISSUE TITLE
ImportError: No module named c2

### ISSUE THREAD

**Issue by earlysleepearlyup** [facebookresearch/Detectron#78]
### Expected results

What did you expect to see?
test success

### Actual results

What did you observe instead?
import utils.c2
ImportError: No module named c2

### Detailed steps to reproduce

E.g.:

```
python2 $DETECTRON/tests/test_spatial_narrow_as_op.py
```

### System information

* Operating system: Ubuntu 14.01
* Compiler version: gcc4.8.4
* CUDA version: CUDA 8.0
* cuDNN version: cuDNN 6.0
* NVIDIA driver version: nvidia-384.111
* GPU models (for all devices if they are not all the same): GTX 1050Ti
* `PYTHONPATH` environment variable: /usr/local:/opt/ros/indigo/lib/python2.7/dist-packages:/usr/local::/home/znjs/caffe2/build:/home/znjs/caffe2/build
* `python --version` output: Python 2.7.6
* Anything else that seems relevant: ?

**Comment by YoungMagic** [comment]
Hi~ You should include /detectron/lib in your pythonpath.

**Comment by ir413** [comment]
Hi @earlysleepearlyup, please make sure that you have set up Python modules following the [installation instructions](https://github.com/facebookresearch/Detectron/blob/master/INSTALL.md).

Relevant extract:

> Set up Python modules:
>```
>cd $DETECTRON/lib && make
>```

**Comment by earlysleepearlyup** [comment]
@YoungMagic  @ir413 Thank you very much ! 
I have solved this problem. Because I had installed apollo-kernel.So my PC enter the apollo-kernel automatically when boot the PC. 
In this kernel,I can't driver my nvidia GPU cards.  And then this problem comes out.
I tried to change my common kernel to solve this problem successfully.
Thank you !

**Comment by DanielNehemiah** [comment]
@earlysleepearlyup could you tell me how to change the apollo kernel? I am facing the same problem as you..

**Comment by earlysleepearlyup** [comment]
@DanielNehemiah When you enter the ubuntu os,you can select the `Linux x.x.x-xx-generic`

**Comment by DanielNehemiah** [comment]
Thanks! The issue was I had installed detectron with sudo and so detectron only works when i use sudo in the terminal

**Comment by gclsoft** [comment]
@YoungMagic But there is no lib folder under DETECTRON project
![image](https://user-images.githubusercontent.com/1269898/41648234-ec582fc8-74aa-11e8-846f-688bd15450c7.png)

**Comment by hainow** [comment]
You just can simply add the cloned detectron path (the one that contains another subdirectory named 'detectron') to your PYTHONPATH

**Comment by BanuSelinTosun** [comment]
Ok. There is no detectron/lib anymore in this repo? Am I looking to the wrong place?
