### ISSUE TITLE
conflicts with caffe project

### ISSUE THREAD

**Issue by MichaelSunEngineer** [facebookresearch/Detectron#789]
when i import a caffe project and a detectron project in one .py file,get something wrong.but if import caffe and detectron in two different .py file is ok.

my caffe project is caffe.crnn my libprotobuf version is 3.6.1 python2.7

###errors:########################
[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'

**Comment by MichaelSunEngineer** [comment]
when i import a caffe project and a detectron project in one .py file,get something wrong.but if import caffe and detectron in two different .py file is ok.
my caffe project is caffe.crnn   my libprotobuf version is 3.6.1  python2.7
[libprotobuf ERROR google/protobuf/descriptor_database.cc:109] Symbol name "caffe.BlobShape" conflicts with the existing symbol "caffe.BlobShape".
[libprotobuf FATAL google/protobuf/descriptor.cc:1018] CHECK failed: generated_database_->Add(encoded_file_descriptor, size): 
terminate called after throwing an instance of 'google::protobuf::FatalException'

**Comment by ir413** [comment]
Hi @MichaelSunEngineer, there probably is some incompatibility between protobuf versions used in your Caffe and Caffe2. I think it would be better to post about this on the Caffe2 / PyTorch GitHub page.

**Comment by MichaelSunEngineer** [comment]
谢谢！


发自孙浩邮箱
On 01/05/2019 02:37, Ilija Radosavovic wrote:

Hi @MichaelSunEngineer, there probably is some incompatibility between protobuf versions used in your Caffe and Caffe2. I think it would be better to post about this on the Caffe2 / PyTorch GitHub page.
