### ISSUE TITLE
A question regarding 'ImportError: No module named config' problem.

### ISSUE THREAD

**Issue by TheIllusion** [facebookresearch/Detectron#79]
Hi, 
I installed caffe2 successfully and tested its operation using the following test commands.

------------------------------
cd ~ && python -c 'from caffe2.python import core' 2>/dev/null && echo "Success" \|\| echo "Failure"
------------------------------

However, when I run test_net.py, I am encountering an error regarding importing config module. 

------------------------------
< Error message >
python2 tools/test_net.py     --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml     TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl     NUM_GPUS 1
Traceback (most recent call last):
  File "tools/test_net.py", line 34, in <module>
    from core.config import assert_and_infer_cfg

ImportError: No module named config
------------------------------

My environment is 
ubuntu 16.04 / python 2.7.

Probably, the problem might be fixed by changing PYTHONPATH.
Could you tell me where 'core.config' is located?

**Comment by Hao-Zhao** [comment]
should be in /detectron/lib/core

**Comment by Hao-Zhao** [comment]
you could add this sys.path.append(os.path.abspath('/detectron/lib/')) in your code, should be fine

**Comment by TheIllusion** [comment]
oh.. thanks a lot!

**Comment by lvpchen** [comment]
when I run common below:

python2 tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo


  File "tools/infer_simple.py", line 41, in <module>
    from core.config import assert_and_infer_cfg
ImportError: No module named config


It also displayed this result, can anyone help me to solve this problem. Thank you very much.

**Comment by xxx09** [comment]
@lvpchen 
I have the same problem as u. u have two choices:
1. u can add " `sys.path.append(os.path.abspath('yourpathto/detectron/lib/'))` " in the infer_simple.py
2. or u can add "`export PYTHONPATH=$PYTHONPATH:/path/detectron/lib`" in the .bashrc file
If u have tried above methods, but still display ImportError, u can do as follows:
1.open a terminal, open python console
2.input two command lines "`import core; core.__file__`" in your python console to see your core module's path(maybe u have another module named core), and forbid the wrong core module
