### ISSUE TITLE
Http 403 errors with dl.fbaipublicfiles.com

### ISSUE THREAD

**Issue by jongoodrumacv** [facebookresearch/Detectron#791]
Yesterday, many of the Detectron assets were moved from `https://s3-us-west-2.amazonaws.com/detectron` to `https://dl.fbaipublicfiles.com/detectron` via this commit ([link](https://github.com/facebookresearch/Detectron/commit/5ed75f9d672b3c78b7da92d9b2321d04f33a7ccc))

Trying to access these files yields a HTTP 403 error.  I'm assuming these require some sort of Facebook API authentication.

How do we access these assets without getting a 403 error?

**Comment by ir413** [comment]
Thanks for reporting @jongoodrumacv. We are looking into it.

**Comment by ir413** [comment]
Hi @jongoodrumacv, this should be addressed now. Could you please double-check?

**Comment by jongoodrumacv** [comment]
Works for me.  Thanks!
