### ISSUE TITLE
Where can I find VGG16 weights for training Faster-RCNN training

### ISSUE THREAD

**Issue by muzammil360** [facebookresearch/Detectron#819]
I am trying to train Faster RCNN with VGG16 as backbone but can't find the training weights URL to update `TRAIN.WEIGHTS` in config file. [MODEL_ZOO.md](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md) lists ResNet and ResNeXt models but not VGG16. 

Can someone share the weight file URL for VGG16 (for caffe2)?

**Comment by ir413** [comment]
Hi @muzammil360, we don't have a VGG16 ImageNet pretrained backbone available at this time. Sorry for the inconvenience.
