### ISSUE TITLE
Want to chance base path 

### ISSUE THREAD

**Issue by goodbye61** [facebookresearch/Detectron#82]
Hi,

I have downloaded two-detectron folder But both have same path. (/path/to/clone/detectron) 
How can I change this base path?

**Comment by JohnnyGambler** [comment]
In the  file:  lib/core/config.py ,change  "__C.DOWNLOAD_CACHE"

**Comment by ir413** [comment]
Hi @goodbye61, `/path/to/clone/detectron` indicates that you should pick the path where you would like to clone the project.

For instance, to clone Detectron to `/foo/bar/detectron` you can run:

```
git clone https://github.com/facebookresearch/detectron /foo/bar/detectron
```
