### ISSUE TITLE
how can I  downloads the weights.pkl for rpn_person_only_R-101-FPN_1x.yaml

### ISSUE THREAD

**Issue by Adhders** [facebookresearch/Detectron#820]
## PLEASE FOLLOW THESE INSTRUCTIONS BEFORE POSTING
1. Please thoroughly read README.md, INSTALL.md, GETTING_STARTED.md, and FAQ.md
2. Please search existing *open and closed* issues in case your issue has already been reported
3. Please try to debug the issue in case you can solve it on your own before posting

## After following steps 1-3 above and agreeing to provide the detailed information requested below, you may continue with posting your issue
(**Delete this line and the text above it.**)

### Expected results

What did you expect to see?

### Actual results

What did you observe instead?

### Detailed steps to reproduce

E.g.:

```
The command that you ran
```

### System information

* Operating system: ?
* Compiler version: ?
* CUDA version: ?
* cuDNN version: ?
* NVIDIA driver version: ?
* GPU models (for all devices if they are not all the same): ?
* `PYTHONPATH` environment variable: ?
* `python --version` output: ?
* Anything else that seems relevant: ?

**Comment by Adhders** [comment]
when i enter  "python3 tools/infer_simple.py --cfg configs/12_2017_baselines/rpn_person_only_R-101-FPN_1x.yaml --output-dir /tmp/detectron-visualizations --image-ext jpg --wts https://dl.fbaipublicfiles.com/detectron/35861858/12_2017_baselines/rpn_person_only_R-101-FPN_1x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl demo"

there is AssertionError: Detectron only automatically caches URLs in the Detectron S3 bucket: https://s3-us-west-2.amazonaws.com/detectron

**Comment by xiang-zhe** [comment]
@Adhders ，i got the same problem in docker，but is was solved by changing _DETECTRON_S3_BASE_URL = 'https://dl.fbaipublicfiles.com/detectron' in line 40 in
 /detectron/lib/utils/io.py， i help it work  to u

**Comment by ir413** [comment]
Hi @Adhders, you can find the up-to-date download links for person only RPN models [here](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md#person-specific-rpn-baselines). Please note that we updated the URLs in 5ed75f9d672b3c78b7da92d9b2321d04f33a7ccc so you may need to rebase on master or make the corresponding changes in the code if your fork diverged from this repo (see #781 for more info).
