### ISSUE TITLE
Any suggestion about model ensemble for faster rcnn?

### ISSUE THREAD

**Issue by BasisPoint** [facebookresearch/Detectron#830]
I have trained several faster rcnn models with different backbones, then I want to ensemble these models for a better performance, but I am totally confused about how to do this , can you give me some suggestion or reference for this? Thank you anyway.

**Comment by ir413** [comment]
Hi @BasisPoint, the easiest way to implement this may be to (1) save predictions from different models to disk (e.g. in pkl format) and (2) write a tool that reads and combines the pre-computed predictions.
