### ISSUE TITLE
About data augmentation with geometric transformations

### ISSUE THREAD

**Issue by gru35** [facebookresearch/Detectron#843]
Hi, I'm trying to implement 3 geometric transformations (rotation, shear and zoom) to augment my data during the training. I add the transformations [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/minibatch.py#L89) and more specifically [here](https://github.com/facebookresearch/Detectron/blob/8a4723835cb163c3c02d90593f2f4f4ef1f45f4b/detectron/utils/blob.py#L117) as you suggested but I am not sure where I need to add the transformation for the new ground truth box. 
I made some changes [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/roi_data/rpn.py#L91) to transform the box to the new location but I am not sure if it's working correctly. 
Can you point me to the correct direction as to where I need to make the final changes?

Thanks in advance.

**Comment by ir413** [comment]
Hi @gru35, our current strategy for implementing data augmentations is not flexible enough to allow adding data augmentations in an easy and scalable way. The easiest may be to follow the way horizontal flipping is implemented (as you have done for transforming the image blobs). You can find the code that augments the training roidb with horizontally flipped ground truth labels [here](https://github.com/facebookresearch/Detectron/blob/master/detectron/datasets/roidb.py#L76).
