### ISSUE TITLE
When is Python 3 supported. 

### ISSUE THREAD

**Issue by norouzzadeh** [facebookresearch/Detectron#85]
Caffe2 now supports Python 3, but i have problems using Detectron with Python 3. When is Python 3 supported by Detectron?

**Comment by rbgirshick** [comment]
We plan to do this, but have no ETA right now.

**Comment by Scitator** [comment]
@rbgirshick Hello! Is there any updates for py3 support?

**Comment by rbgirshick** [comment]
It's something we definitely will do, but there's no ETA for making the change.

**Comment by tengerye** [comment]
Hi, any progress for python 3 support? Do you need help?

**Comment by franva** [comment]
Same here, any update in year 2020?

**Comment by tomgross** [comment]
Detecteron 2 has been released: https://github.com/facebookresearch/detectron2/releases/tag/v0.1
It runs on Linux or macOS with Python ≥ 3.6
