### ISSUE TITLE
How can I get the  visualization of feature maps after trained with Detectron?

### ISSUE THREAD

**Issue by CPFelix** [facebookresearch/Detectron#851]
I have sucessifully trained the mask r-cnn,and I want to visualize the feature maps in FPN and Res50,but I have no ideas.Did anyone have done this?thanks!

**Comment by ir413** [comment]
Hi @CPFelix, the easiest may be to (1) save intermediate features for images you care about to disk (e.g. in pkl format; see #123 for how to extract feature blobs) and (2) write a tool or notebook that visualizes the pre-computed features.

**Comment by zunairaR** [comment]
how i can do this in pytorch. using the latest API
