### ISSUE TITLE
Retninet occupies huge GPU memory during inference

### ISSUE THREAD

**Issue by pkhigh** [facebookresearch/Detectron#853]
Everything is installed properly. Inference is running well.
I just ran the command : 
python tools/infer_simple.py --cfg configs/12_2017_baselines/retinanet_R-50-FPN_1x.yaml --wts RetinaNet50.pkl --output-dir OUT_IMG_DIR_PATH --output-ext jpg INP_IMG_DIR_PATH 

I just want to know that at runtime while evaluating images, Retinanet occupies 3.4 GB GPU memory. Is it acceptable? Given that the model size is just 297MB.

### System information

* Operating system: ? Ubuntu 16
* Compiler version: ? g++-5
* CUDA version: ? 9.2
* cuDNN version: ? 7.5
* GPU models (for all devices if they are not all the same): ? 1 Nvidia GPU
* `python --version` output: ? 3.6

**Comment by ir413** [comment]
Hi @pkhigh, that seems plausible (memory usage is dominated by activations). You can find (train) memory usage for different models and training configurations [here](https://github.com/facebookresearch/Detectron/blob/master/MODEL_ZOO.md).
