### ISSUE TITLE
python2.7 myyaml==3.12  yaml.constructor.ConstructorError: while constructing a Python instance 

### ISSUE THREAD

**Issue by SuperMisswei** [facebookresearch/Detectron#916]
I ran the test demo
python tools/infer_simple.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    --output-dir /tmp/detectron-visualizations \
    --image-ext jpg \
    --wts https://dl.fbaipublicfiles.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    demo

but i get the error as
![image](https://user-images.githubusercontent.com/37127760/61469008-0c2b9880-a9b1-11e9-9ddb-a90f34e52fa3.png)

### System information

* Operating system: ubuntu16.04
* Compiler version: python2.7
* CUDA version: cuda9.0
* cuDNN version: cudnn7.0.5
* NVIDIA driver version: 384.130
* GPU models (for all devices if they are not all the same): TITAN X
* `python --version` output: 2.7

**Comment by ROODAY** [comment]
@SuperMisswei did you solve this?
