### ISSUE TITLE
not clear about minival 

### ISSUE THREAD

**Issue by zhengduoru** [facebookresearch/Detectron#94]
I ran the code you gave:
 python2  tools/test_net.py \
    --cfg configs/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml \
    TEST.WEIGHTS https://s3-us-west-2.amazonaws.com/detectron/35861858/12_2017_baselines/e2e_mask_rcnn_R-101-FPN_2x.yaml.02_32_51.SgT4y1cO/output/train/coco_2014_train:coco_2014_valminusminival/generalized_rcnn/model_final.pkl \
    NUM_GPUS 

however, I guess I haven't properly installed coco_2014_minival , I got an error like

Traceback (most recent call last):
  File "tools/test_net.py", line 157, in <module>
    main(ind_range=args.range, multi_gpu_testing=args.multi_gpu_testing)
  File "tools/test_net.py", line 122, in main
    results = parent_func(multi_gpu=multi_gpu_testing)
  File "/home/zdr/github/Detectron/lib/core/test_engine.py", line 62, in test_net_on_dataset
    all_boxes, all_segms, all_keyps = test_net()
  File "/home/zdr/github/Detectron/lib/core/test_engine.py", line 149, in test_net
    model, im, box_proposals, timers
  File "/home/zdr/github/Detectron/lib/core/test.py", line 65, in im_detect_all
    scores, boxes, im_scales = im_detect_bbox(model, im, box_proposals)
  File "/home/zdr/github/Detectron/lib/core/test.py", line 133, in im_detect_bbox
    inputs, im_scales = _get_blobs(im, boxes)
  File "/home/zdr/github/Detectron/lib/core/test.py", line 981, in _get_blobs
    blobs['data'], im_scale_factors = _get_image_blob(im)
  File "/home/zdr/github/Detectron/lib/core/test.py", line 906, in _get_image_blob
    im, cfg.PIXEL_MEANS, cfg.TEST.SCALES, cfg.TEST.MAX_SIZE
  File "/home/zdr/github/Detectron/lib/utils/blob.py", line 78, in prep_im_for_blob
    im = im.astype(np.float32, copy=False)
AttributeError: 'NoneType' object has no attribute 'astype'

I downloaded 'coco_train2014', 'coco_val2014' , 'annotations'(2014)  as well as the annotations in https://s3-us-west-2.amazonaws.com/detectron/coco/coco_annotations_minival.tgz 

I wanna know that is there something else I missed?

**Comment by ir413** [comment]
Hi @zhengduoru, you can check that your COCO dataset is correctly setup by making sure that it follows the directory structure outlined [here](https://github.com/facebookresearch/Detectron/tree/master/lib/datasets/data).

For example, you can run something like:

```
# Check the top-level structure
ls -al $DETECTRON/lib/datasets/data/coco

# Check that annotations are present
ls -al $DETECTRON/lib/datasets/data/coco/annotations

# Check that train images are present
ls -al $DETECTRON/lib/datasets/data/coco/coco_train2014 | head -n 10

# Check that val images are present
ls -al $DETECTRON/lib/datasets/data/coco/coco_val2014 | head -n 10
```

Looking at the stack trace you posted, it seems that the image files might be missing. We added some additional checks for that in 1a3ae0c. If that is indeed the case, you will get a clearer error message if you pull the latest master and rerun your command.
