### ISSUE TITLE
I can't export model to ONNX: "AttributeError: EXPORT_CAFFE2"

### ISSUE THREAD

**Issue by joaobarros05** [facebookresearch/Detectron#986]
I cannot generate ONNX model. The following error message appears: "AttributeError: EXPORT_CAFFE2".

- **Model export code:**

`torch_model = build_model(cfg)
DetectionCheckpointer(torch_model).resume_or_load(cfg.MODEL.WEIGHTS)

data_loader = build_detection_test_loader(cfg, cfg.DATASETS.TEST[0])
first_batch = next(iter(data_loader))

onnx_model = export_onnx_model(cfg, torch_model, first_batch)
onnx_model.save_protobuf('./teste')`

- **Error output:**
`AttributeError                            Traceback (most recent call last)
<ipython-input-3-38e69027cd9f> in <module>
     14 first_batch = next(iter(data_loader))
     15 
---> 16 onnx_model = export_onnx_model(cfg, torch_model, first_batch)
     17 onnx_model.save_protobuf('./teste')
     18 

/opt/conda/lib/python3.7/site-packages/detectron2/export/api.py in export_onnx_model(cfg, model, inputs)
     80     assert isinstance(cfg, CN), cfg
     81     C2MetaArch = META_ARCH_CAFFE2_EXPORT_TYPE_MAP[cfg.MODEL.META_ARCHITECTURE]
---> 82     c2_compatible_model = C2MetaArch(cfg, model)
     83     c2_format_input = c2_compatible_model.get_caffe2_inputs(inputs)
     84     return export_onnx_model_impl(c2_compatible_model, (c2_format_input,))

/opt/conda/lib/python3.7/site-packages/detectron2/export/caffe2_modeling.py in __init__(self, cfg, torch_model)
    250         super().__init__(cfg, torch_model)
    251 
--> 252         self.roi_heads_patcher = ROIHeadsPatcher(cfg, self._wrapped_model.roi_heads)
    253 
    254     def encode_additional_info(self, predict_net, init_net):

/opt/conda/lib/python3.7/site-packages/detectron2/export/patcher.py in __init__(self, cfg, heads)
    117         self.heads = heads
    118 
--> 119         self.use_heatmap_max_keypoint = cfg.EXPORT_CAFFE2.USE_HEATMAP_MAX_KEYPOINT
    120 
    121     @contextlib.contextmanager

/opt/conda/lib/python3.7/site-packages/yacs/config.py in __getattr__(self, name)
    139             return self[name]
    140         else:
--> 141             raise AttributeError(name)
    142 
    143     def __setattr__(self, name, value):

AttributeError: EXPORT_CAFFE2`

Does anyone have any idea what that is?

**Comment by groumpfette** [comment]
Hi, same problem here, did you solve it?

**Comment by ppwwyyxx** [comment]
Unrelated to Detectron.
