### ISSUE TITLE
RLE to Detectron2 Format

### ISSUE THREAD

**Issue by panditrahulsharma** [facebookresearch/Detectron#989]
i have Sucessfully Implements severstal-steel defect detection Kaggle Challenge in this Dataset are in RLE format But i changed this RLE format to Detectron2 Format and this Script would help to Convert any RLE type Data to Detectron2 Format visit my github
https://github.com/panditrahulsharma/RLE-to-polygon-format
and feel free to contact on linkedin
https://www.linkedin.com/in/rahul-pandit-651ba7166/

**Comment by ppwwyyxx** [comment]
This repo is not about detectron2. Closing.

Detectron2 already supports RLE format as documented in https://detectron2.readthedocs.io/tutorials/datasets.html#standard-dataset-dicts
