### ISSUE TITLE
AssertionError: Override list has odd length

### ISSUE THREAD

**Issue by ChauncyFr** [facebookresearch/Detectron#993]
When I installed detectron2, I wanted to test the instance segmentation model. I executed the following commands as required:

“Python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input input1.jpg --output output --opts ../pretrain/model_final_f10217.pkl

But remind me, "AssertionError: Override list has odd length: ['../pretrain/model_final_f10217.pkl']; it must be a list of pairs"

Specific as shown

![](https://tva1.sinaimg.cn/large/007S8ZIlly1geg93haib0j31n80femyl.jpg)

**Comment by jianghan0213** [comment]
Do you know how to solve this problem?

**Comment by DominikFilipiak** [comment]
@jianghan0213 
Judging by the command, there was a missing `MODEL.WEIGHTS` parameter before the actual path to model weights. It should look more or less like this:
```
python demo.py --config-file ../configs/COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml --input input1.jpg --output output --opts MODEL.WEIGHTS ../pretrain/model_final_f10217.pkl
```
Be sure to set the proper paths to the weights, as it was the cause of problems in my case.

**Comment by koojaekwan** [comment]
['MODEL.WEIGHTS', 'detectron2://COCO-Detection/faster_rcnn_X_101_32x8d_FPN_3x/139173657/model_final_68b088.pkl']
