### ISSUE TITLE
    from detectron2 import _C ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by shiva2410** [facebookresearch/Detectron#994]
I tried it with Detectron2 v0.1 Release 
As this release says PyTorch version 1.4 is required 
Still getting same error 

    from detectron2 import _C
ImportError: libtorch_cpu.so: cannot open shared object file: No such file or directory

_Originally posted by @shiva2410 in https://github.com/facebookresearch/detectron2/issues/1365#issuecomment-624525129_

**Comment by ImadEddineBek** [comment]
SAame problem
